### PR TITLE
[prometheus] Increase aggregation-proxy timeout

### PR DESCRIPTION
**Pull request by scaps1**
## Description
Previously aggregation-proxy had relatively low timeout value (5s) for the Prometheus requests.
This PR increases it to 30s which is expected to be enough for most use cases.
## Why do we need it, and what problem does it solve?
Large dashboards with heavy queries sent simultaneously to Prometheus via aggregation-proxy may (and do) fail due to low request timeout value.
## Why do we need it in the patch release (if we do)?
We don't
## What is the expected result?

big queries and metrics on longer timeout
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: fix
summary: Increase aggregation-proxy timeout.
impact: Aggregation-proxy deployment will restart.
```

### CODE REVIEW

**Review by lazovskiy — APPROVED** [review]

**Review by nabokihms — APPROVED** [review]

**Review by vladimirGuryanov — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10715977910 10715977910-1-con-1-27 /sys/deckhouse-oss/install:pr9579

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10761204620 10761204620-1-con-1-27 /sys/deckhouse-oss/install:pr9579 redos@62.84.127.144

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.27 10761612017 10761612017-1-con-1-27 /sys/deckhouse-oss/install:pr9579 user@34.159.244.191

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
@lazovskiy E2E tests didn't pass.

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vladimirGuryanov. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Pull request merged**
