### PR TITLE
[docs] Update the Deckhouse FAQ

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Add badges with the info, warning, and danger levels.

Update info about tested registries in the Deckhouse FAQ.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: docs
type: chore
summary: Add badges with the info, warning, and danger levels. Update info about tested registries in the Deckhouse FAQ.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Review by konstantin-axenov — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [4996](https://github.com/deckhouse/deckhouse/pull/4996) to the branch [release-1.46](https://github.com/deckhouse/deckhouse/tree/release-1.46) successful!

**Pull request merged**
