### PR TITLE
[cloud-provider-aws] bump version

### PR DESCRIPTION
**Pull request by yalosev**
Signed-off-by: Yuriy Losev <yuriy.losev@flant.com>

## Description
Bump version

## Why do we need it, and what problem does it solve?
This minor patches fixes some problems, for example with [target group](https://github.com/kubernetes/cloud-provider-aws/commit/d5582fffde1aae8e43f49df473f5ff95f37172cf) creation

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-aws
type: fix
summary: Bump cloud provider version to fix LB target group creation.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [2569](https://github.com/deckhouse/deckhouse/pull/2569) to the branch [release-1.36](https://github.com/deckhouse/deckhouse/tree/release-1.36) successful!

**Pull request merged**
