### PR TITLE
DO NOT MERGE! test updating addon operator

### PR DESCRIPTION
**Pull request by name212**
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...

**Comment by name212** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11092055048 11092055048-1-con-1-27 /sys/deckhouse-oss/install:pr9903 redos@51.250.2.110

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by name212** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.29 11092071428 11092071428-1-con-1-29 /sys/deckhouse-oss/install:pr9903 ec2-user@18.199.205.161

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by name212** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.28 11092062643 11092062643-1-con-1-28 /sys/deckhouse-oss/install:pr9903 ec2-user@3.120.204.63

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by name212** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.26 11092047519 11092047519-1-con-1-26 /sys/deckhouse-oss/install:pr9903 redos@89.169.141.237

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by name212** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.30 11092077586 11092077586-1-con-1-30 /sys/deckhouse-oss/install:pr9903 user@34.159.6.143

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by name212** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.30 11094368325 11094368325-1-con-1-30 /sys/deckhouse-oss/install:pr9903 redos@89.169.157.151

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request closed without merging**
