### PR TITLE
[dhctl] add preflight checks for system requirements on the master nodes

### LINKED ISSUE #5068: [preflight-check] Checking compliance with the minimum requirements
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Preventing failures before bootstrap execution

### Proposed Solution

Before performing bootstrap, check compliance with the minimum requirements: RAM, CPU, Storage, CPU architecture

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mvasl**
## Description

Added a preflight check to validate that master nodes in the future cluster are meeting our minimal system requirements on cpu, RAM and root disk size.

Closes #5068

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: feature
summary: Add a preflight checks for system requirements on the master nodes.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...

**Comment by mvasl** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9853054321 9853054321-1-con-1-27 /sys/deckhouse-oss/install:pr8961

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by mvasl** [comment]
/e2e/abort static;Static;containerd;1.27 9853054392 9853054392-1-con-1-27 /sys/deckhouse-oss/install:pr8961 astra@192.168.199.164

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...

**Comment by mvasl** [comment]
/e2e/abort static;Static;containerd;1.27 9870273450 9870273450-1-con-1-27 /sys/deckhouse-oss/install:pr8961 astra@192.168.199.124

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by mvasl** [comment]
/e2e/abort static;Static;containerd;1.27 9871780953 9871780953-1-con-1-27 /sys/deckhouse-oss/install:pr8961 astra@192.168.199.199

**Comment by mvasl** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9871781884 9871781884-1-con-1-27 /sys/deckhouse-oss/install:pr8961

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...

**Comment by mvasl** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9873715297 9873715297-1-con-1-27 /sys/deckhouse-oss/install:pr8961

**Comment by mvasl** [comment]
/e2e/abort static;Static;containerd;1.27 9873717587 9873717587-1-con-1-27 /sys/deckhouse-oss/install:pr8961 astra@192.168.199.24

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/azure'...

**Comment by mvasl** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.27 9875684616 9875684616-1-con-1-27 /sys/deckhouse-oss/install:pr8961

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...

**Comment by mvasl** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 9875684977 9875684977-1-con-1-27 /sys/deckhouse-oss/install:pr8961 ec2-user@18.193.26.19

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/vcd'...

**Comment by mvasl** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 9877628881 9877628881-1-con-1-27 /sys/deckhouse-oss/install:pr8961

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by mvasl** [comment]
/e2e/abort vclouddirector;Standard;containerd;1.27 9877629530 9877629530-1-con-1-27 /sys/deckhouse-oss/install:pr8961

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/gcp'...

**Comment by mvasl** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 9886870556 9886870556-1-con-1-27 /sys/deckhouse-oss/install:pr8961 ubuntu@10.220.203.47

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...

**Comment by mvasl** [comment]
/e2e/abort static;Static;containerd;1.27 9951570904 9951570904-1-con-1-27 /sys/deckhouse-oss/install:pr8961 astra@192.168.199.185

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...

**Comment by name212** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.27 10108373538 10108373538-1-con-1-27 /sys/deckhouse-oss/install:pr8961 user@35.246.254.70

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by name212** [comment]
for gcp e2e was not passed because we have bug with istio

**Review by name212 — APPROVED** [review]

**Pull request merged**
