### PR TITLE
[prometheus] Fix calculation of pvc size and retention size

### PR DESCRIPTION
**Pull request by vitaliy-sn**
## Description

Fixed calculation of pvc size and retention size.

## Why do we need it, and what problem does it solve?

In pr #1446, the `app` label was renamed, causing pvc size and retention to be calculated using the default values.

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: fix
summary: Fixed calculation of pvc size and retention size.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/gcp'...

**Review by konstantin-axenov — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [2934](https://github.com/deckhouse/deckhouse/pull/2934) to the branch [release-1.39](https://github.com/deckhouse/deckhouse/tree/release-1.39) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [2935](https://github.com/deckhouse/deckhouse/pull/2935) to the branch [release-1.38](https://github.com/deckhouse/deckhouse/tree/release-1.38) successful!

**Pull request merged**
