### PR TITLE
[distroless] extended-monitoring

### PR DESCRIPTION
**Pull request by aleksey-su**
## Description
k8s-image-availability-exporter, events_exporter, cert-exporter are now based on minimal image.

## Why do we need it, and what problem does it solve?
We'd like to base our images on a distroless image.

## What is the expected result?
We use scratch along with a minimal number of files from Alpine packages. We pass files in packages though an rsync whitelist.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: extended-monitoring
type: feature
summary: Images are based on a distroless image.
impact_level: default
```

### CODE REVIEW

**Comment by aleksey-su** [comment]
cert-exporter:
image
image

**Comment by aleksey-su** [comment]
events_exporter:
image

**Comment by aleksey-su** [comment]
k8s-image-availability-exporter:
image
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Review by zuzzas — APPROVED** [review]

**Pull request merged**
