### PR TITLE
[site] Replace google slides with a self-hosted solution

### PR DESCRIPTION
**Pull request by valent-ex**
## Description

Switched google slides to a self-hosted solution.

## Changelog entries
```changes
section: deckhouse-web
type: fix
summary: Switched google slides to a self-hosted solution.
impact_level: low
---
section: docs
type: fix
summary: Switched google slides to a self-hosted solution.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Review by z9r5 — APPROVED** [review]

**Comment by z9r5** [comment]
Cherry-picked into release-1.37

**Pull request merged**
