### PR TITLE
[testing] Switch OpenStack testing server flavor

### PR DESCRIPTION
**Pull request by Taior**
## Description
Switch OpenStack testing server flavor to custom

## Why do we need it, and what problem does it solve?
Allows to change allocated resources on e2e tests

## What is the expected result?
Changed available resources on e2e

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: chore
summary: Switch OpenStack testing server flavor.
impact_level: low
```

### CODE REVIEW

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10315](https://github.com/deckhouse/deckhouse/pull/10315) to the branch [release-1.65](https://github.com/deckhouse/deckhouse/tree/release-1.65) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10316](https://github.com/deckhouse/deckhouse/pull/10316) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!

**Pull request merged**
