### PR TITLE
[candi] change desired kernel version for ubuntu 20.04

### PR DESCRIPTION
**Pull request by vitaliy-sn**
Signed-off-by: Vitaliy Snurnitsin <vitaliy.snurnitsin@flant.com>

## Description

Changed desired kernel version to 5.11 for ubuntu 20.04.

## Why do we need it, and what problem does it solve?

For the correct operation of the openvpn and node-local-dns modules in clusters with the cilium module enabled, kernel version 5.7 or higher is required.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Changed desired kernel version to 5.11.0-46-generic for ubuntu 20.04.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Review by yalosev — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [3047](https://github.com/deckhouse/deckhouse/pull/3047) to the branch [release-1.40](https://github.com/deckhouse/deckhouse/tree/release-1.40) successful!

**Pull request merged**
