### PR TITLE
[dhctl] add support wildcard path for config flag

### LINKED ISSUE #8892: [dhctl]: for bootstrap add * option for --config flag
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When using multiple *.yml files for installation, manual operations are required to specify each file in the --config flag.

### Proposed Solution

Use the * option in the directory with the configuration files in the installer container.

For example:
--config=/tmp/config/*.yml

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sprait**
## Description

Add support wildcard path for  dhctl `--config` flag.

## Why do we need it, and what problem does it solve?

These changes make it easier to use configs by mask.
Closes #8892

## What is the expected result?

Allow to use wildcard path for `dhctl --config`:
```
 --config=dir/*
 --config=dir/*.yml
 --config=*.yaml
```
image

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: feature
summary: add support wildcard path for dhctl `--config` flag
impact: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by sprait** [comment]
/e2e/abort openstack;Standard;containerd;1.27 9795468085 9795468085-1-con-1-27 /sys/deckhouse-oss/install:pr8920

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by sprait** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9796219022 9796219022-1-con-1-27 /sys/deckhouse-oss/install:pr8920

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
