### PR TITLE
[core][chore] Update Kubernetes patch versions

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Update Kubernetes:
- 1.23.17
- 1.24.11
- 1.25.7
- 1.26.2

## Why do we need it, and what problem does it solve?
It's important to bring fixes and to stay up to date with upstream.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: feature
summary: "Upgraded patch versions of Kubernetes images: v1.23.17, and v1.24.11, v1.25.7, v1.26.2"
impact: |
  "Kubernetes control-plane components will restart, kubelet will restart"
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 4352268010 4352268010-1-con-1-23 /sys/deckhouse-oss/install:pr4012 centos@18.185.35.196

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.24 4352268010 4352268010-1-con-1-24 /sys/deckhouse-oss/install:pr4012 centos@18.192.172.56

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 4352268010 4352268010-1-con-1-25 /sys/deckhouse-oss/install:pr4012 centos@3.125.241.80

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.23 4352270216 4352270216-1-con-1-23 /sys/deckhouse-oss/install:pr4012 user@35.198.97.148

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.24 4352268010 4352268010-1-con-1-24 /sys/deckhouse-oss/install:pr4012 centos@18.192.172.56

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 4352268010 4352268010-1-con-1-23 /sys/deckhouse-oss/install:pr4012 centos@18.185.35.196

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 4356266358 4356266358-1-con-1-23 /sys/deckhouse-oss/install:pr4012 centos@18.184.108.125

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 4356266358 4356266358-1-con-1-25 /sys/deckhouse-oss/install:pr4012 centos@3.73.137.243

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 4363978449 4363978449-1-con-1-25 /sys/deckhouse-oss/install:pr4012

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
@RomanenkoDenys All the check have passed.

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 4415370374 4415370374-1-con-1-25 /sys/deckhouse-oss/install:pr4012 centos@3.77.25.54

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.26 4415370374 4415370374-1-con-1-26 /sys/deckhouse-oss/install:pr4012 centos@3.73.115.167

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.26 4417154896 4417154896-1-con-1-26 /sys/deckhouse-oss/install:pr4012 centos@3.64.213.225

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.26 4424048284 4424048284-1-con-1-26 /sys/deckhouse-oss/install:pr4012 user@34.89.197.155

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 4424160788 4424160788-1-con-1-25 /sys/deckhouse-oss/install:pr4012 centos@3.76.54.84

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.25 4424153963 4424153963-1-con-1-25 /sys/deckhouse-oss/install:pr4012 user@34.141.55.122

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by duckhawk** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 4424455118 4424455118-1-con-1-25 /sys/deckhouse-oss/install:pr4012 cloud-user@84.201.172.211

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by duckhawk** [comment]
/e2e/abort vsphere;Standard;containerd;1.25 4424589548 4424589548-1-con-1-25 /sys/deckhouse-oss/install:pr4012

**Comment by duckhawk** [comment]
/e2e/abort openstack;Standard;containerd;1.25 4424588364 4424588364-1-con-1-25 /sys/deckhouse-oss/install:pr4012 debian@46.161.53.35

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by duckhawk** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 4424588288 4424588288-1-con-1-25 /sys/deckhouse-oss/install:pr4012 cloud-user@158.160.42.219

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by duckhawk** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 4424588294 4424588294-1-con-1-25 /sys/deckhouse-oss/install:pr4012 centos@54.93.207.49

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by duckhawk** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.25 4425521324 4425521324-1-con-1-25 /sys/deckhouse-oss/install:pr4012 user@34.159.213.51

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by duckhawk** [comment]
/e2e/abort vsphere;Standard;containerd;1.25 4425660071 4425660071-1-con-1-25 /sys/deckhouse-oss/install:pr4012 ubuntu@10.220.203.31

**Comment by duckhawk** [comment]
/e2e/abort openstack;Standard;containerd;1.25 4425659828 4425659828-1-con-1-25 /sys/deckhouse-oss/install:pr4012 debian@188.68.218.203

**Comment by duckhawk** [comment]
/e2e/abort azure;Standard;containerd;1.25 4425659745 4425659745-1-con-1-25 /sys/deckhouse-oss/install:pr4012 azureuser@4.231.29.42

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by duckhawk** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 4425659492 4425659492-1-con-1-25 /sys/deckhouse-oss/install:pr4012 centos@3.67.216.233

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...

**Comment by duckhawk** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 4426079126 4426079126-1-con-1-25 /sys/deckhouse-oss/install:pr4012 centos@3.76.87.47

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/openstack'...

**Comment by z9r5** [comment]
/e2e/abort static;Static;containerd;1.25 4425659792 4425659792-1-con-1-25 /sys/deckhouse-oss/install:pr4012 astra@192.168.199.66

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 4425659889 4425659889-1-con-1-25 /sys/deckhouse-oss/install:pr4012 cloud-user@158.160.36.4

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
