### PR TITLE
[docs] Fix article text in «Cloud provider — AWS: Preparing environment» page

### PR DESCRIPTION
**Pull request by Zhbert**
## Description

The "Cloud provider — AWS: Preparing environment" article reviewing and fixing.

## Changelog entries

```changes
module: docs
type: fix
description: "Review and fix the 'Cloud provider — AWS: Preparing environment' article."
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Running workflow "deploy/web/test"...

**Comment by deckhouse-BOaTswain** [comment]
Running workflow "deploy/web/test"...

**Comment by Zhbert** [comment]
@z9r5 Please check the updates of the first list.

**Comment by deckhouse-BOaTswain** [comment]
Running workflow "deploy/web/test"...

**Pull request merged**
