### PR TITLE
[kube-proxy] fix in kube-proxy DS template for static clusters

### PR DESCRIPTION
**Pull request by duckhawk**
## Description

Fix in kube-proxy DS template for static clusters.

## Why do we need it, and what problem does it solve?

After PR #3914 kube-proxy DS can't be rendered for static clusters, because there is no cloud section in cluster configuration.

## What is the expected result?

Kube-proxy DS template renders properly for static clusters.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: Fix in kube-proxy DS template for static clusters.
type: fix
summary: Fix `kube-proxy` DaemonSet rendering for static cluster.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by duckhawk** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4238475728 4238475728-1-con-1-23 /sys/deckhouse-oss/install:pr3927 cloud-user@84.201.172.220

**Comment by duckhawk** [comment]
/e2e/abort openstack;Standard;containerd;1.23 4238475720 4238475720-1-con-1-23 /sys/deckhouse-oss/install:pr3927 debian@45.94.123.248

**Comment by duckhawk** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.23 4238475470 4238475470-1-con-1-23 /sys/deckhouse-oss/install:pr3927 user@34.89.131.37

**Comment by duckhawk** [comment]
/e2e/abort static;Static;containerd;1.23 4238475338 4238475338-1-con-1-23 /sys/deckhouse-oss/install:pr3927 astra@192.168.199.118

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by duckhawk** [comment]
/e2e/abort vsphere;Standard;containerd;1.23 4238475323 4238475323-1-con-1-23 /sys/deckhouse-oss/install:pr3927 ubuntu@10.220.203.26

**Comment by duckhawk** [comment]
/e2e/abort azure;Standard;containerd;1.23 4238475176 4238475176-1-con-1-23 /sys/deckhouse-oss/install:pr3927 azureuser@74.234.184.66

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by duckhawk** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 4238475070 4238475070-1-con-1-23 /sys/deckhouse-oss/install:pr3927 centos@3.66.193.174

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by duckhawk** [comment]
/e2e/abort static;Static;containerd;1.23 4239647305 4239647305-1-con-1-23 /sys/deckhouse-oss/install:pr3927 astra@192.168.199.167

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by duckhawk** [comment]
/e2e/abort static;Static;containerd;1.23 4240450767 4240450767-1-con-1-23 /sys/deckhouse-oss/install:pr3927 astra@192.168.199.206

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by duckhawk** [comment]
/e2e/abort static;Static;containerd;1.23 4240594584 4240594584-1-con-1-23 /sys/deckhouse-oss/install:pr3927 astra@192.168.199.67

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...

**Comment by duckhawk** [comment]
/e2e/abort azure;Standard;containerd;1.23 4241260593 4241260593-1-con-1-23 /sys/deckhouse-oss/install:pr3927 azureuser@20.224.42.83

**Comment by duckhawk** [comment]
/e2e/abort vsphere;Standard;containerd;1.23 4241260469 4241260469-1-con-1-23 /sys/deckhouse-oss/install:pr3927 ubuntu@10.220.203.26

**Comment by duckhawk** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.23 4241260387 4241260387-1-con-1-23 /sys/deckhouse-oss/install:pr3927 user@34.159.103.68

**Comment by duckhawk** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4241260372 4241260372-1-con-1-23 /sys/deckhouse-oss/install:pr3927 cloud-user@51.250.68.127

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by duckhawk** [comment]
/e2e/abort static;Static;containerd;1.23 4241260142 4241260142-1-con-1-23 /sys/deckhouse-oss/install:pr3927 astra@192.168.199.250

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...

**Comment by duckhawk** [comment]
/e2e/abort static;Static;containerd;1.23 4243018823 4243018823-1-con-1-23 /sys/deckhouse-oss/install:pr3927 astra@192.168.199.97

**Comment by duckhawk** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 4243019567 4243019567-1-con-1-23 /sys/deckhouse-oss/install:pr3927 centos@3.66.50.18

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...

**Comment by duckhawk** [comment]
/e2e/abort static;Static;containerd;1.23 4243428476 4243428476-1-con-1-23 /sys/deckhouse-oss/install:pr3927

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by duckhawk** [comment]
/e2e/abort static;Static;containerd;1.23 4244005325 4244005325-1-con-1-23 /sys/deckhouse-oss/install:pr3927 astra@192.168.199.66

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by name212** [comment]
/e2e/abort static;Static;containerd;1.23 4244005325 4244005325-1-con-1-23 /sys/deckhouse-oss/install:pr3927 astra@192.168.199.66

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 4241260691 4241260691-1-con-1-23 /sys/deckhouse-oss/install:pr3927 centos@18.158.66.102

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Review by apolovov — APPROVED** [review]

**Pull request merged**
