### PR TITLE
[registrypackages] add growpart to rpp

### PR DESCRIPTION
**Pull request by sprait**
## Description

Add `growpart` with static linked dependency (`fdisk/sfdisk`) to registrypackages. 

## Why do we need it, and what problem does it solve?

Reducing dependency on the system's package manager repositories.

## What is the expected result?

growpart from registrypackages.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: registrypackages
type: feature
summary: Use growpart from registrypackages.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Comment by sprait** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 9743172478 9743172478-1-con-1-27 /sys/deckhouse-oss/install:pr8850 centos@3.65.172.243

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/azure'...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by sprait** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 9744855349 9744855349-1-con-1-27 /sys/deckhouse-oss/install:pr8850 centos@35.159.144.184

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
