### PR TITLE
[node-manager][deckhouse][user-authn] relax restriction on time.Duration settings

### PR DESCRIPTION
**Pull request by diafour**
## Description
Time units for hours and minutes can be used simultaneously:

- spec.ttl in User crd
- spec.chaos.period in NodeGroup crd
- minimalNotificationTime in 'deckhouse' module configuration

## Why do we need it, and what problem does it solve?
See #4199 

## What is the expected result?
Settings with time.Duration can use hours and minutes simultaneously.

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: fix
summary: hours and minutes can be used simultaneously in spec.chaos.period field of the NodeGroup
impact_level: default
```

```changes
section: deckhouse
type: fix
summary: hours and minutes can be used simultaneously for the minimalNotificationTime field in ModuleConfig
impact_level: default
```

```changes
section: user-authn
type: fix
summary: hours and minutes can be used simultaneously in spec.tls field of the User
impact_level: default
```

### CODE REVIEW

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by RomanenkoDenys** [comment]
need to set milestone and skip-documentation label

**Review by RomanenkoDenys — CHANGES_REQUESTED** [review]
Why didn't you add russian doc ?

**Comment by diafour** [comment]
> Why didn't you add russian doc ?

Good point! Done.

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @diafour. I've started the workflow for label 'e2e/run/aws'...

**Review by shvgn — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Review by yalosev — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Review by nabokihms — APPROVED** [review]

**Pull request merged**
