### PR TITLE
[candi] Update ccm.yandex versions

### PR DESCRIPTION
**Pull request by ilia601**
## Description
This PR updates candi/version_map.yml to use the latest changes in yandex-cloud-controller-manager

## Why do we need it, and what problem does it solve?
Because we want to use the latest changes in yandex-cloud-controller-manager

## What is the expected result?
The latest changes are used

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: candi/version_map.yml updated to use the latest changes in yandex-cloud-controller-manager
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by ilia601** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.31 11193665777 11193665777-1-con-1-31 /sys/deckhouse-oss/install:pr9855

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by ilia601** [comment]
Screenshot 2024-10-07 at 13 59 46
Screenshot 2024-10-07 at 14 01 18
Screenshot 2024-10-07 at 13 58 59

**Review by aleksey-su — APPROVED** [review]

**Review by name212 — APPROVED** [review]

**Pull request merged**
