### PR TITLE
[linstor] Enforce data locality

### PR DESCRIPTION
**Pull request by kvaps**
## Description

This pull request will prohibit the use of configurations with remotely accessible replicas. Instead, physical volumes will be reconfigured to be tied to specific nodes containing their data. The binding of volumes will now occur on-demand using the WaitForFirstConsumer method

However, DRBD diskless replicas can still be used as a tiebreaker to achieve quorum.

Although we have limited the use cases by no longer supporting data storage separate from workloads, the enforced data locality ensures improved disk subsystem performance.

Users can manually relocate replicas to nodes. The nodeAffinity rules in PVs will be automatically updated by the `linstor-affinity-controller`.

Users still have the ability to create custom storage classes where the use of DRBD diskless primaries will be allowed

## Why do we need it, and what problem does it solve?

As practice has shown, DRBD diskless primaries are unstable and still have some unpleasant bugs, which can only be solved by rebooting the nodes or manually editing the Linstor database.

On the other hand, diskful DRBD technology has been stable in the kernel for over the past 10 years. The recovery logic of diskful DRBD works much more predictably because such resources have state. They are better able to survive in case of an unstable network connection or slow disks.

## What is the expected result?

- StorageClasses will be reconfigured to allow run only on diskful replicas
- The nodeAffinity rules will be assigned the existing and new PVs.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: linstor
type: fix
summary: Enforce data locality.
impact: All the newly created persistent volumes will force to run workloads only on nodes with diskfull DRBD replicas, meaning that diskless primaries are no longer allowed. 
impact_level: high
```

### CODE REVIEW

**Review by z9r5 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...

**Comment by z9r5** [comment]
@kvaps e2e statis tests are broken. They will be fixed in a couple of days.

**Comment by z9r5** [comment]
/e2e/abort static;Static;containerd;1.23 4817246627 4817246627-1-con-1-23 /sys/deckhouse-oss/install:pr4500 astra@192.168.199.13

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Review by z9r5 — DISMISSED** [review]

**Comment by duckhawk** [comment]
@apolovov I think, this must be closed

**Comment by altermann1** [comment]
will be realized in external mudule.

**Pull request closed without merging**
