### PR TITLE
[candi] Fix AWSClusterConfiguration OpenAPI spec

### LINKED ISSUE #4956: [cloud-provider-aws] After adding etcdDisk the diskSizeGB parameter for CloudPermanent stopped working
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.46.8

### Expected Behavior

etcdDisk should not be inherited from the master ng and diskSizeGB should be taken into account.

### Actual Behavior

The server is created with the root disk of the default size, regardless of the specified size.

### Steps To Reproduce

kubectl -n d8-system exec -ti deploy/terraform-auto-converger -- dhctl config edit provider-cluster-configuration
```
piVersion: deckhouse.io/v1alpha1
kind: AWSClusterConfiguration
layout: WithoutNAT
masterNodeGroup:
  instanceClass:
    additionalSecurityGroups:
    - sg-.....
    ami: ami-0ec7f9846da6b0f61
    diskSizeGb: 50
    etcdDisk:
      sizeGb: 150
      type: gp3
    instanceType: m5.xlarge
  replicas: 3
nodeGroups:
- instanceClass:                                                      
    ami: ami-0ec7f9846da6b0f61                                        
    diskSizeGB: 50                                                    
    diskType: gp3                                                                                                        
    instanceType: t2.medium                                           
  name: etcd                                                          
  nodeTemplate:                                                       
    labels:                                                           
      node-role.flant.com/etcd: ""                                    
      node-role.kubernetes.io/etcd: ""                                
    taints:                                                           
    - effect: NoExecute                                               
      key: dedicated                                                  
      value: etcd                                                     
  replicas: 1                                                         
  zones:                                                              
  - eu-central-1a  
```

### Additional Information

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by artbin**
## Description

Remove anchor inheritance in the `AWSClusterConfiguration` OpenAPI specification. 

## Why do we need it, and what problem does it solve?

We need to remove the property `etcdDisk` in `nodeGroups`. This property is inherited from `masterNodeGroup` by mistake.  We can fix this if we avoid anchor inheritance.

Close #4956

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Remove the property `etcdDisk` in `nodeGroups` and remove anchor inheritance in the 'AWSClusterConfiguration' OpenAPI specification.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/aws'...

**Review by konstantin-axenov — APPROVED** [review]

**Comment by konstantin-axenov** [comment]
Rendered current version
```
cat cluster_configuration.yaml | yq -o json | yq -P > /tmp/cluster_configuration_new
```
Checkout and rendered previous
```
cat cluster_configuration.yaml | yq -o json | yq -P > /tmp/cluster_configuration_old
```
Diff seems correct.
```
diff /tmp/cluster_configuration_old /tmp/cluster_configuration_new 
291,302d290
<                   etcdDisk:
<                     type: object
<                     default:
<                       sizeGb: 20
<                       type: gp3
<                     properties:
<                       sizeGb:
<                         description: Etcd disk size in gigabytes.
<                         type: integer
<                       type:
<                         description: Etcd disk type.
<                         type: string
```

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 5441966521 5441966521-1-con-1-23 /sys/deckhouse-oss/install:pr4977 centos@3.78.144.223

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
