### PR TITLE
[monitoring-kubernetes] ebpf-exporter distroless

### PR DESCRIPTION
**Pull request by aleksey-su**
## Description
ebpf_exporter are now based on minimal image and bump version to v2.3.0.

## Why do we need it, and what problem does it solve?
We'd like to base our images on a distroless image.

## What is the expected result?
We use scratch along with a minimal number of files from Alpine packages. We pass files in packages though an rsync whitelist.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: monitoring-kubernetes
type: feature
summary: ebpf_exporter image are based on a distroless image and bump version to v2.3.0.
impact_level: default
```

### CODE REVIEW

**Comment by aleksey-su** [comment]
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Comment by aleksey-su** [comment]
/e2e/abort openstack;Standard;containerd;1.25 7499336599 7499336599-1-con-1-25 /sys/deckhouse-oss/install:pr6241 debian@5.159.103.43

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by aleksey-su** [comment]
/e2e/abort openstack;Standard;containerd;1.25 7499441341 7499441341-1-con-1-25 /sys/deckhouse-oss/install:pr6241 debian@5.159.103.92

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/aws'...

**Comment by aleksey-su** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 7499931876 7499931876-1-con-1-25 /sys/deckhouse-oss/install:pr6241 centos@18.194.100.199

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Review by nabokihms — APPROVED** [review]

**Pull request merged**
