### PR TITLE
[docs] Fix spelling mistakes, slang and formatting

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Fix spelling mistakes, slang and formatting in documentation.

## Changelog entries
```changes
section: docs
type: fix
summary: Fix spelling mistakes, slang and formatting in documentation.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by z9r5** [comment]
Cherry-picked into release-1.32

**Pull request merged**
