### PR TITLE
[docs] Site search refactoring

### PR DESCRIPTION
**Pull request by z9r5**
## Description

Refactoring documentation search:
- Separate search by documents and resources/parameters.
- First show Custom Resources, then parameters.
- Add only the latest versions of parameters to the search index.
- Fix a bug in the API version comparison algorithm.
- Show a fragment of the text corresponding to the search query in the snippet.
- Highlight words from the search query in the snippet.
- Allow using the `:` symbol in the search queries (e.g. `kind: user`).

Use unique anchors in resources (e.g. parameters on the https://deckhouse.io/documentation/v1/installing/configuration.html page have no resource name in the anchor).

Ref: [#326](https://github.com/deckhouse/deckhouse/issues/326?utm=ford_plain-number-sign)

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: docs
type: feature
summary: Improved search in the documentation on the site.
impact: low
---
section: deckhouse-web
type: feature
summary: Improved search in the documentation.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Review by ToyTox — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [3702](https://github.com/deckhouse/deckhouse/pull/3702) to the branch [release-1.43](https://github.com/deckhouse/deckhouse/tree/release-1.43) successful!

**Pull request merged**
