### PR TITLE
[user-authz] split serviceaccount in docs

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Description
Made the documentation for creating a ServiceAccount more understandable.

# Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: user-authz
type: fix 
summary:  Make the documentation for creating a ServiceAccount more understandable.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Review by kirkonru — APPROVED** [review]

**Review by MariaMakeeva — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Review by z9r5 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [7120](https://github.com/deckhouse/deckhouse/pull/7120) to the branch [release-1.56](https://github.com/deckhouse/deckhouse/tree/release-1.56) successful!

**Pull request merged**
