### PR TITLE
[candi] cluster-api static controller various improvements

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

1. Fix CAPI kubeconfig hook, which cannot work on fresh installations. Running this hook after helm deployment.

2. Send name of capi machine to the bootstrapped node to properly patch corresponding instance status field.

3. Instance for cluster-api static instance now enriched with logs info same as for cloud instances.
```
bootstrapStatus:
    description: Use 'nc x.x.x.x 8000' to get bootstrap logs.
    logsEndpoint: x.x.x.x:8000
```
To see the logs from instance run command from master node:
`nc x.x.x.x 8000` now tails logs.

Bootstrap logs now saved to `/opt/deckhouse/tmp/bootstrap.log`.

4. Removed shortNames from CAPI crds.

## Why do we need it, and what problem does it solve?

1. On the fresh install if we try to deploy NG with staticInstances field, we've got an error from deckhouse controller, due to improper order of running `generate_capi_static_kubeconfig_secret.go`. This hook runs before helm and fails due to absence cluster.x-k8s.io resource.

2. When we bootstrap static instance thru CAPS, we cannot properly patch status of instance resource, because instance resource name equals to CAPI machine name, but linux host name can differ from CAPI machine name. 

3. When we bootstrap cluster-api static instances we cannot see bootstrap logs from instance.

4. Cluster-api crds short names overlaps with our crds.
## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Send bootstrap logs from cluster-api static instances.
impact_level: default
---
section: candi
type: fix
summary: Fix CAPI kubeconfig hook, which cannot work on fresh installations.
impact_level: default
---
section: candi
type: fix
summary: Removed `shortNames` from CAPI CRDs.
impact_level: default
```

### CODE REVIEW

**Comment by RomanenkoDenys** [comment]
on bootstrap cloud node
nc x.x.x.x:8000
```
=== Step: /var/lib/bashible/bundle_steps/031_install_containerd.sh
===
bb-rp [INFO] Installing package 'containerd'
Created symlink /etc/systemd/system/multi-user.target.wants/containerd-deckhouse.service -> /lib/systemd/system/containerd-deckhouse.service.
bb-rp [INFO] Installing package 'crictl'
bb-rp [INFO] Installing package 'toml-merge'
===
=== Step: /var/lib/bashible/bundle_steps/034_install_kubelet_and_his_friends.sh
===
bb-rp [INFO] Installing package 'kubernetes-cni'
bb-rp [INFO] Installing package 'kubectl'
bb-rp [INFO] Installing package 'kubelet'
Created symlink /etc/systemd/system/multi-user.target.wants/kubelet.service -> /lib/systemd/system/kubelet.service.
===
=== Step: /var/lib/bashible/bundle_steps/039_add_kubectl_completion.sh
===
===
=== Step: /var/lib/bashible/bundle_steps/041_configure_sysctl_tuner.sh
===
Created symlink /etc/systemd/system/multi-user.target.wants/sysctl-tuner.timer -> /etc/systemd/system/sysctl-tuner.timer.
===
=== Step: /var/lib/bashible/bundle_steps/043_configure_kubectl_passwordless_sudo_for_flant.sh
===
===
=== Step: /var/lib/bashible/bundle_steps/050_configure_and_start_containerd.sh
===
bash [WARNING] 'containerd-need-restart' flag was set. Containerd should be restarted!
===
=== Step: /var/lib/bashible/bundle_steps/051_pull_and_configure_kubernetes_api_proxy.sh
===
Image is up to date for sha256:4370b5e5915fa12e15c6ac5a8313cec8d09ddd5d069ecc5fe6f1ad59bb06f6ff
===
=== Step: /var/lib/bashible/bundle_steps/060_install_kubernetes_ca.sh
===
```

**Comment by RomanenkoDenys** [comment]
CAPS Static instance:

```
root@dev-master-0:~# nc 192.168.199.81 8000
```

```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 http://nova.clouds.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:3 http://nova.clouds.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:4 http://nova.clouds.archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Fetched 338 kB in 1s (438 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
202 packages can be upgraded. Run 'apt list --upgradable' to see them.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
jq is already the newest version (1.6-2.1ubuntu3).
netcat-openbsd is already the newest version (1.218-4ubuntu1).
curl is already the newest version (7.81.0-1ubuntu1.14).
0 upgraded, 0 newly installed, 0 to remove and 202 not upgraded.
{
  "apiVersion": "deckhouse.io/v1alpha1",
  "kind": "Instance",
  "metadata": {
    "creationTimestamp": "2023-10-22T19:21:24Z",
    "finalizers": [
      "node-manager.hooks.deckhouse.io/instance-controller"
    ],
    "generation": 1,
    "labels": {
      "node.deckhouse.io/group": "static-worker"
    },
    "managedFields": [
      {
        "apiVersion": "deckhouse.io/v1alpha1",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:metadata": {
            "f:finalizers": {
              ".": {},
              "v:\"node-manager.hooks.deckhouse.io/instance-controller\"": {}
            },
            "f:labels": {
              ".": {},
              "f:node.deckhouse.io/group": {}
            },
            "f:ownerReferences": {
              ".": {},
              "k:{\"uid\":\"a18853c6-53c5-439c-89fb-c340ebd1df6c\"}": {}
            }
          }
        },
        "manager": "deckhouse-controller",
        "operation": "Update",
        "time": "2023-10-22T19:21:24Z"
      },
      {
        "apiVersion": "deckhouse.io/v1alpha1",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:status": {
            ".": {},
            "f:currentStatus": {
              ".": {},
              "f:lastUpdateTime": {},
              "f:phase": {}
            }
          }
        },
        "manager": "deckhouse-controller",
        "operation": "Update",
        "subresource": "status",
        "time": "2023-10-22T19:21:25Z"
      },
      {
        "apiVersion": "deckhouse.io/v1alpha1",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:status": {
            "f:bootstrapStatus": {
              ".": {},
              "f:description": {},
              "f:logsEndpoint": {}
            }
          }
        },
        "manager": "curl",
        "operation": "Update",
        "subresource": "status",
        "time": "2023-10-22T19:22:54Z"
      }
    ],
    "name": "static-worker-29hld-7s9jk",
    "ownerReferences": [
      {
        "apiVersion": "deckhouse.io/v1",
        "blockOwnerDeletion": false,
        "controller": false,
        "kind": "NodeGroup",
        "name": "static-worker",
        "uid": "a18853c6-53c5-439c-89fb-c340ebd1df6c"
      }
    ],
    "resourceVersion": "45400729",
    "uid": "1a94cbae-d481-471e-8c64-2d1c3ecfb9ec"
  },
  "status": {
    "bootstrapStatus": {
      "description": "Use 'nc 192.168.199.81 8000' to get bootstrap logs.",
      "logsEndpoint": "192.168.199.81:8000"
    },
    "currentStatus": {
      "lastUpdateTime": "2023-10-22T19:21:24Z",
      "phase": "Pending"
    }
  }
}Successfully patched instance dev-static-worker-0 status.
===
=== Step: /var/lib/bashible/bundle_steps/000_discover_node_ip.sh
===
===
=== Step: /var/lib/bashible/bundle_steps/000_set_flag_rolling_update.sh
===
===
=== Step: /var/lib/bashible/bundle_steps/001_configure_kubernetes_api_proxy.sh
===
===
=== Step: /var/lib/bashible/bundle_steps/001_waiting_approval_annotations.sh
===
===
=== Step: /var/lib/bashible/bundle_steps/002_abort_if_not_managed_docker.sh
===
===
=== Step: /var/lib/bashible/bundle_steps/002_add_system_proxy.sh
===
```

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/gcp'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort static;Static;containerd;1.25 6612110460 6612110460-1-con-1-25 /sys/deckhouse-oss/install:pr6252 astra@192.168.199.34

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/static'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort static;Static;containerd;1.25 6613806087 6613806087-1-con-1-25 /sys/deckhouse-oss/install:pr6252 astra@192.168.199.127

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/gcp'...

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [6301](https://github.com/deckhouse/deckhouse/pull/6301) to the branch [release-1.53](https://github.com/deckhouse/deckhouse/tree/release-1.53) successful!

**Comment by meatuses** [comment]
> Instance for cluster-api static instance now enriched with logs info same as for cloud instances.

Now executing `bootstrap.sh` on static nodes does not output setup log to `stdout` (terminal screen). Is this by design? Could be confusing, as you execute the script nothing happens until it exits.

**Pull request merged**
