### PR TITLE
[cni-cilium] Disabling the upload of the service image `base-cilium-dev` to the final container registry.

### PR DESCRIPTION
**Pull request by AndreyPavlovFlant**
## Description

Disabling the upload of the service image `base-cilium-dev` to the final container registry.

## Why do we need it, and what problem does it solve?

`base-cilium-dev` is a service build image and it should not be included in the final container registry.

## Why do we need it in the patch release (if we do)?

There should be no service images in the final container registry.

## What is the expected result?

There should be no service images in the final container registry.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cni-cilium
type: fix
summary: Disabling the upload of the service image `base-cilium-dev` to the final container registry.
impact: All cilium-agent pods will be restarted.
impact_level: default
```

### CODE REVIEW

**Review by Beastlex — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...

**Review by apolovov — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit ab32fb03b62dfd891ac393935d995e85a69c3fe1 to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/11238481920) for details.

**Comment by Taior** [comment]
Cherry-picked into release-1.64 (https://github.com/deckhouse/deckhouse/pull/10086)

**Pull request merged**
