### PR TITLE
[admission-policy-engine] Add deny-exec policy and exclude virtualization controller checks

### PR DESCRIPTION
**Pull request by yalosev**
## Description
Create the security exception for virtualization controllers. Virtualization controllers could create pods event with `restricted` pod security standards.
Also add `DenyExec` policy. But it has runtime limitations, we can deny execution only for pods in a specified namespace and couldn't select pods by labels, so it doesn't have integration in the runtime at the moment.

More reasons are described here: https://github.com/kubernetes/kubernetes/issues/113381

## Why do we need it in the patch release (if we do)?
We need it for Virtualization projects

## What is the expected result?
```sh
# kubectl exec -it nginx-deployment-77d8468669-hn7ht -- sh
Error from server (Forbidden): admission webhook "admission-policy-engine.deckhouse.io" denied the request: [deny-exec-nginx] Interactive exec is not permitted.
[deny-exec-nginx] Only ["ls"] commands are allowed.
```

```sh
# kubectl exec nginx-deployment-77d8468669-hn7ht -- df
Error from server (Forbidden): admission webhook "admission-policy-engine.deckhouse.io" denied the request: [deny-exec-nginx] Only ["ls"] commands are allowed.
```

```sh
# kubectl exec nginx-deployment-77d8468669-hn7ht -- ls
bin
boot
dev
etc
...
```

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: admission-policy-engine
type: feature
summary: Allow to create `virtualization` module's pods even in the restricted namespaces.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.26 10351548340 10351548340-1-con-1-26 /sys/deckhouse-oss/install:pr9316 ec2-user@18.197.255.113

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Review by miklezzzz — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...

**Comment by yalosev** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.26 10352920775 10352920775-1-con-1-26 /sys/deckhouse-oss/install:pr9316 ec2-user@35.156.125.188

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9349](https://github.com/deckhouse/deckhouse/pull/9349) to the branch [release-1.62](https://github.com/deckhouse/deckhouse/tree/release-1.62) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9350](https://github.com/deckhouse/deckhouse/pull/9350) to the branch [release-1.63](https://github.com/deckhouse/deckhouse/tree/release-1.63) successful!

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.26 10351548340 10351548340-1-con-1-26 /sys/deckhouse-oss/install:pr9316 ec2-user@18.197.255.113

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.26 10351548340 10351548340-2-con-1-26 /sys/deckhouse-oss/install:pr9316 ec2-user@3.78.101.220

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
