### PR TITLE
[chore] Update Kubernetes patch versions

### PR DESCRIPTION
**Pull request by nikiGGG**
## Description

Update Kubernetes patch versions:

- 1.26.12 ⇾ 1.26.13
- 1.27.9 ⇾ 1.27.10
- 1.28.5 ⇾ 1.28.6

## Why do we need it, and what problem does it solve?

It's important to bring fixes and to stay up to date with upstream.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: chore
summary: "Bump patch versions of Kubernetes images: `v1.26.13`, `v1.27.10`, `v1.28.6`"
impact: |
  Kubernetes control-plane components will restart, kubelet will restart.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by nikiGGG** [comment]
@RomanenkoDenys All checks passed.

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [7294](https://github.com/deckhouse/deckhouse/pull/7294) to the branch [release-1.57](https://github.com/deckhouse/deckhouse/tree/release-1.57) successful!

**Pull request merged**
