### PR TITLE
[cloud-provider-vcd] enable guest customization

### PR DESCRIPTION
**Pull request by sprait**
## Description

Enable guest customization in terraform configuration for master and cloud static nodes.

## Why do we need it, and what problem does it solve?

For success bootstrap nodes which use vcd template with disabled guest customization spec.

## What is the expected result?

Enable customization in terraform configuration:
image

image

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Enable guest customization in terraform configuration for master and cloud static nodes.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vcd'...

**Comment by sprait** [comment]
/e2e/abort vclouddirector;Standard;containerd;1.27 10005690183 10005690183-1-con-1-27 /sys/deckhouse-oss/install:pr9098 ubuntu@192.168.254.148

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vcd'...

**Comment by sprait** [comment]
/e2e/abort vclouddirector;Standard;containerd;1.27 10008099022 10008099022-1-con-1-27 /sys/deckhouse-oss/install:pr9098 ubuntu@192.168.254.158

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by sprait** [comment]
/e2e/abort vclouddirector;Standard;containerd;1.27 10007530342 10007530342-1-con-1-27 /sys/deckhouse-oss/install:pr9098 debian@10.210.17.36

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vcd'...

**Comment by sprait** [comment]
/e2e/abort vclouddirector;Standard;containerd;1.27 10010514219 10010514219-1-con-1-27 /sys/deckhouse-oss/install:pr9098 ubuntu@192.168.254.166

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vcd'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
