### PR TITLE
[test] Run tests for branch 1.56

### PR DESCRIPTION
**Pull request by nikiGGG**
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: test
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/azure'...

**Comment by nikiGGG** [comment]
/e2e/abort azure;Standard;containerd;1.24 7215134813 7215134813-1-con-1-24 /sys/deckhouse-oss/install:pr6893 azureuser@40.67.192.181

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by nikiGGG** [comment]
/e2e/abort static;Static;containerd;1.24 7214283365 7214283365-1-con-1-24 /sys/deckhouse-oss/install:pr6893 astra@192.168.199.194

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/aws'...

**Comment by nikiGGG** [comment]
/e2e/abort azure;Standard;containerd;1.24 7215134813 7215134813-2-con-1-24 /sys/deckhouse-oss/install:pr6893 azureuser@40.67.192.181

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by nikiGGG** [comment]
/e2e/abort vsphere;Standard;containerd;1.24 7223125080 7223125080-1-con-1-24 /sys/deckhouse-oss/install:pr6893 ubuntu@10.220.203.85

**Comment by nikiGGG** [comment]
/e2e/abort vsphere;Standard;containerd;1.25 7223125080 7223125080-1-con-1-25 /sys/deckhouse-oss/install:pr6893 ubuntu@10.220.203.86

**Comment by nikiGGG** [comment]
/e2e/abort vsphere;Standard;containerd;1.26 7223125080 7223125080-1-con-1-26 /sys/deckhouse-oss/install:pr6893 ubuntu@10.220.203.26

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by nikiGGG** [comment]
/e2e/abort vsphere;Standard;containerd;1.26 7223125080 7223125080-1-con-1-26 /sys/deckhouse-oss/install:pr6893 ubuntu@10.220.203.26

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/azure'...

**Comment by nikiGGG** [comment]
/e2e/abort azure;Standard;containerd;1.24 7226555030 7226555030-1-con-1-24 /sys/deckhouse-oss/install:pr6893

**Comment by nikiGGG** [comment]
/e2e/abort azure;Standard;containerd;1.25 7226555030 7226555030-1-con-1-25 /sys/deckhouse-oss/install:pr6893

**Comment by nikiGGG** [comment]
/e2e/abort azure;Standard;containerd;1.26 7226555030 7226555030-1-con-1-26 /sys/deckhouse-oss/install:pr6893

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by nikiGGG** [comment]
/e2e/abort static;Static;containerd;1.27 7227445432 7227445432-1-con-1-27 /sys/deckhouse-oss/install:pr6893 astra@192.168.199.213

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/eks'...

**Comment by nikiGGG** [comment]
/e2e/abort azure;Standard;containerd;1.27 7230249554 7230249554-1-con-1-27 /sys/deckhouse-oss/install:pr6893

**Comment by nikiGGG** [comment]
/e2e/abort azure;Standard;containerd;1.28 7230249554 7230249554-1-con-1-28 /sys/deckhouse-oss/install:pr6893

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by nikiGGG** [comment]
/e2e/abort openstack;Standard;containerd;1.25 7230880064 7230880064-1-con-1-25 /sys/deckhouse-oss/install:pr6893 debian@45.145.65.111

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/aws'...

**Comment by nikiGGG** [comment]
/e2e/abort azure;Standard;containerd;1.24 7232327161 7232327161-1-con-1-24 /sys/deckhouse-oss/install:pr6893

**Comment by nikiGGG** [comment]
/e2e/abort azure;Standard;containerd;1.27 7232327161 7232327161-1-con-1-27 /sys/deckhouse-oss/install:pr6893

**Comment by nikiGGG** [comment]
/e2e/abort azure;Standard;containerd;1.28 7232327161 7232327161-1-con-1-28 /sys/deckhouse-oss/install:pr6893

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by nikiGGG** [comment]
/e2e/abort openstack;Standard;containerd;1.26 7233162936 7233162936-1-con-1-26 /sys/deckhouse-oss/install:pr6893 debian@45.12.230.103

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by nikiGGG** [comment]
/e2e/abort openstack;Standard;containerd;1.25 7233155772 7233155772-1-con-1-25 /sys/deckhouse-oss/install:pr6893 debian@45.145.65.111

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by nikiGGG** [comment]
/e2e/abort vsphere;Standard;containerd;1.28 7237341377 7237341377-1-con-1-28 /sys/deckhouse-oss/install:pr6893 ubuntu@10.220.203.26

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/eks'...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.24 7225426191 7225426191-1-con-1-24 /sys/deckhouse-oss/install:pr6893 cloud-user@158.160.127.88

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort vsphere;Standard;containerd;1.24 7223125080 7223125080-1-con-1-24 /sys/deckhouse-oss/install:pr6893 ubuntu@10.220.203.85

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by nikiGGG** [comment]
/e2e/abort openstack;Standard;containerd;1.27 7322514087 7322514087-1-con-1-27 /sys/deckhouse-oss/install:pr6893 debian@31.129.32.249

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort openstack;Standard;containerd;1.25 7233155772 7233155772-2-con-1-25 /sys/deckhouse-oss/install:pr6893 debian@45.145.65.122

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/azure'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 7335934558 7335934558-1-con-1-27 /sys/deckhouse-oss/install:pr6893

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/vsphere'...

**Pull request closed without merging**
