### PR TITLE
[node-manager] NodeGroup convesion webhook rewrite to python

### PR DESCRIPTION
**Pull request by name212**
## Description
We have troubles with node groups conversion webhook, it is consuming a lot of cpu utilization.
We have an idea that python webhook will speed up and low memory utilization.

Also we added tests for python webhooks. In this iteration we added tests for group validation and nodegroup conversion webhook. Also added CI job for test verification.

Now all python requirements will add in build time with pip

## Why do we need it, and what problem does it solve?
Add testing framework for webhooks on python.
Try to improve cpu utilization for conversion node group conversion webhook.

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: chore
summary: NodeGroup convesion webhook rewrite to python
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by name212** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 12075708675 12075708675-1-con-1-27 /sys/deckhouse-oss/install:pr10777 redos@84.201.128.188

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Review by miklezzzz — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Review by sprait — APPROVED** [review]

**Review by yalosev — APPROVED** [review]

**Pull request merged**
