### PR TITLE
[descheduler] Do not deploy the descheduler if nodeSelector selects less then 2 nodes

### LINKED ISSUE #4703: [descheduler] Pod stuck in the CrashLoopBackOff state when a cluster size is 0 or 1
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.45.9

### Expected Behavior

I want descheduler module not to run at all if I have one node.

### Actual Behavior

The `descheduler` module runs and gets stuck in the CrashLoopBackOff state with a quite logical error message. As an admin/user, CrashLoopBackOffs scare me.

### Steps To Reproduce

0. **Edition:** EE, **OS:** AlterOS 7.5
1. Follow the installation steps for bare metal
2. Use default config
3. Untaint the only master node

### Additional Information

_No response_

### Logs

```shell
{"ts":1684742211918.2808,"msg":"The cluster size is 0 or 1 meaning eviction causes service disruption or degradation. So aborting..","v":1}
```

### PR DESCRIPTION
**Pull request by artbin**
## Description

Do not deploy the descheduler if nodeSelector selects less then 2 nodes.

## Why do we need it, and what problem does it solve?

Close #4703

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: descheduler
type: fix
summary: Set the number of replicas to 0 if we have only one node.
impact_level: default
```

### CODE REVIEW

**Comment by nabokihms** [comment]
This may not be that simple.
Because descheduler now has a node selector, it still may fail if the selector points to a single node, even if there is more than one not in the cluster. 

Have you tested this case? Could you please provide some testing results if so?

**Review by name212 — APPROVED** [review]

**Review by RomanenkoDenys — COMMENTED** [review]
golangci-lint job is failed, please rebase pr and fix.

**Comment by artbin** [comment]
Manual testing
==============

Get nodes:
```bash
kubectl get nodes
```

```
NAME                      STATUS   ROLES                  AGE   VERSION
akulyabin-main-master-0   Ready    control-plane,master   89d   v1.24.17
```

Create `Descheduler`:
```bash
kubectl create -f - <<EOF
apiVersion: deckhouse.io/v1alpha1
kind: Descheduler
metadata:
  name: test
spec:
  deschedulerPolicy:
    globalParameters:
      nodeSelector: group=worker
      evictFailedBarePods: true
    strategies:
      lowNodeUtilization:
        enabled: true
```

Get all pods in `d8-descheduler` namespace:
```bash
kubectl -n d8-descheduler get pods
```

```
No resources found in d8-descheduler namespace.
```

Get nodes:
```bash
kubectl get nodes
NAME                                         STATUS   ROLES                  AGE     VERSION
akulyabin-main-master-0                      Ready    control-plane,master   89d     v1.24.17
akulyabin-main-worker-c87545be-75fb6-2r47v   Ready    worker                 6m33s   v1.24.17
```

Get pods in `d8-descheduler` namespace:
```bash
kubectl -n d8-descheduler get pods
```

```
No resources found in d8-descheduler namespace.
```

Get nodes:
```bash
kubectl get nodes
NAME                                         STATUS   ROLES                  AGE     VERSION
akulyabin-main-master-0                      Ready    control-plane,master   89d     v1.24.17
akulyabin-main-worker-c87545be-75fb6-2r47v   Ready    worker                 18m     v1.24.17
akulyabin-main-worker-c87545be-75fb6-t8d78   Ready    worker                 8m44s   v1.24.17
```

Get pods in `d8-descheduler` namespace:
```bash
kubectl -n d8-descheduler get pods
```

```
No resources found in d8-descheduler namespace.
```

Add `group=worker` label to node:
```bash
kubectl label nodes akulyabin-main-worker-c87545be-75fb6-2r47v group=worker
```

```
node/akulyabin-main-worker-c87545be-75fb6-2r47v labeled
```

Get pods in `d8-descheduler` namespace:
```bash
kubectl -n d8-descheduler get pods
```

```
No resources found in d8-descheduler namespace.
```

Add `group=worker` label to node:
```bash
kubectl label nodes akulyabin-main-worker-c87545be-75fb6-t8d78 group=worker
```

```
node/akulyabin-main-worker-c87545be-75fb6-t8d78 labeled
```

Get pods in `d8-descheduler` namespace:
```bash
kubectl -n d8-descheduler get pods
NAME                                                              READY   STATUS    RESTARTS   AGE
descheduler-a94a8fe5ccb19ba61c4c0873d391e987982fbbd3-7bfbcgqdx5   1/1     Running   0          61s
```

Overwrite `group=worker` label to `group=worker2`:
```bash
kubectl label nodes --overwrite akulyabin-main-worker-c87545be-75fb6-t8d78 group=worker2
```

```
node/akulyabin-main-worker-c87545be-75fb6-t8d78 labeled
```

Get pods in `d8-descheduler` namespace:
```bash
kubectl -n d8-descheduler get pods
```

```
No resources found in d8-descheduler namespace.
```

**Comment by artbin** [comment]
> This may not be that simple. Because descheduler now has a node selector, it still may fail if the selector points to a single node, even if there is more than one not in the cluster.
> 
> Have you tested this case? Could you please provide some testing results if so?

Added a new implementation with a node selector. Tests are provided.

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [7257](https://github.com/deckhouse/deckhouse/pull/7257) to the branch [release-1.57](https://github.com/deckhouse/deckhouse/tree/release-1.57) successful!

**Pull request merged**
