### PR TITLE
[monitoring-kubernetes] grafana-dashboards edit node

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Description
added 'Storage Filesystem' -> 'Filesystem size'

## Why do we need it, and what problem does it solve?
adds information about the size of fs

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: monitoring-kubernetes
type: feature 
summary: Added 'Storage Filesystem' -> 'Filesystem size' in grafana-dashboard node.
impact_level: default 
```

### CODE REVIEW

**Comment by alexey-gavrilov-flant** [comment]
old
image

new
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 8323607497 8323607497-1-con-1-25 /sys/deckhouse-oss/install:pr7816 cloud-user@158.160.108.147

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by nabokihms — APPROVED** [review]

**Pull request merged**
