### PR TITLE
[core] Add Basic edition (BE)

### PR DESCRIPTION
**Pull request by name212**
## Description
Add basic edition (BE)
Refactor wef.yaml file for adding new edition without pain.
Basic edittion is CE + Russian OS'es support.
unfortunately we have not time for refactor CI and basic edition added by finding substring.
 
## Why do we need it, and what problem does it solve?
For business purposes  

## Why do we need it in the patch release (if we do)?
Business need it to end of month

## What is the expected result?

BE edition
image

EE edition
image
E2e for openstack was paseed https://github.com/deckhouse/deckhouse-test-2/actions/runs/7637781910/job/20807356154

CE edition
image
E2e https://github.com/deckhouse/deckhouse-test-2/actions/runs/7638866734

EE edition passed by e2e test for vsphere and openstack
## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: global
type: feature
summary: Add Deckhouse Kubernetes Platform Basic Вdition (BE).
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Backport failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/7694622707) for details.

**Comment by z9r5** [comment]
Cherry-picked into release-1.57

**Pull request merged**
