### PR TITLE
[docs] Fix the text of the articles in the section «Yandex.Cloud»

### PR DESCRIPTION
**Pull request by Zhbert**
## Description

The "Yandex.Cloud" section reviewing and fixing.

## Changelog entries

```changes
section: docs
type: fix
summary: "Review and fix the 'Yandex.Cloud' section."
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by z9r5** [comment]
Cherry-picked into release-1.31

**Comment by z9r5** [comment]
Cherry-picked into release-1.32

**Pull request merged**
