### PR TITLE
[dhctl] Sudo become password from non-interactive stdin

### PR DESCRIPTION
**Pull request by d2285**
## Description
Use sudo become password from non-interactive stdin with flag --ask-become-sudo. ex.:
`echo "PASSWORD" | dhctl bootstrap`

## Why do we need it, and what problem does it solve?

this allow to use become sudo password for non-interactive usage, if need for example ansible automation

## What is the expected result?
sudo become password get from non-interactive stdin

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: feature
summary: Sudo become password from non-interactive stdin. 
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @d2285. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @d2285. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @d2285. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @d2285. I've started the workflow for label 'e2e/run/static'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
