### PR TITLE
[bashible] add visibility of query errors to curl execution (#4439)

### PR DESCRIPTION
**Pull request by aleksey-su**
## Description
Add visibility of query errors to curl execution

## Why do we need it, and what problem does it solve?
issues #4439 Additional information about the error has occurred will help in investigating the causes.

## What is the expected result?
detailed information about the issues encountered in the request

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: bashible
type: feature
summary: Add visibility of query errors to curl execution
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — COMMENTED** [review]
Looks good but we need to see how it works in real cases.

**Comment by aleksey-su** [comment]
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — CHANGES_REQUESTED** [review]
improve output

**Comment by RomanenkoDenys** [comment]
I think use of "-S" option is more convenient. We will see error message but do not see the progress bar(https://www.cyberciti.biz/faq/curl-hide-progress-bar-output-linux-unix-macos/).

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]

**Review by yalosev — APPROVED** [review]

**Pull request merged**
