### PR TITLE
[dhctl] Support Deckhouse controller high availability mode during bootstrap

### PR DESCRIPTION
**Pull request by mvasl**
## Description

Dhctl will now corretcly handle multiple deckhouse pods in HA mode during bootstrap and detect which one to check via `d8-system/deckhouse-leader-election` lease object.

## Why do we need it, and what problem does it solve?

This is required as a HA mode for deckhouse deployment is the new default now

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: chore
summary: Support Deckhouse controller high availability mode during bootstrap.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/azure'...

**Comment by mvasl** [comment]
Initial bootstrap and converge with single master is fine

Снимок экрана 2024-03-28 в 14 05 20

Снимок экрана 2024-03-27 в 14 57 15

Scaling masters to 3 replicas works

Снимок экрана 2024-03-28 в 14 38 27

Converging 3 masters works (RAM increse in this case)
Снимок экрана 2024-03-28 в 14 58 49
Снимок экрана 2024-03-28 в 15 00 32

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/gcp'...

**Review by name212 — APPROVED** [review]

**Review by name212 — CHANGES_REQUESTED** [review]
Please remove this https://github.com/deckhouse/deckhouse/blob/2402932bdc7a55ba6e5bd50a2f8c50d727133ed6/dhctl/pkg/kubernetes/actions/manifests/manifests.go#L241-L256

And this https://github.com/deckhouse/deckhouse/blob/7c39b3f5729834318fe1141781295fca97660241/modules/002-deckhouse/templates/deployment.yaml#L71-L77

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/aws'...

**Review by name212 — APPROVED** [review]

**Review by aleksey-su — APPROVED** [review]

**Pull request merged**
