### PR TITLE
[dhctl] fix missing static preflight check

### LINKED ISSUE #5653: [dhctl] Preflight check that user in sudoers group
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

User that runs bootstrap.sh must be in sudoers group.

### Proposed Solution

Add check

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mvasl**
## Description

Added a preflight check to validate that bootstrapping user is able to run elevate priviliges using sudo

Closes #5653

## Why do we need it, and what problem does it solve?

We hit a case where root was not in sudoers file some time ago and it was not obvious what is wrong and how to fix the problem

## What is the expected result?

No change in happy path, error message if user cannot use sudo due to lack of privileges or incorrect password

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: added back missing preflight check for sudo access
impact_level: default
```

### CODE REVIEW

**Review by aleksey-su — APPROVED** [review]

**Comment by mvasl** [comment]
User is not in the sudoers file
Снимок экрана 2024-08-06 в 13 50 42

User is in the sudoers file
Снимок экрана 2024-08-06 в 13 51 19

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...

**Comment by mvasl** [comment]
/e2e/abort static;Static;containerd;1.27 10265179026 10265179026-1-con-1-27 /sys/deckhouse-oss/install:pr9290 astra@192.168.199.110

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by mvasl** [comment]
Static test flaked on CA certificates installation step, unrelated to sudo

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...

**Pull request merged**
