### PR TITLE
[control-plane-manager] fix checksum loop

### LINKED ISSUE #7134: [control-plane-manager] kube-apiserver is not restarted after checksum change on cluster bootstrap
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.56

### Expected Behavior

When we bootstrap cluster, kube-apiserver pod should be restarted and control checksum should be added

### Actual Behavior

kube-system/d8-control-plane-manager pod has not reached Ready state. Kube-apiserver is not restarted. Cluster bootstrap is not completed.

### Steps To Reproduce

1. Bootstrap new cluster

### Additional Information

kube-system/d8-contol-plane pod log
```
{"level":"warning","msg":"kubernetes pod kube-apiserver-cmdr-v-master-0 checksum  does not match expected checksum f52e83cf9217783e36a736e5776eb5513f531fc58f10dc8636af5de0c2c82f39","time":"2024-01-12T18:00:16Z"}
{"level":"warning","msg":"kubernetes pod kube-apiserver-cmdr-v-master-0 checksum  does not match expected checksum f52e83cf9217783e36a736e5776eb5513f531fc58f10dc8636af5de0c2c82f39","time":"2024-01-12T18:00:17Z"}
{"level":"warning","msg":"kubernetes pod kube-apiserver-cmdr-v-master-0 checksum  does not match expected checksum f52e83cf9217783e36a736e5776eb5513f531fc58f10dc8636af5de0c2c82f39","time":"2024-01-12T18:00:18Z"}
{"level":"warning","msg":"kubernetes pod kube-apiserver-cmdr-v-master-0 checksum  does not match expected checksum f52e83cf9217783e36a736e5776eb5513f531fc58f10dc8636af5de0c2c82f39","time":"2024-01-12T18:00:19Z"}
{"level":"warning","msg":"kubernetes pod kube-apiserver-cmdr-v-master-0 checksum  does not match expected checksum f52e83cf9217783e36a736e5776eb5513f531fc58f10dc8636af5de0c2c82f39","time":"2024-01-12T18:00:20Z"}
{"level":"warning","msg":"kubernetes pod kube-apiserver-cmdr-v-master-0 checksum  does not match expected checksum f52e83cf9217783e36a736e5776eb5513f531fc58f10dc8636af5de0c2c82f39","time":"2024-01-12T18:00:21Z"}
{"level":"warning","msg":"kubernetes pod kube-apiserver-cmdr-v-master-0 checksum  does not match expected checksum f52e83cf9217783e36a736e5776eb5513f531fc58f10dc8636af5de0c2c82f39","time":"2024-01-12T18:00:22Z"}
{"level":"warning","msg":"kubernetes pod kube-apiserver-cmdr-v-master-0 checksum  does not match expected checksum f52e83cf9217783e36a736e5776eb5513f531fc58f10dc8636af5de0c2c82f39","time":"2024-01-12T18:00:23Z"}
```

kube-apiserver manifest:
```
root@cmdr-v-master-0:~# cat /etc/kubernetes/manifests/kube-apiserver.yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    control-plane-manager.deckhouse.io/checksum: f52e83cf9217783e36a736e5776eb5513f531fc58f10dc8636af5de0c2c82f39
    control-plane-manager.deckhouse.io/kubernetes-version: "1.25"
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 10.241.32.13:6443
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --admission-control-config-file=/etc/kubernetes/deckhouse/extra-files/admission-control-config.yaml
    - --advertise-address=10.241.32.13
    - --allow-privileged=true
    - --anonymous-auth=false
    - --audit-log-format=json
    - --audit-log-maxage=7
    - --audit-log-maxbackup=10
    - --audit-log-maxsize=100
    - --audit-log-path=/var/log/kube-audit/audit.log
    - --audit-log-truncate-enabled=true
    - --audit-policy-file=/etc/kubernetes/deckhouse/extra-files/audit-policy.yaml
    - --authorization-mode=Node,RBAC
    - --bind-address=10.241.32.13
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --default-unreachable-toleration-seconds=300
    - --enable-admission-plugins=EventRateLimit,ExtendedResourceToleration,NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - |
      --etcd-servers=https://127.0.0.1:2379,https://10.241.32.13:2379
    - --feature-gates=TopologyAwareHints=true,RotateKubeletServerCertificate=true,DaemonSetUpdateSurge=true,EndpointSliceTerminatingCondition=true,InTreePluginRBDUnregister=true
    - --kubelet-certificate-authority=/etc/kubernetes/pki/ca.crt
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --profiling=false
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --request-timeout=300s
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-issuer=https://kubernetes.default.svc.cluster.local
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.222.0.0/16
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    image: registry.deckhouse.io/deckhouse/ee@sha256:2b900023910577f7958118b4cf08c0ee5cf7ed45edd6812f14a6e4d0b211e40e
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 10.241.32.13
        path: /livez
        port: 3990
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: kube-apiserver
    readinessProbe:
      failureThreshold: 3
      httpGet:
        host: 10.241.32.13
        path: /healthz
        port: 3990
        scheme: HTTP
      periodSeconds: 1
      timeoutSeconds: 15
    resources:
      requests:
        cpu: 488m
        memory: "1063004405"
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 10.241.32.13
        path: /livez
        port: 3990
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/kubernetes/deckhouse/extra-files
      name: deckhouse-extra-files
      readOnly: true
    - mountPath: /etc/ca-certificates
      name: etc-ca-certificates
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /var/log/kube-audit
      name: kube-audit-log
    - mountPath: /usr/local/share/ca-certificates
      name: usr-local-share-ca-certificates
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-share-ca-certificates
      readOnly: true
  - args:
    - --ca-cert=/secrets/ca.crt
    - --client-cert=/secrets/client.crt
    - --client-key=/secrets/client.key
    - --listen-address=10.241.32.13
    - --listen-port=3990
    - --api-server-address=10.241.32.13
    - --api-server-port=6443
    command:
    - /usr/local/bin/kube-apiserver-healthcheck
    image: registry.deckhouse.io/deckhouse/ee@sha256:d9059d07c797957a093eb13fbd46e6d987b9e2c0ac4bad17284641f1a278521e
    livenessProbe:
      httpGet:
        host: 10.241.32.13
        path: /.kube-apiserver-healthcheck/healthz
        port: 3990
      initialDelaySeconds: 5
      timeoutSeconds: 5
    name: healthcheck
    resources:
      requests:
        cpu: 29m
        memory: "64424509"
    volumeMounts:
    - mountPath: /secrets/ca.crt
      name: healthcheck-secrets-ca
      readOnly: true
    - mountPath: /secrets/client.crt
      name: healthcheck-secrets-client-crt
      readOnly: true
    - mountPath: /secrets/client.key
      name: healthcheck-secrets-client-key
      readOnly: true
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
  priority: 2000001000
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/ca.crt
      type: File
    name: healthcheck-secrets-ca
  - hostPath:
      path: /etc/kubernetes/pki/apiserver-kubelet-client.crt
      type: File
    name: healthcheck-secrets-client-crt
  - hostPath:
      path: /etc/kubernetes/pki/apiserver-kubelet-client.key
      type: File
    name: healthcheck-secrets-client-key
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/kubernetes/deckhouse/extra-files
      type: DirectoryOrCreate
    name: deckhouse-extra-files
  - hostPath:
      path: /etc/ca-certificates
      type: DirectoryOrCreate
    name: etc-ca-certificates
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /var/log/kube-audit
      type: DirectoryOrCreate
    name: kube-audit-log
  - hostPath:
      path: /usr/local/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-local-share-ca-certificates
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
status: {}
```
```
root@cmdr-v-master-0:~# ls -l /etc/kubernetes/manifests/kube-apiserver.yaml
-rw------- 1 root root 7278 Jan 12 12:02 /etc/kubernetes/manifests/kube-apiserver.yaml
```

### Logs

_No response_

### PR DESCRIPTION
**Pull request by sprait**
## Description

Fix infinite loop of checksum verification.

## Why do we need it, and what problem does it solve?

Closes #7134

In cases where the static manifest get changes while the kube-apiserver  is unavaliable, we may are stuck in an infinite loop. This behavior looks like a issue:
https://github.com/kubernetes/kubernetes/issues/109596#issuecomment-1219172244

## What is the expected result?

After 120 tries/seconds, we try to recreate static pod:

```
{"level":"warning","msg":"kubernetes pod kube-apiserver-dev-master-0 checksum  does not match expected checksum 079bac0150a77fbe9e1f1937fff87c941b91e2d469fd8c74a3d684fc506ebdbf","time":"2024-04-09T13:48:05Z"}
{"level":"warning","msg":"kubernetes pod kube-apiserver-dev-master-0 checksum  does not match expected checksum 079bac0150a77fbe9e1f1937fff87c941b91e2d469fd8c74a3d684fc506ebdbf","time":"2024-04-09T13:48:06Z"}
{"level":"warning","msg":"kubernetes pod kube-apiserver-dev-master-0 checksum  does not match expected checksum 079bac0150a77fbe9e1f1937fff87c941b91e2d469fd8c74a3d684fc506ebdbf","time":"2024-04-09T13:48:07Z"}
{"level":"warning","msg":"kubernetes pod kube-apiserver-dev-master-0 checksum  does not match expected checksum 079bac0150a77fbe9e1f1937fff87c941b91e2d469fd8c74a3d684fc506ebdbf","time":"2024-04-09T13:48:08Z"}
{"level":"warning","msg":"kubernetes pod kube-apiserver-dev-master-0 checksum  does not match expected checksum 079bac0150a77fbe9e1f1937fff87c941b91e2d469fd8c74a3d684fc506ebdbf","time":"2024-04-09T13:48:09Z"}
{"level":"warning","msg":"timeout waiting for pod kube-apiserver-dev-master-0 to become ready with expected checksum 079bac0150a77fbe9e1f1937fff87c941b91e2d469fd8c74a3d684fc506ebdbf","time":"2024-04-09T13:48:10Z"}
{"level":"error","msg":"trying to trigger kubelet to re-read manifest","time":"2024-04-09T13:48:12Z"}
{"level":"info","msg":"remove backups older than 5","time":"2024-04-09T13:48:12Z"}
```

```
Apr 09 13:48:10 dev-master-0 d8-kubelet-forker[1057915]: I0409 13:48:10.360952 1057915 kubelet.go:2399] "SyncLoop REMOVE" source="file" pods=["kube-system/kube-apiserver-dev-master-0"]
Apr 09 13:48:10 dev-master-0 d8-kubelet-forker[1057915]: I0409 13:48:10.361207 1057915 kuberuntime_container.go:745] "Killing container with a grace period" pod="kube-system/kube-apiserver-dev-master-0" podUID="afaa2e4b4613eaf5b2f692b321b8fe70" containerName="kube-apiserver" containerID="containerd://b273184bd90cf5a61f033cd4c5b960a1f38597c190bae2861b3913e479aa3b42" gracePeriod=30
Apr 09 13:48:10 dev-master-0 d8-kubelet-forker[1057915]: I0409 13:48:10.361281 1057915 kuberuntime_container.go:745] "Killing container with a grace period" pod="kube-system/kube-apiserver-dev-master-0" podUID="afaa2e4b4613eaf5b2f692b321b8fe70" containerName="healthcheck" containerID="containerd://52eacc53741f467ec4cfbd5646556f1f358c4084280370229bdca6cfafe166c1" gracePeriod=30
Apr 09 13:48:11 dev-master-0 d8-kubelet-forker[1057915]: I0409 13:48:11.092493 1057915 generic.go:334] "Generic (PLEG): container finished" podID="afaa2e4b4613eaf5b2f692b321b8fe70" containerID="52eacc53741f467ec4cfbd5646556f1f358c4084280370229bdca6cfafe166c1" exitCode=2
Apr 09 13:48:12 dev-master-0 d8-kubelet-forker[1057915]: E0409 13:48:12.361108 1057915 file.go:108] "Unable to process watch event" err="can't process config file \"/etc/kubernetes/manifests/kube-apiserver.yaml\": /etc/kubernetes/manifests/kube-apiserver.yaml: couldn't parse as pod(Object 'Kind' is missing in 'null'), please check config file"
Apr 09 13:48:12 dev-master-0 d8-kubelet-forker[1057915]: I0409 13:48:12.369141 1057915 kubelet.go:2389] "SyncLoop ADD" source="file" pods=["kube-system/kube-apiserver-dev-master-0"]
Apr 09 13:48:43 dev-master-0 d8-kubelet-forker[1057915]: I0409 13:48:43.330377 1057915 kubelet.go:2421] "SyncLoop (PLEG): event for pod" pod="kube-system/kube-apiserver-dev-master-0" event={"ID":"afaa2e4b4613eaf5b2f692b321b8fe70","Type":"ContainerStarted","Data":"b092d7a29298f625accfb8719f595393ae3cb0e1f0a1971678b75ea5322c80d0"}
Apr 09 13:48:43 dev-master-0 d8-kubelet-forker[1057915]: I0409 13:48:43.807910 1057915 kubelet_getters.go:187] "Pod status updated" pod="kube-system/kube-apiserver-dev-master-0" status="Running"
```

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: control-plane-manager
type: fix
summary: Fix infinite loop of checksum verification in control-plane-manager.
impact: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by sprait** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 8537260113 8537260113-1-con-1-25 /sys/deckhouse-oss/install:pr7983 redos@51.250.73.201

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by sprait** [comment]
/e2e/abort openstack;Standard;containerd;1.25 8618033421 8618033421-1-con-1-25 /sys/deckhouse-oss/install:pr7983 redos@5.159.102.50

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [8199](https://github.com/deckhouse/deckhouse/pull/8199) to the branch [release-1.59](https://github.com/deckhouse/deckhouse/tree/release-1.59) successful!

**Pull request merged**
