### PR TITLE
[deckhouse] update addon-operator version to v1.4.1

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
This pr updates addon-operator to v1.4.1 and fixes applying new registry settings after updating module source objects.

## Why do we need it, and what problem does it solve?
v1.4.1 of Addon-operator contains following improvements:
- modules' hooks discovery mechanism ignores `lib` subdirectories;
- a module's static values (values.yaml file) are ignored when calculating the module's values OpenAPI schema;
- Addon-operator of v1.4.1 uses Module Scheduler and Extenders at its core to standardize the process of deciding which modules should be enabled/disabled;
- Addon-operator of v1.4.1 provides stderr if a hooks fails (if any).

## What is the expected result?
Everything should work as expected (module converge/enable/disable processes, etc)

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse
type: feature
summary: Update addon-operator to v1.4.1.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/aws'...

**Comment by miklezzzz** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 9219718099 9219718099-1-con-1-25 /sys/deckhouse-oss/install:pr8285 centos@18.159.28.202

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by miklezzzz** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 9219718099 9219718099-1-con-1-25 /sys/deckhouse-oss/install:pr8285 centos@18.159.28.202

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/gcp'...

**Comment by miklezzzz** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.27 9778152871 9778152871-1-con-1-27 /sys/deckhouse-oss/install:pr8285 user@35.234.72.129 -

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by miklezzzz** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9778977922 9778977922-1-con-1-27 /sys/deckhouse-oss/install:pr8285 redos@51.250.87.6

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by miklezzzz** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9790409705 9790409705-1-con-1-27 /sys/deckhouse-oss/install:pr8285 redos@51.250.11.5

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/openstack'...

**Comment by miklezzzz** [comment]
/e2e/abort openstack;Standard;containerd;1.27 9792998545 9792998545-1-con-1-27 /sys/deckhouse-oss/install:pr8285 redos@45.12.231.199

**Comment by miklezzzz** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9791846437 9791846437-1-con-1-27 /sys/deckhouse-oss/install:pr8285 redos@51.250.93.168

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by yalosev — APPROVED** [review]

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.27 9778152871 9778152871-1-con-1-27 /sys/deckhouse-oss/install:pr8285 user@35.234.72.129

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
