### PR TITLE
[docs] Getting started and prometheus-metrics-adapter minor changes

### PR DESCRIPTION
**Pull request by z9r5**
Getting started and prometheus-metrics-adapter minor changes

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "deploy/web/test"...

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "deploy/web/test"...

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "deploy/web/stage"...

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "deploy/web/test"...

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "deploy/web/stage"...

**Comment by z9r5** [comment]
Cherry-picked into release-1.30

**Pull request merged**
