### PR TITLE
[l2-load-balancer] Cancelling the feature in favor of the renewed approach coming

### PR DESCRIPTION
**Pull request by apolovov**
## Description
The l2-load-balancer module is cancelled now. The new one with classic `Service` interface is under developing.

Reverting https://github.com/deckhouse/deckhouse/pull/7752 and some further fixes.

## Why do we need it, and what problem does it solve?
The module design is considered incorrect. It is important not to provide the new interfaces (`L2LoadBalancer`) when it is unnecessary (there is `Service`).

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: l2-load-balancer
type: chore
summary: The l2-load-balancer module is cancelled.
impact: The experimental l2-load-balancer module is not available anymore. A renewed one is coming soon.
impact_level: high
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Comment by apolovov** [comment]
/e2e/abort static;Static;containerd;1.25 9161721183 9161721183-2-con-1-25 /sys/deckhouse-oss/install:pr8429 astra@192.168.199.219

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Review by yalosev — APPROVED** [review]

**Review by Beastlex — APPROVED** [review]

**Comment by z9r5** [comment]
/e2e/abort static;Static;containerd;1.25 9161721183 9161721183-2-con-1-25 /sys/deckhouse-oss/install:pr8429 astra@192.168.199.219

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [8443](https://github.com/deckhouse/deckhouse/pull/8443) to the branch [release-1.60](https://github.com/deckhouse/deckhouse/tree/release-1.60) successful!

**Pull request merged**
