### PR TITLE
[ingress-nginx] add kruise state metrics

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
Kruise state metrics service has been added as a sidecar container to kruise-controller-manager deployment in d8-ingress-nginx namespace. This service provides metrics for advanced daemonsets create by kruise-controller manager, which are pretty similar to the metrics for original daemonsets. Also, several alerting rules has been add so as to get notifications in case Nginx Ingress daemonsets/pods experience some problems (like restarts, pending state, etc).

## Why do we need it, and what problem does it solve?
At the moment Nginx Ingress pods and daemonsets are lacking some basic monitoring and alerting.

## Why do we need it in the patch release (if we do)?
The changes implement vital monitoring and alerting functionality.

## What is the expected result?
The expected result is to get the relevant alerts firing in case there is an issue with Nginx Ingress pods.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: [ingress-nginx]
type: fix
summary: Add metrics and alerts for Nginx Ingress DaemonSets created by Kruise controller manager.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/aws'...

**Review by yalosev — APPROVED** [review]

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [4717](https://github.com/deckhouse/deckhouse/pull/4717) to the branch [release-1.45](https://github.com/deckhouse/deckhouse/tree/release-1.45) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [4718](https://github.com/deckhouse/deckhouse/pull/4718) to the branch [release-1.46](https://github.com/deckhouse/deckhouse/tree/release-1.46) successful!

**Pull request merged**
