### PR TITLE
[dhctl] feat(dhctl-for-commander): prepare dhctl for commander usage

### PR DESCRIPTION
**Pull request by distorhead**
## Description

This PR provides set of changes needed to perform management of clusters using dhctl-as-a-library approach as the first step:

1. Exposed dhctl commands in pkg/operations package and subpackages.
2. Added ability to pass initial state and on-phase callback for dhctl operations (bootstrap, converge, destroy and abort).
3. Added ability to set OutStream for dhctl logger.
4. Introduced a new explicit bootstrap phase called InstallAdditionalMastersAndStaticNodes.
5. Added ability to get dhctl-state from the cache after operation completion.

## Why do we need it, and what problem does it solve?

After this PR dhctl will acquire abilities to execute operations phases in synchonized way, ability to get intermediate dhctl-state, ability to pause operation execution when some phase has completed so that commander could safely save intermediate dhctl-state, and then continue operation execution.

At first step dhctl will be used as a library. Next step would imply usage of the dhctl from the official dhctl docker-image, but on top of the same interaction basics which introduced in the current PR (phased execution with callbacks and dhctl-state passing).

## Why do we need it in the patch release (if we do)?

Not necessarily.

## What is the expected result?

It is not expected that this PR will change dhctl-CLI behaviour in any way.
All additional functions needed for the commander added as options which are disabled by default.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

```changes
section: dhctl
type: feature
summary: Prepare dhctl for commander usage
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Comment by name212** [comment]
e2e passed, converge checked manually and it works

**Review by name212 — APPROVED** [review]

**Pull request merged**
