### PR TITLE
[candi] fix detecting bundle

### PR DESCRIPTION
**Pull request by kvaps**
## Description

This PR is fixing regression introduced by https://github.com/deckhouse/deckhouse/pull/2232

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [X] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: fix detecting bundle
impact: default
```

### CODE REVIEW

**Comment by kvaps** [comment]
```console
sh-3.2$ docker run -ti --rm -v ${PWD}/candi/bashible/detect_bundle.sh:/detect_bundle.sh centos:7 /detect_bundle.sh
centos
sh-3.2$ docker run -ti --rm -v ${PWD}/candi/bashible/detect_bundle.sh:/detect_bundle.sh quay.io/centos/centos:stream9 /detect_bundle.sh
centos
sh-3.2$ docker run -ti --rm -v ${PWD}/candi/bashible/detect_bundle.sh:/detect_bundle.sh rockylinux:9 /detect_bundle.sh
centos
sh-3.2$ docker run -ti --rm -v ${PWD}/candi/bashible/detect_bundle.sh:/detect_bundle.sh ubuntu:20.04 /detect_bundle.sh
ubuntu-lts
sh-3.2$ docker run -ti --rm -v ${PWD}/candi/bashible/detect_bundle.sh:/detect_bundle.sh ubuntu:22.04 /detect_bundle.sh
ubuntu-lts
sh-3.2$ docker run -ti --rm -v ${PWD}/candi/bashible/detect_bundle.sh:/detect_bundle.sh debian:9 /detect_bundle.sh
debian
sh-3.2$ docker run -ti --rm -v ${PWD}/candi/bashible/detect_bundle.sh:/detect_bundle.sh debian:10 /detect_bundle.sh
debian
```

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/gcp'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Review by nabokihms — CHANGES_REQUESTED** [review]
This PR changes logic of how deckhouse acts if there is no bundle detected. Previously it was always debian, but with the changes from this PR it fails.

This is a potentially huge breaking change.

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/aws'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM.

**Pull request merged**
