### PR TITLE
[prometheus] Drop some metrics

### PR DESCRIPTION
**Pull request by nabokihms**
Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>

## Why do we need it, and what problem does it solve?
In the past, we believed, that all metrics have their meaning. In case of an accident, we will be able to investigate any situation if we have as much information as possible. Unfortunately, there are deprecated/unneded/accidentally exported metrics. The only purpose for these metrics is to consume memory/disk of Prometheus instances.

* `node-exporter`:
    * veth interfaces metrics does not show any statistic, despite the id metric they are always nil
    * interrupts collector was enabled only for one rarely used dashboard, but its cardinality is too high
* `cadvisor`:
    * Has deprecated metrics
    * Has metrics that do not show any useful information (that are described in the code in detail)
* `kube-apiserver`:
    * There are too many buckets for latency metrics. It is ok to drop some of them.
* `deckhouse`:
    * _bucket metrics aren't useful to debug, having total values is enough. We can enable buckets later.

## What is the expected result?
Fewer metrics in Prometheus.

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests are passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: feature
summary: Do not collect some deprecated and unneeded metrics
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/azure'...

**Review by yalosev — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]
Please add metric name `apiserver_request_duration_seconds_bucket` to release message

**Pull request merged**
