### PR TITLE
[chore] Update K8s patch versions

### PR DESCRIPTION
**Pull request by z9r5**
## Description

Update Kubernetes patch versions:
- 1.24.16 ⇾ 1.24.17
- 1.25.12 ⇾ 1.25.13
- 1.26.7 ⇾ 1.26.8
- 1.27.4 ⇾ 1.27.5

## Why do we need it, and what problem does it solve?
It's important to bring fixes and to stay up to date with upstream.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: candi
type: chore
summary: "Bump patch versions of Kubernetes images: `v1.24.17`, `v1.25.13`, `v1.26.8`, `v1.27.5`.
impact: |
  Kubernetes control-plane components will restart, kubelet will restart.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 6009576573 6009576573-1-con-1-25 /sys/deckhouse-oss/install:pr5666

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.26 6009576573 6009576573-1-con-1-26 /sys/deckhouse-oss/install:pr5666

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Pull request merged**
