### PR TITLE
[ingress-nginx] add migration hook for updating kruise controller image before updating ingress-nginx module

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
Add migration hook for updating `kruise controller` deployment's image in `d8-ingress-nginx` namespace before updating `Ingress-Nginx` module so that a new version of `kruise controller` takes care of `Ingress-nginx` daemonsets during an update.
When executing, `ingress.deckhouse.io/force-max-unavailable` annotation is set to kruise controller deployment to prevent it from possible further updates by the hook. 
After updating the image, hook checks if a new `kruise controller` deployment is up and ready (up to 10 seconds so as not to block the whole update) and exits.

## Why do we need it, and what problem does it solve?
Previous kruise controller version can cause an ingress-nginx outage by updating multiple (all) ingress-nginx pods at the same time.

## Why do we need it in the patch release (if we do)?
Upcoming releases may trigger an undesirable update strategy in case an old kruise controller deployment starts updating ingress-nginx daemonsets.

## What is the expected result?
Kruise controller manager deployment gets updated  before updating Deckhouse Ingress-Nginx module to ensure that the previous version of kruise control doesn't have an opportunity to initiate daemonsets' updates.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: ingress-nginx
type: fix
summary: Update kruise controller manager deployment before updating Ingress-Nginx module so that an updated kruise controller takes care of Ingress-Nginx demonsets.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by miklezzzz — COMMENTED** [review]
debatable how long should we wait

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by yalosev — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [5088](https://github.com/deckhouse/deckhouse/pull/5088) to the branch [release-1.47](https://github.com/deckhouse/deckhouse/tree/release-1.47) successful!

**Comment by deckhouse-BOaTswain** [comment]
Backport failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/5422418717) for details.

**Comment by deckhouse-BOaTswain** [comment]
Backport failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/5422418717) for details.

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [5103](https://github.com/deckhouse/deckhouse/pull/5103) to the branch [release-1.46](https://github.com/deckhouse/deckhouse/tree/release-1.46) successful!

**Pull request merged**
