### PR TITLE
[secret-copier] Keep annotations on copied secrets

### PR DESCRIPTION
**Pull request by haosb**
## Description

Keep annotations from the main secret on copied secrets.

## Why do we need it, and what problem does it solve?
In some cases, we need to keep annotations.

## What is the expected result?
After secret-copier copy the main secret, we can see on copied secrets all annotations from the main secret.

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: secret-copier
type: feature
summary: Added the ability to keep annotations in copied secrets
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @haosb. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @haosb. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @haosb. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @haosb. I've started the workflow for label 'e2e/run/aws'...

**Comment by haosb** [comment]
Loops are fixed if Secret have `namespace-selector`. I just keep annotation, because this annotation only works if secret in `default` namespace.

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @haosb. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @haosb. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @haosb. I've started the workflow for label 'e2e/run/aws'...

**Pull request closed without merging**
