### PR TITLE
[docs] Fixed command at ModulePullOverride

### PR DESCRIPTION
**Pull request by mortelumina98**
## Description
Fixed incorrect spelling of the command at ModulePullOverride.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

```changes
section: docs
type: fix
summary: Fixed incorrect spelling of the command at ModulePullOverride.
impact_level: low
```

### CODE REVIEW

**Review by z9r5 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10058](https://github.com/deckhouse/deckhouse/pull/10058) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10059](https://github.com/deckhouse/deckhouse/pull/10059) to the branch [release-1.63](https://github.com/deckhouse/deckhouse/tree/release-1.63) successful!

**Pull request merged**
