### PR TITLE
[cloud-provider-aws] Added the ability to specify your IAM role

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Description
added documentation about ECR repository configuration and the ability to specify your iam role

## Why do we need it, and what problem does it solve?
Close https://github.com/deckhouse/deckhouse/issues/7167

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-aws
type: feature
summary: Added the ability to specify your IAM role.
impact_level: default
```

### CODE REVIEW

**Review by Zhbert — APPROVED** [review]

**Review by z9r5 — APPROVED** [review]

**Review by name212 — APPROVED** [review]

**Review by aleksey-su — APPROVED** [review]

**Comment by name212** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11254029584 11254029584-1-con-1-27 /sys/deckhouse-oss/install:pr9530 ec2-user@18.199.14.228

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Review by nabokihms — APPROVED** [review]
API - approve

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/aws'...

**Pull request merged**
