### PR TITLE
[cloud-provider-zvirt] Fix zvirt token refresh

### PR DESCRIPTION
**Pull request by m1ron0xFF**
## Description
`CSI` / `capz-controller-manager` don't refresh zvirt oauth token and can't access zvirt API after token expiration. 

## Why do we need it, and what problem does it solve?
This PR fixes zvirt token refresh on its expiration. 

## What is the expected result?
zvirt oauth token should be renewed and API should be accessible. 

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-zvirt
type: fix
summary: fix zvirt SDK API token refresh
impact_level: default
```

### CODE REVIEW

**Comment by m1ron0xFF** [comment]
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @m1ron0xFF. I've started the workflow for label 'e2e/run/openstack'...

**Comment by m1ron0xFF** [comment]
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @m1ron0xFF. I've started the workflow for label 'e2e/run/openstack'...

**Review by sprait — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @m1ron0xFF. I've started the workflow for label 'e2e/run/openstack'...

**Review by aleksey-su — APPROVED** [review]

**Pull request merged**
