### PR TITLE
[cloud-provider-vcd] Fix impossibility to use 0 as value of Max IOPS in storage policy

### PR DESCRIPTION
**Pull request by name212**
## Description
Fix build csi-controller. Use right command for apply patch

## Why do we need it, and what problem does it solve?
CSI controller cannot work with storage policy using 0 as Max IOPS 

## Why do we need it in the patch release (if we do)?

Affect new clients

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-vcd
type: fix
summary: Fix impossibility to use 0 as value of Max IOPS in storage policy
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/vcd'...

**Review by RomanenkoDenys — APPROVED** [review]
Good work

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9235](https://github.com/deckhouse/deckhouse/pull/9235) to the branch [release-1.62](https://github.com/deckhouse/deckhouse/tree/release-1.62) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9238](https://github.com/deckhouse/deckhouse/pull/9238) to the branch [release-1.63](https://github.com/deckhouse/deckhouse/tree/release-1.63) successful!

**Pull request merged**
