### PR TITLE
[dhctl] One flag for resources and configs in bootstrap command

### PR DESCRIPTION
**Pull request by name212**
## Description
Use one flag `--config` multiple times for logical separation bootstrap configuration.
`--resources` flag is deprecated now.

## Why do we need it, and what problem does it solve?
Improve the user experience

## What is the expected result?

image

image

image

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: feature
summary: One flag for resources and configs in bootstrap command
impact: In bootstrap command please use multiple --config flag for logical separation bootstrap configuration. --resources flag is deprecated now. 
impact_level: high
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by name212** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.25 8851647756 8851647756-1-con-1-25 /sys/deckhouse-oss/install:pr8277 user@34.141.69.7

**Comment by name212** [comment]
/e2e/abort static;Static;containerd;1.25 8851647564 8851647564-1-con-1-25 /sys/deckhouse-oss/install:pr8277 astra@192.168.199.207

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by name212** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.25 8851647756 8851647756-1-con-1-25 /sys/deckhouse-oss/install:pr8277 user@34.141.69.7

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Comment by name212** [comment]
/e2e/abort static;Static;containerd;1.25 8858129546 8858129546-1-con-1-25 /sys/deckhouse-oss/install:pr8277 astra@192.168.199.216

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Review by aleksey-su — APPROVED** [review]

**Review by distorhead — APPROVED** [review]

**Pull request merged**
