### PR TITLE
[distroless] move cloud-data-discoverer binaries to distroless

### PR DESCRIPTION
**Pull request by universal-itengineer**
## Description

cloud-data-discoverer binaries use distroless images and built from our repos instead of using alpine:go images.

- [x] cloud-provider-aws
- [x] cloud-provider-azure
- [x] cloud-provider-gcp
- [x] ee/cloud-provider-openstack

## Why do we need it, and what problem does it solve?

This PR is a part of moving Deckhouse to distroless.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-aws
type: chore
summary: "`cloud-data-discoverer` use distroless based image."
impact_level: default
---
section: cloud-provider-azure
type: chore
summary: "`cloud-data-discoverer` use distroless based image."
impact_level: default
---
section: cloud-provider-gcp
type: chore
summary: "`cloud-data-discoverer` use distroless based image."
impact_level: default
---
section: ee/cloud-provider-openstack
type: chore
summary: "`cloud-data-discoverer` use distroless based image."
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Review by konstantin-axenov — APPROVED** [review]

**Pull request merged**
