### PR TITLE
[e2e] update redos ver for e2e

### PR DESCRIPTION
**Pull request by sprait**
## Description

Redos image update in e2e.

## Why do we need it, and what problem does it solve?

For using actual redos version in e2e.

## What is the expected result?

e2e with redos 7.3.4 was passed:
openstack:
image
https://github.com/deckhouse/deckhouse/actions/runs/8392076004

static:
image
https://github.com/deckhouse/deckhouse/actions/runs/8417452675

yandex-cloud:
image
https://github.com/deckhouse/deckhouse/actions/runs/8418482812

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: chore
summary: redos version image update in e2e.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by sprait** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 8418217785 8418217785-1-con-1-25 /sys/deckhouse-oss/install:pr7888 cloud-user@178.154.202.0

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Review by name212 — APPROVED** [review]

**Pull request merged**
