### PR TITLE
[user-authn] fixed if idTokenTTL > keepUsersLoggedInFor

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Description
Fix boundary value when [idTokenTTL](https://deckhouse.io/documentation/v1/modules/150-user-authn/configuration.html#parameters-idtokenttl) is too large.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: user-authn
type: fix 
summary: Fix boundary value when `idTokenTTL` is too large.
impact_level: default 
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by alexey-gavrilov-flant** [comment]
`/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 8526379310 8526379310-1-con-1-27 /sys/deckhouse-oss/install:pr7903 redos@158.160.38.171`

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 8526379310 8526379310-1-con-1-27 /sys/deckhouse-oss/install:pr7903 redos@158.160.38.171

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Review by nabokihms — CHANGES_REQUESTED** [review]
Parsing duration format using regex looks fragile. Helm has all the necessary functions to compare durations.

[There is an example](https://helm-playground.com/#t=N7C0AIBMFMDMEsB21wCIC2SD6kCuAnAQwBd4B7RVcUAXxoChxwQIASSARnAC4BecJDAAe4AHTgutBkxbh2AJh79B0EeMl1GzMHJgAbYoSXhEZAO7VNM4ANjgA5sXAAKdtANGAPuHS4AzsQAIiTQALJkkPCwAJ66XN64iPBCAKIADmQAxgAWAJQubh7g3r4BwcRhEVGxCsXgicnpWXmWDLK1UkzgWrLufihS9O2c4FbaENCIkK1DOpPTg-Sgy-SqhOhpetDc2gKImXq4MGiYiDgEJOSULnrwAWjy6FSoAMx%2BqPmaaxtb8jsgewORxQGGweCIpAoVGct3uqA42XkAAZ0G9nhwUR9RgxvptoC9-jYkEDjqCzuDLlCbncnK8kX4EejMZ8cUJ1niACyEwGHUmnc4Qq7Q2G0l70xloBFi94s1Zsn7QACs3OJvJB-IpkOuMJpkuy0ue0sZsvoQA&v=LQhQEsBcFMFsGcBcACA2gIgGbgE70ugDTLrzQDGA9gHYAm6AuqEA) of how you can compare two durations using the `mustDateModify` function. 
1. This helper makes the code more bulletproof because it uses [default go time.ParseDuration and Add functions](https://github.com/Masterminds/sprig/blob/581758eb7d96ae4d113649668fa96acc74d46e7f/date.go#L58-L64).
2. It is easier to read the code because there are no ifs in templates (only in the helper).

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 8600236858 8600236858-1-con-1-27 /sys/deckhouse-oss/install:pr7903 redos@178.154.202.205

**Review by name212 — APPROVED** [review]

**Review by nabokihms — APPROVED** [review]

**Pull request merged**
