### PR TITLE
[node-manager] fix instance controller hook

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

Fix instance-controller hook.
## Why do we need it, and what problem does it solve?

Reduce fields in instance filter to prevent hook start on changing managed fields.

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: chore
summary: Fix instance controller hook.
impact_level: default
```

### CODE REVIEW

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10737547504 10737547504-1-con-1-27 /sys/deckhouse-oss/install:pr9639

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9642](https://github.com/deckhouse/deckhouse/pull/9642) to the branch [release-1.63](https://github.com/deckhouse/deckhouse/tree/release-1.63) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9643](https://github.com/deckhouse/deckhouse/pull/9643) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!

**Pull request merged**
