### PR TITLE
[log-shipper] Add buffer to the examples

### PR DESCRIPTION
**Pull request by hugik-88**
## Description

Add buffer to the module examples
## Why do we need it, and what problem does it solve?

In some clusters, there were problems with the log-shipper module in case of disk overflow. Added buffering to the examples to prevent unexpected problems with the cluster
## Why do we need it in the patch release (if we do)?

Not necessary
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: log-shipper
type: chore 
summary: In standard examples buffering becomes possible.
impact_level: low
```

### CODE REVIEW

**Review by nabokihms — CHANGES_REQUESTED** [review]
Instead of adding buffer to all examples, you need to add a new example with buffer settings and describe what is required to configure. As we discussed internally, it is good to provide an example of how to drop new events when the buffer is full (and increase the in-memory buffer events limit).

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @hugik-88. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @hugik-88. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @hugik-88. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @hugik-88. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @hugik-88. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @hugik-88. I've started the workflow for label 'deploy/web/test'...

**Comment by hugik-88** [comment]
> Instead of adding buffer to all examples, you need to add a new example with buffer settings and describe what is required to configure. As we discussed internally, it is good to provide an example of how to drop new events when the buffer is full (and increase the in-memory buffer events limit).

I tried to take into account all the wishes in the corrected version

**Review by z9r5 — APPROVED** [review]

**Pull request merged**
