### PR TITLE
[dhctl] fix cluster configuration secret name label

### PR DESCRIPTION
**Pull request by ipaqsa**
## Description
It sets the 'name' label to the 'd8-cluster-configuration' secret.

## Why do we need it, and what problem does it solve?
Deckhouse controller caches the 'd8-cluster-configuration' secret by the 'name' label. This label was removed, and deckhouse cannot check k8s automatic version.

## What is the expected result?
Deckhouse can check k8s automatic version

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Add the 'name' label to the 'd8-cluster-configuration' secret.
impact_level: low
```

### CODE REVIEW

**Review by yalosev — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...

**Review by name212 — APPROVED** [review]

**Comment by yalosev** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.29 12232580565 12232580565-1-con-1-29 /sys/deckhouse-oss/install:pr10994 ec2-user@3.125.16.97

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [11010](https://github.com/deckhouse/deckhouse/pull/11010) to the branch [release-1.66](https://github.com/deckhouse/deckhouse/tree/release-1.66) successful!

**Pull request merged**
