### PR TITLE
[deckhouse] fix the number of replicas if cluster isn't bootstrapped and add extra labels

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
- Throws in a conditional for the replicas number of the Deckhouse deployment to set it to 1 if the cluster isn't bootstrapped yet.
- Adds a hook to to check if a master node has a kube-apiserver pod running and ready and label the node with `node.deckhouse.io/deckhouse-ready: true/false` label.
- Adds nodeAfinity of preferredDuringScheduling type to the deckhouse deployment so that it would prefer to be scheduled on the masters with the `node.deckhouse.io/deckhouse-ready: true` labels. 

## Why do we need it, and what problem does it solve?
Without checking whether the cluster is bootstrapped or not it's not safe to set the Deckhouse deployment replicas to something bigger than 1 as it may end up having multiple Deckhouse instances, running simulateneously, in the cluster.
Also, extra labels on master nodes and the dechkouse deployment's nodeAffinity settings should help circumvent in a situation when not all master nodes are ready to run a deckhouse pod.

## Why do we need it in the patch release (if we do)?
It's a moderate bug affecting bootstrapping new multi-master clusters.

## What is the expected result?
If a cluster isn't bootstrapped, it must have Deckhouse running in 1 replica and HA mode must be disabled.

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse
type: fix
summary: Fix the number of deckhouse replicas for not bootstrapped clusters.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/aws'...

**Review by yalosev — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/eks'...

**Comment by yalosev** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.25 9314834504 9314834504-1-con-1-25 /sys/deckhouse-oss/install:pr8526

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [8574](https://github.com/deckhouse/deckhouse/pull/8574) to the branch [release-1.60](https://github.com/deckhouse/deckhouse/tree/release-1.60) successful!

**Pull request merged**
