### PR TITLE
[candi] Disable managing foreign ip rules by systemd-networkd

### PR DESCRIPTION
**Pull request by AndreyPavlovFlant**
## Description

  Disable managing "foreign" ip rules by systemd-networkd.

## Why do we need it, and what problem does it solve?

By default, `systemd-networkd` manages **all** `IP rules` on a node.
After starting `cilium-agent` on the node, it rewrites the standard `IP-rules` and adds its own.
If you run the `netplan apply` command or restart `systemd-networkd`, all "foreign" IP rules will be removed and the node will become unavailable.

  Fixes https://github.com/deckhouse/deckhouse/issues/5709.

## What is the expected result?

  After changing network settings using `systemd-networkd` (for example, using the `netplan apply` command), the "foreign" `ip rules` are not removed and host does not become unreachable.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Disable managing "foreign" ip rules by systemd-networkd.
impact: systemd-networkd.service will be restarted to apply the settings.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Comment by apolovov** [comment]
/e2e/abort static;Static;containerd;1.25 6893343196 6893343196-1-con-1-25 /sys/deckhouse-oss/install:pr6561

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Comment by RomanenkoDenys** [comment]
Approve, but need exact description why node is unreachable after `netplan apply`.

**Comment by AndreyPavlovFlant** [comment]
In all systems, two rt_tables are created by default: 
- `local` - this table contains routes to all server ip addresses that are assigned on its interfaces (/32), broadcast addresses, and 127.0.0.0/8. 
- `main` is the main routing table we usually work with. 

Two ip rules are also created for lookups in them:
`0: from all lookup local`.
`32766: from all lookup main`.
* The `lookup local` rule must be "higher" than `lookup main`.

cilium-agent changes rule priority for the default rule `from all lookup local` from 0 to 100 (deletes a rule with priority 0 and recreates it with priority 100).

systemd-networkd deletes all rules created by something else after each restart.

This removes the rule (`#100 from all lookup local`) that allowed local table lookup and routing traffic to local addresses.

It becomes impossible to determine that arrived the traffic is destined to the ip interfaces of the server itself. In fact it does not get into the INPUT chain.

Traffic stops reaching applications.

**Pull request merged**
