### PR TITLE
debug

### PR DESCRIPTION
**Pull request by vitaliy-sn**
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by vitaliy-sn** [comment]
/e2e/abort static;Static;containerd;1.27 7274529979 7274529979-1-con-1-27 /sys/deckhouse-oss/install:pr6283 astra@192.168.199.155

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...

**Comment by vitaliy-sn** [comment]
/e2e/abort static;Static;containerd;1.28 7275063981 7275063981-1-con-1-28 /sys/deckhouse-oss/install:pr6283

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...

**Comment by vitaliy-sn** [comment]
/e2e/abort static;Static;containerd;1.27 7274852169 7274852169-2-con-1-27 /sys/deckhouse-oss/install:pr6283 astra@192.168.199.238

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by vitaliy-sn** [comment]
/e2e/abort static;Static;containerd;1.28 7275200555 7275200555-1-con-1-28 /sys/deckhouse-oss/install:pr6283 astra@192.168.199.231

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort static;Static;containerd;1.27 7274852169 7274852169-1-con-1-27 /sys/deckhouse-oss/install:pr6283 astra@192.168.199.95

**Comment by z9r5** [comment]
/e2e/abort static;Static;containerd;1.27 7274852169 7274852169-1-con-1-27 /sys/deckhouse-oss/install:pr6283 astra@192.168.199.95

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by vitaliy-sn** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 8660159700 8660159700-1-con-1-27 /sys/deckhouse-oss/install:pr6283 ubuntu@10.220.203.26

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by vitaliy-sn** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 8660769784 8660769784-1-con-1-27 /sys/deckhouse-oss/install:pr6283 ubuntu@10.220.203.70

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by vitaliy-sn** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 8665456904 8665456904-1-con-1-27 /sys/deckhouse-oss/install:pr6283 ubuntu@10.220.203.75

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by vitaliy-sn** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 8665456904 8665456904-1-con-1-27 /sys/deckhouse-oss/install:pr6283 ubuntu@10.220.203.75

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by vitaliy-sn** [comment]
/e2e/abort vsphere;Standard;containerd;1.26 8666641450 8666641450-1-con-1-26 /sys/deckhouse-oss/install:pr6283 ubuntu@10.220.203.75

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by vitaliy-sn** [comment]
/e2e/abort vsphere;Standard;containerd;1.26 8679776587 8679776587-1-con-1-26 /sys/deckhouse-oss/install:pr6283 ubuntu@10.220.203.102

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by vitaliy-sn** [comment]
/e2e/abort vsphere;Standard;containerd;1.26 8685113865 8685113865-1-con-1-26 /sys/deckhouse-oss/install:pr6283 ubuntu@10.220.203.26

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by vitaliy-sn** [comment]
/e2e/abort vsphere;Standard;containerd;1.26 8685928302 8685928302-1-con-1-26 /sys/deckhouse-oss/install:pr6283 ubuntu@10.220.203.26

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/vsphere'...

**Pull request closed without merging**
