### PR TITLE
[dhctl] del name label on d8-node-terraform-state secret

### PR DESCRIPTION
**Pull request by sprait**
## Description

Fix creation cloudPermanent nodes with valid length name ( no longer 42 symbols ).

## Why do we need it, and what problem does it solve?

CloudPermanent ng with correct length name  ( cluster prefix + node group name should be no longer then 42 symbols ) doesn't create.

## What is the expected result?

 In example used cluster prefix `dev-` and node group name `worker-permanent-to-looooooooooooooong`, that give valid name with 42 symbols. Try apply it:

```
nodeGroups:
- instanceClass:
    configDrive: false
    flavorName: m1.medium
    imageName: redos-standard-7.3.4
    mainNetwork: dev
  name: worker-permanent-to-looooooooooooooong
  replicas: 1
```

Behavior before:
```
...
│ │ │ State path: terraform.tfstate
│ │ │ Terraform runner "static-node" process exited.
│ │ │ Save intermediate state error: timeout while "Save intermediate Terraform state for Node                                             ↵
│ │ │ \"dev-worker-permanent-to-looooooooooooooong-0\"": last error: Create 'Secret                                                        ↵
│ │ │ "d8-node-terraform-state-dev-worker-permanent-to-looooooooooooooong-0"': Secret                                                      ↵
│ │ │ "d8-node-terraform-state-dev-worker-permanent-to-looooooooooooooong-0" is invalid: metadata.labels: Invalid value:                   ↵
│ │ │ "d8-node-terraform-state-dev-worker-permanent-to-looooooooooooooong-0": must be no more than 63 characters
│ │ └ terraform apply ... (453.09 seconds)
│ └ 🌱 ~ Terraform: Pipeline static-node for dev-worker-permanent-to-looooooooooooooong-0 (456.50 seconds)
│
│ ┌ Save Terraform state for Node "dev-worker-permanent-to-looooooooooooooong-0"
│ │ Manifest for Secret "d8-node-terraform-state-dev-worker-permanent-to-looooooooooooooong-0"
│ │ ️⛱️️ Attempt #1 of 45 |
│ │ 	Save Terraform state for Node "dev-worker-permanent-to-looooooooooooooong-0" failed, next attempt will be in 10s"
│ │ 	Error: create resource: Secret "d8-node-terraform-state-dev-worker-permanent-to-looooooooooooooong-0" is invalid: metadata.labels:    ↵
│ │ Invalid value: "d8-node-terraform-state-dev-worker-permanent-to-looooooooooooooong-0": must be no more than 63 characters
...
```

Behavior after:
```
...
│ │ │ State path: terraform.tfstate
│ │ │ Terraform runner "static-node" process exited.
│ │ └ terraform apply ... (82.47 seconds)
│ └ 🌱 ~ Terraform: Pipeline static-node for dev-worker-permanent-to-looooooooooooooong-0 (85.84 seconds)
│
│ ┌ Save Terraform state for Node "dev-worker-permanent-to-looooooooooooooong-0"
│ │ Manifest for Secret "d8-node-terraform-state-dev-worker-permanent-to-looooooooooooooong-0"
│ │ Secret "d8-node-terraform-state-dev-worker-permanent-to-looooooooooooooong-0" already exists. Trying to update ... OK!
│ │ 🎉 Succeeded!
│ └ Save Terraform state for Node "dev-worker-permanent-to-looooooooooooooong-0" (0.18 seconds)
│
│ ┌ Waiting for NodeGroup worker-permanent-to-looooooooooooooong to become Ready
│ │ ️⛱️️ Attempt #1 of 100 |
│ │ 	Waiting for NodeGroup worker-permanent-to-looooooooooooooong to become Ready failed, next attempt will be in 20s"
│ │ 	Error: Nodes Ready 0 of 1
│ │
│ │ ️⛱️️ Attempt #2 of 100 |
│ │ 	Waiting for NodeGroup worker-permanent-to-looooooooooooooong to become Ready failed, next attempt will be in 20s"
│ │ 	Error: Nodes Ready 0 of 1
│ │
│ │ ️⛱️️ Attempt #3 of 100 |
│ │ 	Waiting for NodeGroup worker-permanent-to-looooooooooooooong to become Ready failed, next attempt will be in 20s"
│ │ 	Error: Nodes Ready 0 of 1
│ │
│ │ ️⛱️️ Attempt #4 of 100 |
│ │ 	Waiting for NodeGroup worker-permanent-to-looooooooooooooong to become Ready failed, next attempt will be in 20s"
│ │ 	Error: Nodes Ready 0 of 1
│ │
│ │ ️⛱️️ Attempt #5 of 100 |
│ │ 	Waiting for NodeGroup worker-permanent-to-looooooooooooooong to become Ready failed, next attempt will be in 20s"
│ │ 	Error: Nodes Ready 0 of 1
│ │
│ │ ️⛱️️ Attempt #6 of 100 |
│ │ 	Waiting for NodeGroup worker-permanent-to-looooooooooooooong to become Ready failed, next attempt will be in 20s"
│ │ 	Error: Nodes Ready 0 of 1
│ │
│ │ ️⛱️️ Attempt #7 of 100 |
│ │ 	Waiting for NodeGroup worker-permanent-to-looooooooooooooong to become Ready failed, next attempt will be in 20s"
│ │ 	Error: Nodes Ready 0 of 1
│ │
│ │ ️⛱️️ Attempt #8 of 100 |
│ │ 	Waiting for NodeGroup worker-permanent-to-looooooooooooooong to become Ready failed, next attempt will be in 20s"
│ │ 	Error: Nodes Ready 0 of 1
│ │ * dev-worker-permanent-to-looooooooooooooong-0 | NotReady
│ │
│ │ ️⛱️️ Attempt #9 of 100 |
│ │ 	Waiting for NodeGroup worker-permanent-to-looooooooooooooong to become Ready failed, next attempt will be in 20s"
│ │ 	Error: Nodes Ready 0 of 1
│ │ * dev-worker-permanent-to-looooooooooooooong-0 | NotReady
│ │
│ │ Nodes Ready 1 of 1
│ │ * dev-worker-permanent-to-looooooooooooooong-0 | Ready
│ │
│ │ 🎉 Succeeded!
│ └ Waiting for NodeGroup worker-permanent-to-looooooooooooooong to become Ready (180.75 seconds)
└ 🛸 ~ Converge: Add NodeGroup worker-permanent-to-looooooooooooooong (replicas: 1)️ (277.34 seconds)
...
```

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Fix creation cloudPermanent nodes with valid length name (no longer 42 symbols).
impact: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by sprait** [comment]
/e2e/abort openstack;Standard;containerd;1.27 10004485586 10004485586-1-con-1-27 /sys/deckhouse-oss/install:pr9075 redos@31.129.33.204

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
