### PR TITLE
[prometheus] fix alerts-receiver lock issue

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
Instead of deleting resolved alerts one by one, we accumulate them in a list, take a Lock over memStore and delete all of them at once.

## Why do we need it, and what problem does it solve?
There is a bug in the code: It takes RLock for the whole loop over memstore map while inside the loop there is another Lock to delete some elemets from the map. It prevents alerts-receiver from deleting stale alerts from memStore.

## Why do we need it in the patch release (if we do)?
It fixes a bug introduced by another fix.

## What is the expected result?
Clusteralerts are get deleted properly.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus-operator
type: fix
summary: Fix alerts-receiver reconcile loop issue.
impact: Alerts-receiver pod will be recreated.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by miklezzzz** [comment]
tests. before
image

**Comment by miklezzzz** [comment]
after
image

**Comment by miklezzzz** [comment]
relevant logs
image

**Review by yalosev — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [7308](https://github.com/deckhouse/deckhouse/pull/7308) to the branch [release-1.57](https://github.com/deckhouse/deckhouse/tree/release-1.57) successful!

**Pull request merged**
