### PR TITLE
[kube-dns] Return alert about deprecated service annotation

### PR DESCRIPTION
**Pull request by vitaliy-sn**
## Description

Return alert about deprecated service annotation `service.alpha.kubernetes.io/tolerate-unready-endpoints`

## Check

image

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: kube-dns
type: feature
summary: Return alert about deprecated service annotation service.alpha.kubernetes.io/tolerate-unready-endpoints
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...

**Comment by vitaliy-sn** [comment]
/e2e/abort static;Static;containerd;1.25 6821820419 6821820419-1-con-1-25 /sys/deckhouse-oss/install:pr6407 astra@192.168.199.39

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
