### PR TITLE
[e2e] add nodeUser to test

### PR DESCRIPTION
**Pull request by sprait**
## Description

Add NodeUser check for e2e tests.

## Why do we need it, and what problem does it solve?

Improvement of e2e.

## What is the expected result?
Example test result:
image

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: feature
summary: add nodeUser to e2e-test 
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by sprait** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9935454986 9935454986-1-con-1-27 /sys/deckhouse-oss/install:pr9020 redos@158.160.126.253

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by sprait** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9936980224 9936980224-1-con-1-27 /sys/deckhouse-oss/install:pr9020 redos@178.154.222.185

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by sprait** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9937599822 9937599822-1-con-1-27 /sys/deckhouse-oss/install:pr9020 redos@62.84.115.46

**Comment by sprait** [comment]
/e2e/abort openstack;Standard;containerd;1.27 9937465266 9937465266-1-con-1-27 /sys/deckhouse-oss/install:pr9020 redos@31.129.32.108

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by sprait** [comment]
/e2e/abort openstack;Standard;containerd;1.27 9941420784 9941420784-1-con-1-27 /sys/deckhouse-oss/install:pr9020 redos@45.12.229.45

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Comment by sprait** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.27 9943782703 9943782703-1-con-1-27 /sys/deckhouse-oss/install:pr9020 user@34.141.114.127

**Comment by sprait** [comment]
/e2e/abort static;Static;containerd;1.27 9943782656 9943782656-1-con-1-27 /sys/deckhouse-oss/install:pr9020 astra@192.168.199.208

**Comment by sprait** [comment]
/e2e/abort openstack;Standard;containerd;1.27 9943782136 9943782136-1-con-1-27 /sys/deckhouse-oss/install:pr9020 redos@45.12.229.225

**Comment by sprait** [comment]
/e2e/abort azure;Standard;containerd;1.27 9943781660 9943781660-1-con-1-27 /sys/deckhouse-oss/install:pr9020 azureuser@20.56.3.125

**Comment by sprait** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9943701390 9943701390-1-con-1-27 /sys/deckhouse-oss/install:pr9020 redos@158.160.116.248

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by sprait** [comment]
/e2e/abort openstack;Standard;containerd;1.27 9951561806 9951561806-1-con-1-27 /sys/deckhouse-oss/install:pr9020 redos@45.12.229.196

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/azure'...

**Review by aleksey-su — APPROVED** [review]

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9937599822 9937599822-1-con-1-27 /sys/deckhouse-oss/install:pr9020 redos@62.84.115.46

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9941421241 9941421241-1-con-1-27 /sys/deckhouse-oss/install:pr9020 redos@51.250.88.131

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Review by name212 — APPROVED** [review]

**Pull request merged**
