### PR TITLE
[flant-integration] Remove module

### PR DESCRIPTION
**Pull request by asviel**
## Description

Remove the flant-integration internal module (embedded module will be replaced by a module).

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse-controller
type: chore
summary: Remove the flant-integration internal module.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by z9r5** [comment]
There is go_lib/deckhouse-config/testdata/validator/flant-integration directory. What should we do with it?
@miklezzzz

**Review by z9r5 — APPROVED** [review]

**Review by yalosev — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Comment by sprait** [comment]
/e2e/abort openstack;Standard;containerd;1.27 11343281061 11343281061-1-con-1-27 /sys/deckhouse-oss/install:pr8392

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
