### PR TITLE
[kube-proxy] start kube-proxy only if cni-flannel or cni-simple-bridge modules is enabled

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

Closes https://github.com/deckhouse/deckhouse/issues/7602.

This PR enables kube-proxy module only if cni-flannel or cni-simple-bridge enabled.
Also, service working is needed for cloud controller manager to work. 
To prevent problems with ccm access to kube api, we change KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT for kube api host ip and host port on the bootstrap phase.

## Why do we need it, and what problem does it solve?

If we bootstrap cluster in the cloud, we have two ways to set up cni. 
1. Create appropriate module config.
2. Use predefined cni for cloud provider.

In the second case:
* deckhouse starts
* kube-proxy starts
* cloud-provider starts and define default cni plugin
* deckhouse use cni-plugin configuration to start appropriate cni
* if cni is cni-cilium deckhouse disables kube-proxy module

In that case if something goes wrong, kube-proxy cannot disabled and cni-cilium cannot start due to cilium and kube-proxy uses same ports.
## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: core
type: fix
summary: start kube-proxy only if cni-flannel or cni-simple-bridge modules is enabled
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort vsphere;Standard;containerd;1.25 8821385422 8821385422-1-con-1-25 /sys/deckhouse-oss/install:pr8258 ubuntu@10.220.203.28

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/gcp'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 8827886104 8827886104-1-con-1-25 /sys/deckhouse-oss/install:pr8258 centos@3.73.186.207

**Comment by RomanenkoDenys** [comment]
/e2e/abort openstack;Standard;containerd;1.25 8827885943 8827885943-1-con-1-25 /sys/deckhouse-oss/install:pr8258 redos@31.41.155.244

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by RomanenkoDenys** [comment]
/e2e/abort azure;Standard;containerd;1.25 8827886298 8827886298-1-con-1-25 /sys/deckhouse-oss/install:pr8258 azureuser@4.210.220.114

**Comment by RomanenkoDenys** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.25 8827887541 8827887541-1-con-1-25 /sys/deckhouse-oss/install:pr8258 user@34.141.64.123

**Comment by RomanenkoDenys** [comment]
/e2e/abort static;Static;containerd;1.25 8827887082 8827887082-1-con-1-25 /sys/deckhouse-oss/install:pr8258 astra@192.168.199.130

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by RomanenkoDenys** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 8827886887 8827886887-1-con-1-25 /sys/deckhouse-oss/install:pr8258 redos@158.160.53.83

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by RomanenkoDenys** [comment]
```
root@8822844695-1-con-1-25-master-0:~# kubectl get pods -A -w
NAMESPACE     NAME                                                     READY   STATUS    RESTARTS   AGE
kube-system   kube-apiserver-8822844695-1-con-1-25-master-0            0/2     Pending   0          50s
kube-system   kube-controller-manager-8822844695-1-con-1-25-master-0   0/1     Pending   0          50s
kube-system   kube-apiserver-8822844695-1-con-1-25-master-0            1/2     Running   2 (6s ago)   51s
kube-system   kube-scheduler-8822844695-1-con-1-25-master-0            0/1     Pending   0            0s
kube-system   kube-scheduler-8822844695-1-con-1-25-master-0            0/1     Running   1 (11s ago)   3s
kube-system   kube-controller-manager-8822844695-1-con-1-25-master-0   0/1     Running   1 (11s ago)   56s
kube-system   etcd-8822844695-1-con-1-25-master-0                      0/1     Pending   0             0s
kube-system   etcd-8822844695-1-con-1-25-master-0                      1/1     Running   1 (14s ago)   0s
kube-system   kube-controller-manager-8822844695-1-con-1-25-master-0   0/1     Running   1 (16s ago)   61s
kube-system   kube-controller-manager-8822844695-1-con-1-25-master-0   1/1     Running   1 (16s ago)   61s
kube-system   kube-scheduler-8822844695-1-con-1-25-master-0            0/1     Running   1 (18s ago)   10s
kube-system   kube-scheduler-8822844695-1-con-1-25-master-0            1/1     Running   1 (18s ago)   10s
kube-system   kube-apiserver-8822844695-1-con-1-25-master-0            1/2     Running   2 (20s ago)   65s
kube-system   kube-apiserver-8822844695-1-con-1-25-master-0            2/2     Running   2 (20s ago)   65s
d8-system     deckhouse-5f86b45d4f-l4jtw                               0/1     Pending   0             0s
d8-system     deckhouse-5f86b45d4f-l4jtw                               0/1     Pending   0             0s
d8-system     deckhouse-5f86b45d4f-l4jtw                               0/1     ContainerCreating   0             0s
d8-system     deckhouse-5f86b45d4f-l4jtw                               0/1     Running             0             11s
kube-system   kubernetes-api-proxy-8822844695-1-con-1-25-master-0      0/2     Pending             0             0s
d8-system     deckhouse-5f86b45d4f-l4jtw                               0/1     Running             0             52s
kube-system   kubernetes-api-proxy-8822844695-1-con-1-25-master-0      2/2     Running             2 (91s ago)   7s
d8-system     deckhouse-5f86b45d4f-l4jtw                               0/1     Terminating         0             58s
d8-system     webhook-handler-7db89755fd-zh54s                         0/1     Pending             0             0s
d8-system     webhook-handler-7db89755fd-zh54s                         0/1     Pending             0             0s
d8-system     deckhouse-5f86b45d4f-l4jtw                               0/1     Terminating         0             58s
d8-system     deckhouse-5f86b45d4f-l4jtw                               0/1     Terminating         0             58s
d8-system     deckhouse-5f86b45d4f-l4jtw                               0/1     Terminating         0             58s
d8-system     deckhouse-689fc5c5b4-zkbmx                               0/2     Pending             0             0s
d8-system     deckhouse-689fc5c5b4-zkbmx                               0/2     Pending             0             0s
d8-system     deckhouse-689fc5c5b4-zkbmx                               0/2     Init:0/1            0             0s
d8-system     deckhouse-689fc5c5b4-zkbmx                               0/2     PodInitializing     0             3s
d8-system     deckhouse-689fc5c5b4-zkbmx                               0/2     Running             0             5s
d8-system     deckhouse-689fc5c5b4-zkbmx                               1/2     Running             0             5s
d8-system     deckhouse-689fc5c5b4-zkbmx                               1/2     Running             0             15s
d8-cloud-provider-vsphere   cloud-data-discoverer-6f7f8888b4-fggqp                   0/2     Pending             0             0s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          0/5     Pending             0             0s
d8-cloud-provider-vsphere   cloud-controller-manager-6668479c4d-w8cs9                0/1     Pending             0             0s
d8-cloud-provider-vsphere   cloud-data-discoverer-6f7f8888b4-fggqp                   0/2     Pending             0             0s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          0/5     Pending             0             0s
d8-cloud-provider-vsphere   cloud-controller-manager-6668479c4d-w8cs9                0/1     Pending             0             0s
d8-cloud-provider-vsphere   cloud-controller-manager-6668479c4d-w8cs9                0/1     ContainerCreating   0             0s
d8-cloud-provider-vsphere   cloud-controller-manager-6668479c4d-w8cs9                0/1     Running             0             2s
d8-cloud-provider-vsphere   cloud-controller-manager-6668479c4d-w8cs9                1/1     Running             0             3s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          0/5     Pending             0             4s
d8-system                   webhook-handler-7db89755fd-zh54s                         0/1     Pending             0             41s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          0/5     ContainerCreating   0             4s
d8-system                   webhook-handler-7db89755fd-zh54s                         0/1     ContainerCreating   0             41s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          5/5     Running             0             13s
d8-cloud-instance-manager   registry-packages-proxy-8f95c76f9-sjgkg                  0/2     Pending             0             0s
d8-cloud-instance-manager   registry-packages-proxy-8f95c76f9-sjgkg                  0/2     Pending             0             0s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          2/5     Error               1 (1s ago)    35s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          5/5     Running             4 (2s ago)    36s
d8-cloud-instance-manager   bashible-apiserver-784db5bc68-gdzst                      0/1     Pending             0             0s
d8-cloud-instance-manager   bashible-apiserver-784db5bc68-gdzst                      0/1     Pending             0             0s
kube-system                 d8-kube-dns-646559d469-w5xh9                             0/2     Pending             0             0s
kube-system                 d8-kube-dns-646559d469-xl97x                             0/2     Pending             0             0s
kube-system                 d8-kube-dns-646559d469-w5xh9                             0/2     Pending             0             0s
kube-system                 d8-kube-dns-646559d469-xl97x                             0/2     Pending             0             0s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          4/5     Error               4 (8s ago)    42s
d8-network-gateway          snat-svhzl                                               0/1     Pending             0             0s
d8-network-gateway          snat-svhzl                                               0/1     Pending             0             0s
d8-network-gateway          dhcp-0                                                   0/1     Pending             0             0s
d8-network-gateway          snat-svhzl                                               0/1     ContainerCreating   0             0s
d8-network-gateway          dhcp-0                                                   0/1     Pending             0             0s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          5/5     Running             5 (2s ago)    43s
d8-cloud-provider-vsphere   cloud-controller-manager-6668479c4d-w8cs9                1/1     Running             0             45s
d8-network-gateway          snat-svhzl                                               1/1     Running             0             4s
d8-system                   deckhouse-689fc5c5b4-zkbmx                               2/2     Running             0             86s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          2/5     Error               5 (17s ago)   58s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          2/5     CrashLoopBackOff    5 (2s ago)    59s
d8-system                   webhook-handler-d7b9c996-n2bhh                           0/1     Pending             0             0s
d8-system                   webhook-handler-d7b9c996-n2bhh                           0/1     Pending             0             0s
d8-system                   webhook-handler-d7b9c996-n2bhh                           0/1     ContainerCreating   0             0s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          2/5     CrashLoopBackOff    6 (1s ago)    65s
d8-cni-cilium               safe-agent-updater-s6tsj                                 0/3     Pending             0             0s
d8-cni-cilium               agent-g4dqx                                              0/2     Pending             0             0s
d8-cni-cilium               safe-agent-updater-s6tsj                                 0/3     Pending             0             0s
d8-cni-cilium               operator-f95f84958-lqn9l                                 0/2     Pending             0             0s
d8-cni-cilium               agent-g4dqx                                              0/2     Pending             0             0s
d8-cni-cilium               operator-f95f84958-lqn9l                                 0/2     Pending             0             0s
d8-cni-cilium               safe-agent-updater-s6tsj                                 0/3     Init:0/4            0             0s
d8-cni-cilium               agent-g4dqx                                              0/2     Init:0/6            0             0s
d8-cni-cilium               operator-f95f84958-lqn9l                                 0/2     ContainerCreating   0             0s
d8-cni-cilium               agent-g4dqx                                              0/2     Init:1/6            0             2s
d8-cni-cilium               safe-agent-updater-s6tsj                                 0/3     Init:1/4            0             2s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          1/5     CrashLoopBackOff    6 (9s ago)    73s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          4/5     CrashLoopBackOff    9 (2s ago)    74s
d8-cni-cilium               agent-g4dqx                                              0/2     Init:2/6            0             15s
d8-cni-cilium               safe-agent-updater-s6tsj                                 0/3     Init:2/4            0             15s
d8-cni-cilium               agent-g4dqx                                              0/2     Init:3/6            0             16s
d8-cni-cilium               agent-g4dqx                                              0/2     Init:4/6            0             17s
d8-cni-cilium               safe-agent-updater-s6tsj                                 0/3     Init:3/4            0             17s
d8-cni-cilium               operator-f95f84958-lqn9l                                 2/2     Running             0             17s
d8-cni-cilium               agent-g4dqx                                              0/2     Init:5/6            0             18s
d8-cni-cilium               agent-g4dqx                                              0/2     PodInitializing     0             19s
d8-cni-cilium               safe-agent-updater-s6tsj                                 0/3     PodInitializing     0             19s
d8-cni-cilium               safe-agent-updater-s6tsj                                 3/3     Running             0             20s
d8-cni-cilium               agent-g4dqx                                              1/2     Running             0             20s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          5/5     Running             10 (16s ago)   88s
d8-cni-cilium               agent-g4dqx                                              1/2     Running             0              24s
d8-cni-cilium               agent-g4dqx                                              2/2     Running             0              24s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          2/5     Error               11 (1s ago)    95s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          1/5     CrashLoopBackOff    11 (2s ago)    96s
kube-system                 d8-kube-dns-646559d469-w5xh9                             0/2     Pending             0              56s
kube-system                 d8-kube-dns-646559d469-xl97x                             0/2     Pending             0              56s
d8-cloud-provider-vsphere   csi-node-xc6j8                                           0/2     Pending             0              0s
d8-cloud-provider-vsphere   csi-node-xc6j8                                           0/2     Pending             0              0s
kube-system                 d8-kube-dns-646559d469-w5xh9                             0/2     ContainerCreating   0              56s
kube-system                 d8-kube-dns-646559d469-xl97x                             0/2     ContainerCreating   0              56s
d8-cloud-provider-vsphere   csi-node-xc6j8                                           0/2     ContainerCreating   0              0s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          1/5     CrashLoopBackOff    11 (2s ago)    97s
d8-system                   webhook-handler-d7b9c996-n2bhh                           1/1     Running             0              41s
d8-system                   webhook-handler-7db89755fd-zh54s                         0/1     Terminating         0              2m18s
d8-cloud-provider-vsphere   csi-node-xc6j8                                           2/2     Running             0              6s
d8-cloud-provider-vsphere   csi-node-xc6j8                                           1/2     Error               0              8s
kube-system                 d8-kube-dns-646559d469-w5xh9                             1/2     Running             0              64s
kube-system                 d8-kube-dns-646559d469-w5xh9                             2/2     Running             0              64s
kube-system                 d8-kube-dns-646559d469-xl97x                             1/2     Running             0              64s
kube-system                 d8-kube-dns-646559d469-xl97x                             2/2     Running             0              64s
d8-cloud-provider-vsphere   csi-node-xc6j8                                           2/2     Running             1 (2s ago)     9s
d8-cloud-instance-manager   registry-packages-proxy-8f95c76f9-sjgkg                  0/2     Pending             0              88s
d8-cloud-instance-manager   bashible-apiserver-784db5bc68-gdzst                      0/1     Pending             0              68s
d8-cloud-provider-vsphere   cloud-data-discoverer-6f7f8888b4-fggqp                   0/2     Pending             0              106s
kube-system                 d8-control-plane-manager-7s56x                           0/6     Pending             0              0s
d8-cloud-instance-manager   early-oom-lb4sq                                          0/2     Pending             0              0s
kube-system                 d8-control-plane-manager-7s56x                           0/6     Pending             0              0s
d8-cloud-instance-manager   early-oom-lb4sq                                          0/2     Pending             0              0s
d8-cloud-instance-manager   registry-packages-proxy-8f95c76f9-sjgkg                  0/2     ContainerCreating   0              88s
d8-chrony                   chrony-master-l7nh4                                      0/1     Pending             0              0s
d8-cloud-instance-manager   bashible-apiserver-784db5bc68-gdzst                      0/1     ContainerCreating   0              68s
d8-chrony                   chrony-master-l7nh4                                      0/1     Pending             0              0s
d8-cloud-provider-vsphere   cloud-data-discoverer-6f7f8888b4-fggqp                   0/2     ContainerCreating   0              106s
kube-system                 d8-control-plane-manager-7s56x                           0/6     ContainerCreating   0              0s
d8-cloud-instance-manager   early-oom-lb4sq                                          0/2     ContainerCreating   0              0s
d8-cloud-instance-manager   bashible-apiserver-784db5bc68-gdzst                      0/1     ContainerCreating   0              68s
d8-chrony                   chrony-master-l7nh4                                      0/1     ContainerCreating   0              0s
d8-chrony                   chrony-master-l7nh4                                      1/1     Running             0              4s
kube-system                 d8-control-plane-manager-7s56x                           5/6     Running             0              4s
d8-keepalived               keepalived-master-gateway-0                              0/1     Pending             0              0s
d8-keepalived               keepalived-master-gateway-0                              0/1     Pending             0              0s
d8-keepalived               keepalived-master-gateway-0                              0/1     Init:0/1            0              0s
d8-cloud-instance-manager   early-oom-lb4sq                                          1/2     Running             0              6s
d8-cloud-instance-manager   bashible-apiserver-784db5bc68-gdzst                      0/1     Running             0              74s
d8-cloud-instance-manager   early-oom-lb4sq                                          2/2     Running             0              7s
d8-cloud-instance-manager   bashible-apiserver-784db5bc68-gdzst                      1/1     Running             0              75s
d8-cloud-instance-manager   registry-packages-proxy-8f95c76f9-sjgkg                  0/2     Running             0              96s
d8-cloud-provider-vsphere   cloud-data-discoverer-6f7f8888b4-fggqp                   1/2     Running             0              115s
d8-cloud-instance-manager   registry-packages-proxy-8f95c76f9-sjgkg                  1/2     Running             0              97s
d8-cloud-instance-manager   registry-packages-proxy-8f95c76f9-sjgkg                  2/2     Running             0              97s
d8-cloud-provider-vsphere   csi-controller-6c4674c485-fh59v                          5/5     Running             15 (21s ago)   116s
d8-cloud-provider-vsphere   cloud-data-discoverer-6f7f8888b4-fggqp                   2/2     Running             0              116s
d8-cloud-instance-manager   machine-controller-manager-6648856f7-rw5w9               0/2     Pending             0              0s
d8-cloud-instance-manager   machine-controller-manager-6648856f7-rw5w9               0/2     Pending             0              0s
d8-cloud-instance-manager   machine-controller-manager-6648856f7-rw5w9               0/2     ContainerCreating   0              0s
d8-keepalived               keepalived-master-gateway-0                              0/1     Init:0/1            0              6s
d8-keepalived               keepalived-master-gateway-0                              0/1     PodInitializing     0              7s
d8-keepalived               keepalived-master-gateway-0                              1/1     Running             0              8s
d8-cloud-instance-manager   machine-controller-manager-6648856f7-rw5w9               1/2     Running             0              3s
d8-cloud-instance-manager   machine-controller-manager-6648856f7-rw5w9               2/2     Running             0              3s
```

**Comment by RomanenkoDenys** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 8829721775 8829721775-1-con-1-25 /sys/deckhouse-oss/install:pr8258 redos@51.250.79.52

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by RomanenkoDenys** [comment]
```
[root@a8830844967-1-con-1-25-master-0 ~]# kubectl get pods -A -w
NAMESPACE     NAME                                                      READY   STATUS    RESTARTS      AGE
kube-system   etcd-a8830844967-1-con-1-25-master-0                      0/1     Pending   0             3s
kube-system   kube-apiserver-a8830844967-1-con-1-25-master-0            1/2     Running   2 (25s ago)   53s
kube-system   kube-controller-manager-a8830844967-1-con-1-25-master-0   1/1     Running   1 (25s ago)   54s
kube-system   kube-scheduler-a8830844967-1-con-1-25-master-0            1/1     Running   1 (25s ago)   54s
kube-system   etcd-a8830844967-1-con-1-25-master-0                      1/1     Running   1 (25s ago)   3s
kube-system   kube-apiserver-a8830844967-1-con-1-25-master-0            1/2     Running   2 (31s ago)   59s
kube-system   kube-apiserver-a8830844967-1-con-1-25-master-0            2/2     Running   2 (31s ago)   59s
d8-system     deckhouse-5999b54456-4n94h                                0/1     Pending   0             0s
d8-system     deckhouse-5999b54456-4n94h                                0/1     Pending   0             0s
d8-system     deckhouse-5999b54456-4n94h                                0/1     ContainerCreating   0             0s
kube-system   kubernetes-api-proxy-a8830844967-1-con-1-25-master-0      0/2     Pending             0             0s
d8-system     deckhouse-5999b54456-4n94h                                0/1     Running             0             22s
kube-system   kubernetes-api-proxy-a8830844967-1-con-1-25-master-0      2/2     Running             2 (85s ago)   10s
d8-system     deckhouse-5999b54456-4n94h                                0/1     Running             0             61s
d8-system     deckhouse-5999b54456-4n94h                                0/1     Terminating         0             64s
d8-system     webhook-handler-86f7c8fcdb-dfzm8                          0/1     Pending             0             0s
d8-system     webhook-handler-86f7c8fcdb-dfzm8                          0/1     Pending             0             0s
d8-system     deckhouse-5999b54456-4n94h                                0/1     Terminating         0             64s
d8-system     deckhouse-5999b54456-4n94h                                0/1     Terminating         0             64s
d8-system     deckhouse-5999b54456-4n94h                                0/1     Terminating         0             64s
d8-system     deckhouse-658fbbb69f-dbcsc                                0/2     Pending             0             0s
d8-system     deckhouse-658fbbb69f-dbcsc                                0/2     Pending             0             0s
d8-system     deckhouse-658fbbb69f-dbcsc                                0/2     Init:0/1            0             0s
d8-system     deckhouse-658fbbb69f-dbcsc                                0/2     PodInitializing     0             2s
d8-system     deckhouse-658fbbb69f-dbcsc                                0/2     Running             0             4s
d8-system     deckhouse-658fbbb69f-dbcsc                                1/2     Running             0             4s
d8-system     deckhouse-658fbbb69f-dbcsc                                1/2     Running             0             13s
d8-cloud-provider-yandex   cloud-data-discoverer-85dc8db9d-46c5h                     0/2     Pending             0             0s
d8-cloud-provider-yandex   cloud-controller-manager-7c8c4bb695-4xq9p                 0/1     Pending             0             0s
d8-cloud-provider-yandex   csi-controller-6f6c9d7cd9-7cjnq                           0/5     Pending             0             0s
d8-cloud-provider-yandex   cloud-data-discoverer-85dc8db9d-46c5h                     0/2     Pending             0             0s
d8-cloud-provider-yandex   cloud-controller-manager-7c8c4bb695-4xq9p                 0/1     Pending             0             0s
d8-cloud-provider-yandex   csi-controller-6f6c9d7cd9-7cjnq                           0/5     Pending             0             0s
d8-cloud-provider-yandex   cloud-controller-manager-7c8c4bb695-4xq9p                 0/1     ContainerCreating   0             0s
d8-cloud-provider-yandex   cloud-controller-manager-7c8c4bb695-4xq9p                 0/1     Running             0             3s
d8-cloud-provider-yandex   cloud-controller-manager-7c8c4bb695-4xq9p                 1/1     Running             0             3s
d8-system                  webhook-handler-86f7c8fcdb-dfzm8                          0/1     Pending             0             35s
d8-cloud-provider-yandex   csi-controller-6f6c9d7cd9-7cjnq                           0/5     Pending             0             4s
d8-system                  webhook-handler-86f7c8fcdb-dfzm8                          0/1     ContainerCreating   0             35s
d8-cloud-provider-yandex   csi-controller-6f6c9d7cd9-7cjnq                           0/5     ContainerCreating   0             4s
d8-cloud-provider-yandex   csi-controller-6f6c9d7cd9-7cjnq                           5/5     Running             0             14s
d8-cloud-instance-manager   registry-packages-proxy-8f95c76f9-9qfgn                   0/2     Pending             0             0s
d8-cloud-instance-manager   registry-packages-proxy-8f95c76f9-9qfgn                   0/2     Pending             0             0s
d8-cloud-instance-manager   bashible-apiserver-784db5bc68-mck7n                       0/1     Pending             0             0s
d8-cloud-instance-manager   bashible-apiserver-784db5bc68-mck7n                       0/1     Pending             0             0s
kube-system                 d8-kube-dns-646559d469-7t4p6                              0/2     Pending             0             0s
kube-system                 d8-kube-dns-646559d469-nkjp9                              0/2     Pending             0             0s
kube-system                 d8-kube-dns-646559d469-7t4p6                              0/2     Pending             0             0s
kube-system                 d8-kube-dns-646559d469-nkjp9                              0/2     Pending             0             0s
d8-cloud-provider-yandex    csi-controller-6f6c9d7cd9-7cjnq                           4/5     Error               0             44s
d8-cloud-provider-yandex    cloud-controller-manager-7c8c4bb695-4xq9p                 1/1     Running             0             45s
d8-cloud-provider-yandex    csi-controller-6f6c9d7cd9-7cjnq                           5/5     Running             1 (1s ago)    45s
d8-system                   deckhouse-658fbbb69f-dbcsc                                2/2     Running             0             81s
d8-system                   webhook-handler-f8598cc-cw2zk                             0/1     Pending             0             0s
d8-system                   webhook-handler-f8598cc-cw2zk                             0/1     Pending             0             0s
d8-system                   webhook-handler-f8598cc-cw2zk                             0/1     ContainerCreating   0             1s
d8-cni-simple-bridge        simple-bridge-4sd8l                                       0/1     Pending             0             0s
d8-cni-simple-bridge        simple-bridge-4sd8l                                       0/1     Pending             0             0s
d8-cni-simple-bridge        simple-bridge-4sd8l                                       0/1     ContainerCreating   0             0s
kube-system                 d8-kube-proxy-5z2n6                                       0/2     Pending             0             0s
kube-system                 d8-kube-proxy-5z2n6                                       0/2     Pending             0             0s
kube-system                 d8-kube-proxy-5z2n6                                       0/2     Init:0/1            0             0s
d8-cni-simple-bridge        simple-bridge-4sd8l                                       1/1     Running             0             2s
kube-system                 d8-kube-proxy-5z2n6                                       0/2     Init:0/1            0             4s
kube-system                 d8-kube-proxy-5z2n6                                       0/2     PodInitializing     0             7s
d8-cni-simple-bridge        simple-bridge-4sd8l                                       0/1     Error               0             7s
d8-cni-simple-bridge        simple-bridge-4sd8l                                       1/1     Running             1 (1s ago)    8s
kube-system                 d8-kube-proxy-5z2n6                                       2/2     Running             0             9s
d8-cni-simple-bridge        simple-bridge-4sd8l                                       0/1     Error               1 (7s ago)    14s
```

**Review by apolovov — APPROVED** [review]
👍

**Review by name212 — APPROVED** [review]

**Review by yalosev — APPROVED** [review]

**Pull request merged**
