### PR TITLE
[c] improve backport on comment

### PR DESCRIPTION
**Pull request by yalosev**
Signed-off-by: Yuriy Losev <yuriy.losev@flant.com>

## Description
Improve CI

## Why do we need it, and what problem does it solve?
Avoid mistakes on comment format, support all types:
- /backport 1.34
- /backport v1.34
- /backport 1.34.14
- /backport v1.34.14

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: ci
type: fix
summary: Improve backport comment format
impact_level: low
```

### CODE REVIEW

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [2239](https://github.com/deckhouse/deckhouse/pull/2239) to the branch [release-1.35](https://github.com/deckhouse/deckhouse/tree/release-1.35) successful!

**Comment by deckhouse-BOaTswain** [comment]
Backport failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/2882216009) for details.

**Comment by deckhouse-BOaTswain** [comment]
Backport failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/2882437080) for details.

**Pull request merged**
