### PR TITLE
[deckhouse] pilot add bootstrapped extender

### PR DESCRIPTION
**Pull request by ipaqsa**
## Description
It provides the bootstrapped extender and continues this https://github.com/deckhouse/deckhouse/pull/8997/

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse
type: feature
summary: Add bootstrapped extender.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ipaqsa. I've started the workflow for label 'e2e/run/gcp'...

**Comment by ipaqsa** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.27 10140973152 10140973152-1-con-1-27 /sys/deckhouse-oss/install:pr9164 user@35.246.174.49

**Comment by ipaqsa** [comment]
@deckhouse-BOaTswain /e2e/abort gcp;WithoutNAT;containerd;1.27 10140973152 10140973152-1-con-1-27 /sys/deckhouse-oss/install:pr9164 user@35.246.174.49

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ipaqsa. I've started the workflow for label 'e2e/run/gcp'...

**Comment by ipaqsa** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.27 10140973152 10140973152-1-con-1-27 /sys/deckhouse-oss/install:pr9164 user@35.246.174.49

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ipaqsa. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ipaqsa. I've started the workflow for label 'e2e/run/gcp'...

**Review by juev — APPROVED** [review]

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.27 10141901577 10141901577-1-con-1-27 /sys/deckhouse-oss/install:pr9164 user@34.159.84.169

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.27 10144902804 10144902804-1-con-1-27 /sys/deckhouse-oss/install:pr9164 user@34.89.159.20

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request closed without merging**
