### PR TITLE
[module-manager] Deployed and installed external modules aren't deleted if relevant modules configs are deleted

### PR DESCRIPTION
**Pull request by libmonsoon-dev**
## Description
Added removal of a module when deleting its configuration

## Why do we need it, and what problem does it solve?
https://github.com/deckhouse/deckhouse/issues/7734

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: module-manager
type: fix
summary: Added removal of a module when deleting its configuration
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/openstack'...

**Comment by libmonsoon-dev** [comment]
/e2e/abort openstack;Standard;containerd;1.29 8614993855 8614993855-1-con-1-29 /sys/deckhouse-oss/install:pr7831 redos@5.159.102.73

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/static'...

**Review by yalosev — CHANGES_REQUESTED** [review]
Well. This is definitely not working as before.
For example, if we delete MC `prometheus`, d8 also removes `prometheus` module when it's enabled via the static values
```
aggregating-proxy-85ccf766b-s2wsh                3/3     Terminating   0               6d18h
extended-monitoring-exporter-6f995767b8-cftmt    2/2     Terminating   0               15d
grafana-dex-authenticator-564d87756b-zkx6n       2/2     Running       1 (6d18h ago)   6d18h
grafana-v10-dex-authenticator-77967f47c8-wp4f9   2/2     Running       1 (6d18h ago)   6d18h
prometheus-main-0                                3/3     Terminating   0               6d18h
```

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/static'...

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/openstack'...

**Review by aleksey-su — APPROVED** [review]

**Comment by yalosev** [comment]
Will do in the another PR

**Pull request closed without merging**
