### PR TITLE
[operator-prometheus] added secret-field-selector

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Description
Added secret-field-selector

## Why do we need it, and what problem does it solve?
Eliminates unnecessary secrets from surveillance

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: operator-prometheus
type: fix
summary: Added secret-field-selector in args.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/openstack'...

**Comment by alexey-gavrilov-flant** [comment]
@deckhouse-BOaTswain

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort openstack;Standard;containerd;1.23 4948576335 4948576335-1-con-1-23 /sys/deckhouse-oss/install:pr4619 debian@31.41.154.50

**Comment by alexey-gavrilov-flant** [comment]
```
/e2e/abort openstack;Standard;containerd;1.23 4948576335 4948576335-1-con-1-23 /sys/deckhouse-oss/install:pr4619 debian@31.41.154.50
```

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by alexey-gavrilov-flant** [comment]
`/e2e/abort openstack;Standard;containerd;1.23 4948576335 4948576335-1-con-1-23 /sys/deckhouse-oss/install:pr4619 debian@31.41.154.50`

**Review by nabokihms — APPROVED** [review]

**Comment by z9r5** [comment]
/e2e/abort openstack;Standard;containerd;1.23 4948576335 4948576335-1-con-1-23 /sys/deckhouse-oss/install:pr4619 debian@31.41.154.50

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
