### PR TITLE
[docs] Update docs about module creation and fixes

### PR DESCRIPTION
**Pull request by haosb**
## Description
The documentation has been fixed for clearer and faster testing of module creation.

## Why do we need it, and what problem does it solve?
With this PR we can use all steps in documentation and module will deploy to the cluster without problems.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: docs
type: fix
summary: Update docs about module creation, fix bugs
impact_level: default
```

### CODE REVIEW

**Review by Zhbert — APPROVED** [review]

**Review by kirkonru — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10769](https://github.com/deckhouse/deckhouse/pull/10769) to the branch [release-1.66](https://github.com/deckhouse/deckhouse/tree/release-1.66) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10770](https://github.com/deckhouse/deckhouse/pull/10770) to the branch [release-1.65](https://github.com/deckhouse/deckhouse/tree/release-1.65) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10771](https://github.com/deckhouse/deckhouse/pull/10771) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!

**Pull request merged**
