### PR TITLE
[candi] Change containerd restart flow to avoid unwanted restarts

### PR DESCRIPTION
**Pull request by asviel**
## Description

Change containerd restart flow to avoid unwanted restarts. Add some logging to make future debugging easier.

## Why do we need it, and what problem does it solve?

Handlers declared via `bb-event-on` are executed after the step is completed. Thus `_on_containerd_config_changed` is called after the `containerd-need-restart` flag is checked and unset at the end of step 032, and sets this flag again, resulting in an unwanted restart of containerd on the next bashible run.

## Why do we need it in the patch release (if we do)?

Double containerd restarts  can have unwanted consequences.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Change containerd restart flow to avoid unwanted restarts.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [8010](https://github.com/deckhouse/deckhouse/pull/8010) to the branch [release-1.58](https://github.com/deckhouse/deckhouse/tree/release-1.58) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [8013](https://github.com/deckhouse/deckhouse/pull/8013) to the branch [release-1.59](https://github.com/deckhouse/deckhouse/tree/release-1.59) successful!

**Pull request merged**
