### PR TITLE
[docs] Add a list of DKP alerts to the documentation

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Render DKP alerts in the documentation.

Fix the helm_generate tool for the alert_template runner:
- Modified value assignments to iterate over all template items of just the first one.
- Add support for basic and standard editions

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: docs
type: feature
summary: Add a list of DKP alerts to the documentation.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Review by yalosev — APPROVED** [review]

**Review by ToyTox — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ToyTox. I've started the workflow for label 'deploy/web/test'...

**Pull request merged**
