### PR TITLE
[bashible] Do not use cloud metadata server for static nodegroup

### PR DESCRIPTION
**Pull request by borg-z**
## Description

This update removes the cloud metadata request from the bootstrap script (`http://169.254.169.254/`) when adding static nodes in hybrid clusters. This change is needed to support environments where nodes are in on-premise data centers without access to cloud metadata.

## Why do we need it, and what problem does it solve?

The change fixes an issue where static nodes in hybrid clusters failed to bootstrap correctly because the script tried to use cloud metadata, which isn't available in on-prem environments.

## What is the expected result?

Static nodes in hybrid clusters should bootstrap without errors related to cloud metadata.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Fix bootstrap script for static nodes in hybrid clusters to avoid using cloud metadata
impact:
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by name212 — APPROVED** [review]

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort static;Static;containerd;1.27 10575013341 10575013341-1-con-1-27 /sys/deckhouse-oss/install:pr9502 astra@192.168.199.99

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
