### PR TITLE
Removed migrator init containers from upmeter, loki and prometheus modules

### PR DESCRIPTION
**Pull request by duckhawk**
## Description

Remove migrator init containers from modules:
- upmeter
- loki
- prometheus

## Why do we need it, and what problem does it solve?

In some cases, this component can cause a CrashLoopBackoff in Pods within the modules.

## Why do we need it in the patch release (if we do)?

We have clients who are experiencing issues due to this component.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: upmeter, loki, prometheus
type: fix
summary: Removed migrator init containers from modules
impact_level: default
```

### CODE REVIEW

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/aws'...

**Review by vladimirGuryanov — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...

**Comment by duckhawk** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11365782291 11365782291-1-con-1-27 /sys/deckhouse-oss/install:pr10150 ec2-user@63.176.8.55

**Comment by duckhawk** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11365782291 11365782291-1-con-1-27 /sys/deckhouse-oss/install:pr10150 ec2-user@63.176.8.55

**Comment by duckhawk** [comment]
/e2e/abort static;Static;containerd;1.27 11368357741 11368357741-1-con-1-27 /sys/deckhouse-oss/install:pr10150 astra@192.168.199.167

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by Taior** [comment]
/e2e/abort static;Static;containerd;1.27 11368357741 11368357741-1-con-1-27 /sys/deckhouse-oss/install:pr10150 astra@192.168.199.167

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/static'...

**Comment by Taior** [comment]
/e2e/abort static;Static;containerd;1.27 11436316962 11436316962-1-con-1-27 /sys/deckhouse-oss/install:pr10150 astra@192.168.199.171

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit aa3f56e89545c4bb669de60862f52434ae8a2ab3 to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/11438676885) for details.

**Comment by Taior** [comment]
Cherry-picked to 1.64 in #10215

**Pull request merged**
