### PR TITLE
[candi] Disable and remove unattended upgrades early for debian and ubuntu and astra

### PR DESCRIPTION
**Pull request by name212**
## Description

Disable and remove unattended upgrades early for debian and ubuntu and astra
Remove cni-cilium from cluster configuration for vcd e2e

## Why do we need it, and what problem does it solve?
In some cases unattended upgrades block apt install

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Disable and remove unattended upgrades early for debian and ubuntu and astra.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/vcd'...

**Comment by name212** [comment]
/e2e/abort vcd;Standard;containerd;1.27 10672779475 10672779475-1-con-1-27 /sys/deckhouse-oss/install:pr9574 ubuntu@192.168.254.132

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/vcd'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Pull request merged**
