### PR TITLE
[docs] Refine instruction about Nexus

### PR DESCRIPTION
**Pull request by unreturned**
## Description
Refine instruction about Nexus

## Why do we need it, and what problem does it solve?
Improve documentation

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: docs
type: chore
summary: Update documentation.
impact_level: low
```

### CODE REVIEW

**Review by z9r5 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [7616](https://github.com/deckhouse/deckhouse/pull/7616) to the branch [release-1.58](https://github.com/deckhouse/deckhouse/tree/release-1.58) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [7617](https://github.com/deckhouse/deckhouse/pull/7617) to the branch [release-1.57](https://github.com/deckhouse/deckhouse/tree/release-1.57) successful!

**Pull request merged**
