### PR TITLE
[candi] Update kubernetes patch versions

### PR DESCRIPTION
**Pull request by z9r5**
## Description

Update Kubernetes patch versions:

1.24.13 ⇾ 1.24.14
1.25.9 ⇾ 1.25.10
1.26.4 ⇾ 1.26.5

## Why do we need it, and what problem does it solve?
It's important to bring fixes and to stay up to date with upstream.

## Why do we need it in the patch release (if we do)?
It is better to make changes in a patch release before the minor release gets to the early-access update channel.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: candi
type: chore
summary: Upgraded patch versions of Kubernetes images `1.24.14`, `1.25.10`, `1.26.5`.
impact: "Kubernetes control-plane components will restart, kubelet will restart."
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
> red_circle `e2e: GCP` for `deckhouse:chore-updatek8s-patch-202305` [failed](https://github.com/deckhouse/deckhouse/actions/runs/5068611314) in 31m42s.
> 
> Workflow details (1 job failed)

Passed. Just Github API timeout...

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
