### PR TITLE
[prometheus] enrich alert labels TargetSampleLimitExceeded 

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Description
Improves the `TargetSampleLimitExceeded` alert by adding target labels.
https://github.com/deckhouse/deckhouse/issues/4214

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: feature 
summary: Improves the TargetSampleLimitExceeded alert by adding target labels.
impact_level: default
```

### CODE REVIEW

**Comment by alexey-gavrilov-flant** [comment]
https://github.com/deckhouse/deckhouse/issues/4214

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 5381339324 5381339324-1-con-1-23 /sys/deckhouse-oss/install:pr4795 centos@18.158.3.229

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 5381339324 5381339324-1-con-1-23 /sys/deckhouse-oss/install:pr4795 centos@18.158.3.229

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by nabokihms — APPROVED** [review]

**Pull request merged**
