### PR TITLE
[candi] reduced the use of apt and yum

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Description
Changed to a static nvme build.
Removed apt|yum update calls.
Removed the open-vm-tools installation.

## Why do we need it, and what problem does it solve?
Will allow not using operating system repositories.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: chore
summary: reduced the use of apt and yum
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 12085266619 12085266619-1-con-1-27 /sys/deckhouse-oss/install:pr10867 ubuntu@192.168.240.60

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/openstack'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 12086125901 12086125901-1-con-1-27 /sys/deckhouse-oss/install:pr10867

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by sprait — APPROVED** [review]

**Pull request merged**
