### PR TITLE
Chore: Utilize metav1.LabelSelectorOperator and corev1.NodeSelectorOperator type constants in the code

### PR DESCRIPTION
**Pull request by dmvolod**
## Description
Utilize `metav1.LabelSelectorOperator` type and `corev1.NodeSelectorOperator` type constants instead of hardcoded string values. Also optimized code a bit for validating  `machine.sapcloud.io` CRD's while delete resources. 

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse
type: chore
summary: Utilize metav1.LabelSelectorOperator and corev1.NodeSelectorOperator type constants in the code
impact_level: low
```

### CODE REVIEW

**Comment by nabokihms** [comment]
@dmvolod Hello! Thank you for opening the PR. The code looks good.

We need you to sign your commit (DCO). Otherwise, we will not be able to merge it.

One way to sign it is:
1. `git rebase HEAD~1 --signoff`
2. Force-push the branch

**Comment by dmvolod** [comment]
Hello, @nabokihms 
Did it. Thank you.

**Review by shvgn — APPROVED** [review]
LGTM

**Review by apolovov — APPROVED** [review]
Thank you!

**Review by yalosev — APPROVED** [review]

**Review by name212 — APPROVED** [review]

**Pull request merged**
