### PR TITLE
[dhctl] fix empty registry credentials preflight check failure

### PR DESCRIPTION
**Pull request by marriva**
## Why do we need it, and what problem does it solve?

Fix registry credentials preflight check failure when `registryDockerCfg` contains empty auth for host, for example `{"auths":{"registry.deckhouse.io":{}}}`

```yaml
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  imagesRepo: registry.deckhouse.io/deckhouse/ce
  registryDockerCfg: eyJhdXRocyI6eyJyZWdpc3RyeS5kZWNraG91c2UuaW8iOnt9fX0=
```

```
🎈 ~ Common: Global preflight checks
│ ┌ Checking PublicDomainTemplate is correctly
│ │ 🎉 Succeeded!
│ └ Checking PublicDomainTemplate is correctly (0.00 seconds)
│
│ ┌ Checking registry credentials are correct
│ │ ️⛱️️ Attempt #1 of 1 |
│ │ 	Checking registry credentials are correct failed, next attempt will be in 10s"
│ │ 	Error: authentication failed
│ │
│ └ Checking registry credentials are correct (0.49 seconds) FAILED
└ 🎈 ~ Common: Global preflight checks (0.49 seconds) FAILED

Installation aborted: Timeout while "Checking registry credentials are correct": last error: authentication failed
Please fix this problem or skip it if you're sure with preflight-skip-registry-credential flag
```

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Fix empty registry credentials preflight check failure.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/static'...

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10231](https://github.com/deckhouse/deckhouse/pull/10231) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!

**Comment by Taior** [comment]
/e2e/abort static;Static;containerd;1.27 11444664253 11444664253-1-con-1-27 /sys/deckhouse-oss/install:pr10226 astra@192.168.199.119

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
