### PR TITLE
[deckhouse-controller] reflect extenders in modules' statuses

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
Reworking the way modules' statuses are calculated, considering information about applied extenders.

## Why do we need it, and what problem does it solve?
It makes modules' statuses a bit more transparent by reflecting extra information related to modules being filtered out by extenders.

## What is the expected result?
See before/after examples.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse-controller
type: feature
summary: Reflect info about applied extenders in modules' statuses.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by miklezzzz** [comment]
before (in general)
```
NAME                                  WEIGHT   STATE      SOURCE       STAGE   STATUS   MESSAGE
admission-policy-engine               15       Enabled    Embedded             Ready    
basic-auth                            500      Disabled   Embedded                      Info: disabled by Default bundle
ceph-csi                              31       Disabled   Embedded                      Info: disabled by Default bundle
cert-manager                          101      Enabled    Embedded             Ready    
chrony                                470      Enabled    Embedded             Ready    
cilium-hubble                         500      Disabled   Embedded                      Info: disabled by Default bundle
cloud-data-crd                        10       Enabled    Embedded             Ready    
cloud-provider-aws                    30       Disabled   Embedded                      Info: disabled by Default bundle
cloud-provider-azure                  30       Disabled   Embedded                      Info: disabled by Default bundle
cloud-provider-gcp                    30       Disabled   Embedded                      Info: disabled by Default bundle
cloud-provider-openstack              30       Enabled    Embedded             Ready    
cloud-provider-vcd                    30       Disabled   Embedded                      Info: disabled by Default bundle
cloud-provider-vsphere                30       Disabled   Embedded                      Info: disabled by Default bundle
cloud-provider-yandex                 30       Disabled   Embedded                      Info: disabled by Default bundle
cloud-provider-zvirt                  30       Disabled   Embedded                      Info: disabled by Default bundle
cni-cilium                            21       Disabled   Embedded                      Info: disabled by Default bundle
cni-flannel                           35       Enabled    Embedded             Ready    
cni-simple-bridge                     35       Disabled   Embedded                      Info: disabled by Default bundle
control-plane-manager                 40       Enabled    Embedded             Ready    
csi-ceph                              920      Disabled   deckhouse                     Info: apply module config to enable
dashboard                             500      Enabled    Embedded             Ready    Info: check module configuration status
deckhouse                             2        Enabled    Embedded             Ready    
deckhouse-tools                       800      Enabled    Embedded             Ready    
delivery                              502      Disabled   Embedded                      Info: disabled by Default bundle
descheduler                           400      Enabled    Embedded             Ready    
documentation                         810      Enabled    Embedded             Ready    
echo                                  910      Enabled    losev-test           Ready    
extended-monitoring                   340      Disabled   Embedded                      Info: turned off by 'enabled'-script, refer to the module documentation
flant-integration                     600      Disabled   Embedded                      Info: disabled by module config
flow-schema                           11       Enabled    Embedded             Ready    
ingress-nginx                         402      Enabled    Embedded             Ready    
istio                                 110      Disabled   Embedded                      Info: disabled by module config
keepalived                            450      Disabled   Embedded                      Info: disabled by Default bundle
kube-dns                              42       Enabled    Embedded             Ready    
kube-proxy                            36       Enabled    Embedded             Ready    
l2-load-balancer                      381      Disabled   Embedded                      Info: disabled by Default bundle
local-path-provisioner                31       Enabled    Embedded             Ready    
log-shipper                           460      Enabled    Embedded             Ready    
loki                                  462      Disabled   Embedded                      Info: disabled by module config
mcplay                                900      Disabled   foxtrot                       Info: apply module config to enable
metallb                               380      Disabled   Embedded                      Info: disabled by Default bundle
metallb-crd                           10       Enabled    Embedded             Ready    
monitoring-applications               340      Disabled   Embedded                      Info: disabled by Default bundle
monitoring-custom                     340      Disabled   Embedded                      Info: disabled by Default bundle
monitoring-deckhouse                  340      Disabled   Embedded                      Info: disabled by Default bundle
monitoring-kubernetes                 340      Disabled   Embedded                      Info: disabled by Default bundle
monitoring-kubernetes-control-plane   340      Disabled   Embedded                      Info: disabled by Default bundle
monitoring-ping                       340      Disabled   Embedded                      Info: disabled by Default bundle
multitenancy-manager                  160      Disabled   Embedded                      Info: disabled by module config
namespace-configurator                600      Enabled    Embedded             Ready    
network-gateway                       450      Disabled   Embedded                      Info: disabled by module config
network-policy-engine                 50       Disabled   Embedded                      Info: disabled by Default bundle
node-local-dns                        350      Enabled    Embedded             Ready    
node-manager                          40       Enabled    Embedded             Ready    
okmeter                               500      Disabled   Embedded                      Info: disabled by Default bundle
openvpn                               500      Disabled   Embedded                      Info: disabled by Default bundle
operator-ceph                         900      Disabled   deckhouse                     Info: apply module config to enable
operator-prometheus                   200      Enabled    Embedded             Ready    
operator-prometheus-crd               10       Enabled    Embedded             Ready    
operator-trivy                        500      Disabled   Embedded                      Info: disabled by module config
parca                                 900      Disabled   foxtrot                       Info: apply module config to enable
pod-reloader                          465      Enabled    Embedded             Ready    
priority-class                        1        Enabled    Embedded             Ready    
prometheus                            300      Disabled   Embedded                      Info: disabled by module config
prometheus-crd                        10       Enabled    Embedded             Ready    
prometheus-metrics-adapter            301      Disabled   Embedded                      Info: disabled by Default bundle
prometheus-pushgateway                303      Disabled   Embedded                      Info: disabled by Default bundle
registry-packages-proxy               39       Enabled    Embedded             Ready    
runtime-audit-engine                  650      Disabled   Embedded                      Info: disabled by module config
sds-drbd                              910      Disabled   deckhouse                     Info: disabled by module config
secret-copier                         600      Enabled    Embedded             Ready    
secrets-store-integration             900      Disabled   deckhouse                     Info: apply module config to enable
snapshot-controller                   45       Enabled    Embedded             Ready    
snapshot-controller-crd               10       Enabled    Embedded             Ready    
static-routing-manager                25       Disabled   Embedded                      Info: disabled by Default bundle
stronghold                            900      Disabled   deckhouse                     Info: apply module config to enable
terraform-manager                     40       Enabled    Embedded             Ready    
upmeter                               500      Disabled   Embedded                      Info: disabled by module config
user-authn                            150      Enabled    Embedded             Ready    Info: check module configuration status
user-authn-crd                        10       Enabled    Embedded             Ready    
user-authz                            140      Enabled    Embedded             Ready    
vertical-pod-autoscaler               302      Disabled   Embedded                      Info: disabled by Default bundle
vertical-pod-autoscaler-crd           10       Enabled    Embedded             Ready    

```
after (in general)
```
root@dev-master-0:~# kubectl  get modules -o wide
NAME                                  WEIGHT   STATE      SOURCE       STAGE   STATUS   MESSAGE
admission-policy-engine               15       Enabled    Embedded             Ready    Info: turned on by module config
basic-auth                            500      Disabled   Embedded                      Info: turned off by Default bundle
ceph-csi                              31       Disabled   Embedded                      Info: turned off by Default bundle
cert-manager                          101      Enabled    Embedded             Ready    Info: turned on by module config
chrony                                470      Enabled    Embedded             Ready    Info: turned on by Default bundle
cilium-hubble                         500      Disabled   Embedded                      Info: turned off by Default bundle
cloud-data-crd                        10       Enabled    Embedded             Ready    Info: turned on by Default bundle
cloud-provider-aws                    30       Disabled   Embedded                      Info: turned off by Default bundle
cloud-provider-azure                  30       Disabled   Embedded                      Info: turned off by Default bundle
cloud-provider-gcp                    30       Disabled   Embedded                      Info: turned off by Default bundle
cloud-provider-openstack              30       Enabled    Embedded             Ready    Info: turned on by dynamic global hook
cloud-provider-vcd                    30       Disabled   Embedded                      Info: turned off by Default bundle
cloud-provider-vsphere                30       Disabled   Embedded                      Info: turned off by Default bundle
cloud-provider-yandex                 30       Disabled   Embedded                      Info: turned off by Default bundle
cloud-provider-zvirt                  30       Disabled   Embedded                      Info: turned off by Default bundle
cni-cilium                            21       Disabled   Embedded                      Info: turned off by Default bundle
cni-flannel                           35       Enabled    Embedded             Ready    Info: turned on by module config
cni-simple-bridge                     35       Disabled   Embedded                      Info: turned off by Default bundle
control-plane-manager                 40       Enabled    Embedded             Ready    Info: turned on by Default bundle
csi-ceph                              920      Disabled   deckhouse                     Info: turned off by Default bundle, apply module config to enable
dashboard                             500      Enabled    Embedded             Ready    Info: check module configuration status, turned on by module config
deckhouse                             2        Enabled    Embedded             Ready    Info: turned on by module config
deckhouse-tools                       800      Enabled    Embedded             Ready    Info: turned on by Default bundle
delivery                              502      Disabled   Embedded                      Info: turned off by Default bundle
descheduler                           400      Enabled    Embedded             Ready    Info: turned on by Default bundle
documentation                         810      Enabled    Embedded             Ready    Info: turned on by module config
echo                                  910      Disabled   losev-test                    Info: turned off by KubernetesVersion constraint, requirements are not satisfied: current kubernetes version is not suitable: 1.27.16 is less than or equal to v1.30.0
extended-monitoring                   340      Disabled   Embedded                      Info: turned off by 'enabled'-script, refer to the module's documentation
flant-integration                     600      Disabled   Embedded                      Info: turned off by module config
flow-schema                           11       Enabled    Embedded             Ready    Info: turned on by Default bundle
ingress-nginx                         402      Enabled    Embedded             Ready    Info: turned on by module config
istio                                 110      Disabled   Embedded                      Info: turned off by module config
keepalived                            450      Disabled   Embedded                      Info: turned off by Default bundle
kube-dns                              42       Enabled    Embedded             Ready    Info: turned on by module config
kube-proxy                            36       Enabled    Embedded             Ready    Info: turned on by Default bundle
l2-load-balancer                      381      Disabled   Embedded                      Info: turned off by Default bundle
local-path-provisioner                31       Enabled    Embedded             Ready    Info: turned on by Default bundle
log-shipper                           460      Enabled    Embedded             Ready    Info: turned on by Default bundle
loki                                  462      Disabled   Embedded                      Info: turned off by module config
mcplay                                900      Disabled   foxtrot                       Info: turned off by Default bundle, apply module config to enable
metallb                               380      Disabled   Embedded                      Info: turned off by Default bundle
metallb-crd                           10       Enabled    Embedded             Ready    Info: turned on by Default bundle
monitoring-applications               340      Disabled   Embedded                      Info: turned off by 'enabled'-script, refer to the module's documentation
monitoring-custom                     340      Disabled   Embedded                      Info: turned off by 'enabled'-script, refer to the module's documentation
monitoring-deckhouse                  340      Disabled   Embedded                      Info: turned off by 'enabled'-script, refer to the module's documentation
monitoring-kubernetes                 340      Disabled   Embedded                      Info: turned off by Default bundle
monitoring-kubernetes-control-plane   340      Disabled   Embedded                      Info: turned off by Default bundle
monitoring-ping                       340      Disabled   Embedded                      Info: turned off by Default bundle
multitenancy-manager                  160      Disabled   Embedded                      Info: turned off by module config
namespace-configurator                600      Enabled    Embedded             Ready    Info: turned on by module config
network-gateway                       450      Disabled   Embedded                      Info: turned off by module config
network-policy-engine                 50       Disabled   Embedded                      Info: turned off by Default bundle
node-local-dns                        350      Enabled    Embedded             Ready    Info: turned on by module config
node-manager                          40       Enabled    Embedded             Ready    Info: turned on by Default bundle
okmeter                               500      Disabled   Embedded                      Info: turned off by Default bundle
openvpn                               500      Disabled   Embedded                      Info: turned off by Default bundle
operator-ceph                         900      Disabled   deckhouse                     Info: turned off by Default bundle, apply module config to enable
operator-prometheus                   200      Enabled    Embedded             Ready    Info: turned on by Default bundle
operator-prometheus-crd               10       Enabled    Embedded             Ready    Info: turned on by Default bundle
operator-trivy                        500      Disabled   Embedded                      Info: turned off by module config
parca                                 900      Disabled   foxtrot                       Info: turned off by Default bundle, apply module config to enable
pod-reloader                          465      Enabled    Embedded             Ready    Info: turned on by Default bundle
priority-class                        1        Enabled    Embedded             Ready    Info: turned on by Default bundle
prometheus                            300      Disabled   Embedded                      Info: turned off by module config
prometheus-crd                        10       Enabled    Embedded             Ready    Info: turned on by Default bundle
prometheus-metrics-adapter            301      Disabled   Embedded                      Info: turned off by Default bundle
prometheus-pushgateway                303      Disabled   Embedded                      Info: turned off by Default bundle
registry-packages-proxy               39       Enabled    Embedded             Ready    Info: turned on by Default bundle
runtime-audit-engine                  650      Disabled   Embedded                      Info: turned off by module config
sds-drbd                              910      Disabled   deckhouse                     Info: turned off by module config
secret-copier                         600      Enabled    Embedded             Ready    Info: turned on by Default bundle
secrets-store-integration             900      Disabled   deckhouse                     Info: turned off by Default bundle, apply module config to enable
snapshot-controller                   45       Enabled    Embedded             Ready    Info: turned on by Default bundle
snapshot-controller-crd               10       Enabled    Embedded             Ready    Info: turned on by Default bundle
static-routing-manager                25       Disabled   Embedded                      Info: turned off by Default bundle
stronghold                            900      Disabled   deckhouse                     Info: turned off by Default bundle, apply module config to enable
terraform-manager                     40       Enabled    Embedded             Ready    Info: turned on by Default bundle
upmeter                               500      Disabled   Embedded                      Info: turned off by module config
user-authn                            150      Enabled    Embedded             Ready    Info: check module configuration status, turned on by module config
user-authn-crd                        10       Enabled    Embedded             Ready    Info: turned on by Default bundle
user-authz                            140      Enabled    Embedded             Ready    Info: turned on by module config
vertical-pod-autoscaler               302      Disabled   Embedded                      Info: turned off by 'enabled'-script, refer to the module's documentation
vertical-pod-autoscaler-crd           10       Enabled    Embedded             Ready    Info: turned on by Default bundle

```

**Comment by miklezzzz** [comment]
some other examples

dynamic extender
```
cloud-provider-openstack              30       Enabled    Embedded             Ready      Info: turned on by dynamic global hook
```
enabled script extender
```
extended-monitoring                   340      Disabled   Embedded                      Info: turned off by 'enabled'-script, refer to the module's documentation

```
dechkouse_version_extender
```
echo                                  910      Disabled   losev-test                      Info: turned off by DechouseVersion constraint, requirements are not satisfied: current deckhouse version is not suitable: 2.0.0 is less than or equal to v2.63.0
```
k8s_version_extender
```
echo                                  910      Disabled   losev-test                    Info: turned off by KubernetesVersion constraint, requirements are not satisfied: current kubernetes version is not suitable: 1.27.16 is less than or equal to v1.30.0
```
bootstrapped extender
```
admission-policy-engine               15       Disabled   Embedded                        Info: turned off by ClusterBoostrapped constraint, the cluster isn't bootstrapped yet

```

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by yalosev — APPROVED** [review]

**Pull request merged**
