### PR TITLE
[testing] change tinyproxy image for e2e static

### PR DESCRIPTION
**Pull request by sprait**
## Description

Change the tinyproxy image in e2e-static.

## Why do we need it, and what problem does it solve?

Sometimes the proxy stops responding to requests, causing errors when running e2e tests. The latest version fixes many bugs, which should increase the stability of passing tests.

## What is the expected result?

Successful completion of e2e static.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: chore
summary: Changing the tinyproxy image to e2e-static.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/static'...

**Comment by sprait** [comment]
/e2e/abort static;Static;containerd;1.25 9364080987 9364080987-1-con-1-25 /sys/deckhouse-oss/install:pr8608 astra@192.168.199.66

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/static'...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [8616](https://github.com/deckhouse/deckhouse/pull/8616) to the branch [release-1.61](https://github.com/deckhouse/deckhouse/tree/release-1.61) successful!

**Pull request merged**
