### PR TITLE
[cloud-provider-aws] Explicitly provide tags to root_block_device

### LINKED ISSUE #5120: [cloud-provider-aws] Missing tags in root_block_device
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.46.11

### Expected Behavior

When settings tags in `AWSClusterConfiguration`, these tags are expected to be applied to `root_block_device`

### Actual Behavior

Tags are missing from `root_block_device` when settings them in `AWSClusterConfiguration`

### Steps To Reproduce

_No response_

### Additional Information

https://github.com/deckhouse/deckhouse/blob/146da888d0d6927be5d8f566e8964567a719dc9c/candi/cloud-providers/aws/terraform-modules/master-node/main.tf#L73C3-L76

### Logs

_No response_

### PR DESCRIPTION
**Pull request by mvasl**
## Description

Explicitly specified tags from `AWSClusterConfiguration` for `root_block_device` in `master-node` and `static-node` terraform configurations

## Why do we need it, and what problem does it solve?

Fixes #5120 

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: "AWS node's root_block_device is now marked with tags from AWSClusterConfiguration"
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/aws'...

**Comment by RomanenkoDenys** [comment]
> der adding tags to `aws_instance.volume_tags` instead, but for now this sho

This is another disk, please check master node root disk

**Review by RomanenkoDenys — COMMENTED** [review]
Code looks good, but i need to see tags on root device

**Review by name212 — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Pull request merged**
