### PR TITLE
Get rid of crd modules

### PR DESCRIPTION
**Pull request by yalosev**
## Description
Get rid of `xxx-crd` modules.

## Why do we need it, and what problem does it solve?
We don't need `xxx-crd` modules, that only contain CRD, anymore. Also, we don't need `ensure_crds` hooks in most of the cases. The `crds` directory in a module's directory is discovered by the addon-operator and all the CRDs are installed automatically when the module transitions from `disabled` to `enabled` state.

## What is the expected result?
There are no `xxx-crd` modules in Deckhouse's `modules` directory and all modules' CRDs get installed beforehand.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse-controller
type: feature
summary: Get rid of crd modules.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Review by z9r5 — APPROVED** [review]

**Pull request merged**
