### PR TITLE
[global] SE plus edition

### PR DESCRIPTION
**Pull request by sprait**
## Description

1. Add Standard Edition Plus (SE+).
Standard Edition Plus (`SE+`) is `SE`, with modules:

- [030-cloud-provider-vsphere](https://deckhouse.ru/products/kubernetes-platform/documentation/latest/modules/cloud-provider-vsphere/)
- [030-cloud-provider-zvirt](https://deckhouse.ru/products/kubernetes-platform/documentation/latest/modules/cloud-provider-zvirt/)
- [021-cni-cilium](https://deckhouse.ru/products/kubernetes-platform/documentation/latest/modules/cni-cilium/) (with support EgressGateway and EgressGatewayPolicy)
- [commander](https://deckhouse.ru/products/kubernetes-platform/modules/commander/stable/)
- [sds-drbd](https://deckhouse.ru/products/kubernetes-platform/modules/sds-drbd/stable/)

Revision comparison:
https://deckhouse.ru/products/kubernetes-platform/documentation/latest/revision-comparison.html

2. Also updated build `csi-external-provisioner` on BASE_GOLANG_23_ALPINE ( fix requires  error: go >= 1.22.7 ).

## Why do we need it, and what problem does it solve?

For business purposes.

## What is the expected result?

FE
image

EE
image
e2e (vsphere) - success: https://github.com/deckhouse/deckhouse/pull/10852#issuecomment-2507332224
e2e (static) - success: https://github.com/deckhouse/deckhouse/pull/10852#issuecomment-2507389608

SE+
image
e2e (vsphere) - success: https://github.com/deckhouse/deckhouse-test-1/pull/373#issuecomment-2507441757

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: global
type: feature
summary: Add Deckhouse Kubernetes Platform Standard Edition Plus (SE+).
impact_level: default
```
```changes
section: candi
type: fix
summary: Use golang 1.23 for build csi-external-provisioner.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by sprait** [comment]
/e2e/use/edition/ee

**Comment by sprait** [comment]
/e2e/run/vsphere

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/static'...

**Review by RomanenkoDenys — APPROVED** [review]

**Review by name212 — APPROVED** [review]

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Pull request merged**
