### PR TITLE
[candi] Enable IPv4 forwarding for all interfaces via sysctl-tuner

### PR DESCRIPTION
**Pull request by vitaliy-sn**
## Description

Packet forwarding for IPv4 is enabled via sysctl-tuner.

## Why do we need it, and what problem does it solve?

This is necessary to prevent a situation where, after a non-standard system boot, forwarding is not enabled on all network interfaces.
This problem is observed in the Yandex cloud with preemptible VMs, after the VM was interrupted and started again.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Packet forwarding for IPv4 is enabled via sysctl-tuner.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...

**Comment by vitaliy-sn** [comment]
/e2e/abort static;Static;containerd;1.25 7647682494 7647682494-1-con-1-25 /sys/deckhouse-oss/install:pr7278 astra@192.168.199.32

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...

**Review by RomanenkoDenys — COMMENTED** [review]
Why we cannot pass this parameter in the sysctl-tuner ?

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by name212** [comment]
/e2e/abort openstack;Standard;containerd;1.25 7916253833 7916253833-1-con-1-25 /sys/deckhouse-oss/install:pr7278 debian@31.129.32.208

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by name212** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 7914627069 7914627069-1-con-1-25 /sys/deckhouse-oss/install:pr7278 cloud-user@51.250.81.113

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Comment by vitaliy-sn** [comment]
/e2e/abort openstack;Standard;containerd;1.25 7927604962 7927604962-1-con-1-25 /sys/deckhouse-oss/install:pr7278 debian@46.161.52.242

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by vitaliy-sn** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 7928151596 7928151596-1-con-1-25 /sys/deckhouse-oss/install:pr7278 cloud-user@62.84.113.34

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 7928151596 7928151596-1-con-1-25 /sys/deckhouse-oss/install:pr7278 cloud-user@62.84.113.34

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
