### PR TITLE
[ingress-nginx] tune kruise leader election and verbosity

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
By default, `kruise controller` uses `configmapLeasese` leader-election-resource-lock type. The leader election timers are also a bit aggressive (lease duration - 15s, retry period - 2s). 
We change resource-lock type to use only leases, decreasing the amount of API requests, and readjust leader election timers to:
* lease retry - 10s
* lease duration - 35s
* lease renew deadline - 30s.

Tests show that kruise controller is able to elect its leader and start converging after a full restart in 50-60 seconds.

Also, the verbosity level of `kruise controller` was raised from 2 to 5 so that system administrators and cluster operators could perform preliminary diagnosis and troubleshooting of what was going on.

## Why do we need it, and what problem does it solve?
We update timers and resource lock type to decrease "the noise" of `kruise controller` in a cluster, without compromising severely its perfomance.
Log verbosity is increased for the sake of making it easier to understand `kruise controller's` logic and behavior when an issue arises.

## What is the expected result?
Kruise controller operates in a bit more inert but still robust way in terms of electing a leader, providing more logs about what it's up to.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: ingress-nginx
type: feature
summary: Tune kruise controller's leader election and verbosity.
impact: Kruise controller deployment will be updated and restarted.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by miklezzzz** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 5442270583 5442270583-1-con-1-23 /sys/deckhouse-oss/install:pr5092 cloud-user@51.250.75.145

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 5442270583 5442270583-1-con-1-23 /sys/deckhouse-oss/install:pr5092 cloud-user@51.250.75.145

**Review by yalosev — APPROVED** [review]

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [5118](https://github.com/deckhouse/deckhouse/pull/5118) to the branch [release-1.47](https://github.com/deckhouse/deckhouse/tree/release-1.47) successful!

**Pull request merged**
