### PR TITLE
[upmeter] Add link to CustomResources into the sidebar of the site

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Added link to CustomResources into the sidebar of the site.

## Changelog entries
```changes
section: upmeter
type: fix
summary: Added link to CustomResources into the sidebar of the site.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by z9r5** [comment]
Cherry-picked into release-1.32

**Pull request merged**
