### PR TITLE
[chore] Update Kubernetes

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Update Kubernetes patch versions.

1.24.12 ⇾ 1.24.13
1.25.8 ⇾ 1.25.9
1.26.3 ⇾ 1.26.4

## Why do we need it, and what problem does it solve?
It's important to bring fixes and to stay up to date with upstream.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: candi
type: feature
summary: "Upgraded patch versions of Kubernetes images: v1.24.13, v1.25.9, and v1.26.4."
impact: |
  "Kubernetes control-plane components will restart, kubelet will restart"
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.25 4733937556 4733937556-1-con-1-25 /sys/deckhouse-oss/install:pr4414 user@35.198.70.55

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.26 4733937556 4733937556-1-con-1-26 /sys/deckhouse-oss/install:pr4414 user@34.159.141.102

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.26 4734439786 4734439786-1-con-1-26 /sys/deckhouse-oss/install:pr4414 centos@52.29.79.86

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 4734439786 4734439786-1-con-1-25 /sys/deckhouse-oss/install:pr4414 centos@3.77.127.188

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 4739365994 4739365994-1-con-1-25 /sys/deckhouse-oss/install:pr4414 centos@18.185.25.134

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 4739711582 4739711582-1-con-1-25 /sys/deckhouse-oss/install:pr4414 cloud-user@158.160.61.144

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Review by fl64 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [4436](https://github.com/deckhouse/deckhouse/pull/4436) to the branch [release-1.45](https://github.com/deckhouse/deckhouse/tree/release-1.45) successful!

**Pull request merged**
