### PR TITLE
[ci] migrate from ansible to shell in werf

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Description
migrate from ansible to shell in werf

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: ci
type: chore
summary: Migrate from ansible to Shell in werf.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10778464238 10778464238-1-con-1-27 /sys/deckhouse-oss/install:pr9671 redos@84.201.128.246

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10789518165 10789518165-1-con-1-27 /sys/deckhouse-oss/install:pr9671 redos@84.201.174.253

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/run/yandex-cloud main
/e2e/use/k8s/1.27

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by z9r5** [comment]
Should we get rid of using the artifact werf directive in the PR? @alexey-gavrilov-flant

**Comment by alexey-gavrilov-flant** [comment]
@z9r5 Yes. This needs to be scheduled as it will prevent us from upgrading to werf v2.

**Review by z9r5 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
