### PR TITLE
[node-manager][deckhouse-controller] bashible-apiserver readiness probe tied to deckhouse readiness

### PR DESCRIPTION
**Pull request by mvasl**
## Description

`bashible-apiserver`'s readiness probe now fails if `deckhouse` deployment has no pods in `Ready` state.

This PR reverts `bashible-apiserver` downscaling during registry changes from https://github.com/deckhouse/deckhouse/pull/5603

## Why do we need it, and what problem does it solve?

See #5645

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: chore
summary: `bashible-apiserver`'s readiness probe now fails if `deckhouse` deployment has no pods in `Ready` state.
impact_level: default
```

```changes
section: deckhouse-controller
type: chore
summary: `bashible-apiserver` no longer scaled-down during registry changes.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...

**Review by yalosev — APPROVED** [review]

**Pull request merged**
