### PR TITLE
[dhctl] Preflight check ssh credentials before start instalations

### PR DESCRIPTION
**Pull request by aleksey-su**
## Description

Preflight check ssh credentials before start instalations

## Why do we need it, and what problem does it solve?
Before performing bootstrap, checks the possibility of autorize by ssh

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: feature
summary: Preflight check ssh credentials before start instalations
impact_level: default
```

### CODE REVIEW

**Comment by aleksey-su** [comment]
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Comment by aleksey-su** [comment]
/e2e/abort openstack;Standard;containerd;1.25 9223786691 9223786691-1-con-1-25 /sys/deckhouse-oss/install:pr8409 redos@46.161.52.68

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
