### PR TITLE
[testing][e2e] AltLinux node bootstrap fixes.

### PR DESCRIPTION
**Pull request by borg-z**
## Description

Added NGC for AltLinux node bootstrap fixes. 
`apt-get update` in ALT Linux can crash if a connection is broken while apt-get is running. In this case, there are partially loaded files in `var/lib/apt/lists/partial`, which prevent apt-get update from working.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: chore
summary: fix e2e ALT Linux bootstrap
impact: 
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by borg-z** [comment]
/e2e/abort static;Static;containerd;1.27 11327909500 11327909500-1-con-1-27 /sys/deckhouse-oss/install:pr10113 astra@192.168.199.130

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by borg-z** [comment]
/e2e/abort static;Static;containerd;1.27 11330061307 11330061307-1-con-1-27 /sys/deckhouse-oss/install:pr10113 astra@192.168.199.92

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by borg-z** [comment]
/e2e/abort static;Static;containerd;1.27 11380640565 11380640565-3-con-1-27 /sys/deckhouse-oss/install:pr10113

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by borg-z** [comment]
/e2e/abort static;Static;containerd;1.27 11380640565 11380640565-3-con-1-27 /sys/deckhouse-oss/install:pr10113

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Review by sprait — APPROVED** [review]

**Review by name212 — APPROVED** [review]

**Pull request merged**
