### PR TITLE
[cni-cilium] bump cilium and virt-cilium to v1.12.8

### PR DESCRIPTION
**Pull request by kvaps**
## Description

Bump:
- Cilium v1.12.7 --> v1.12.8
- Cilium (for virtualization) v1.11.14 --> v1.12.8

includes https://github.com/cilium/cilium/pull/24075

## What is the expected result?

Same cilium everywhere

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cni-cilium
type: feature
summary: bump cilium and virt-cilium to v1.12.8
impact: All cilium-agent pods will be restarted
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/openstack'...

**Comment by fl64** [comment]
It would be nice to update the cilium operator as well

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/openstack'...

**Comment by kvaps** [comment]
> It would be nice to update the cilium operator as well
Good point, done!

**Review by fl64 — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
