### PR TITLE
Update Kubernetes patch versions:

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Update Kubernetes patch versions:

- 1.30.1 ⇾ 1.30.2

## Why do we need it, and what problem does it solve?

It's important to bring fixes and to stay up to date with upstream.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: candi
type: chore
summary: "Bump patch versions of Kubernetes images: `v1.30.2`"
impact: |
  Kubernetes v1.30 control-plane components will restart, kubelet will restart.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.30 9757529314 9757529314-1-con-1-30 /sys/deckhouse-oss/install:pr8873 redos@178.154.226.89

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...

**Pull request merged**
