### PR TITLE
[monitoring] Fix node exporter NTP address

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

Fix node exporter ntp address.
## Why do we need it, and what problem does it solve?

Node exporter awaits ntp server on localhost, bu our chrony listens on the node ip.
This PR fixes access from node-exporter to the chrony on the node.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: monitoring
type: fix
summary: Fix node exporter NTP address.
impact: node-exporter will restart.
impact_level: default
```

### CODE REVIEW

**Comment by RomanenkoDenys** [comment]
Screenshot 2024-07-11 at 16 28 39

**Comment by RomanenkoDenys** [comment]
Screenshot 2024-07-12 at 13 53 19

**Review by vladimirGuryanov — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9951329662 9951329662-1-con-1-27 /sys/deckhouse-oss/install:pr9016 redos@158.160.111.217

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9952158790 9952158790-1-con-1-27 /sys/deckhouse-oss/install:pr9016 redos@158.160.38.16

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9053](https://github.com/deckhouse/deckhouse/pull/9053) to the branch [release-1.62](https://github.com/deckhouse/deckhouse/tree/release-1.62) successful!

**Pull request merged**
