### PR TITLE
[core] Move `global.storageClass` to `global.modules.storageClass`

### PR DESCRIPTION
**Pull request by Ranger-X**
## Description
`global.storageClass` parameter (which used for specify default StorageClass for Deckhouse's components PVCs) moved to `global.modules.storageClass`.

## Why do we need it, and what problem does it solve?

This is necessary so that users do not confuse it with the `global.defaultClusterStorageClass` setting.

## What is the expected result?

`global.modules.storageClass` will use the value from the `global.storageClass` parameter via the conversion mechanism. Therefore, the changes will not expect to be noticeable to users.

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: global-hooks
type: chore
summary: Move `global.storageClass` to `global.modules.storageClass`.
impact: 
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Ranger-X. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Ranger-X. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Ranger-X. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Ranger-X. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Review by z9r5 — APPROVED** [review]

**Pull request merged**
