### PR TITLE
[prometheus] Fix permissions for existing files

### PR DESCRIPTION
**Pull request by vitaliy-sn**
## Description

Fixed permissions for existing files after changing GID and UID.

## Why do we need it, and what problem does it solve?

Prometheus can't start

## Test results

<details>

```shell
# kubectl -n d8-monitoring logs prometheus-main-0 fix-permissions  -f
changed ownership of '/prometheus-db/01HAAYRKFEESRWBYSNZDG445S8/meta.json' to 64535:64535
changed ownership of '/prometheus-db/01HAAYRKFEESRWBYSNZDG445S8/index' to 64535:64535
changed ownership of '/prometheus-db/01HAAYRKFEESRWBYSNZDG445S8/tombstones' to 64535:64535
changed ownership of '/prometheus-db/01HAAYRKFEESRWBYSNZDG445S8/chunks/000001' to 64535:64535
changed ownership of '/prometheus-db/01HAAYRKFEESRWBYSNZDG445S8/chunks' to 64535:64535
changed ownership of '/prometheus-db/01HAAYRKFEESRWBYSNZDG445S8' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PN8J7238BFGPER3SYFTP/meta.json' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PN8J7238BFGPER3SYFTP/index' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PN8J7238BFGPER3SYFTP/tombstones' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PN8J7238BFGPER3SYFTP/chunks/000001' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PN8J7238BFGPER3SYFTP/chunks' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PN8J7238BFGPER3SYFTP' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PSD3GR5EE31Q0PA2YQHG/meta.json' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PSD3GR5EE31Q0PA2YQHG/index' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PSD3GR5EE31Q0PA2YQHG/tombstones' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PSD3GR5EE31Q0PA2YQHG/chunks/000001' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PSD3GR5EE31Q0PA2YQHG/chunks' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PSD3GR5EE31Q0PA2YQHG' to 64535:64535
changed ownership of '/prometheus-db/01HAK3P143KSNP0D6EXVB4Y7NJ/meta.json' to 64535:64535
changed ownership of '/prometheus-db/01HAK3P143KSNP0D6EXVB4Y7NJ/index' to 64535:64535
changed ownership of '/prometheus-db/01HAK3P143KSNP0D6EXVB4Y7NJ/tombstones' to 64535:64535
changed ownership of '/prometheus-db/01HAK3P143KSNP0D6EXVB4Y7NJ/chunks/000001' to 64535:64535
changed ownership of '/prometheus-db/01HAK3P143KSNP0D6EXVB4Y7NJ/chunks' to 64535:64535
changed ownership of '/prometheus-db/01HAK3P143KSNP0D6EXVB4Y7NJ' to 64535:64535
changed ownership of '/prometheus-db/01HAKAHRC2MJDBSBD4X1ZX5N5Y/meta.json' to 64535:64535
changed ownership of '/prometheus-db/01HAKAHRC2MJDBSBD4X1ZX5N5Y/index' to 64535:64535
changed ownership of '/prometheus-db/01HAKAHRC2MJDBSBD4X1ZX5N5Y/tombstones' to 64535:64535
changed ownership of '/prometheus-db/01HAKAHRC2MJDBSBD4X1ZX5N5Y/chunks/000001' to 64535:64535
changed ownership of '/prometheus-db/01HAKAHRC2MJDBSBD4X1ZX5N5Y/chunks' to 64535:64535
changed ownership of '/prometheus-db/01HAKAHRC2MJDBSBD4X1ZX5N5Y' to 64535:64535
changed ownership of '/prometheus-db/01HAKAHWKEJ847D2Y4R7WBCHFY/meta.json' to 64535:64535
changed ownership of '/prometheus-db/01HAKAHWKEJ847D2Y4R7WBCHFY/index' to 64535:64535
changed ownership of '/prometheus-db/01HAKAHWKEJ847D2Y4R7WBCHFY/tombstones' to 64535:64535
changed ownership of '/prometheus-db/01HAKAHWKEJ847D2Y4R7WBCHFY/chunks/000001' to 64535:64535
changed ownership of '/prometheus-db/01HAKAHWKEJ847D2Y4R7WBCHFY/chunks' to 64535:64535
changed ownership of '/prometheus-db/01HAKAHWKEJ847D2Y4R7WBCHFY' to 64535:64535
changed ownership of '/prometheus-db/01HAKHDFMM6MTKTYG7BFCSVCKK/meta.json' to 64535:64535
changed ownership of '/prometheus-db/01HAKHDFMM6MTKTYG7BFCSVCKK/index' to 64535:64535
changed ownership of '/prometheus-db/01HAKHDFMM6MTKTYG7BFCSVCKK/tombstones' to 64535:64535
changed ownership of '/prometheus-db/01HAKHDFMM6MTKTYG7BFCSVCKK/chunks/000001' to 64535:64535
changed ownership of '/prometheus-db/01HAKHDFMM6MTKTYG7BFCSVCKK/chunks' to 64535:64535
changed ownership of '/prometheus-db/01HAKHDFMM6MTKTYG7BFCSVCKK' to 64535:64535
changed ownership of '/prometheus-db/chunk_snapshot.000049.0009437184/00000000' to 64535:64535
changed ownership of '/prometheus-db/chunk_snapshot.000049.0009437184' to 64535:64535
changed ownership of '/prometheus-db/chunks_head/000010' to 64535:64535
changed ownership of '/prometheus-db/chunks_head/000011' to 64535:64535
changed ownership of '/prometheus-db/chunks_head/000009' to 64535:64535
changed ownership of '/prometheus-db/chunks_head/000008' to 64535:64535
changed ownership of '/prometheus-db/chunks_head' to 64535:64535
changed ownership of '/prometheus-db/permissions-fixed-flag' to 64535:64535
changed ownership of '/prometheus-db/queries.active' to 64535:64535
changed ownership of '/prometheus-db/wal/00000049' to 64535:64535
changed ownership of '/prometheus-db/wal/00000048' to 64535:64535
changed ownership of '/prometheus-db/wal/00000047' to 64535:64535
changed ownership of '/prometheus-db/wal/00000046' to 64535:64535
changed ownership of '/prometheus-db/wal/checkpoint.00000044/00000000' to 64535:64535
changed ownership of '/prometheus-db/wal/checkpoint.00000044' to 64535:64535
changed ownership of '/prometheus-db/wal/00000045' to 64535:64535
changed ownership of '/prometheus-db/wal' to 64535:64535
```

</details>

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: fix
summary: Fixed permissions for existing files after changing GID and UID.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...

**Comment by vitaliy-sn** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 6219736597 6219736597-1-con-1-25 /sys/deckhouse-oss/install:pr5847 centos@3.124.210.232

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [5858](https://github.com/deckhouse/deckhouse/pull/5858) to the branch [release-1.51](https://github.com/deckhouse/deckhouse/tree/release-1.51) successful!

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 6219736597 6219736597-1-con-1-25 /sys/deckhouse-oss/install:pr5847 centos@3.124.210.232

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
