### PR TITLE
[candi] Fix bootstrap by replace bb-error checks with trap

### PR DESCRIPTION
**Pull request by asviel**
## Description

`if bb-error?` code doesn't work because of the "bash strict mode" (`set -e`) because an error causes an immediate exit and we can't process the return code. `trap` solves this problem.

## Why do we need it, and what problem does it solve?

Since the if block doesn't execute, we don't clean up temporary files or re-fetch registry packages in case of an error. This leads to bootstrap failure.

## Why do we need it in the patch release (if we do)?

This affects clients, but it doesn't happen very often.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Fix bootstrap by replace bb-error checks with trap.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/gcp'...

**Comment by asviel** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.25 8064498048 8064498048-1-con-1-25 /sys/deckhouse-oss/install:pr7647 user@34.89.153.235

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've recognized your '/e2e/abort' command and started the workflow...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/gcp'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
