### PR TITLE
[testing] Ignore alerts generated by not init ebpf exporter only for older kernels in e2e tests

### PR DESCRIPTION
**Pull request by nikiGGG**
## Description

On kernels <5.08, the ebpf exporter cannot start. Fix the validation warning in the e2e tests that are displayed on older kernels.

## Why do we need it, and what problem does it solve?

In some clouds, we run vm's with a kernel lower than 5.08. e2e tests with this vm's fail due to an incorrect kernel. We have to ignore it.

## What is the expected result?

The e2e test runs on virtual machines running on old kernels. On a newer kernel, we should not ignore the alerts "D8NodeHasUnmetKernelRequirements" and "KubernetesDaemonSetReplicasUnavailable".

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: fix
summary: Ignore alerts generated by not init ebpf exporter only for older kernels in e2e tests.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/aws'...

**Comment by nikiGGG** [comment]
ignore alert in [e2e test](https://github.com/deckhouse/deckhouse/actions/runs/7746934544) on AWS cloud:
Снимок экрана 2024-02-02 в 00 35 10

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by nikiGGG** [comment]
on kernel version >5.08 alert does not ignore. Example (kernel 5.10):
Снимок экрана 2024-02-02 в 14 53 30

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
