### PR TITLE
[dhctl] Fix panic during resources creation

### PR DESCRIPTION
**Pull request by name212**
## Description
Fix panic while resources creation

```
│ ┌ Create deckhouse.io/v1alpha1, Kind=ModuleSource resources
│ │ Manifest for ModuleSource deckhouse
│ │ 🎉 Succeeded!
│ └ Create deckhouse.io/v1alpha1, Kind=ModuleSource resources (0.01 seconds)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1a7693d]

goroutine 7 [running]:
github.com/deckhouse/deckhouse/dhctl/pkg/kubernetes/actions/resources.(*clusterIsBootstrapCheck).outputNodeGroups(0x0?)
    /dhctl/pkg/kubernetes/actions/resources/cluster_is_bootstrap.go:174 +0x1d
github.com/deckhouse/deckhouse/dhctl/pkg/kubernetes/actions/resources.(*clusterIsBootstrapCheck).outputProgressInfo(0x0)
    /dhctl/pkg/kubernetes/actions/resources/cluster_is_bootstrap.go:168 +0x18
github.com/deckhouse/deckhouse/dhctl/pkg/kubernetes/actions/resources.CreateResourcesLoop.func1()
    /dhctl/pkg/kubernetes/actions/resources/resources.go:278 +0xbe
github.com/deckhouse/deckhouse/dhctl/pkg/util/retry.(*Loop).Run.func1()
```

## Why do we need it, and what problem does it solve?

`dhctl bootstrap-phase create-resources` does not work

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix 
summary: Fix panic during resources creation
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
