### PR TITLE
[docs][testing] Add support of Astra Linux 1.7.5 on the site and in e2e tests

### PR DESCRIPTION
**Pull request by nikiGGG**
## Description

Documentation and tests update

## Why do we need it, and what problem does it solve?

Documentation is up-to-date. Need to use in e2e tests

## What is the expected result?

Astra 1.7.5 listed at https://deckhouse.ru/documentation/v1/supported_versions.html. e2e Static tests pass successfully using alse-1.7.5

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [x] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: docs
type: fix
summary: Add support of Astra `1.7.5`.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by nikiGGG** [comment]
/e2e/abort static;Static;containerd;1.25 7799464870 7799464870-1-con-1-25 /sys/deckhouse-oss/install:pr7396

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by nikiGGG** [comment]
/e2e/abort static;Static;containerd;1.25 7805586922 7805586922-1-con-1-25 /sys/deckhouse-oss/install:pr7396

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/static'...

**Comment by nikiGGG** [comment]
Astra linux 1.7.5 (6.1 kernel) successfully bootstrapped in e2e test:
Снимок экрана 2024-02-07 в 00 42 29

**Review by z9r5 — APPROVED** [review]

**Pull request merged**
