### PR TITLE
[docs] Get rid of numeric prefixes in module URL on the site

### PR DESCRIPTION
**Pull request by z9r5**
## Description

- Adjust module naming to remove numeric prefixes in module URL on the site and in the `documentation` module.
- Build refactoring to improve efficiency.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: docs, documentation
type: chore
summary: Get rid of numeric prefixes in module URL.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit 16f8c7805c2df87a9b419488106544c06c5e8176 to the branch [release-1.66](https://github.com/deckhouse/deckhouse/tree/release-1.66) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/11818382987) for details.

**Comment by z9r5** [comment]
Cherry-picked into release-1.66

**Pull request merged**
