### PR TITLE
[docs][cloud-provider-vsphere] Fix spec. network name for VSphere

### PR DESCRIPTION
**Pull request by haosb**
## Description
Fix unknown field in InstanceClass example

## Why do we need it, and what problem does it solve?
Fix unknown field that lead to misunderstanding

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: docs
type: fix
summary: Fix spec. network name for VSphere
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10679](https://github.com/deckhouse/deckhouse/pull/10679) to the branch [release-1.66](https://github.com/deckhouse/deckhouse/tree/release-1.66) successful!

**Comment by deckhouse-BOaTswain** [comment]
Backport failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/11854095072) for details.

**Comment by z9r5** [comment]
Cherry-picked into release-1.66, release-1.65

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10680](https://github.com/deckhouse/deckhouse/pull/10680) to the branch [release-1.65](https://github.com/deckhouse/deckhouse/tree/release-1.65) successful!

**Pull request merged**
