### PR TITLE
[dhctl] Refactor resources checking

### PR DESCRIPTION
**Pull request by name212**
## Description

In this pull request https://github.com/deckhouse/deckhouse/pull/8328 we went the wrong way.
Tracking resources using watchers has serious disadvantages:
- watchers can be lost and re-subscription greatly complicates the code;
- watchers are launched in separate goroutines, we lose the ability to adequately display progress.

In this pull request we returned to cyclic resource checking.

## Why do we need it, and what problem does it solve?
Incorrect tracking resources implementation fix.

## What is the expected result?

image
image
image

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Refactor resources checking
impact_level: low
```

### CODE REVIEW

**Comment by name212** [comment]
/e2e/abort static;Static;containerd;1.27 10432435030 10432435030-1-con-1-27 /sys/deckhouse-oss/install:pr9397 astra@192.168.199.192

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by name212** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10433840321 10433840321-1-con-1-27 /sys/deckhouse-oss/install:pr9397 redos@89.169.147.75

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Pull request merged**
