### PR TITLE
[common] Bump shell-operator version for common/shell-operator image

### PR DESCRIPTION
**Pull request by yalosev**
## Description
Bump shell-operator image

## Why do we need it, and what problem does it solve?
Logrus in the previous version has memory leak in the loaded environments

## Why do we need it in the patch release (if we do)?
Avoid memory leak

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: common
type: fix
summary: Bump shell-operator image.
impact: Fix webhook-handler memory leak.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit 05b7ea58cef7bdd9bfcee1db5d3d42f578a4d041 to the branch [release-1.65](https://github.com/deckhouse/deckhouse/tree/release-1.65) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/11952570095) for details.

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10763](https://github.com/deckhouse/deckhouse/pull/10763) to the branch [release-1.66](https://github.com/deckhouse/deckhouse/tree/release-1.66) successful!

**Comment by yalosev** [comment]
backport to 1.65 - https://github.com/deckhouse/deckhouse/pull/10764

**Pull request merged**
