### PR TITLE
 [candi] fix bashible rights to run when SELixux in Enforcement mode

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

Fix bashible rights to run when SELixux in Enforcement mode.
## Why do we need it, and what problem does it solve?

Bashible does not start in SELinux Enforcement mode.
## Why do we need it in the patch release (if we do)?

This PR needed in the patch release due to new clusters bootstrap on Centos 8 should fail without it.
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix | feature | chore
summary: fix bashible rights to run when SELixux in Enforcement mode
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/azure'...

**Comment by RomanenkoDenys** [comment]
manually checked in cluster on Rocky Linux 8

**Comment by RomanenkoDenys** [comment]
/e2e/abort azure;Standard;containerd;1.23 5478592930 5478592930-2-con-1-23 /sys/deckhouse-oss/install:pr5148 azureuser@20.224.19.111

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
