### PR TITLE
Feat/werf division

### PR DESCRIPTION
**Pull request by KraMorK**
## Description

werf.yaml becomes large and unreadable.
## Why do we need it, and what problem does it solve?

werf.yaml is necessary to continue to split it into different files
## Why do we need it in the patch release (if we do)?

Not releated to release
## What is the expected result?

werf.yaml divided into logical blocks
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

werf.yaml is necessary to continue to split it into different files
```changes
section: ci
type: chore
summary: werf.yaml is necessary to continue to split it into different files.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by KraMorK** [comment]
fe - 68 modules
ce - 
be -
se - 
ee -

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Review by RomanenkoDenys — APPROVED** [review]

**Review by name212 — APPROVED** [review]

**Pull request merged**
