### PR TITLE
[testing] set centos 9 stream for aws

### PR DESCRIPTION
**Pull request by sprait**
## Description

Use centos 9 stream image in aws e2e because centos 7 end of life is June 30. 

## Why do we need it, and what problem does it solve?

Centos 7 end of life is June 30. 

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: fix
summary: Use centos 9 stream image in aws e2e. 
impact_level: low
```
```changes
section: terraform-manager
type: fix
summary: Rebuild with dev base-image. 
impact_level: low
```
```changes
section: candi
type: fix
summary: Fix 001_create_nvme_ebs_aliases.sh step for cases without requirements symlinks.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by sprait** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 9758671675 9758671675-1-con-1-27 /sys/deckhouse-oss/install:pr8876

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Comment by sprait** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 9758798082 9758798082-1-con-1-27 /sys/deckhouse-oss/install:pr8876 centos@18.198.148.154

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by sprait** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 9759462768 9759462768-1-con-1-27 /sys/deckhouse-oss/install:pr8876 ec2-user@35.156.88.229

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [8885](https://github.com/deckhouse/deckhouse/pull/8885) to the branch [release-1.62](https://github.com/deckhouse/deckhouse/tree/release-1.62) successful!

**Comment by z9r5** [comment]
/e2e/abort openstack;Standard;containerd;1.27 9758671838 9758671838-1-con-1-27 /sys/deckhouse-oss/install:pr8876 redos@45.12.229.43

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit 91940eedacfaaf64d453bc8741d38b9f79bbcaee to the branch [release-1.61](https://github.com/deckhouse/deckhouse/tree/release-1.61) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/9807744925) for details.

**Comment by z9r5** [comment]
Cherry-picked into release-1.61

**Pull request merged**
