### PR TITLE
[docs][cloud-provider-yandex] Update docs about parameters

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Update docs about the `existingZoneToSubnetIDMap` and `exporterAPIKey` parameters.

Ref: #2563

## Changelog entries
```changes
section: cloud-provider-yandex
type: fix
summary: Update docs about the `existingZoneToSubnetIDMap` and `exporterAPIKey` parameters.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [2743](https://github.com/deckhouse/deckhouse/pull/2743) to the branch [release-1.37](https://github.com/deckhouse/deckhouse/tree/release-1.37) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [2745](https://github.com/deckhouse/deckhouse/pull/2745) to the branch [release-1.38](https://github.com/deckhouse/deckhouse/tree/release-1.38) successful!

**Pull request merged**
