### PR TITLE
[external-module-manager] fix restore absent module for multi master

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
Update restoreAbsentSourceModules so that it also checks that there is up to date version of a module is used by deckhouse.

## Why do we need it, and what problem does it solve?
It should fix the problem with multi-master clusters when masters have different version of modules on their file systems. Only latest deployed version should be used by masters.

## Why do we need it in the patch release (if we do)?
It fixes a bug.

## What is the expected result?
If there is a symlink leading to an old superseded version of a module, this symlink should be updated to the latest module version directory.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: external-module-manager
type: fix
summary: Fix outdated module versions in multi-master environment.
impact_level: default
```

### CODE REVIEW

**Review by nabokihms — APPROVED** [review]

**Comment by miklezzzz** [comment]
before
image

**Comment by miklezzzz** [comment]
after :))
```
{"component":"ModuleReleaseController","level":"warning","msg":"Couldn't create module symlink: Create symlink for module \"echo\" failed: symlink ../echo/v0.3.56 /deckhouse/external-modules/modules/935-echo: file exists","time":"2024-01-19T12:23:51Z"}
```

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [7232](https://github.com/deckhouse/deckhouse/pull/7232) to the branch [release-1.56](https://github.com/deckhouse/deckhouse/tree/release-1.56) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [7234](https://github.com/deckhouse/deckhouse/pull/7234) to the branch [release-1.57](https://github.com/deckhouse/deckhouse/tree/release-1.57) successful!

**Pull request merged**
