### PR TITLE
[registry-packages] refactor build

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

Move registry packages to build from local repo.
Refactored components:
- [x] conntrack-debian. Removed. The component is unused now (previously we use it to work on astra linux with debian bundle).
- [x] containerd.
- [x] crictl.
- [x] curl. Updated to 8.2.1.
- [x] inotify-tools. Removed. The component is unused now (previously we use it to kubernetes-api-proxy work).
- [x] jq.
- [x] kubernetes-cni.
- [x] toml-merge.
- [x] virt-what-debian. Removed. The component is unused now (previously we use it to work on astra linux with debian bundle).

## Why do we need it, and what problem does it solve?

This PR is a part of moving to Distroless.
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: chore
summary: move registry packages to build from local repos.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort static;Static;containerd;1.25 6199502991 6199502991-1-con-1-25 /sys/deckhouse-oss/install:pr5798 astra@192.168.199.186

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/static'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
