### PR TITLE
[monitoring-kubernetes] Fix helm releases scan

### PR DESCRIPTION
**Pull request by yalosev**
## Description
Refactor hook with checking helm releases for deprecated versions

## Why do we need it, and what problem does it solve?
Previous versions doesn't work for Automatic kubernetes version check

## Why do we need it in the patch release (if we do)?
We have to check requirements in the next release

## What is the expected result?
```yaml
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  name: v1.60.1
spec:
  requirements:
    autoK8sVersion: "1.32"
  version: v1.60.1
```

```sh
v1.60.1   Pending   2m19s            "autoK8sVersion" requirement for DeckhouseRelease "1.60.1" not met: k8s version is not available because deprecated resources are used. Check alerts for details
```

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: monitoring-kubernetes
type: fix
summary: Fix hook with helm releases scan for deprecated api versions.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...

**Review by miklezzzz — APPROVED** [review]

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 8737426929 8737426929-1-con-1-27 /sys/deckhouse-oss/install:pr8159

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [8198](https://github.com/deckhouse/deckhouse/pull/8198) to the branch [release-1.59](https://github.com/deckhouse/deckhouse/tree/release-1.59) successful!

**Pull request merged**
