### PR TITLE
[testing] Skip OSS linter for the deckhouse-config module

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Skip OSS linter for the deckhouse-config module

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: testing
type: chore
summary: Skip OSS linter for the `deckhouse-config` module.
impact_level: low
```

### CODE REVIEW

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [3517](https://github.com/deckhouse/deckhouse/pull/3517) to the branch [release-1.42](https://github.com/deckhouse/deckhouse/tree/release-1.42) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [3518](https://github.com/deckhouse/deckhouse/pull/3518) to the branch [release-1.41](https://github.com/deckhouse/deckhouse/tree/release-1.41) successful!

**Pull request merged**
