### PR TITLE
[e2e] fix preserve_hostname and disk.EnableUUID in vcd template debian-12

### PR DESCRIPTION
**Pull request by sprait**
## Description

Fix vcd template debian 12 for e2e.

## Why do we need it, and what problem does it solve?

For success complete vcd e2e.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: e2e
type: fix
summary: Fix vcd template debian 12 for e2e.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vcd'...

**Comment by sprait** [comment]
/e2e/abort vclouddirector;Standard;containerd;1.27 10162580469 10162580469-1-con-1-27 /sys/deckhouse-oss/install:pr9213 ubuntu@192.168.254.208

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/vcd'...

**Comment by sprait** [comment]
/e2e/abort vclouddirector;Standard;containerd;1.27 10163941613 10163941613-1-con-1-27 /sys/deckhouse-oss/install:pr9213

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vcd'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
