### PR TITLE
[global] BE edition improvements

### PR DESCRIPTION
**Pull request by name212**
## Description
Modules removed from BE:
- ceph-csi
- openvpn

Added to BE:
- user-authz
- node-local-dns
- flant-integration

## Why do we need it, and what problem does it solve?
It needs for business 

## Why do we need it in the patch release (if we do)?
It needs for business 

## What is the expected result?

FE openstack
image
image
image
image

E2e was passed for vsphere, openstack, yandex

BE
image
image
image
image
image

ceph-csi and openvpn excluded successfully 
node-local-dns and flant-integration is working
E2e test was not passed for openstack. It is normal.
E2e  was passed for yandex with REDOS.

CE

Boes not bootstrap on alt linux it is OK
image
image
image
image

openvpn and ceph-csi enabled successfully. user-authz webhook was not start and is ok.
flant-integration was not enabled and it is ok

e2e passed for gcp and not passed for openstack - it is ok.

EE
image
image
image

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: global
type: fix
summary: BE edition improvements
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by z9r5** [comment]
We need to update the comparison table of editions...

**Review by z9r5 — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [7376](https://github.com/deckhouse/deckhouse/pull/7376) to the branch [release-1.57](https://github.com/deckhouse/deckhouse/tree/release-1.57) successful!

**Pull request merged**
