### PR TITLE
[node-manager] fixed pull/9436

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Description
Hotfix for PR https://github.com/deckhouse/deckhouse/pull/9436

## Why do we need it, and what problem does it solve?
Fix installing CE on OpenSuse.

## Why do we need it in the patch release (if we do)?
1.65 has already been cut off.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: fix
summary: Fix installing CE on OpenSuse.
impact_level: low 
```

### CODE REVIEW

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10333](https://github.com/deckhouse/deckhouse/pull/10333) to the branch [release-1.65](https://github.com/deckhouse/deckhouse/tree/release-1.65) successful!

**Pull request merged**
