### PR TITLE
[cni-cilium] Upgrade to 1.14.14

### PR DESCRIPTION
**Pull request by AndreyPavlovFlant**
## Description

Updating `cilium` and its components to version 1.14.14

## Why do we need it, and what problem does it solve?

From time to time, new updates are released to fix serious bugs and critical vulnerabilities.

## What is the expected result?

We are using the "cilium" version, which fixes serious bugs and closes critical vulnerabilities.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cni-cilium
type: chore
summary: Updating `cilium` and its components to version 1.14.14
impact: All cilium pods will be restarted.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by AndreyPavlovFlant** [comment]
/e2e/abort openstack;Standard;containerd;1.27 10882741754 10882741754-1-con-1-27 /sys/deckhouse-oss/install:pr9650 redos@37.9.4.159

**Comment by AndreyPavlovFlant** [comment]
/e2e/abort static;Static;containerd;1.27 10882741763 10882741763-1-con-1-27 /sys/deckhouse-oss/install:pr9650 astra@192.168.199.129

**Comment by AndreyPavlovFlant** [comment]
/e2e/abort vcd;Standard;containerd;1.27 10882742188 10882742188-1-con-1-27 /sys/deckhouse-oss/install:pr9650 ubuntu@192.168.254.11

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by AndreyPavlovFlant** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 10882742715 10882742715-1-con-1-27 /sys/deckhouse-oss/install:pr9650 ubuntu@10.220.203.26

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vsphere'...

**Review by apolovov — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
