### PR TITLE
[delivery][linstor][virtualization] Fix deprecated PDB APIs

### PR DESCRIPTION
**Pull request by kvaps**
## Description

Fix deprecated PDB APIs

## Why do we need it, and what problem does it solve?

Kubernetes v1.25+ support

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: delivery
type: fix
summary: Fix deprecated PDB APIs for Kubernetes v1.25+
impact_level: low
---
section: linstor
type: fix
summary: Fix deprecated PDB APIs for Kubernetes v1.25+
impact_level: low
---
section: virtualization
type: fix
summary: Fix deprecated PDB APIs for Kubernetes v1.25+
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @shvgn. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Review by yalosev — APPROVED** [review]

**Review by shvgn — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [3697](https://github.com/deckhouse/deckhouse/pull/3697) to the branch [release-1.43](https://github.com/deckhouse/deckhouse/tree/release-1.43) successful!

**Pull request merged**
