### PR TITLE
[upmeter] rescheduler hook: more reliable Pod re-creating, deleting PVC on zone change

### LINKED ISSUE #281: [upmeter] Smoke-mini pods pending because the resheduler hook does not delete PVC when zone changes
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.25.0

### Expected Behavior

Smoke-mini pods start running on nodes they are assigned to. The rescheduler hook takes into account volumes that have nodeAffinity specified.

### Actual Behavior

Smoke-mini pods do not schedule due to 'volume node affinity conflict'. See logs below.

There is a zone conflict between PVC and PV. Removing PVCs of pending pods resolved the problem. Rescheduler should delete PVCs itself, but it doesn't happend. So it is a bug. It might fail with timeout errors seen in deckhouse logs.

### Steps To Reproduce

_No response_

### Additional Information

_No response_

### Logs

```
5m18s       Warning   FailedScheduling         pod/smoke-mini-b-0           skip schedule deleting pod: d8-upmeter/smoke-mini-b-0
4m51s       Warning   FailedScheduling         pod/smoke-mini-b-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
4m26s       Warning   FailedScheduling         pod/smoke-mini-a-0           skip schedule deleting pod: d8-upmeter/smoke-mini-a-0
4m22s       Warning   FailedScheduling         pod/smoke-mini-a-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
4m24s       Warning   FailedScheduling         pod/smoke-mini-a-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
3m59s       Normal    NotTriggerScaleUp        pod/smoke-mini-b-0           pod didn't trigger scale-up (it wouldn't fit if a new node is added): 4 node(s) didn't match node selector, 11 max node group size reached
3m34s       Warning   FailedScheduling         pod/smoke-mini-b-0           skip schedule deleting pod: d8-upmeter/smoke-mini-b-0
3m32s       Warning   FailedScheduling         pod/smoke-mini-b-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
3m25s       Warning   FailedScheduling         pod/smoke-mini-b-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
2m42s       Warning   FailedScheduling         pod/smoke-mini-a-0           skip schedule deleting pod: d8-upmeter/smoke-mini-a-0
2m38s       Warning   FailedScheduling         pod/smoke-mini-a-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
2m23s       Warning   FailedScheduling         pod/smoke-mini-a-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
2m18s       Normal    NotTriggerScaleUp        pod/smoke-mini-b-0           pod didn't trigger scale-up (it wouldn't fit if a new node is added): 4 node(s) didn't match node selector, 11 max node group size reached
2m18s       Normal    NotTriggerScaleUp        pod/smoke-mini-a-0           pod didn't trigger scale-up (it wouldn't fit if a new node is added): 4 node(s) didn't match node selector, 11 max node group size reached
109s        Warning   FailedScheduling         pod/smoke-mini-b-0           skip schedule deleting pod: d8-upmeter/smoke-mini-b-0
108s        Warning   FailedScheduling         pod/smoke-mini-b-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
82s         Warning   FailedScheduling         pod/smoke-mini-b-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
57s         Warning   FailedScheduling         pod/smoke-mini-a-0           skip schedule deleting pod: d8-upmeter/smoke-mini-a-0
56s         Warning   FailedScheduling         pod/smoke-mini-a-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
22s         Warning   FailedScheduling         pod/smoke-mini-a-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
36s         Normal    NotTriggerScaleUp        pod/smoke-mini-b-0           pod didn't trigger scale-up (it wouldn't fit if a new node is added): 4 node(s) didn't match node selector, 11 max node group size reached
36s         Normal    NotTriggerScaleUp        pod/smoke-mini-a-0           pod didn't trigger scale-up (it wouldn't fit if a new node is added): 4 node(s) didn't match node selector, 11 max node group size reached
5s          Warning   FailedScheduling         pod/smoke-mini-b-0           skip schedule deleting pod: d8-upmeter/smoke-mini-b-0
4s          Warning   FailedScheduling         pod/smoke-mini-b-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
4s          Warning   FailedScheduling         pod/smoke-mini-b-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
0s          Warning   FailedScheduling         pod/smoke-mini-b-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
60m         Warning   FailedScheduling         pod/smoke-mini-a-0           skip schedule deleting pod: d8-upmeter/smoke-mini-a-0
60m         Warning   FailedScheduling         pod/smoke-mini-a-0           0/27 nodes are available: 1 node(s) had volume node affinity conflict, 26 node(s) didn't match node selector.
60m         Warning   FailedScheduling         pod/smoke-mini-b-0           skip schedule deleting pod: d8-upmeter/smoke-mini-b-0
60m         Warning   FailedScheduling         pod/smoke-mini-b-0           0/27 nodes are available: 1 node(s) had volume node affinity conflict, 26 node(s) didn't match node selector.
0s          Warning   FailedScheduling         pod/smoke-mini-a-0           skip schedule deleting pod: d8-upmeter/smoke-mini-a-0
0s          Normal    SuccessfulCreate         statefulset/smoke-mini-a     create Pod smoke-mini-a-0 in StatefulSet smoke-mini-a successful
0s          Warning   FailedScheduling         pod/smoke-mini-a-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
0s          Warning   FailedScheduling         pod/smoke-mini-a-0           0/29 nodes are available: 1 node(s) had volume node affinity conflict, 28 node(s) didn't match node selector.
60m         Normal    NotTriggerScaleUp        pod/smoke-mini-b-0           pod didn't trigger scale-up (it wouldn't fit if a new node is added): 5 node(s) didn't match node selector, 10 max node group size reached
0s          Normal    NotTriggerScaleUp        pod/smoke-mini-a-0           pod didn't trigger scale-up (it wouldn't fit if a new node is added): 4 node(s) didn't match node selector, 11 max node group size reached
0s          Normal    NotTriggerScaleUp        pod/smoke-mini-b-0           pod didn't trigger scale-up (it wouldn't fit if a new node is added): 11 max node group size reached, 4 node(s) didn't match node selector
0s          Normal    NotTriggerScaleUp        pod/smoke-mini-c-0           pod didn't trigger scale-up (it wouldn't fit if a new node is added): 11 max node group size reached, 4 node(s) didn't match node selector
```

### Changelog

```changelog
module: upmeter
type: fix
description: ensure PVC deletion when smoke-mini pods change zone
```

### PR DESCRIPTION
**Pull request by shvgn**
## Description

Ensure PVC deletion when pods zone change

## Why we need it and what problem does it solve?

Makes PVC not to get stuck and change zone on rescheduling (#281)

## Changelog entries

```changes
module: upmeter
type: fix
description: Re-create pods which change their availability zones by re-creating corresponding StatefulSets
note: Accidentally, fix PVC re-creation by avoiding a race with kube-controller-manager. Fixes #281
```

### CODE REVIEW

**Comment by nabokihms** [comment]
@shvgn, could you please rebase it onto the main branch?

**Comment by shvgn** [comment]
@nabokihms done

**Review by nabokihms — COMMENTED** [review]
@shvgn code looks good. Could you please squash commits so we can merge this?

**Comment by shvgn** [comment]
@nabokihms squashed.

**Review by nabokihms — APPROVED** [review]

**Pull request merged**
