### PR TITLE
[deckhouse-controller] set default release channel for embedded deckhouse policy

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
Adds default releaseChannel value "Stable" for embedded deckhouse policy if releaseChannel isn't specified in the `deckhouse` module config.

## Why do we need it, and what problem does it solve?
In some clusters `deckhouse` may be running without .releaseChannel attribute set, yet its value is used for getting available module releases. Having an empty value when checking available module releases doesn't make sense, so a default value of "Stable" is applied.

## What is the expected result?
If deckhouse isn't subscribed to any release channel, module sources are still able to fetch available module releases from the "Stable" channel.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse-controller
type: chore
summary: Set default releaseChannel for ebedded deckhouse policy.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by miklezzzz** [comment]
no releaseChannel
```
Defaulted container "deckhouse" out of: deckhouse, kube-rbac-proxy, init-external-modules (init)
{"level":"debug","msg":"Embedded deckhouse policy release channel set to Stable","time":"2024-07-25T15:26:42Z"}
{"level":"debug","msg":"Embedded deckhouse policy release channel set to Stable","time":"2024-07-25T15:26:42Z"}
{"component":"ModuleSourceController","level":"info","msg":"ModuleUpdatePolicy for ModuleSource: \"foxtrot\", Module: \"mcplay\" not found, using Embedded policy: {Update:{Mode:Auto Windows:[]} ReleaseChannel:Stable ModuleReleaseSelector:{LabelSelector:nil}}","time":"2024-07-25T15:26:46Z"}
```

**Comment by miklezzzz** [comment]
releaseChannel is set to Beta
```
{"component":"ModuleSourceController","level":"info","msg":"ModuleUpdatePolicy for ModuleSource: \"foxtrot\", Module: \"mcplay\" not found, using Embedded policy: {Update:{Mode:Auto Windows:[]} ReleaseChannel:Beta ModuleReleaseSelector:{LabelSelector:nil}}","time":"2024-07-25T15:29:47Z"}
```

**Comment by miklezzzz** [comment]
no moduleconfig at all
```
{"component":"ModuleSourceController","level":"info","msg":"ModuleUpdatePolicy for ModuleSource: \"foxtrot\", Module: \"mcplay\" not found, using Embedded policy: {Update:{Mode:Auto Windows:[]} ReleaseChannel:Stable ModuleReleaseSelector:{LabelSelector:nil}}","time":"2024-07-25T15:31:59Z"}
```

**Review by yalosev — APPROVED** [review]

**Pull request merged**
