### PR TITLE
[candi] add preflight check containerd restart

### PR DESCRIPTION
**Pull request by sprait**
## Description

Add `containerd config dump` check, before restart containerd in bashible step.

## Why do we need it, and what problem does it solve?

Allow restart `containerd` in bashible step only with valid configuration files.

## What is the expected result?

image

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: feature
summary: Add preflight check containerd restart.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by sprait** [comment]
/e2e/abort static;Static;containerd;1.25 8969350597 8969350597-1-con-1-25 /sys/deckhouse-oss/install:pr8312 astra@192.168.199.115

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/static'...

**Review by name212 — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
