### PR TITLE
[cloud-provider-yandex] fix working in hybrid environments

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

Fix working in hybrid environments for cloud-provider-yandex.

## Why do we need it, and what problem does it solve?

In hybrid environment cloud-provider-yandex does not work properly.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-yandex
type: fix
summary: fix working in hybrid environments for cloud-provider-yandex
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6436211510 6436211510-1-con-1-25 /sys/deckhouse-oss/install:pr6094 cloud-user@51.250.86.56

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6449359972 6449359972-1-con-1-25 /sys/deckhouse-oss/install:pr6094 cloud-user@51.250.5.79

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by konstantin-axenov — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [6117](https://github.com/deckhouse/deckhouse/pull/6117) to the branch [release-1.52](https://github.com/deckhouse/deckhouse/tree/release-1.52) successful!

**Pull request merged**
