### PR TITLE
[prometheus-pushgateway] distroless pushgateway

### PR DESCRIPTION
**Pull request by aleksey-su**
## Description
pushgateway are now based on minimal image and bump version to v1.6.2.

## Why do we need it, and what problem does it solve?
We'd like to base our images on a distroless image.

## What is the expected result?
We use scratch along with a minimal number of files from Alpine packages. We pass files in packages though an rsync whitelist.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus-pushgateway
type: feature
summary: Pushgateway image are based on a distroless image and bump version to v1.6.2.
impact_level: default
```

### CODE REVIEW

**Comment by aleksey-su** [comment]
image

**Comment by aleksey-su** [comment]
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Comment by aleksey-su** [comment]
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]

**Review by name212 — APPROVED** [review]

**Review by nabokihms — APPROVED** [review]

**Pull request merged**
