### PR TITLE
[cni-cilium] bump cilium version to v1.11.13

### PR DESCRIPTION
**Pull request by fl64**
## Description
Bump cilium to `v1.11.13`.

## Why do we need it, and what problem does it solve?
Cilium bug fixes and security patches.

## What is the expected result?
Update cilium agents and operator are deployed.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cni-cilium
type: chore
summary: Bump cilium to `v1.11.13`
impact: All cilium Pods will be restarted.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]
lgtm

**Pull request merged**
