### PR TITLE
[candi] add scratch image with created field

### PR DESCRIPTION
**Pull request by sprait**
## Description

Update scratch image.

## Why do we need it, and what problem does it solve?

Previously image doesn't contain `created` field in oci.image.config that caused error in specific cases in builds.

## What is the expected result?

Success build with our scratch image.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: chore
summary: Update scratch image.
impact: All modules with distroless image will be restarted.
impact_level: high
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by sprait** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 12142852475 12142852475-1-con-1-27 /sys/deckhouse-oss/install:pr10921 redos@158.160.32.202

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
