### PR TITLE
[deckhouse] use Golang 1.23 for deckhouse-controller

### PR DESCRIPTION
**Pull request by vadimartynov**
## Description
This PR updates the Go version to 1.23.
This update is necessary due to the addition of the dhctl dependency in the deckhouse-cli project, which requires Go 1.23 for compatibility.

Pipelines with Test Results:
https://github.com/deckhouse/deckhouse-test-2/actions/runs/11609963962
https://github.com/deckhouse/deckhouse-test-2/actions/runs/11610003870

After rebase(resolved conflicts by rebase):
https://github.com/deckhouse/deckhouse-test-2/actions/runs/11627516010

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse-controller
type: chore
summary: Use Go 1.23.
```

### CODE REVIEW

**Review by yalosev — APPROVED** [review]

**Comment by vadimartynov** [comment]
Resolved conflicts by rebase

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vadimartynov. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vadimartynov. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vadimartynov. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by vadimartynov** [comment]
Forgot to wait for the build to finish. Restarting e2e tests

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vadimartynov. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vadimartynov. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vadimartynov. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by vadimartynov** [comment]
/e2e/abort openstack;Standard;containerd;1.27 11627965897 11627965897-1-con-1-27 /sys/deckhouse-oss/install:pr10396 redos@45.12.230.86

**Comment by vadimartynov** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11627965822 11627965822-1-con-1-27 /sys/deckhouse-oss/install:pr10396 redos@89.169.144.159

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vadimartynov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vadimartynov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vadimartynov. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vadimartynov. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by miklezzzz — APPROVED** [review]

**Review by ldmonster — APPROVED** [review]

**Pull request merged**
