### PR TITLE
[cloud-provider-azure] Removed node-termination-handler

### PR DESCRIPTION
**Pull request by zuzzas**
## Description

Removed prematurely added node-termination-handler from cloud-provider-azure.

## Why do we need it, and what problem does it solve?

It works only for spot instances. And we do not support spot instances in Azure.

## Changelog entries

```changes
section: cloud-provider-azure
type: fix
summary: Removed node-termination-handler
impact_level: low
```

### CODE REVIEW

**Review by nabokihms — CHANGES_REQUESTED** [review]
Could you please open an issue to return node-termination-handler?

**Comment by zuzzas** [comment]
@nabokihms 
https://github.com/deckhouse/deckhouse/issues/1863

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/azure'...

**Review by nabokihms — APPROVED** [review]

**Comment by z9r5** [comment]
Cherry-picked into release-1.33

**Pull request merged**
