### PR TITLE
[common] Fix build csi-external-* images

### PR DESCRIPTION
**Pull request by vitaliy-sn**
## Description

Fixed build csi-external-* images

## Info

<details>

before
```shell
Status: Image is up to date for registry.deckhouse.io/deckhouse/fe/install:stable
[deckhouse] root@04f534d56612 / # cat /deckhouse/candi/images_digests.json | grep csiE | sort -V
    "csiExternalAttacher123": "sha256:635e7eb58d71d692f29c5dfa832631adb60c4b546bbca3deb8eb21627b6d7c5a",
    "csiExternalAttacher124": "sha256:635e7eb58d71d692f29c5dfa832631adb60c4b546bbca3deb8eb21627b6d7c5a",
    "csiExternalAttacher125": "sha256:635e7eb58d71d692f29c5dfa832631adb60c4b546bbca3deb8eb21627b6d7c5a",
    "csiExternalAttacher126": "sha256:635e7eb58d71d692f29c5dfa832631adb60c4b546bbca3deb8eb21627b6d7c5a",
    "csiExternalAttacher127": "sha256:635e7eb58d71d692f29c5dfa832631adb60c4b546bbca3deb8eb21627b6d7c5a",
    "csiExternalProvisioner123": "sha256:c83ee44239d77a77f382064b55cba5c7101f74d366cc6b2f613fcd2f70e3cb92",
    "csiExternalProvisioner124": "sha256:c83ee44239d77a77f382064b55cba5c7101f74d366cc6b2f613fcd2f70e3cb92",
    "csiExternalProvisioner125": "sha256:c83ee44239d77a77f382064b55cba5c7101f74d366cc6b2f613fcd2f70e3cb92",
    "csiExternalProvisioner126": "sha256:c83ee44239d77a77f382064b55cba5c7101f74d366cc6b2f613fcd2f70e3cb92",
    "csiExternalProvisioner127": "sha256:c83ee44239d77a77f382064b55cba5c7101f74d366cc6b2f613fcd2f70e3cb92",
    "csiExternalResizer123": "sha256:da412007b219d38bf09507fa673c5d104d60ae55e6151e9c933334f2a1f24953",
    "csiExternalResizer124": "sha256:da412007b219d38bf09507fa673c5d104d60ae55e6151e9c933334f2a1f24953",
    "csiExternalResizer125": "sha256:da412007b219d38bf09507fa673c5d104d60ae55e6151e9c933334f2a1f24953",
    "csiExternalResizer126": "sha256:da412007b219d38bf09507fa673c5d104d60ae55e6151e9c933334f2a1f24953",
    "csiExternalResizer127": "sha256:da412007b219d38bf09507fa673c5d104d60ae55e6151e9c933334f2a1f24953",
    "csiExternalSnapshotter123": "sha256:3d1ed8fbe086881a546f0caaeaf862d254caf7dc0bd18976f6ffdf697d5dc389",
    "csiExternalSnapshotter124": "sha256:3d1ed8fbe086881a546f0caaeaf862d254caf7dc0bd18976f6ffdf697d5dc389",
    "csiExternalSnapshotter125": "sha256:3d1ed8fbe086881a546f0caaeaf862d254caf7dc0bd18976f6ffdf697d5dc389",
    "csiExternalSnapshotter126": "sha256:3d1ed8fbe086881a546f0caaeaf862d254caf7dc0bd18976f6ffdf697d5dc389",
    "csiExternalSnapshotter127": "sha256:3d1ed8fbe086881a546f0caaeaf862d254caf7dc0bd18976f6ffdf697d5dc389",
```

after
```shell
Status: Image is up to date for dev-registry.deckhouse.io/sys/deckhouse-oss/install:pr6378
[deckhouse] root@f23179ac7692 / # cat /deckhouse/candi/images_digests.json | grep csiE | sort -V
    "csiExternalAttacher124": "sha256:793ad7a88134fb4a847eacf055ed0ef376cdca1efcae3039e70547ef3f11f3c7",
    "csiExternalAttacher125": "sha256:793ad7a88134fb4a847eacf055ed0ef376cdca1efcae3039e70547ef3f11f3c7",
    "csiExternalAttacher126": "sha256:793ad7a88134fb4a847eacf055ed0ef376cdca1efcae3039e70547ef3f11f3c7",
    "csiExternalAttacher127": "sha256:6b6f2cc3ce4d175208c51f03499f87df7d74c9e2153b7978df043c34bcce9a6a",
    "csiExternalAttacher128": "sha256:8ff8cc34f5e31dc13c09e60021ff7d5b663914b017ff527ceeda31d46e01d71b",
    "csiExternalProvisioner124": "sha256:8bc3e46fcb09c7c72b0d5561b442ebb23958eb575da93281f82d578e1792f2a6",
    "csiExternalProvisioner125": "sha256:8bc3e46fcb09c7c72b0d5561b442ebb23958eb575da93281f82d578e1792f2a6",
    "csiExternalProvisioner126": "sha256:8bc3e46fcb09c7c72b0d5561b442ebb23958eb575da93281f82d578e1792f2a6",
    "csiExternalProvisioner127": "sha256:9f34028f5ff745a52193a58f20d3540a42cfa38f2e97bcff88c735ba83fcf49d",
    "csiExternalProvisioner128": "sha256:5f84179c4f07b4334766c2ed82aaaf20cb9109bc45899899204a11252eac0c1d",
    "csiExternalResizer124": "sha256:e2af494ee8a61c5479716b7fd7b2c0bbc4c6625b99e3e8635d9397010f1efdf4",
    "csiExternalResizer125": "sha256:e2af494ee8a61c5479716b7fd7b2c0bbc4c6625b99e3e8635d9397010f1efdf4",
    "csiExternalResizer126": "sha256:e2af494ee8a61c5479716b7fd7b2c0bbc4c6625b99e3e8635d9397010f1efdf4",
    "csiExternalResizer127": "sha256:29d248d48ef1c085aa9d5257f8761cf1b411449e4e890b757e4d01fc110b3214",
    "csiExternalResizer128": "sha256:d8f44bda299fe80fd984dfab2beae8aa61a40421906a31a06eae2e4d9241814e",
    "csiExternalSnapshotter124": "sha256:cf04a41c8d039da9005bb8f6f7b1e3146928811baafa8e921d4c83d18b0d2959",
    "csiExternalSnapshotter125": "sha256:cf04a41c8d039da9005bb8f6f7b1e3146928811baafa8e921d4c83d18b0d2959",
    "csiExternalSnapshotter126": "sha256:cf04a41c8d039da9005bb8f6f7b1e3146928811baafa8e921d4c83d18b0d2959",
    "csiExternalSnapshotter127": "sha256:cf04a41c8d039da9005bb8f6f7b1e3146928811baafa8e921d4c83d18b0d2959",
    "csiExternalSnapshotter128": "sha256:f5419dcc39d61df0538ae3177564884cebc9e843315281503b3040fa818766b8",
```

</details>

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: common
type: fix
summary: Fixed build csi-external-* images
impact: The csi-controller pod will be restarted
impact_level: default 
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Backport failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/6717145636) for details.

**Pull request merged**
