### PR TITLE
[docs] Fix forms on the site

### PR DESCRIPTION
**Pull request by z9r5**
Fix forms in the documentation on the site.

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ToyTox. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ToyTox. I've started the workflow for label 'deploy/web/stage'...

**Comment by z9r5** [comment]
Cherry-picked into release-1.50.

**Comment by z9r5** [comment]
Cherry-picked into release-1.49.

**Pull request merged**
