### PR TITLE
[linstor] Automate kernel headers installation

### PR DESCRIPTION
**Pull request by kvaps**
## Description

Automate kernel headers installation

## Why do we need it, and what problem does it solve?

Kernel-headers required to compile DRBD kernel module 

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: linstor
type: feature
summary: Automate kernel headers installation
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...

**Review by RomanenkoDenys — CHANGES_REQUESTED** [review]
Matrix tests were not successful

**Comment by kvaps** [comment]
> Matrix tests were not successful
There were some for cilium. PR rebased.

**Review by RomanenkoDenys — DISMISSED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Review by z9r5 — APPROVED** [review]

**Pull request merged**
