### PR TITLE
[docs][module-builder] Improve error handling

### PR DESCRIPTION
**Pull request by z9r5**
## Description
There is a error.  When docs-builder can't render templates, not all containers of the frontend deployment are ready, but something bad happens.  Investigating the issue.

## Why do we need it, and what problem does it solve?
If we have a global build error (affect all site), we need to mark readiness check to false, to respond with only good site

* global build error - our site has error when build default platform documentation
* module build error - will skip module build and try to rebuild all other site pages

### Before
Documentation site show result with errors and pods are still running in cluster
```
documentation-b5dbff57c-9rj95                        2/2     Running
```

### After
Documentation site show 503 Service Temporarily Unavailable nginx page and pods are not ready in cluster
```
documentation-b5dbff57c-9rj95                        1/2     Running
```

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: docs
type: fix
summary: |
  Improve readiness probe for the `docs-builder` component. Set pods as *not ready* If we have global build error.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Review by yalosev — APPROVED** [review]

**Pull request merged**
