### PR TITLE
[helm] changes in tpl

### PR DESCRIPTION
**Pull request by duckhawk**
Signed-off-by: v.oleynikov <vasily.oleynikov@flant.com>

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by duckhawk** [comment]
/e2e/abort static;Static;containerd;1.23 4004738375 4004738375-1-con-1-23 /sys/deckhouse-oss/install:pr3621 astra@192.168.199.59

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by duckhawk** [comment]
/e2e/abort static;Static;containerd;1.23 4004738375 4004738375-1-con-1-23 /sys/deckhouse-oss/install:pr3621 astra@192.168.199.59

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request closed without merging**
