### PR TITLE
Distroless prometheus

### PR DESCRIPTION
**Pull request by aleksey-su**
## Description
alerts-receiver, alertmanager, prometheus, grafana, trickster are now based on distroless image.

## Why do we need it, and what problem does it solve?
We'd like to base our images on a distroless image.

## What is the expected result?
We use scratch along with a minimal number of files from Alpine packages. We pass files in packages though an rsync whitelist.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: feature
summary: Images are based now on a distroless image.
impact: alertmanager, prometheus, grafana, trickster pods will be restarted.
impact_level: default
```

### CODE REVIEW

**Comment by aleksey-su** [comment]
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Comment by nabokihms** [comment]
/e2e/abort openstack;Standard;containerd;1.25 6123574141 6123574141-1-con-1-25 /sys/deckhouse-oss/install:pr5783 debian@31.129.33.180

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [5789](https://github.com/deckhouse/deckhouse/pull/5789) to the branch [release-1.51](https://github.com/deckhouse/deckhouse/tree/release-1.51) successful!

**Pull request merged**
