### PR TITLE
[deckhouse-controller] Fix auth data handling in change-registry helper

### PR DESCRIPTION
**Pull request by mvasl**
## Description

Fixed a bug where helper would not properly marshal provided credentials for registry into the secret. Unit tests of `deckhouse-controller` are now enabled as part of CI pipeline.

## Why do we need it, and what problem does it solve?

This fixes a reported bug introduced with a `go-containerregistry` update.

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse-controller
type: fix
summary: fix for `change-registry` helper's handling of registry credentials.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by yalosev — CHANGES_REQUESTED** [review]
Seems very risky, honestly. Because `authn.AuthConfig` has some attributes (at least custom json.Marshaller) which is used in a certain pieces of the Deckhouse.
I don't think that it's a good idea to replace it in a such way

**Comment by mvasl** [comment]
Filed a bug to the go-containerregistry team about problems with their JSON marshalling implementation for `authn.AuthConfig`
https://github.com/google/go-containerregistry/issues/1864

Until it's fixed we can use this as a workaround.

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by yalosev — APPROVED** [review]

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Backport failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/7566928764) for details.

**Pull request merged**
