### PR TITLE
[cloud-provider-zvirt] Allow volume expansion

### PR DESCRIPTION
**Pull request by ilia601**
## Description
This PR allows volume expansion in Zvirt clusters

## Why do we need it, and what problem does it solve?
To be able to expand volumes in Zvirt clusters

## What is the expected result?
After a PVC spec resources requests storage has been increased, we expect the status capacity storage to be increased accordingly

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-zvirt
type: feature
summary: Allow Zvirt volume expansion.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/openstack'...

  :fast_forward: `e2e: OpenStack, Containerd, Kubernetes 1.27` for `deckhouse:zvirt-allow-volume-expansion` [started](https://github.com/deckhouse/deckhouse/actions/runs/10795422568).

**Comment by ilia601** [comment]
Screenshot 2024-09-10 at 18 14 36
Screenshot 2024-09-10 at 18 15 27
Screenshot 2024-09-10 at 18 16 41
Screenshot 2024-09-10 at 18 16 59
Screenshot 2024-09-10 at 18 18 51

**Review by aleksey-su — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9691](https://github.com/deckhouse/deckhouse/pull/9691) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!

**Pull request merged**
