### PR TITLE
[global] preventing rendering of unavailable components

### PR DESCRIPTION
**Pull request by ipaqsa**
## Description
Provides an additional check to prevent rendering of components that require CRDs from operator-prometheus-crd module, if this module is disabled.

## Why do we need it, and what problem does it solve?
Closes https://github.com/deckhouse/deckhouse/issues/7433

Some modules use CRDs from operator-prometheus-crd module in their components(PodMonitor, PrometheusRules). But if operator-prometheus-crd is disabled, the modules cannot be deployed because they are trying to deploy unavailable resources. Adding an additional condition will fix the problem, modules will be deployed without unavailable components. 

## Why do we need it in the patch release (if we do)?
It allows to use the modules whose components use CRDs from operator-prometheus-crd module without it.

## What is the expected result?
Using some modules (for example ingress-nginx) without the operator-prometheus-crd module. The modules will be deployed without PodMonitors and PrometheusRules components.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: global
type: fix
summary: Preventing rendering of unavailable components.
```

### CODE REVIEW

**Review by yalosev — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by miklezzzz** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 8137327296 8137327296-1-con-1-25 /sys/deckhouse-oss/install:pr7663 cloud-user@130.193.51.146

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...

**Review by miklezzzz — APPROVED** [review]

**Review by yalosev — APPROVED** [review]

**Pull request merged**
