### PR TITLE
[node-manager] Fix CloudStatic nodes bootstrap

### PR DESCRIPTION
**Pull request by asviel**
## Description

Set `providerID: static://` only on Static nodes. CloudStatic nodes contain their own ID.

Also, add cleanup script on CloudStatic nodes

**NOTE:** Static nodes will still not work in AWS. Read more https://github.com/deckhouse/deckhouse/issues/7543

## Why do we need it, and what problem does it solve?

Now we can't bootstrap CloudStatic nodes, 'cause the hook is triggered before CCM sets the providerID.
```
E0212 15:15:46.751452       1 runtime.go:79] Observed a panic: &errors.errorString{s:"unable to calculate an index entry for key \"ip-10-190-0-234\" on index \"instanceID\": error mapping node \"ip-10-190-0-234\"'s provider ID \"static://\" to instance ID: Invalid format for AWS instance (static://)"} (unable to calculate an index entry for key "ip-10-190-0-234" on index "instanceID": error mapping node "ip-10-190-0-234"'s provider ID "static://" to instance ID: Invalid format for AWS instance (static://))
```

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: fix
summary: Set providerID only on Static nodes (fix CloudStatic nodes bootstrap).
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 7885408833 7885408833-1-con-1-25 /sys/deckhouse-oss/install:pr7486 centos@52.59.110.16

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 7886247071 7886247071-1-con-1-25 /sys/deckhouse-oss/install:pr7486 centos@52.57.88.101

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 7917871767 7917871767-1-con-1-25 /sys/deckhouse-oss/install:pr7486 centos@3.73.208.199

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've recognized your '/e2e/abort' command and started the workflow...

**Review by z9r5 — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
