### PR TITLE
[go_lib] Optimize EnsureCRDs hook

### PR DESCRIPTION
**Pull request by yalosev**
## Description
Optimize EnsureCRD hook

## Why do we need it, and what problem does it solve?
Reduce memory and CPU usage

## What is the expected result?
```
BenchmarkEnsureCRDs/old-12              1000000000               0.09505 ns/op  
BenchmarkEnsureCRDs/new-12              1000000000               0.03931 ns/op 
```

unfortunately we can't measure the memory allocations. Because Benchmem measures only the heap allocations, ignoring the stack

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: go_lib
type: chore
summary: Optimize EnsureCRDs hook memory and CPU usage.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by yalosev** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6632134369 6632134369-1-con-1-25 /sys/deckhouse-oss/install:pr6305 cloud-user@158.160.47.179

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...

**Comment by yalosev** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 6639003560 6639003560-1-con-1-25 /sys/deckhouse-oss/install:pr6305 centos@3.66.0.146

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've recognized your '/e2e/abort' command and started the workflow...

**Review by nabokihms — APPROVED** [review]

**Pull request merged**
