### PR TITLE
2 DONT MERGE Testing 1.66

### PR DESCRIPTION
**Pull request by KraMorK**
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by KraMorK** [comment]
/e2e/abort azure;Standard;containerd;1.29 11815104214 11815104214-1-con-1-29 /sys/deckhouse-oss/install:pr10619 azureuser@68.219.186.7

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by KraMorK** [comment]
/e2e/abort azure;Standard;containerd;1.29 11815850119 11815850119-1-con-1-29 /sys/deckhouse-oss/install:pr10619 azureuser@20.82.118.208

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by KraMorK** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.30 11817240870 11817240870-1-con-1-30 /sys/deckhouse-oss/install:pr10619 redos@51.250.13.129

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/gcp'...

**Comment by KraMorK** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.28 11819775218 11819775218-1-con-1-28 /sys/deckhouse-oss/install:pr10619 user@35.242.201.131

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/azure'...

**Comment by KraMorK** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.31 11819728413 11819728413-1-con-1-31 /sys/deckhouse-oss/install:pr10619 ec2-user@3.77.15.108

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by KraMorK** [comment]
/e2e/abort azure;Standard;containerd;1.30 11820590553 11820590553-1-con-1-30 /sys/deckhouse-oss/install:pr10619 azureuser@172.205.227.221

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/azure'...

**Pull request closed without merging**
