### PR TITLE
[docs] Add auto generation of HTML descriptions

### PR DESCRIPTION
**Pull request by Zhbert**
## Description

- Added automatic description generation for some documentation pages (FAQ, CR, CONFIGURATION, USAGE, EXAMPLES).
- Added detailed descriptions to various documentation pages.

## Why do we need it, and what problem does it solve?

This will improve the SEO of the documentation pages.

## What is the expected result?

Descriptions are generated on the documentation pages based on the content of the pages.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: docs
type: feature
summary: Added automatic description generation for some documentation pages.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit 5d75763f41aa9d766b996236056ec3203d40eb9d to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/11381214288) for details.

**Comment by z9r5** [comment]
Cherry-picked into release-1.64

**Pull request merged**
