### PR TITLE
[dhctl](preflight-check) Add python2 support for `check_ports.sh`

### LINKED ISSUE #7391: [dhctl] Checking required ports availability FAIL, but shouldn't
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.56.9

### Expected Behavior

Pass step: Checking required ports availability

### Actual Behavior

Fail step: Checking required ports availability
```
 ┌ Checking required ports availability
│ │ Checking if kubernetes API port is open (6443) Port 6443 is closed, but required for Kubernetes API server to function. Probably       ↵
│ │ control-plane node is protected by firewall rules or another software (like antivirus) and blocks connections.
│ │ SUCCESS
│ │ Checking if Etcd ports are available (2379, 2380) Port 2379 is closed, but required for Etcd clients to communicate with it. Probably  ↵
│ │ control-plane node is protected by firewall rules or another software (like antivirus) and blocks connections.
│ │ Port 2380 is closed, but required for Etcd database server peers communications. Probably control-plane node is protected by firewall  ↵
│ │ rules or another software (like antivirus) and blocks connections.
│ │ SUCCESS
│ │ ️⛱️️ Attempt #1 of 1 |
│ │     Checking required ports availability failed, next attempt will be in 10s"
│ │     Error: Could not execute a script to check if all necessary ports are open on the node: execute on remote: exit status 1
│ │
│ └ Checking required ports availability (1.09 seconds) FAILED
└ 🎈 ~ Common: Preflight checks for static-cluster (1.35 seconds) FAILED

Installation aborted: timeout while "Checking required ports availability": last error: Could not execute a script to check if all         ↵
necessary ports are open on the node: execute on remote: exit status 1
Please fix this problem or skip it if you're sure with preflight-skip-availability-ports-check flag
```

### Steps To Reproduce

1. Master-node environment:
```
   Static hostname: dd-rzd-dh-master-01
         Icon name: computer-vm
           Chassis: vm
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1160.108.1.el7.x86_64
      Architecture: x86-64
```
Deploy PC environment:
```
   Static hostname: vbox
         Icon name: computer-vm
           Chassis: vm
    Virtualization: oracle
  Operating System: Ubuntu 18.04.6 LTS
            Kernel: Linux 5.4.0-150-generic
      Architecture: x86-64
```
2. Vanila config.yml with my data.
3. I run:
```
docker run --pull=always -it -v "$PWD/config.yml:/config.yml" -v "$HOME/.ssh/:/tmp/.ssh/" registry.deckhouse.ru/deckhouse
/ce/install:stable dhctl bootstrap --ssh-user=deployer --ssh-host=10.154.144.23 --ssh-agent-private-keys=/tmp/.ssh/my-key --config=/config.yml
```
4. Directly connect inside docker:
```
[deckhouse] root@0ccb765a46c8 / # nc -vz 10.154.144.23 6443
10.154.144.23 (10.154.144.23:6443) open
[deckhouse] root@0ccb765a46c8 / # nc -vz 10.154.144.23 2379
10.154.144.23 (10.154.144.23:2379) open
[deckhouse] root@0ccb765a46c8 / # nc -vz 10.154.144.23 2380
10.154.144.23 (10.154.144.23:2380) open
```
5. Run with --preflight-skip-availability-ports-check is OK.

### Additional Information

_No response_

### Logs

```shell
┌ Checking required ports availability
│ │ Checking if kubernetes API port is open (6443) Port 6443 is closed, but required for Kubernetes API server to function. Probably       ↵
│ │ control-plane node is protected by firewall rules or another software (like antivirus) and blocks connections.
│ │ SUCCESS
│ │ Checking if Etcd ports are available (2379, 2380) Port 2379 is closed, but required for Etcd clients to communicate with it. Probably  ↵
│ │ control-plane node is protected by firewall rules or another software (like antivirus) and blocks connections.
│ │ Port 2380 is closed, but required for Etcd database server peers communications. Probably control-plane node is protected by firewall  ↵
│ │ rules or another software (like antivirus) and blocks connections.
│ │ SUCCESS
│ │ ️⛱️️ Attempt #1 of 1 |
│ │     Checking required ports availability failed, next attempt will be in 10s"
│ │     Error: Could not execute a script to check if all necessary ports are open on the node: execute on remote: exit status 1
│ │
│ └ Checking required ports availability (1.09 seconds) FAILED
└ 🎈 ~ Common: Preflight checks for static-cluster (1.35 seconds) FAILED

Installation aborted: timeout while "Checking required ports availability": last error: Could not execute a script to check if all         ↵
necessary ports are open on the node: execute on remote: exit status 1
Please fix this problem or skip it if you're sure with preflight-skip-availability-ports-check flag
```

### PR DESCRIPTION
**Pull request by artbin**
## Description

Fix checking the possibility of opening ports 6443 2379 2380 on the server.

## Why do we need it, and what problem does it solve?

Close #7391.
If the master node does not have python3, the `check_ports.sh` script fails.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Fix preflight ports checking when static cluster is bootstrapping.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/static'...

**Comment by artbin** [comment]
/e2e/abort static;Static;containerd;1.25 8462707260 8462707260-1-con-1-25 /sys/deckhouse-oss/install:pr7917 astra@192.168.199.28

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/static'...

**Comment by artbin** [comment]
Manual testing:
===========

```bash
docker run --pull=always -it -v "$PWD/config.yml:/config.yml" -v "$HOME/.ssh/:/tmp/.ssh/" dev-registry.deckhouse.io/sys/deckhouse-oss/install:pr7917 dhctl bootstrap --ssh-user=static --ssh-host=158.160.117.49 --ssh-agent-private-keys=/tmp/.ssh/tfadm-id-rsa --config=/config.yml
```

Screenshot 2024-03-28 at 15 21 59

**Comment by artbin** [comment]
/e2e/abort static;Static;containerd;1.25 8463755783 8463755783-1-con-1-25 /sys/deckhouse-oss/install:pr7917 astra@192.168.199.221

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
