### PR TITLE
[testing] Check alerts in e2e tests

### PR DESCRIPTION
**Pull request by nikiGGG**
## Description

Check alerts in e2e tests. Check that DeadMansSwitch alert exists and no more.

## Why do we need it, and what problem does it solve?

Check that every part of deckhouse starts correctly without alerts. DeadMansSwitch alert tell that prometheus works correctly, so it's should be exist.

## What is the expected result?

e2e test now checks does alerts is ok or not

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: feature
summary: Check alerts in e2e tests
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/eks'...

**Comment by nikiGGG** [comment]
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by name212** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.25 7006469672 7006469672-1-con-1-25 /sys/deckhouse-oss/install:pr6620

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Review by name212 — APPROVED** [review]

**Pull request merged**
