### PR TITLE
[chore] Update Kubernetes patch versions

### PR DESCRIPTION
**Pull request by z9r5**
## Description

Update Kubernetes patch versions:
- 1.25.13 ⇾ 1.25.14
- 1.26.8 ⇾ 1.26.9
- 1.27.5 ⇾ 1.27.6

## Why do we need it, and what problem does it solve?
It's important to bring fixes and to stay up to date with upstream.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: candi
type: chore
summary: "Bump patch versions of Kubernetes images: `v1.25.14`, `v1.26.9`, `v1.27.6`"
impact: |
  Kubernetes control-plane components will restart, kubelet will restart.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6326501743 6326501743-1-con-1-25 /sys/deckhouse-oss/install:pr5873 cloud-user@158.160.111.225

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort vsphere;Standard;containerd;1.25 6326500087 6326500087-1-con-1-25 /sys/deckhouse-oss/install:pr5873 ubuntu@10.220.203.26

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6326501743 6326501743-1-con-1-25 /sys/deckhouse-oss/install:pr5873 cloud-user@158.160.111.225

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
