### PR TITLE
[docs] Show the module's enable status

### PR DESCRIPTION
**Pull request by z9r5**
## Description

Ref: #1729 
Ref: #278 

Show the module's enable status according to bundles on a module configuration page.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: docs
type: feature
summary: Show the module's enable status according to bundles on a module configuration page.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by z9r5** [comment]
For merging after https://github.com/deckhouse/deckhouse/pull/1729

**Comment by EvgenySamoylov** [comment]
Blocked by #1729

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Review by yalosev — APPROVED** [review]

**Pull request merged**
