### PR TITLE
[bashible] add debug info (#4128)

### PR DESCRIPTION
**Pull request by aleksey-su**
## Description
Add debug info to the bashible steps for all run type

## Why do we need it, and what problem does it solve?
Additional information about the error has occurred will help in investigating the causes.

## What is the expected result?
detailed information about the issues

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: bashible
type: feature
summary: Add debug info to the bashible steps for all run type
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — COMMENTED** [review]
Looks good, but we need to see how it works. Please test it and put some info to comments,

**Comment by aleksey-su** [comment]
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
