### PR TITLE
[user-authn] fix generation self signet certificate for crowd-basic-auth-proxy

### PR DESCRIPTION
**Pull request by aleksey-su**
## Description
Fix generation a self signed certificate for crowd-basic-auth-proxy

## Why do we need it, and what problem does it solve?
No certificate is generated for crowd-basic-auth-proxy

## Why do we need it in the patch release (if we do)?
Cusromer issue

## What is the expected result?
Certificate generated successfully

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: user-authen
type: fix
summary: Fix generation a self signed certificate for `crowd-basic-auth-proxy`.
impact_level: default
```

### CODE REVIEW

**Comment by aleksey-su** [comment]
image
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [6077](https://github.com/deckhouse/deckhouse/pull/6077) to the branch [release-1.52](https://github.com/deckhouse/deckhouse/tree/release-1.52) successful!

**Pull request merged**
