### PR TITLE
[istio] docs refresh

### PR DESCRIPTION
**Pull request by apolovov**
## Description
Istio README refactoring.

## Why do we need it, and what problem does it solve?
The Istio module is quite complicated and needs clear logs.

## Changelog entries
```changes
section: istio
type: chore
summary: Istio README refactoring.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'deploy/web/test'...

**Comment by z9r5** [comment]
Cherry-picked into release-1.32

**Pull request merged**
