### PR TITLE
[prometheus]  Grafana 8.5.9 to fix various CVE

### PR DESCRIPTION
**Pull request by nabokihms**
Signed-off-by: Maksim Nabokikh <maksim.nabokikh@flant.com>

## Why do we need it, and what problem does it solve?
https://grafana.com/blog/2022/07/14/grafana-v9-0-3-8-5-9-8-4-10-and-8-3-10-released-with-high-severity-security-fix/

## What is the expected result?
Grafana pod will be restarted.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: fix
summary: Update Grafana to 8.5.9 to fix various CVE
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/gcp'...

**Comment by shvgn** [comment]
@nabokihms Did you test it in  a cluster?

**Comment by nabokihms** [comment]
@shvgn no, as the opening post states, I did not. I only looked through the Grafana change log.

**Review by shvgn — APPROVED** [review]
Probably we should smoke-test it in a cluster.

**Comment by nabokihms** [comment]
Tested it manually in the cluster. Everything seems ok. Let's merge the PR.

**Comment by z9r5** [comment]
Cherry-picked into release-1.34

**Pull request merged**
