### PR TITLE
[node-manager] CAPI sa migration

### PR DESCRIPTION
**Pull request by borg-z**
## Description

Migration for existing capi-controller-manager sa which adopts it for use in helm.

## Why do we need it, and what problem does it solve?

Without this migration, we got an error:

{"binding":"ConvergeModules","event.type":"OperatorStartup","level":"error","module":"node-manager","modules":"control-plane-manager,node-manager","msg":"ModuleRun failed in phase 'CanRunHelm'. Requeue task to retry after delay. Failed count is 9. Error: helm upgrade failed: Unable to continue with update: ServiceAccount \"capi-controller-manager\" in namespace \"d8-cloud-instance-manager\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key \"app.kubernetes.io/managed-by\": must be set to \"Helm\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"node-manager\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"d8-system\"\n","order":"40","queue":"main","task.id":"98766ade-a00d-4263-8818-1ffed5ba37fa","time":"2024-10-18T17:14:55Z"}

## What is the expected result?

Migration adds the necessary labels for sa if it has already been created

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: fix 
summary: CAPI sa migration
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by name212** [comment]
manually checked - ok.

**Review by name212 — APPROVED** [review]

**Pull request merged**
