### PR TITLE
[ci] fix e2e tests

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

Fix e2e tests
## Why do we need it, and what problem does it solve?

After merging #7101 envsubst binary is missing in install image. This leads to cloud-tests fail.
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: ci
type: fix
summary: fix e2e tests
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 7903209334 7903209334-1-con-1-25 /sys/deckhouse-oss/install:pr7502 centos@3.76.64.47

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by RomanenkoDenys** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 7903209334 7903209334-1-con-1-25 /sys/deckhouse-oss/install:pr7502 centos@3.76.64.47

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 7902855122 7902855122-1-con-1-25 /sys/deckhouse-oss/install:pr7502

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 7902389050 7902389050-1-con-1-25 /sys/deckhouse-oss/install:pr7502

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
