### PR TITLE
[candi] improve bashible steps running order

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

Move install and configure and run scripts for kubelet and containerd together

## Why do we need it, and what problem does it solve?

If in release we have new versions of kubernetes patch and containerd, sometimes we got the problem when node is in notReady state for a long period of time.
This happens due to network problems. Let's see the bashible flow:
- download and reinstall containerd (it is not run)
- download and reinstall kubelet
- configure and start containerd
- configure and start kubelet
If, for example, download and reinstall kubelet takes long time (5 min for example), all this time containerd isn't running. Kubelet cannot give access to containerd sock and fails. 
,

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: improve bashible steps running order
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/static'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort static;Static;containerd;1.25 6632138393 6632138393-1-con-1-25 /sys/deckhouse-oss/install:pr6307 astra@192.168.199.116

**Comment by RomanenkoDenys** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.25 6632138691 6632138691-1-con-1-25 /sys/deckhouse-oss/install:pr6307 user@35.234.64.129

**Comment by RomanenkoDenys** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 6632138723 6632138723-1-con-1-25 /sys/deckhouse-oss/install:pr6307 centos@3.70.90.88

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Review by name212 — APPROVED** [review]

**Review by konstantin-axenov — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [6319](https://github.com/deckhouse/deckhouse/pull/6319) to the branch [release-1.53](https://github.com/deckhouse/deckhouse/tree/release-1.53) successful!

**Pull request merged**
