### PR TITLE
[dhctl] add checks for bootstrap dependencies

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
Before bootstrap dhctl checks whether some relevant binaries/utils are present in the system.

## Why do we need it, and what problem does it solve?
Needed for providing a more transparent bootstrap process.
Related to https://github.com/deckhouse/deckhouse/issues/4576

## What is the expected result?
Dhctl should abort the bootstrap process in case some dependencies are missing

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: feature
summary: Introduces dependency verification on bootstrap.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/aws'...

**Comment by miklezzzz** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 4983593119 4983593119-1-con-1-23 /sys/deckhouse-oss/install:pr4647 centos@18.196.117.164

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/aws'...

**Comment by miklezzzz** [comment]
some examples
image
image

**Review by name212 — APPROVED** [review]

**Review by name212 — APPROVED** [review]

**Pull request merged**
