### PR TITLE
[node-manager](capi) add RBAC rules for `kube-rbac-proxy`

### LINKED ISSUE #6821: [node-manager] Cannot get metrics from capi-controller-manager with 401 error
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.55.3

### Expected Behavior

Get Metrics

### Actual Behavior

server returned HTTP status 401 Unauthorized

### Steps To Reproduce

Enable module capi-controller-manager

### Additional Information

Internal communication https://flant.slack.com/archives/CNEHQ004A/p1702032161568429?thread_ts=1701688796.362409&cid=CNEHQ004A

### Logs

_No response_

### PR DESCRIPTION
**Pull request by artbin**
## Description

Add RBAC rules for kube-rbac-proxy.

## Why do we need it, and what problem does it solve?

Fix #6821.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: fix
summary: Add RBAC rules for kube-rbac-proxy in capi-controller-manager.
impact_level: default
```

### CODE REVIEW

**Comment by artbin** [comment]
Screenshot 2023-12-13 at 15 17 13

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Comment by name212** [comment]
/e2e/abort openstack;Standard;containerd;1.25 7478853123 7478853123-1-con-1-25 /sys/deckhouse-oss/install:pr6854 debian@31.129.33.7

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
