### PR TITLE
[cloud-provider-azure] Update cloud-controller-manager

### PR DESCRIPTION
**Pull request by vitaliy-sn**
## Description

Azure cloud-controller-manager has been updated to the latest versions for all supported kubernetes versions.

## Checks

<details><summary>Look here</summary>

```shell
[root@candi-6926419106-1-con-1-25-master-0 ~]# kubectl get no -o wide
NAME                                                      STATUS     ROLES                  AGE   VERSION    INTERNAL-IP   EXTERNAL-IP       OS-IMAGE         KERNEL-VERSION                 CONTAINER-RUNTIME
candi-6926419106-1-con-1-25-master-0                      Ready      control-plane,master   11m   v1.25.15   10.50.0.4     172.205.129.247   CentOS Linux 8   4.18.0-240.10.1.el8_3.x86_64   containerd://1.6.24
candi-6926419106-1-con-1-25-worker-30985b0d-589f6-kbkgc   Ready      worker                 26s   v1.25.15   10.50.0.5     <none>            CentOS Linux 8   4.18.0-240.10.1.el8_3.x86_64   containerd://1.6.24

[root@candi-6926419106-1-con-1-25-worker-30985b0d-589f6-kbkgc ~]# ping 1.1.1.1 -c4
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=55 time=1.66 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=55 time=1.48 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=55 time=1.51 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=55 time=1.65 ms

--- 1.1.1.1 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 7ms
rtt min/avg/max/mdev = 1.483/1.574/1.658/0.087 ms
[root@candi-6926419106-1-con-1-25-worker-30985b0d-589f6-kbkgc ~]#
```

</details>

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-azure
type: fix
summary: Azure cloud-controller-manager has been updated to the latest versions for all supported kubernetes versions.
impact: cloud-controller-manager pod will be restarted.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/azure'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Pull request merged**
