### PR TITLE
[e2e] Use hardened kernel by astra for Static cluster tests

### PR DESCRIPTION
**Pull request by apolovov**
## Description
Using hardened kernel by astra for Static e2e tests.

## Why do we need it, and what problem does it solve?
To be sure d8 works fine with hardened kernel.

## What is the expected result?
Both instances in test are deployed with hardened kernel.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: e2e
type: chore
summary: Using hardened kernel by astra for Static e2e tests.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Comment by apolovov** [comment]
/e2e/abort static;Static;containerd;1.25 4178977522 4178977522-1-con-1-25 /sys/deckhouse-oss/install:pr3865 astra@192.168.199.250

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by apolovov** [comment]
/e2e/abort static;Static;containerd;1.25 4178977522 4178977522-1-con-1-25 /sys/deckhouse-oss/install:pr3865 astra@5.159.103.150

**Comment by apolovov** [comment]
/e2e/abort static;Static;containerd;1.25 4178977522 4178977522-1-con-1-25 /sys/deckhouse-oss/install:pr3865 astra@5.159.103.150

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Comment by apolovov** [comment]
/e2e/abort static;Static;containerd;1.25 4184087402 4184087402-1-con-1-25 /sys/deckhouse-oss/install:pr3865

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Comment by apolovov** [comment]
/e2e/abort static;Static;containerd;1.25 4185447669 4185447669-1-con-1-25 /sys/deckhouse-oss/install:pr3865 astra@192.168.199.8

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Comment by apolovov** [comment]
/e2e/abort static;Static;containerd;1.25 4185553655 4185553655-1-con-1-25 /sys/deckhouse-oss/install:pr3865 astra@192.168.199.43

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Comment by apolovov** [comment]
/e2e/abort static;Static;containerd;1.25 4185992996 4185992996-1-con-1-25 /sys/deckhouse-oss/install:pr3865

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Comment by apolovov** [comment]
/e2e/abort static;Static;containerd;1.25 4186108742 4186108742-1-con-1-25 /sys/deckhouse-oss/install:pr3865 astra@192.168.199.112

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/static'...

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
