### PR TITLE
[terraform-manager][ci]  Migrate from werf ansible to werf shell image builds for terraform based images

### PR DESCRIPTION
**Pull request by name212**
Signed-off-by: Nikolay Mitrofanov <nikolay.mitrofanov@flant.com>

## Description
Migrate from werf ansible to werf shell for terraform based images.

Move terraform and cloud providers into artifacts images.

## Why do we need it, and what problem does it solve?
Terraform based images can not build.
Ansible step is trying use its own CA certificates and we can not download terraform and terrafrom plugins.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Migrate from werf ansible to werf shell image builds for terraform based images
impact_level: low
```

```changes
section: terraform-manager
type: fix
summary: Migrate from werf ansible to werf shell image builds for terraform based images
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/aws'...

**Review by konstantin-axenov — APPROVED** [review]

**Comment by z9r5** [comment]
Cherry-picked into release-1.32

**Pull request merged**
