### PR TITLE
[testing] Update module schema version for e2e tests

### PR DESCRIPTION
**Pull request by Taior**
## Description
Update module schema version for e2e tests.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: chore
summary: Update module schema version for e2e tests.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/static'...

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit 5bbd125c590e669746c8892e6af9f6379fcfc025 to the branch [release-1.66](https://github.com/deckhouse/deckhouse/tree/release-1.66) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/12352253818) for details.

**Pull request merged**
