### PR TITLE
Astra Linux 1.8

### PR DESCRIPTION
**Pull request by borg-z**
## Description
Added support for Astra Linux 1.8

## Why do we need it, and what problem does it solve?
This update ensures compatibility with the latest version of Astra Linux 1.8

## Why do we need it in the patch release (if we do)?
Not necessarily.

## What is the expected result?
The system should now correctly detect and install necessary packages for Astra Linux 1.8

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: feature
summary: Add support for Astra Linux 1.8. Support for Astra Linux 1.8 ensures compatibility with the latest OS version, providing updated packages and configurations.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by borg-z** [comment]
```
root@candi-10280909085-1-con-1-27-master-0:~# cat /etc/os-release
PRETTY_NAME="Astra Linux"
NAME="Astra Linux"
ID=astra
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://astralinux.ru"
SUPPORT_URL="https://astralinux.ru/support"
LOGO=astra
VERSION_ID=1.8_x86-64
VERSION_CODENAME=1.8_x86-64
root@candi-10280909085-1-con-1-27-master-0:~# uname -r
6.1.90-1-generic
root@candi-10280909085-1-con-1-27-master-0:~#
```

**Comment by borg-z** [comment]
/e2e/abort static;Static;containerd;1.27 10280909085 10280909085-1-con-1-27 /sys/deckhouse-oss/install:pr9296 astra@192.168.199.78

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by borg-z** [comment]
/e2e/abort static;Static;containerd;1.27 10285849021 10285849021-1-con-1-27 /sys/deckhouse-oss/install:pr9296 astra@192.168.199.216

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by borg-z** [comment]
| Kernel Image          | cilium | runtime-audit-engine | btf |
| --------------------- | ------ | -------------------- | --- |
| linux-image-6.1       | ✓      |                      |     |
| linux-image-6.1-debug | ✓      | ✓                    | ✓   |
| linux-image-6.6       | ✓      |                      |     |
| linux-image-6.6-debug |        |                      | ✓   |

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9866](https://github.com/deckhouse/deckhouse/pull/9866) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!

**Pull request merged**
