### PR TITLE
[docs] Update 'How to configure' article

### PR DESCRIPTION
**Pull request by Zhbert**
## Description
The "How to configure" article reviewing and fixing.

## Changelog entries

```changes
module: documentation
type: fix
description: "Review and fix the 'How to configure' article."
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "deploy/web/test"...

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "deploy/web/test"...

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "deploy/web/stage"...

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "deploy/web/stage"...

**Review by z9r5 — APPROVED** [review]

**Pull request merged**
