### PR TITLE
[docs] Move DKP documentation to the new location

### PR DESCRIPTION
**Pull request by z9r5**
## Description
The new location for the DKP documentation is - /products/kubernetes-platform/documentation/. For DKP getting started - /products/kubernetes-platform/gs/. For DKP guides - /products/kubernetes-platform/guides/

Make HTTP 302 redirect from the old URLs for the first time.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: docs
type: chore
summary: Move DKP documentation to the new location `/products/kubernetes-platform/` on the site.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9431](https://github.com/deckhouse/deckhouse/pull/9431) to the branch [release-1.63](https://github.com/deckhouse/deckhouse/tree/release-1.63) successful!

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit aedbe27ba830770ecd2c8f364f0a727659040895 to the branch [release-1.62](https://github.com/deckhouse/deckhouse/tree/release-1.62) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/10463839628) for details.

**Comment by z9r5** [comment]
Cherry-picked to the following branches:
- release-1.63
- release-1.62
- release-1.61
- release-1.60
- release-1.59

**Pull request merged**
