### PR TITLE
[monitoring-kubernetes] resolve symbolic links

### PR DESCRIPTION
**Pull request by artbin**
## Description

Resolve symbolic links before getting file system statistics from the `kubelet` root directory and the container runtime root directory in `kubelet-eviction-thresholds-exporter`.

## Why do we need it, and what problem does it solve?

We need it for the correct generation of metrics.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: monitoring-kubernetes
type: fix
summary: Resolve symbolic links before getting file system statistics in kubelet-eviction-thresholds-exporter.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Review by name212 — APPROVED** [review]

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [4936](https://github.com/deckhouse/deckhouse/pull/4936) to the branch [release-1.46](https://github.com/deckhouse/deckhouse/tree/release-1.46) successful!

**Pull request merged**
