### PR TITLE
[go_lib] add probe to the cloud-data reconciler

### PR DESCRIPTION
**Pull request by aleksey-su**
## Description
add probe to the cloud-data reconciler

## Why do we need it, and what problem does it solve?
Some clients have cloud-data-discoverer hangs.

## What is the expected result?
When cloud-data-discoverer hangs, it should restart itself

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: go_lib
type: fix
summary: add probe to the cloud-data reconciler
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
