### PR TITLE
[deckhouse] change default kubernetes version to 1.23

### PR DESCRIPTION
**Pull request by vitaliy-sn**
Signed-off-by: Vitaliy Snurnitsin <vitaliy.snurnitsin@flant.com>

## Description

Changed default kubernetes version to 1.23.

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse
type: chore
summary: Changed the default Kubernetes version to `1.23`.
impact: Clusters with the `kubernetesVersion` parameter set to `Automatic` will be upgraded to Kubernetes `1.23`.
impact_level: high
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by name212** [comment]
please change default [here](https://github.com/deckhouse/deckhouse/blob/k8s-1.23-by-default/.github/scripts/js/ci.js#L1149) and [here](https://github.com/deckhouse/deckhouse/blob/k8s-1.23-by-default/.github/scripts/js/constants.js#L141) too

**Review by name212 — CHANGES_REQUESTED** [review]
https://github.com/deckhouse/deckhouse/pull/3292#issuecomment-1350874644

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/gcp'...

**Review by yalosev — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Review by name212 — APPROVED** [review]

**Review by diafour — APPROVED** [review]
lgtm

**Pull request merged**
