### PR TITLE
[testing] fixed $python_binary

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Description
fixed $python_binary

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: fix 
summary: fixed $python_binary
impact_level:  low
```

### CODE REVIEW

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10625](https://github.com/deckhouse/deckhouse/pull/10625) to the branch [release-1.66](https://github.com/deckhouse/deckhouse/tree/release-1.66) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10627](https://github.com/deckhouse/deckhouse/pull/10627) to the branch [release-1.65](https://github.com/deckhouse/deckhouse/tree/release-1.65) successful!

**Pull request merged**
