### PR TITLE
[ingress-nginx] fix maxmind db download for controller 1.9

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

Fix maxmind db download for controller 1.9.

## Why do we need it in the patch release (if we do)?

Now if we set maxmind db parameters to ingressNginxController resource, nothing is download.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: ingress-nginx
type: fix
summary: fix maxmind db download for controller 1.9
impact: ingress-nginx 1.9 controller should be restarted
impact_level: default
```

### CODE REVIEW

**Comment by RomanenkoDenys** [comment]
How to use curl to debug
```
bash-4.4$ unshare  -S 101 -R /chroot curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

**Comment by RomanenkoDenys** [comment]
```
bash-4.4$ ls -l /etc/nginx/geoip/
total 32088
-rw-r--r-- 1 www-data www-data  1242574 Mar 29 07:16 GeoIP.dat
-rw-r--r-- 1 www-data www-data  4638365 Mar 29 07:16 GeoIPASNum.dat
-rw-r--r-- 1 www-data www-data  6427301 Mar 29 10:21 GeoLite2-Country.mmdb
-rw-r--r-- 1 www-data www-data 20539238 Mar 29 07:16 GeoLiteCity.dat
```

**Comment by RomanenkoDenys** [comment]
```
bash-4.4$ ls -l /etc/nginx/geoip
total 32092
-rw-r--r-- 1 www-data www-data  1242574 Mar 29 07:16 GeoIP.dat
-rw-r--r-- 1 www-data www-data  4638365 Mar 29 07:16 GeoIPASNum.dat
-rw-r--r-- 1 www-data www-data  6432778 Mar 29 14:06 GeoLite2-Country.mmdb
-rw-r--r-- 1 www-data www-data 20539238 Mar 29 07:16 GeoLiteCity.dat
```

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [7951](https://github.com/deckhouse/deckhouse/pull/7951) to the branch [release-1.58](https://github.com/deckhouse/deckhouse/tree/release-1.58) successful!

**Pull request merged**
