### PR TITLE
[testing] Disable early-oom for centos based e2e tests

### PR DESCRIPTION
**Pull request by name212**
## Description
Disable early-oom for centos based e2e tests

## Why do we need it, and what problem does it solve?
Centos based images contains old kernel and early oom pods do not start

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: fix
summary: Disable early-oom for centos based e2e tests
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/azure'...

**Review by nikiGGG — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [6907](https://github.com/deckhouse/deckhouse/pull/6907) to the branch [release-1.56](https://github.com/deckhouse/deckhouse/tree/release-1.56) successful!

**Pull request merged**
