### PR TITLE
[CI] Update go test image

### PR DESCRIPTION
**Pull request by libmonsoon-dev**
## Description
To 1.23.1

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: CI
summary: Upgraded go test image
type: chore
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/openstack'...

**Comment by libmonsoon-dev** [comment]
/e2e/abort openstack;Standard;containerd;1.31 11315468221 11315468221-1-con-1-31 /sys/deckhouse-oss/install:pr10104

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request closed without merging**
