### PR TITLE
[cloud-provider-yandex][discovery] Add data discoverer for YandexCloud

### PR DESCRIPTION
**Pull request by asviel**
## Description

Added a feature to discover orphaned disks for YandexCloud.

## Why do we need it, and what problem does it solve?

Partially closes https://github.com/deckhouse/deckhouse/issues/4708.

## Why do we need it in the patch release (if we do)?

We don't.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-yandex
type: feature
summary: Add a feature to discover orphaned disks for YandexCloud.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by asviel** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 8048915682 8048915682-1-con-1-25 /sys/deckhouse-oss/install:pr7603 cloud-user@158.160.110.227

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by aleksey-su — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by name212 — APPROVED** [review]

**Comment by asviel** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 8051797743 8051797743-1-con-1-25 /sys/deckhouse-oss/install:pr7603 cloud-user@84.252.131.216

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've recognized your '/e2e/abort' command and started the workflow...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Pull request merged**
