### PR TITLE
[chore] Update Kubernetes patch versions

### PR DESCRIPTION
**Pull request by z9r5**
## Description

Update Kubernetes patch versions:

- 1.27.16
- 1.28.12
- 1.29.7
- 1.30.3

## Why do we need it, and what problem does it solve?

It's important to bring fixes and to stay up to date with upstream.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: chore
summary: "Bump patch versions of Kubernetes images: `v1.27.16`, `v1.28.12`, `v1.29.7`, `v1.30.3`"
impact: Kubernetes control-plane components will restart, kubelet will restart.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.30 10160182820 10160182820-1-con-1-30 /sys/deckhouse-oss/install:pr9203 ec2-user@3.126.202.252

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.29 10160182820 10160182820-1-con-1-29 /sys/deckhouse-oss/install:pr9203 ec2-user@35.157.71.167

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.30 10161002352 10161002352-1-con-1-30 /sys/deckhouse-oss/install:pr9203 user@35.246.190.184

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.30 10161002352 10161002352-2-con-1-30 /sys/deckhouse-oss/install:pr9203 user@34.89.214.209

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.30 10161002352 10161002352-2-con-1-30 /sys/deckhouse-oss/install:pr9203 user@34.89.214.209

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.30 10161002352 10161002352-1-con-1-30 /sys/deckhouse-oss/install:pr9203 user@35.246.190.184

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Pull request merged**
