### PR TITLE
[deckhoues-controller] ha

### LINKED ISSUE #4163: HA mode for deckhouse pod.
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Now we have only one replica of deckhouse controller pod, and in case if node with deckhouse is not ready, we should manually delete pod to reschedule it on another node. This is because deckhouse pod tolerates every taints. Such toleration is needed to allow deckhouse pod to work on cluster bootstrap, on cluster with errors, etc. 
We want to have HA for deckhouse pod.

### Proposed Solution

Deckhouse pod's HA mode should be similar to Kubernetes components:
for example, 3 deckhouse pods on 3 master nodes with leader election. 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
Provides HA mode based on leases and leader election for deckhouse deployment.
Relates to https://github.com/flant/addon-operator/pull/454

## Why do we need it, and what problem does it solve?
It allows to have multiple deckhouse pods, running simultaneously, with a dedicated leader, holding the lease and doing the operator's job. In case of the leader not capable of renewing the lease in a certain amount of time, a new leader is elected among other pods and the new elected leader is promoted to do all the operations.
Closes #4163

## What is the expected result?
The expected result is that it's possible to set deckhouse module to run in highavailability mode via its module settings.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse-controller
type: feature
summary: Provides deckhouse HA mode.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by miklezzzz** [comment]
image

**Comment by miklezzzz** [comment]
standby pod's logs
image

**Comment by miklezzzz** [comment]
lease and endpoints
image

**Review by yalosev — APPROVED** [review]

**Pull request merged**
