### PR TITLE
[common] update common/shell-operator images

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Description
The base image and Python version in dependent images have been updated.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
---
section: common
type: chore
summary: Update base images in `common/shell-operator`.
impact_level: default
---
section: flant-integration
type: chore
summary: Update Python in images `flant-pricing`.
impact_level: default
---
section: deckhouse
type: chore
summary: Update Python in images `webhook-handler`.
impact_level: default
---
section: prometheus
type: chore
summary: Update Python in images `grafana-dashboard-provisioner`.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10315961502 10315961502-1-con-1-27 /sys/deckhouse-oss/install:pr9289 redos@89.169.148.146

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by name212 — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10615925375 10615925375-1-con-1-27 /sys/deckhouse-oss/install:pr9289 redos@89.169.153.52

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Pull request merged**
