### PR TITLE
[monitoring-deckhouse] Remove old grafana panels

### PR DESCRIPTION
**Pull request by meatuses**
## Description
Removes `Snapshots size` and `Kubernetes client requests frequency` panels from Main / Deckhouse

also migrating from deprecated `graph` type to `timeseries`

closes https://github.com/deckhouse/deckhouse/issues/5619

## Why do we need it, and what problem does it solve?
Metrics `deckhouse_kube_snapshot_bytes` and `deckhouse_kubernetes_client_request_result_total` don't exist.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: monitoring-deckhouse
type: chore
summary: Removed old grafana panels from deckhouse monitoring.
impact_level: low
```

### CODE REVIEW

**Comment by meatuses** [comment]
image

**Review by nabokihms — APPROVED** [review]

**Comment by meatuses** [comment]
These errors probably should be fixed within another PR
```
ERRORS:
  * modules/340-monitoring-deckhouse/monitoring/grafana-dashboards/main/deckhouse.json ... ERROR: deprecated panel type
      Panel Queue rate is of deprecated type: 'graph', consider using 'timeseries'
```

**Comment by meatuses** [comment]
@nabokihms are `Grafana Dashboard Validation` errors blocking?

**Comment by meatuses** [comment]
@vladimirGuryanov I've migrated panels to `timeseries` type

**Review by vladimirGuryanov — APPROVED** [review]

**Pull request merged**
