### PR TITLE
[operator-trivy] Add option for configure custom CAs for docker registries 

### LINKED ISSUE #9759: [operator-trivy] Add parameter for custom CA certificates
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Currently, the Trivy module does not have the ability to specify additional CA certificates used in the registries from which scanning is performed. Only the CA certificate used in the DKP components is used. This is a significant drawback, since there may be a situation where third-party regsitry uses a certificate issued by another private CA.
Customers have already made a similar request.

### Proposed Solution

Please add a module setting that allows adding additional ca-certificates.
Or a request to implement mounting of host ca certificates inside trivy containers. Then we will be able to add additional CAs using k8s host settingsttings to specify custom ca-certificates. 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Suselz**
## Description
A `registriesCA` parameter has been added to the trivy module which allows additional CA to be specified for private docker registries. 
This is necessary for situation where multiple docker registries are in use in the cluster and not just the one from which the module is launched.

## Why do we need it, and what problem does it solve?

Currently, only an unsecured connection to additional docker registries is permitted. This addition problematically resolves this situation by permitting the configuration of a trusted, secured connection.
Closes #9759

## What is the expected result?

The `registriesCA` parameter should start to allow the configuration of additional CA for private docker registries within the cluster. 
It should become possible to establish secure, trusted connections to multiple docker registries. 

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section:  operator-trivy
type: feature 
summary: add option for configure custom CAs for docker registries 
impact_level: default 
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Suselz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Suselz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Suselz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by mortelumina98 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mortelumina98. I've started the workflow for label 'deploy/web/stage'...

**Review by z9r5 — APPROVED** [review]

**Comment by Suselz** [comment]
> I propose organizing this configuration in a bit more structured way, for example:
> 
> ```
> additionalRegistryCA:
> - name: example.com
>    ca: |
>      <CA>
> - name: test.com
>    ca: |
>      <CA>
> ```

Made changes based on review
* Renamed parameter to `additionalRegistryCA`
* Changed parameter type to object
* Corrected documentation


> moreover, it makes sense to ensure that TRIVY_REGISTRY_CA variable is either not empty or absent at all.

The code contains a check to see if a variable needs to be set - 
* https://github.com/deckhouse/deckhouse/pull/10768/files#diff-149d5f47bacbd492ffc348076374f34ebdf420c2d64a65611472deb759cc2cc5R91
* https://github.com/deckhouse/deckhouse/pull/10768/files#diff-ed8516b1e039db70b568794aaf6828acf482f9a52e375bf7899ff3e8efeb3fb5R82

**Review by mortelumina98 — APPROVED** [review]

**Review by z9r5 — APPROVED** [review]

**Review by miklezzzz — APPROVED** [review]
:+1:

**Review by yalosev — APPROVED** [review]

**Pull request merged**
