### PR TITLE
[docs] Update title of the editions

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Updated the description of the feature types.
There are four types of features - usual, experimental, ee (available only in Enterprise Edition), fe (experimental and available only in Enterprise Edition).

## Changelog entries
```changes
section: docs
type: fix
summary: Update the description of the feature types.
impact_level: low
```

### CODE REVIEW

**Review by kvaps — APPROVED** [review]
lgtm

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by z9r5** [comment]
Cherry-picked into release-1.31

**Comment by z9r5** [comment]
Cherry-picked into release-1.32

**Pull request merged**
