### PR TITLE
[candi] Add the tzdata package to the bootstrap script on AltLinux

### PR DESCRIPTION
**Pull request by nikiGGG**
## Description

Add the `tzdata` package to the bootstrap script on AltLinux `10.0`.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Add the `tzdata` package to the bootstrap script on AltLinux `10.0`.
```

### CODE REVIEW

**Comment by nikiGGG** [comment]
The 'tzdata' package will be installed at the bootstrap stage:
tzdata at bootstrap src=
The locales are displayed in the system, and log-shipper is successfully launched:
master stage

**Comment by z9r5** [comment]
/e2e/abort static;Static;containerd;1.25 7869086543 7869086543-1-con-1-25 /sys/deckhouse-oss/install:pr7403 astra@192.168.199.67

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/static'...

**Comment by z9r5** [comment]
/e2e/abort static;Static;containerd;1.25 7869401187 7869401187-1-con-1-25 /sys/deckhouse-oss/install:pr7403 astra@192.168.199.37

**Pull request merged**
