### PR TITLE
Update Kubernetes patch versions:

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Update Kubernetes patch versions:
- 1.27.1 ⇾ 1.27.3

## Why do we need it, and what problem does it solve?
It's important to bring fixes and to stay up to date with upstream.

## Why do we need it in the patch release (if we do)?
It is better to take the PR in a patch release.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: candi
type: chore
summary: "Bump patch versions of Kubernetes images: `v1.27.3`"
impact: |
  Kubernetes 1.27 control-plane components will restart, kubelet will restart.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/openstack'...

**Comment by z9r5** [comment]
@RomanenkoDenys All the check have been passsed.

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [5288](https://github.com/deckhouse/deckhouse/pull/5288) to the branch [release-1.48](https://github.com/deckhouse/deckhouse/tree/release-1.48) successful!

**Pull request merged**
