### PR TITLE
[candi] Update kubernetes patch versions

### PR DESCRIPTION
**Pull request by z9r5**
Signed-off-by: Artem Kladov <artem.kladov@flant.com>

## Description
Update Kubernetes:
- 1.22.16 ⇾ 1.22.17
- 1.23.14 ⇾ 1.23.15
- 1.24.8 ⇾ 1.24.9

## Why do we need it, and what problem does it solve?

It's important to bring fixes and to stay up to date with upstream.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: candi
type: feature
summary: "Upgraded patch versions of Kubernetes images: v1.22.17, v1.23.15, and v1.24.9"
impact: |
  "Kubernetes control-plane components will restart, kubelet will restart"
```

### CODE REVIEW

**Comment by z9r5** [comment]
/e2e/run/gcp
/e2e/use/k8s 1.22
/e2e/use/cri/containerd

**Comment by z9r5** [comment]
/e2e/run/gcp
/e2e/use/k8s/1.22
/e2e/use/cri/containerd

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Review by apolovov — APPROVED** [review]

**Pull request merged**
