### PR TITLE
[testing] Release 1.61

### PR DESCRIPTION
**Pull request by Zhbert**
PR for testing purpose.

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by Zhbert** [comment]
/e2e/abort azure;Standard;containerd;1.25 9401125649 9401125649-1-con-1-25 /sys/deckhouse-oss/install:pr8626 azureuser@20.82.117.154

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/eks'...

**Comment by Zhbert** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.25 9417775244 9417775244-2-con-1-25 /sys/deckhouse-oss/install:pr8626 user@34.141.4.232

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by Zhbert** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.29 9446213430 9446213430-1-con-1-29 /sys/deckhouse-oss/install:pr8626 redos@178.154.220.110
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.28 9446213430 9446213430-1-con-1-28 /sys/deckhouse-oss/install:pr8626 redos@178.154.229.82
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9446213430 9446213430-1-con-1-27 /sys/deckhouse-oss/install:pr8626 redos@178.154.230.143

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by Zhbert** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.28 9446213430 9446213430-1-con-1-28 /sys/deckhouse-oss/install:pr8626 redos@178.154.229.82

**Comment by Zhbert** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9446213430 9446213430-1-con-1-27 /sys/deckhouse-oss/install:pr8626 redos@178.154.230.143

**Comment by Zhbert** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 9446213239 9446213239-1-con-1-27 /sys/deckhouse-oss/install:pr8626 centos@18.158.34.203

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by Zhbert** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.29 9446213239 9446213239-1-con-1-29 /sys/deckhouse-oss/install:pr8626 centos@52.28.66.232

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by Zhbert** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.27 9446212878 9446212878-1-con-1-27 /sys/deckhouse-oss/install:pr8626 user@34.107.101.88

**Comment by Zhbert** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.28 9446212878 9446212878-1-con-1-28 /sys/deckhouse-oss/install:pr8626 user@34.141.32.147

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by Zhbert** [comment]
/e2e/abort azure;Standard;containerd;1.27 9446212866 9446212866-1-con-1-27 /sys/deckhouse-oss/install:pr8626 azureuser@172.205.228.32

**Comment by Zhbert** [comment]
/e2e/abort azure;Standard;containerd;1.28 9446212866 9446212866-1-con-1-28 /sys/deckhouse-oss/install:pr8626 azureuser@172.205.228.33

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by Zhbert** [comment]
/e2e/abort azure;Standard;containerd;1.29 9446212866 9446212866-1-con-1-29 /sys/deckhouse-oss/install:pr8626 azureuser@172.205.128.110

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by Zhbert** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 9448127511 9448127511-1-con-1-27 /sys/deckhouse-oss/install:pr8626 ubuntu@10.220.203.122

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by Zhbert** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.28 9448571722 9448571722-1-con-1-28 /sys/deckhouse-oss/install:pr8626 redos@158.160.111.242

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/static'...

**Comment by Zhbert** [comment]
/e2e/abort static;Static;containerd;1.25 9459588833 9459588833-2-con-1-25 /sys/deckhouse-oss/install:pr8626

**Comment by Zhbert** [comment]
/e2e/abort static;Static;containerd;1.26 9459588833 9459588833-2-con-1-26 /sys/deckhouse-oss/install:pr8626 astra@192.168.199.169

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by Zhbert** [comment]
/e2e/abort static;Static;containerd;1.25 9459588833 9459588833-3-con-1-25 /sys/deckhouse-oss/install:pr8626

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/eks'...

**Comment by Zhbert** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.28 9469396818 9469396818-1-con-1-28 /sys/deckhouse-oss/install:pr8626 centos@3.76.2.94

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/aws'...

**Comment by Zhbert** [comment]
/e2e/abort static;Static;containerd;1.25 9496345454 9496345454-1-con-1-25 /sys/deckhouse-oss/install:pr8626

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/static'...

**Comment by Zhbert** [comment]
/e2e/abort static;Static;containerd;1.26 9497934554 9497934554-2-con-1-26 /sys/deckhouse-oss/install:pr8626

**Comment by Zhbert** [comment]
/e2e/abort static;Static;containerd;1.27 9497934554 9497934554-2-con-1-27 /sys/deckhouse-oss/install:pr8626

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/static'...

**Comment by Zhbert** [comment]
/e2e/abort static;Static;containerd;1.25 9498375628 9498375628-1-con-1-25 /sys/deckhouse-oss/install:pr8626

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by Zhbert** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.28 9546674253 9546674253-1-con-1-28 /sys/deckhouse-oss/install:pr8626 redos@158.160.43.144

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/static'...

**Comment by Zhbert** [comment]
/e2e/abort static;Static;containerd;1.25 9563310913 9563310913-1-con-1-25 /sys/deckhouse-oss/install:pr8626 astra@192.168.199.10

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by Zhbert** [comment]
/e2e/abort static;Static;containerd;1.25 9563310913 9563310913-2-con-1-25 /sys/deckhouse-oss/install:pr8626 astra@192.168.199.191

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by Zhbert** [comment]
/e2e/abort vsphere;Standard;containerd;1.25 9579266252 9579266252-1-con-1-25 /sys/deckhouse-oss/install:pr8626 ubuntu@10.220.203.174

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/openstack'...

**Comment by z9r5** [comment]
/e2e/abort vsphere;Standard;containerd;1.25 9675835191 9675835191-1-con-1-25 /sys/deckhouse-oss/install:pr8626 ubuntu@10.220.203.43

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by z9r5** [comment]
/e2e/abort vsphere;Standard;containerd;1.25 9677402361 9677402361-1-con-1-25 /sys/deckhouse-oss/install:pr8626 ubuntu@10.220.203.136

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by z9r5** [comment]
/e2e/abort vsphere;Standard;containerd;1.25 9677611403 9677611403-1-con-1-25 /sys/deckhouse-oss/install:pr8626 ubuntu@10.220.203.148

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/azure'...

**Comment by z9r5** [comment]
/e2e/abort vsphere;Standard;containerd;1.26 9690347519 9690347519-1-con-1-26 /sys/deckhouse-oss/install:pr8626 ubuntu@10.220.203.43

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by z9r5** [comment]
/e2e/abort azure;Standard;containerd;1.26 9690478827 9690478827-1-con-1-26 /sys/deckhouse-oss/install:pr8626

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by z9r5** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 9694868366 9694868366-1-con-1-27 /sys/deckhouse-oss/install:pr8626 ubuntu@10.220.203.164

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by z9r5** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 9694964260 9694964260-1-con-1-27 /sys/deckhouse-oss/install:pr8626 ubuntu@10.220.203.165

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.28 9547461118 9547461118-1-con-1-28 /sys/deckhouse-oss/install:pr8626 redos@158.160.42.151

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request closed without merging**
