### PR TITLE
[deckhouse-controller] Unify release mechanism

### PR DESCRIPTION
**Pull request by libmonsoon-dev**
## Description
Added a module release mechanism similar to the Deckhouse release mechanism

## Why do we need it, and what problem does it solve?
https://github.com/deckhouse/deckhouse/issues/6846

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse-controller
type: feature
summary: Add a module release mechanism similar to the Deckhouse release mechanism.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/static'...

**Comment by libmonsoon-dev** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.29 7912342432 7912342432-2-con-1-29 /sys/deckhouse-oss/install:pr7348

**Comment by libmonsoon-dev** [comment]
/e2e/abort static;Static;containerd;1.29 7912342547 7912342547-1-con-1-29 /sys/deckhouse-oss/install:pr7348

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by miklezzzz** [comment]
@libmonsoon-dev is it still in progress?
can't approve a module release, it seems manualApprovalAnnotation doesn't work :(
image
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
I've created v1.1.2 after having v1.2.0 deployed. Don't remember what should happen in such a situation to v1.1.2, it should have been Skipped/Superseded presumably, shouldn't it?
image
Anyway, it even doesn't provide any message like `manual approval required` or its auto-mode counterpart.

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
apply-now annotation didn't work for me, but in general it seems to be working

**Review by yalosev — APPROVED** [review]

**Review by miklezzzz — APPROVED** [review]

**Pull request merged**
