### PR TITLE
node-termination-handler-test

### PR DESCRIPTION
**Pull request by ilia601**
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/aws'...

**Comment by ilia601** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11003047193 11003047193-1-con-1-27 /sys/deckhouse-oss/install:pr9812 ec2-user@3.74.62.13

**Comment by ilia601** [comment]
`/e2e/abort aws;WithoutNAT;containerd;1.27 11003047193 11003047193-1-con-1-27 /sys/deckhouse-oss/install:pr9812 ec2-user@3.74.62.13`

**Comment by ilia601** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11003047193 11003047193-1-con-1-27 /sys/deckhouse-oss/install:pr9812 ec2-user@3.74.62.13

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by ilia601** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11013567299 11013567299-1-con-1-27 /sys/deckhouse-oss/install:pr9812 ec2-user@3.66.152.4

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/aws'...

**Comment by ilia601** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11016228521 11016228521-1-con-1-27 /sys/deckhouse-oss/install:pr9812 ec2-user@3.75.28.166

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/aws'...

**Comment by ilia601** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11115222749 11115222749-1-con-1-27 /sys/deckhouse-oss/install:pr9812 ec2-user@3.69.192.56

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by ilia601** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11115222749 11115222749-1-con-1-27 /sys/deckhouse-oss/install:pr9812 ec2-user@3.69.192.56

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/aws'...

**Comment by ilia601** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11257382592 11257382592-1-con-1-27 /sys/deckhouse-oss/install:pr9812 ec2-user@3.79.200.154

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by ilia601** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11257382592 11257382592-1-con-1-27 /sys/deckhouse-oss/install:pr9812 ec2-user@3.79.200.154

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/aws'...

**Pull request closed without merging**
