### PR TITLE
[testing] feat: add e2e tests for requirements

### PR DESCRIPTION
**Pull request by juev**
## Description

When switching releases, it is important to check that the `release.yaml` file is filled out correctly

## Why do we need it, and what problem does it solve?

To avoid problems during release associated with incorrect parameters filled in the release.yaml file, we add a check to ensure that the fields are filled in correctly

## What is the expected result?

When running e2e tests, the correctness of filling in the fields in the release.yaml file is checked.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: feature
summary: Add E2E tests for requirements.
impact_level: low
```

### CODE REVIEW

**Comment by juev** [comment]
[e2e passed](https://github.com/deckhouse/deckhouse-test-2/actions/runs/10094525480/job/27912580086)

Screenshot 2024-07-25 at 16 18 51

**Comment by juev** [comment]
[failed e2e test](https://github.com/deckhouse/deckhouse-test-2/actions/runs/10095093147/job/27914416757)

Screenshot 2024-07-25 at 16 54 33

**Comment by juev** [comment]
[refactored e2e failed test](https://github.com/deckhouse/deckhouse-test-2/actions/runs/10095627811/job/27916256847)

Screenshot 2024-07-25 at 17 29 41

**Review by yalosev — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9227](https://github.com/deckhouse/deckhouse/pull/9227) to the branch [release-1.63](https://github.com/deckhouse/deckhouse/tree/release-1.63) successful!

**Pull request merged**
