### PR TITLE
[candi] Update kubernetes patch versions

### PR DESCRIPTION
**Pull request by konstantin-axenov**
Signed-off-by: Konstantin Aksenov <konstantin.aksenov@flant.com>

## Description

Update Kubernetes:
- 1.22.12 ⇾ 1.22.16
- 1.23.9 ⇾ 1.23.14
- 1.24.3 ⇾ 1.24.8

## Why do we need it, and what problem does it solve?

It's important to bring fixes and to stay up to date with upstream.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: feature
summary: "Upgraded patch versions of Kubernetes images: v1.22.16, v1.23.14, and v1.24.8"
impact: |
  "Kubernetes control-plane components will restart, kubelet will restart"
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/aws'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Review by yalosev — APPROVED** [review]

**Pull request merged**
