### PR TITLE
[operator-trivy] fix description for `insecureDbRegistry` and   `insecureRegistries`

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Fix description for  `insecureDbRegistry` and   `insecureRegistries` of the operator-trivy module.

Ref: https://github.com/deckhouse/deckhouse/pull/10559

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: docs
type: chore
summary: Fix description for  `insecureDbRegistry` and   `insecureRegistries` of the operator-trivy module.
impact_level: low
```

### CODE REVIEW

**Comment by z9r5** [comment]
Cherry-picked into release-1.65

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10667](https://github.com/deckhouse/deckhouse/pull/10667) to the branch [release-1.66](https://github.com/deckhouse/deckhouse/tree/release-1.66) successful!

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit 946b08ae3a3aae2d7d49b051c5d43efddc771f98 to the branch [release-1.65](https://github.com/deckhouse/deckhouse/tree/release-1.65) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/11841604735) for details.

**Pull request merged**
