### PR TITLE
[candi][cloud-provider-yandex] Allow to customize NAT instance resources

### PR DESCRIPTION
**Pull request by asviel**
## Description

Allow to customize NAT instance resources, instead of hardcoded values (2 CPUs/2048MiB).

## Why do we need it, and what problem does it solve?

In highly loaded environments, the resources provided by default are not enough.

## Why do we need it in the patch release (if we do)?

We don't.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: feature
summary: Allow to customize Yandex Cloud NAT instance resources.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by z9r5 — APPROVED** [review]

**Review by name212 — APPROVED** [review]

**Pull request merged**
