### PR TITLE
[node-manager] fixed the key usage with cert-authority

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Description
Ran a test using the cert-authority key.
Corrected the generation of machines in mcm.

Cloud does not allow parameters for ssh-key:
AWS
Azure
openstack

Cloud in which cert-authority can be used:
GCP
vcd
VMware vSphere
Yandex Cloud

## Why do we need it, and what problem does it solve?
Allows you to add specific keys.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: fix
summary: fixed the key usage with cert-authority
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11909879583 11909879583-1-con-1-27 /sys/deckhouse-oss/install:pr10718 redos@51.250.71.161

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/vcd'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11910302626 11910302626-1-con-1-27 /sys/deckhouse-oss/install:pr10718 ubuntu@10.220.203.75

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/openstack'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort vcd;Standard;containerd;1.27 11910422024 11910422024-1-con-1-27 /sys/deckhouse-oss/install:pr10718 ubuntu@192.168.254.5

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort openstack;Standard;containerd;1.27 11910545084 11910545084-1-con-1-27 /sys/deckhouse-oss/install:pr10718

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11910606171 11910606171-1-con-1-27 /sys/deckhouse-oss/install:pr10718 redos@89.169.158.229

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11913299877 11913299877-1-con-1-27 /sys/deckhouse-oss/install:pr10718 redos@51.250.14.134

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/azure'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort azure;Standard;containerd;1.27 11934818776 11934818776-1-con-1-27 /sys/deckhouse-oss/install:pr10718

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/aws'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11935413311 11935413311-1-con-1-27 /sys/deckhouse-oss/install:pr10718

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Review by name212 — APPROVED** [review]

**Review by aleksey-su — APPROVED** [review]

**Pull request merged**
