### PR TITLE
[core] Revert d8 cni configuration

### PR DESCRIPTION
**Pull request by AndreyPavlovFlant**
## Description

Canceling migration from d8-cni-configuration secret to proper CNI module configs.

https://github.com/deckhouse/deckhouse/pull/9347
https://github.com/deckhouse/deckhouse/pull/9782
https://github.com/deckhouse/deckhouse/pull/9805

## Why do we need it, and what problem does it solve?

In some cases, this migration may disrupt the network communication within the cluster.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
---
section: cloud-provider-openstack
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
---
section: cloud-provider-vcd
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
---
section: cloud-provider-vsphere
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
---
section: cloud-provider-zvirt
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
---
section: global-hooks
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
---
section: go_lib
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
---
section: common
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
---
section: cni-cilium
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
---
section: cloud-provider-aws
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
---
section: cloud-provider-azure
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
---
section: cloud-provider-gcp
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
---
section: cloud-provider-yandex
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
---
section: cni-flannel
type: fix
summary: |
  Canceling migration from d8-cni-configuration secret to proper CNI module configs.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/aws'...

**Comment by AndreyPavlovFlant** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11070598967 11070598967-1-con-1-27 /sys/deckhouse-oss/install:pr9900 ec2-user@3.79.88.91

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by AndreyPavlovFlant** [comment]
/e2e/abort vcd;Standard;containerd;1.27 11070598822 11070598822-1-con-1-27 /sys/deckhouse-oss/install:pr9900 ubuntu@192.168.254.87

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/vcd'...

**Comment by Taior** [comment]
/e2e/abort vcd;Standard;containerd;1.27 11071948217 11071948217-1-con-1-27 /sys/deckhouse-oss/install:pr9900 ubuntu@192.168.254.88

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vcd'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/eks'...

**Comment by AndreyPavlovFlant** [comment]
/e2e/abort static;Static;containerd;1.27 11105639719 11105639719-1-con-1-27 /sys/deckhouse-oss/install:pr9900 astra@192.168.199.113

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by AndreyPavlovFlant** [comment]
/e2e/abort static;Static;containerd;1.27 11105639719 11105639719-1-con-1-27 /sys/deckhouse-oss/install:pr9900 astra@192.168.199.238

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...

**Review by name212 — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Review by apolovov — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit 9121fc2a26d99a255304b7ab2988373952bce611 to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/11137901411) for details.

**Comment by z9r5** [comment]
Cherry-picked into release-1.64 (https://github.com/deckhouse/deckhouse/pull/9938)

**Pull request merged**
