### PR TITLE
Test PR do not merge

### PR DESCRIPTION
**Pull request by Taior**

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/aws'...

**Comment by Taior** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.29 12461682830 12461682830-1-con-1-29 /sys/deckhouse-oss/install:pr11207 ec2-user@63.176.119.39

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request closed without merging**
