### PR TITLE
[bashible] Remove bb-package-module-install function dupicate

### PR DESCRIPTION
**Pull request by duckhawk**
## Description

Remove bb-package-module-install function dupicate

## Why do we need it, and what problem does it solve?

Now we have duplicated function in bb

## What is the expected result?

Correct bb work

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: bashible
type: fix
summary: Remove bb-package-module-install function dupicate.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10043913334 10043913334-1-con-1-27 /sys/deckhouse-oss/install:pr9101 redos@89.169.138.153

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9122](https://github.com/deckhouse/deckhouse/pull/9122) to the branch [release-1.62](https://github.com/deckhouse/deckhouse/tree/release-1.62) successful!

**Pull request merged**
