### PR TITLE
[docs][openvpn] Update documentation

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Minor fixes in the openvpn module documentation and OpenAPI spec (added examples).

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: openvpn
type: fix
summary: Minor fixer in the openvpn module documentation.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Review by vitaliy-sn — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [2748](https://github.com/deckhouse/deckhouse/pull/2748) to the branch [release-1.38](https://github.com/deckhouse/deckhouse/tree/release-1.38) successful!

**Pull request merged**
