### PR TITLE
[e2e tests, azure] Fix zone discovery and matching

### PR DESCRIPTION
**Pull request by shvgn**
## Description

Fix nodegroup probe for clusters in Azure Cloud

## Why do we need it, and what problem does it solve?

In Azure, we have mismatch between VM zones ("1", "2", "3") used in upmeter zone discovery. But nodes have topology.kubernetes.io/zone label in the form '$region-1', '$region-2', etc. We have to add a workaround for that.

In future, deckhouse-wise zone notation can be chosen separately from what Azure tooling accepts on input. 

## What is the expected result?

e2e tests in Azure pass

## Checklist
- [x] e2e tests passed.

## Changelog entries

```changes
section: upmeter
type: fix
summary: Fixed nodegroup probe for clusters in Azure by fixing zone name discovery.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @shvgn. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @shvgn. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @shvgn. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @shvgn. I've started the workflow for label 'e2e/run/gcp'...

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [3172](https://github.com/deckhouse/deckhouse/pull/3172) to the branch [release-1.40](https://github.com/deckhouse/deckhouse/tree/release-1.40) successful!

**Pull request merged**
