### PR TITLE
[user-authz] Distroless

### PR DESCRIPTION
**Pull request by zuzzas**
## Description

Changed all images to use distroless image by default.

## Why do we need it, and what problem does it solve?

Using images with nothing inside them except statically linked program improves security.

## What is the expected result?

webhook works correctly

```
kubectl -n d8-user-authz logs user-authz-webhook-j6bsr  | head
2023/08/18 10:54:11 server is starting to listen on  127.0.0.1:40443 ...
2023/08/18 10:54:11 configuration was reloaded successfully
2023/08/18 10:55:13 response body: {"apiVersion":"authorization.k8s.io/v1beta1","kind":"SubjectAccessReview","spec":{"resourceAttributes":{"version":"v1","namespace":"d8-user-authn","resource":"secrets","verb":"watch"},"group":["system:nodes","system:authenticated"],"user":"system:node:klimentyev-system-530a423c-64bc8-4gkzj"},"status":{"allowed":false}}
2023/08/18 10:55:13 response body: {"apiVersion":"authorization.k8s.io/v1beta1","kind":"SubjectAccessReview","spec":{"resourceAttributes":{"version":"v1","namespace":"argocd","resource":"configmaps","verb":"watch"},"group":["system:nodes","system:authenticated"],"user":"system:node:klimentyev-system-530a423c-64bc8-crk56"},"status":{"allowed":false}}
```

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: user-authz
type: feature
summary: All images are now based on distroless image
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 5902033144 5902033144-1-con-1-25 /sys/deckhouse-oss/install:pr5511 centos@18.159.28.152

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 5902033144 5902033144-1-con-1-25 /sys/deckhouse-oss/install:pr5511 centos@18.159.28.152

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/aws'...

**Review by RomanenkoDenys — DISMISSED** [review]
LGTM

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 5923004753 5923004753-1-con-1-25 /sys/deckhouse-oss/install:pr5511 centos@3.127.99.37

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 5948368094 5948368094-1-con-1-25 /sys/deckhouse-oss/install:pr5511 centos@3.71.244.150

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Review by aleksey-su — DISMISSED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/aws'...

**Review by nabokihms — APPROVED** [review]

**Pull request merged**
