### PR TITLE
[cni-cilium] bump cilium to v1.12.7 

### PR DESCRIPTION
**Pull request by fl64**
## Description
Bump cilium to v1.12.7.

## Why do we need it, and what problem does it solve?
Cilium bug fixes and security patches.
https://docs.cilium.io/en/v1.12/operations/upgrade/#upgrade-notes

## What is the expected result?
Updated cilium agents and operator are deployed.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cni-cilium
type: chore
summary: Bump cilium to `v1.12.7`
impact: All cilium Pods will be restarted.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by fl64** [comment]
/e2e/abort vsphere;Standard;containerd;1.23 4426684833 4426684833-1-con-1-23 /sys/deckhouse-oss/install:pr4079 ubuntu@10.220.203.32

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @fl64. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — DISMISSED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/openstack'...

**Review by zuzzas — APPROVED** [review]

**Pull request merged**
