### PR TITLE
[ci] Add a script to upload base images and remove labels

### PR DESCRIPTION
**Pull request by nabokihms**
Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>

## Description
* Update base images to fix various CVE
* Add regcopy tool to upload base images

## Why do we need it, and what problem does it solve?
This PRs applies security patches to almost all of Deckhouse containers.

## Changelog entries

```changes
section: candi
type: chore
summary: |
  Update base images:
  - alpine: alpine:3.16.0
  - debian buster: debian:buster-20220527
  - debian bullseye: debian:bullseye-20220527
  - nginx: nginx:1.23.0-alpine
  - python: python:3.7.13-alpine3.16
  - shell-operator: flant/shell-operator:v1.0.10
  - ubuntu: ubuntu:bionic-20220531
impact: All Deckhouse components will be restarted including control-plane, ingress-nginx.
impact_level: high
---
section: tools
type: feat
summary: Add regcopy tool to upload base images with modifications
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/gcp'...

**Comment by nabokihms** [comment]
Blocked by https://github.com/deckhouse/deckhouse/pull/1897

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/aws'...

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
