### PR TITLE
Add CI job number in vpc name

### PR DESCRIPTION
**Pull request by Strange0ne**
## Description

Resources created by EKS test have to contain github action job number, instance number, K8s version.

## Why do we need it, and what problem does it solve?
Change EKS resource naming
## Why do we need it in the patch release (if we do)?

Not related to release
## What is the expected result?

Resource naming is standard
## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

```changes
section: ci
type: fix
summary: Change EKS resource naming.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/eks'...

**Comment by KraMorK** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.27 11552830703 11552830703-1-con-1-27 /sys/deckhouse-oss/install:pr9702

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/eks'...

**Comment by KraMorK** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.27 11552997465 11552997465-1-con-1-27 /sys/deckhouse-oss/install:pr9702

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/eks'...

**Comment by KraMorK** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.27 11553383628 11553383628-1-con-1-27 /sys/deckhouse-oss/install:pr9702

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/eks'...

**Comment by KraMorK** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.27 11553918813 11553918813-1-con-1-27 /sys/deckhouse-oss/install:pr9702

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Review by name212 — APPROVED** [review]

**Pull request merged**
