### PR TITLE
[control-plane-manager] basicAuditPolicy fix generation serviceaccounts

### PR DESCRIPTION
**Pull request by aleksey-su**
## Description
basicAuditPolicy fix generation serviceaccounts

## Why do we need it, and what problem does it solve?
#6183 

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: control-plane-manager
type: fix
summary: basicAuditPolicy fix generation serviceaccounts
impact_level: default
```

### CODE REVIEW

**Comment by aleksey-su** [comment]
image

**Comment by aleksey-su** [comment]
image

**Comment by aleksey-su** [comment]
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Comment by aleksey-su** [comment]
/e2e/abort openstack;Standard;containerd;1.25 7737186850 7737186850-1-con-1-25 /sys/deckhouse-oss/install:pr7342

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Review by name212 — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
