### PR TITLE
[prometheus] Use endpointslices instead of endpoints

### PR DESCRIPTION
**Pull request by yalosev**
## Description
Use EndpointSlices instead of Endpoints in ServiceMonitor.
Add fallback for ServiceMonitor relabeling

## Why do we need it, and what problem does it solve?
Endpoints are out-of-date. EndpointSlices is a more advanced mechanism.

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus-operator
type: chore
summary: Bump prometheus-operator from 0.62 to 0.68 version.
```
```changes
section: prometheus-operator
type: feature
summary: Add EndpointSlice support for service discovery.
```
```changes
section: prometheus
type: feature
summary: Add alert about ServiceMonitors with deprecated relabelings.
```
```changes
section: prometheus
type: fix
summary: Remove unused config for longterm prometheus.
impact_level: low
```

### CODE REVIEW

**Comment by yalosev** [comment]
image

**Comment by yalosev** [comment]
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by yalosev** [comment]
image

**Review by z9r5 — APPROVED** [review]

**Review by nabokihms — APPROVED** [review]

**Pull request merged**
