### PR TITLE
[prometheus] Fix trickster authentication

### PR DESCRIPTION
**Pull request by nabokihms**
## Description
Fixed token-based authentication between trickster and prometheus.

## Why do we need it, and what problem does it solve?
The trickster didn't set Authorization header properly and couldn't set it if the original connection had no the header.

## What is the expected result?
It is possible to make request to trickster without a token but with client cert.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: protmetheus
type: fix
summary: Fixed token-based authentication between trickster and prometheus.
```

### CODE REVIEW

**Review by apolovov — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by nabokihms** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 3893243435 3893243435-1-con-1-23 /sys/deckhouse-oss/install:pr3519 cloud-user@51.250.78.218

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [3528](https://github.com/deckhouse/deckhouse/pull/3528) to the branch [release-1.42](https://github.com/deckhouse/deckhouse/tree/release-1.42) successful!

**Pull request merged**
