### PR TITLE
Change operator-trivy module license from Apache to EE License

### PR DESCRIPTION
**Pull request by gmaiorov**
## Description

This PR changes `operator-trivy` module license from Apache to EE License and moves corresponding module to `ee/modules`.

I've tested this PR manually on FE dev-cluster. Module works same as on `main` when enabled.
`make FOCUS=operator-trivy tests-modules` passes without problems.

## What is the expected result?

* CE will no longer include `operator-trivy` module in future releases;
* `operator-trivy` module is now licensed under [EE License](https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE).
## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: operator-trivy
type: chore
summary: Change operator-trivy module license from Apache to EE License.
impact: The `operator-trivy` module will no longer be available in CE.
impact_level: high
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/gcp'...

**Review by kvaps — DISMISSED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Review by z9r5 — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...

**Review by kvaps — APPROVED** [review]
linstor hook lgtm

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...

**Review by kvaps — DISMISSED** [review]
LGTM for the rest

**Review by diafour — DISMISSED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
