### PR TITLE
[e2e] add third static node and update bootstrap script

### LINKED ISSUE #4572: [e2e] Add more OS to test in the air gapped environments
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Our clients use a wide range of OSs in air-gapped environments.

### Proposed Solution

Add all the supported OSs to e2e tests in the air-gapped environments.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
Openstack environment has been updated:
* alt linux p10 cloud image has been added;
* redos 7.3.2 qcow2-baked image has been added;

E2e static test infrastructure template has been updated:
* one more node group 'worker' has been added;
* one more node 'worker' running redos 7.3.2 has been added;
* system node has been updated to run altlinux p10;
* different OS versions use different user-data scripts for bootstrap testing;

E2e preparation script has been updated:
* a worker node bootstrapping has been added;
* the script is connecting to different nodes with corresponding users (astra, altlinux, redos);

## Why do we need it, and what problem does it solve?
We must have a possibility to run e2e tests against different supported OSs.
Close #4572 

## What is the expected result?
```
NAME                                   STATUS   ROLES                  AGE     VERSION
candi-5102516668-1-con-1-23-master-0   Ready    control-plane,master   9m30s   v1.23.17
candi-5102516668-1-con-1-23-system-0   Ready    system                 3m19s   v1.23.17
candi-5102516668-1-con-1-23-worker-0   Ready    worker                 63s     v1.23.17
```

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: e2e
type: chore
summary: E2e static environment has been updated to run tests against astra, altlinux, and redos OSs.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5081403731 5081403731-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5087560204 5087560204-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5088234574 5088234574-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5088536103 5088536103-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5088679516 5088679516-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5089084903 5089084903-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5091300046 5091300046-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5091591920 5091591920-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5098463001 5098463001-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5098671979 5098671979-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5098721380 5098721380-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5098964634 5098964634-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5098964634 5098964634-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5099115820 5099115820-1-con-1-23 /sys/deckhouse-oss/install:pr4784

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
