### PR TITLE
[cloud-provider-vsphere] Bump csi driver to v2.5.4

### PR DESCRIPTION
**Pull request by konstantin-axenov**
Signed-off-by: Konstantin Aksenov <konstantin.aksenov@flant.com>

## Description

Bump csi driver to [v2.5.4](https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.5.4).

## Why do we need it, and what problem does it solve?

Closes https://github.com/deckhouse/deckhouse/issues/2985

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-vsphere
type: fix
summary: Bump csi driver to v2.5.3
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/vsphere'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Pull request merged**
