### PR TITLE
[snapshot-controller] Move CRDs to separate module

### PR DESCRIPTION
**Pull request by kvaps**
## Description

snapshot-controller wasn't working because of dependency problems

## Why do we need it, and what problem does it solve?

Module snapshot-controller was using it's own CRDs, so deploying them as single module was not possible.

This PR is brings the following changes:
- Move CRDs to separate snapshot-controller-crd module, which is enabled by default
- Enables snapshot-controller if any of supported cloud-providers or linstor is enabled
- Modifies `enabled` script which allows snapshot-controller be enabled explicitly by user 

## Changelog entries

```changes
section: snapshot-controller
type: fix
summary: fix snapshot-controller wasn't working because of dependency problems
impact_level: low
```

### CODE REVIEW

**Comment by z9r5** [comment]
@kvaps Please add info to the PR description and changelog blocks.

**Comment by kvaps** [comment]
sure, done

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Review by z9r5 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/openstack'...

**Review by nabokihms — APPROVED** [review]

**Comment by z9r5** [comment]
Cherry-picked into release-1.33

**Pull request merged**
