### PR TITLE
[common] Add commonName field to Deckhouse X.509 certificates

### LINKED ISSUE #4926: [common] Add commonName to all deckhouse certificate
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Request from internal client 

### Proposed Solution

Add `commonName` field equals to all certificates.
For example, https://github.com/deckhouse/deckhouse/blob/main/modules/300-prometheus/templates/grafana/ingress.yaml#L82

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by artbin**
## Description

Add commonName field to Deckhouse X.509 certificates.

## Why do we need it, and what problem does it solve?

Close #4926.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: common
type: fix
summary: Add commonName field to Deckhouse X.509 certificates.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Comment by artbin** [comment]
Manual testing:

Command:
```
kubectl -n d8-system set image deployment/deckhouse deckhouse=dev-registry.deckhouse.io/sys/deckhouse-oss:pr4999`
```

Output:
```
deployment.apps/deckhouse image updated
```

Command:
```
nmap -p 443 --script ssl-cert grafana.dev.a-kulyabin.hf.flant.com
```

Output:
```
| ssl-cert: Subject: commonName=grafana.dev.a-kulyabin.hf.flant.com
| Subject Alternative Name: DNS:grafana.dev.a-kulyabin.hf.flant.com, DNS:prometheus.dev.a-kulyabin.hf.flant.com
| Issuer: commonName=R3/organizationName=Let's Encrypt/countryName=US
```

Command:
```
nmap -p 443 --script ssl-cert prometheus.dev.a-kulyabin.hf.flant.com
```

Output:
```
| ssl-cert: Subject: commonName=grafana.dev.a-kulyabin.hf.flant.com
| Subject Alternative Name: DNS:grafana.dev.a-kulyabin.hf.flant.com, DNS:prometheus.dev.a-kulyabin.hf.flant.com
| Issuer: commonName=R3/organizationName=Let's Encrypt/countryName=US
```

**Review by name212 — APPROVED** [review]

**Comment by name212** [comment]
Before
image
After
image
Certificates were not renewed

**Review by shvgn — DISMISSED** [review]
delivery+upmeter

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Review by nabokihms — APPROVED** [review]

**Pull request merged**
