### PR TITLE
[deckhouse] Block main queue until deckhouse helm release is become ready

### PR DESCRIPTION
**Pull request by yalosev**
## Description
Block the main queue until deckhouse helm release is deployed

## Why do we need it, and what problem does it solve?
Deckhouse could restart in the middle of upgrade process and helm release will stuck in the pending-upgrade state.
Entrypoint sleep breaks module-configs logic, so we have to stop in the deckhouse module

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse
type: fix
summary: Block the main queue until helm release is not ready
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by yalosev** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4302996887 4302996887-1-con-1-23 /sys/deckhouse-oss/install:pr3960 cloud-user@158.160.63.190

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by yalosev** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4303571822 4303571822-1-con-1-23 /sys/deckhouse-oss/install:pr3960 cloud-user@158.160.39.235

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by yalosev** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4304027176 4304027176-1-con-1-23 /sys/deckhouse-oss/install:pr3960 cloud-user@158.160.33.57

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...

**Comment by yalosev** [comment]
resolved in https://github.com/deckhouse/deckhouse/pull/3976

**Pull request closed without merging**
