### PR TITLE
[testing] Switch Azure e2e test machine size

### PR DESCRIPTION
**Pull request by Taior**
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/azure'...

**Comment by Taior** [comment]
/e2e/abort azure;Standard;containerd;1.29 12388490628 12388490628-1-con-1-29 /sys/deckhouse-oss/install:pr11122 azureuser@20.82.124.97

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Taior. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vadimartynov. I've started the workflow for label 'e2e/run/azure'...

**Comment by vadimartynov** [comment]
/e2e/abort azure;Standard;containerd;1.29 12428334080 12428334080-1-con-1-29 /sys/deckhouse-oss/install:pr11122 azureuser@172.211.240.62

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vadimartynov. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request closed without merging**
