### PR TITLE
[secret-copier] Delete argocd labels from copied secrets

### PR DESCRIPTION
**Pull request by haosb**
## Description
Delete labels that belong to ArgoCD on copied secrets

## Why do we need it, and what problem does it solve?
Now secrets copied by module does not belong to ArgoCD.

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: secret-copier
type: feature
summary: Delete ArgoCD labels on copied secrets
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @haosb. I've started the workflow for label 'e2e/run/aws'...

**Comment by haosb** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.30 10780316006 10780316006-1-con-1-30 /sys/deckhouse-oss/install:pr9670 ec2-user@35.157.23.248

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @haosb. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by haosb** [comment]
```
[root@10780316006-1-con-1-30-master-0 ~]# kubectl get secret deckhouse-registry-test -n d8-system -o yaml
apiVersion: v1
data:
  address: cmVnaXN0cnkuZGVja2hvdXNlLmlv
  path: L2RlY2tob3VzZS9lZQ==
  scheme: aHR0cHM=
kind: Secret
metadata:
  annotations:
    secret-copier.deckhouse.io/created-at: "2024-09-09T20:25:26Z"
  creationTimestamp: "2024-09-09T20:25:26Z"
  labels:
    name: deckhouse-registry
    secret-copier.deckhouse.io/enabled: ""
  name: deckhouse-registry-test
  namespace: d8-system
  resourceVersion: "10696"
  uid: c447c465-2aa5-4e00-b06d-92b61710d83b
type: Opaque

[root@10780316006-1-con-1-30-master-0 ~]# kubectl get secret deckhouse-registry-test -o yaml
apiVersion: v1
data:
  address: cmVnaXN0cnkuZGVja2hvdXNlLmlv
  path: L2RlY2tob3VzZS9lZQ==
  scheme: aHR0cHM=
kind: Secret
metadata:
  creationTimestamp: "2024-09-09T20:19:25Z"
  labels:
    argocd.argoproj.io/instance: testargo
    name: deckhouse-registry
    secret-copier.deckhouse.io/enabled: ""
  name: deckhouse-registry-test
```

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9719](https://github.com/deckhouse/deckhouse/pull/9719) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!

**Pull request merged**
