### PR TITLE
[dhctl] Add validation rules for ClusterConfiguration.cloud.prefix specific to cloud providers

### PR DESCRIPTION
**Pull request by borg-z**
## Description

Different cloud providers have different restrictions on resource names (instances, networks, etc.). In this case we added validation for YandexCloud.

This is not a complete solution because we cannot accurately validate the length of the claud resource name, which is the length of the prefix and the name, e.g. `bob-yc-9858` + `-master-` + `1`.

terraform-provider-yandex has validation for some resources, but not for all, for example here: https://github.com/yandex-cloud/terraform-provider-yandex/blob/9a7e19d14e32a9d5e05ff349afbc3ba2d60bb46e/yandex/resource_yandex_smartcaptcha_captcha.go#L92
 

Similar issue:
https://github.com/yandex-cloud/terraform-provider-yandex/issues/353#issuecomment-1614502414

## Why do we need it, and what problem does it solve?

At the moment we don't do prefix validation, based on which we then create cloud resources with terraform. This can lead to problems as described in the linked issue

## What is the expected result?

An invalid prefix will cause an error when attempting to bootstrap:
```
invalid prefix '1bob-yc-9858' for provider 'Yandex', prefix must match the pattern: ^([a-z]([-a-z0-9]{0,61}[a-z0-9])?)$
```

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Add validation for ClusterConfiguration.cloud.prefix
impact_level: default
```

### CODE REVIEW

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by name212** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11124558273 11124558273-1-con-1-27 /sys/deckhouse-oss/install:pr9858 redos@89.169.128.63

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Pull request merged**
