### PR TITLE
[cloud-providers-openstack] documentation improvement. 

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Description
Documentation improvement. Added commands to help filling `domainName` and `volumeTypeMap`

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: cloud-providers-openstack
type: fix 
summary: Add commands to help filling `domainName` and `volumeTypeMap`.
impact_level: low 
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Review by nabokihms — DISMISSED** [review]

**Comment by nabokihms** [comment]
@z9r5, let's merge, looks totally fine.

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [5319](https://github.com/deckhouse/deckhouse/pull/5319) to the branch [release-1.48](https://github.com/deckhouse/deckhouse/tree/release-1.48) successful!

**Pull request merged**
