### PR TITLE
[common] Fix k8s patches for 1.28 and 1.29

### PR DESCRIPTION
**Pull request by vitaliy-sn**
## Description

Fixed k8s patches:

-   kube-controller-manager/1.28/pdb-daemonset.patch
-   kube-controller-manager/1.29/pdb-daemonset.patch
-   kubeadm/1.29/07-local-init-configuration.patch

Changed the way patches are applied. Now if the patch is not applied, the build will fail.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: common
type: fix
summary: Fix k8s patches for 1.28 and 1.29.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...

**Comment by vitaliy-sn** [comment]
/e2e/abort static;Static;containerd;1.28 7930519234 7930519234-1-con-1-28 /sys/deckhouse-oss/install:pr7537 astra@192.168.199.184

**Comment by vitaliy-sn** [comment]
/e2e/abort static;Static;containerd;1.29 7930519234 7930519234-1-con-1-29 /sys/deckhouse-oss/install:pr7537 astra@192.168.199.117

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...

**Comment by z9r5** [comment]
/e2e/abort static;Static;containerd;1.28 7935896652 7935896652-1-con-1-28 /sys/deckhouse-oss/install:pr7537 astra@192.168.199.8

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...

**Comment by vitaliy-sn** [comment]
/e2e/abort static;Static;containerd;1.28 7940362968 7940362968-1-con-1-28 /sys/deckhouse-oss/install:pr7537

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Review by z9r5 — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
