### PR TITLE
[discovery] Fix Kubernetes version hook for DigitalOcean

### PR DESCRIPTION
**Pull request by artbin**
## Description

Fix Kubernetes version hook for DigitalOcean.

## Why do we need it, and what problem does it solve?

We need it to support deployment for managed DigitalOcean Kubernetes clusters.

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: discovery
type: fix
summary: Fix Kubernetes version hook for DigitalOcean
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Comment by name212** [comment]
/e2e/abort openstack;Standard;containerd;1.23 4818085020 4818085020-1-con-1-23 /sys/deckhouse-oss/install:pr4473 debian@91.236.196.33

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by name212** [comment]
/e2e/abort openstack;Standard;containerd;1.23 4818085020 4818085020-1-con-1-23 /sys/deckhouse-oss/install:pr4473 debian@91.236.196.33

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by name212** [comment]
/e2e/abort openstack;Standard;containerd;1.23 4818085020 4818085020-1-con-1-23 /sys/deckhouse-oss/install:pr4473 debian@91.236.196.33

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
