### PR TITLE
[node-manager] tune caps sync period

### PR DESCRIPTION
**Pull request by borg-z**
## Description

The synchronization period for the CAPS controller has been reduced from 10 minutes to 1 minute.
This helps us fix a number of issues that arise due to long controller response times. This is a small fix to give time to deal with the problem completely.

`SyncPeriod` description:

```
	// This applies to all controllers.
	//
	// A period sync happens for two reasons:
	// 1. To insure against a bug in the controller that causes an object to not
	// be requeued, when it otherwise should be requeued.
	// 2. To insure against an unknown bug in controller-runtime, or its dependencies,
	// that causes an object to not be requeued, when it otherwise should be
	// requeued, or to be removed from the queue, when it otherwise should not
	// be removed.
```

## Why do we need it, and what problem does it solve?

Prevent problems with CAPS

## What is the expected result?

CAPS will more frequently reconcile resources, which prevents errors from occurring.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: fix
summary: tune caps sync period
impact: 
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/openstack'...

**Comment by borg-z** [comment]
/e2e/abort openstack;Standard;containerd;1.29 12525111738 12525111738-1-con-1-29 /sys/deckhouse-oss/install:pr11384 redos@31.129.35.104

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @borg-z. I've recognized your '/e2e/abort' command and started the workflow...

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [11390](https://github.com/deckhouse/deckhouse/pull/11390) to the branch [release-1.67](https://github.com/deckhouse/deckhouse/tree/release-1.67) successful!

**Pull request merged**
