### PR TITLE
[candi] Add RSA in tls-cipher-suites apiserver for CIS Benchmark 1.6

### PR DESCRIPTION
**Pull request by trofimovdals**
## Description

Should pass 1.2.35 - "Ensure that the API Server only makes use of Strong Cryptographic Ciphers (Manual)" in CIS Benchmark 1.6 in new clusters

## Changelog entries

```changes
section: candi
type: fix
summary: Add RSA in tls-cipher-suites apiserver for CIS Benchmark 1.6
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by trofimovdals** [comment]
Do we need to do a "migration" for the current clusters?

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by name212** [comment]
> Do we need to do a "migration" for the current clusters?

No. Control-plane-manager will add new suits

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10255](https://github.com/deckhouse/deckhouse/pull/10255) to the branch [release-1.65](https://github.com/deckhouse/deckhouse/tree/release-1.65) successful!

**Pull request merged**
