### PR TITLE
feat(dhctl-server): options to skip preflight checks for dhctl-server operations

### PR DESCRIPTION
**Pull request by distorhead**
## Description

Added options to skip preflight checks for dhctl-server operations.

## Why do we need it, and what problem does it solve?

In the commander it is needed to skip some preflight checks in dhctl operations.

## Why do we need it in the patch release (if we do)?

This is small change, but it will enable some commander usage scenarios.

## What is the expected result?

It is not expected to change dhctl-cli behaviour in any way.

## Changelog entries

```changes
section: dhctl
type: feature
summary: Options to skip preflight checks for dhctl-server operations.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @distorhead. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @distorhead. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @distorhead. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @distorhead. I've started the workflow for label 'e2e/run/static'...

**Comment by name212** [comment]
/e2e/abort static;Static;containerd;1.27 11443407407 11443407407-1-con-1-27 /sys/deckhouse-oss/install:pr10043 astra@192.168.199.221

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by Taior** [comment]
Backported to 1.64 in #10221

**Pull request merged**
