### PR TITLE
[prometheus] add beforeHelm for alertmanager_crds hook

### PR DESCRIPTION
**Pull request by sprait**
## Description

Add beforeHelm binding for `alertmanager_crds` hook.

## Why do we need it, and what problem does it solve?

Sometimes when we create a cluster, we get cr prometheus created without alertmanager. 

## What is the expected result?

Correct render cr prometheus with alertmanager spec.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: fix
summary: Add beforeHelm binding for `alertmanager_crds` hook.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Comment by sprait** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 9466731230 9466731230-1-con-1-25 /sys/deckhouse-oss/install:pr8669 centos@3.126.35.52

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Review by vladimirGuryanov — APPROVED** [review]

**Pull request merged**
