### PR TITLE
[flow-schema] fix apiversion for k8s < 1.23

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
Signed-off-by: Denis Romanenko <denis.romanenko@flant.com>

## Description

 Fix flowschema apiversion for k8s < 1.23.
## Why do we need it, and what problem does it solve?

In k8s < 1.23 flowschema uses flowcontrol.apiserver.k8s.io/v1beta1 apiversion.
## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: fix flowschema apiversion for k8s < 1.23
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.21 4073516769 4073516769-1-con-1-21 /sys/deckhouse-oss/install:pr3738 centos@3.121.97.191

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Review by yalosev — APPROVED** [review]

**Pull request merged**
