### PR TITLE
[docs] corrected various spelling errors in the documentation #10758

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Corrected various spelling errors in the documentation 

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: docs
type: chore
summary: Corrected various spelling errors in the documentation.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10759](https://github.com/deckhouse/deckhouse/pull/10759) to the branch [release-1.66](https://github.com/deckhouse/deckhouse/tree/release-1.66) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10760](https://github.com/deckhouse/deckhouse/pull/10760) to the branch [release-1.65](https://github.com/deckhouse/deckhouse/tree/release-1.65) successful!

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit 0498eeb85823d36eb02b7189b7fb15f6d9caaf6f to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/11951312956) for details.

**Comment by z9r5** [comment]
Cherry-picked into release-1.64

**Pull request merged**
