### PR TITLE
[testing] Force use of specific openstack provider that we built

### PR DESCRIPTION
**Pull request by mvasl**
## Description

Hardcoded specific openstack terraform provider version that we build ourselves.

## Why do we need it, and what problem does it solve?

This fixes daily static tests.

## Changelog entries

```changes
section: testing
type: chore
summary: Forced use of specific openstack provider that we build.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...

**Comment by mvasl** [comment]
/e2e/abort static;Static;containerd;1.25 7098216040 7098216040-1-con-1-25 /sys/deckhouse-oss/install:pr6761

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...

**Comment by mvasl** [comment]
/e2e/abort static;Static;containerd;1.25 7098558973 7098558973-1-con-1-25 /sys/deckhouse-oss/install:pr6761

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by mvasl** [comment]
/e2e/abort static;Static;containerd;1.25 7099665655 7099665655-1-con-1-25 /sys/deckhouse-oss/install:pr6761

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...

**Pull request closed without merging**
