### PR TITLE
[candi] Clean /tmp after bootstrap

### PR DESCRIPTION
**Pull request by mvasl**
## Description

Candi's `098_cleanup.sh` will now also clean `/tmp` from remnants of the bootstrap bundle.

## Why do we need it, and what problem does it solve?

See [#5597](https://github.com/deckhouse/deckhouse/issues/5597#issuecomment-1695348015), point №2

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: chore
summary: `/tmp` is now cleared before node is rebooted after bootstrap.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — CHANGES_REQUESTED** [review]
Discussed, need some additions

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Pull request merged**
