### PR TITLE
[deckhouse] add discovered GVKs from modules' CRDs to global values

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
This pr updates the addon-operator to support [the following functionality.](https://github.com/flant/addon-operator/pull/511)
Also, a NodeGroup CRD is moved to the node-manager` `crds` directory for consistency with other modules.

## Why do we need it, and what problem does it solve?
It should allow developers to check more precisely and straightforward if required CRs are installed in the cluster.

## What is the expected result?
The deckhouse controller should have up-to-date list of installed CR in the `.global.discovery.apiVersions` key.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse-controller
type: feature
summary: Add discovered GVKs from modules' CRDs to global values.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by miklezzzz** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11148062276 11148062276-1-con-1-27 /sys/deckhouse-oss/install:pr9963 redos@89.169.159.114

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
logs
```
{"level":"debug","msg":"CheckCRDsEnsured: set to true","time":"2024-10-03T07:58:27Z"}
{"binding":"ConvergeModules","event.type":"OperatorStartup","level":"debug","modules":"dashboard,operator-trivy,upmeter","msg":"ModuleEnsureCRDs task done, result is 'Success' for module 'upmeter', trigger is EnsureCRDs","order":"500","queue":"main","task.flow":"end","task.id":"04f23258-4bb3-4682-8cd2-dc65b97bf292","time":"2024-10-03T07:58:27Z"}
{"level":"debug","msg":"CheckCRDsEnsured: set to false","time":"2024-10-03T08:01:35Z"}
{"event.id":"e52a9570-107e-49f9-87b5-35d182661455","level":"info","msg":"head task ModuleEnsureCRDs for module 'admission-policy-engine', trigger is EnsureCRDs","source":"KubeConfigExtenderChanged","task.flow":"add","task.id":"fe339f43-9fce-48aa-a72f-2ea7ae8dbfa9","time":"2024-10-03T08:01:35Z","type":"ModuleScheduler event"}
{"event.id":"e52a9570-107e-49f9-87b5-35d182661455","level":"info","module":"admission-policy-engine","msg":"ModuleEnsureCRDs task for module 'admission-policy-engine', trigger is EnsureCRDs","source":"KubeConfigExtenderChanged","task.flow":"start","task.id":"1ea53a24-2055-4f9b-8e9f-44894863fa58","time":"2024-10-03T08:01:35Z","type":"ModuleScheduler event"}
{"level":"debug","msg":"CheckCRDsEnsured: set to true","time":"2024-10-03T08:01:35Z"}
{"event.id":"e52a9570-107e-49f9-87b5-35d182661455","level":"debug","module":"admission-policy-engine","msg":"ModuleEnsureCRDs task done, result is 'Success' for module 'admission-policy-engine', trigger is EnsureCRDs","source":"KubeConfigExtenderChanged","task.flow":"end","task.id":"1ea53a24-2055-4f9b-8e9f-44894863fa58","time":"2024-10-03T08:01:35Z","type":"ModuleScheduler event"}
```

**Comment by miklezzzz** [comment]
global values
```
clusterConfiguration:
  apiVersion: deckhouse.io/v1
  cloud:
    prefix: dev
    provider: OpenStack
  clusterDomain: cluster.local
  clusterType: Cloud
  defaultCRI: Containerd
  kind: ClusterConfiguration
  kubernetesVersion: "1.27"
  podSubnetCIDR: 10.111.0.0/16
  podSubnetNodeCIDRPrefix: "24"
  serviceSubnetCIDR: 10.222.0.0/16
clusterIsBootstrapped: true
deckhouseEdition: FE
deckhouseVersion: dev
discovery:
  apiVersions:
    - deckhouse.io/v1beta1/ClusterServiceMetric
    - deckhouse.io/v1alpha1/StatefulSetMetric
    - deckhouse.io/v1beta1/PodMetric
    - autoscaling.k8s.io/v1beta1/VerticalPodAutoscalerCheckpoint
    - deckhouse.io/v1alpha1/ClusterLogDestination
    - machine.sapcloud.io/v1alpha1/MachineDeployment
    - deckhouse.io/v1alpha1/DexClient
    - deckhouse.io/v1alpha1/IstioMulticluster
    - deckhouse.io/v1alpha1/AuthorizationRule
    - deckhouse.io/v1alpha1/ClusterAuthorizationRule
    - deckhouse.io/v1alpha1/PodMetric
    - deckhouse.io/v1alpha1/IngressNginxController
    - snapshot.storage.k8s.io/v1alpha1/VolumeSnapshot
    - cluster.x-k8s.io/v1beta1/MachineDeployment
    - monitoring.coreos.com/v1/Alertmanager
    - aquasecurity.github.io/v1alpha1/RbacAssessmentReport
    - mutations.gatekeeper.sh/v1/AssignMetadata
...
```

**Comment by miklezzzz** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11159249687 11159249687-1-con-1-27 /sys/deckhouse-oss/install:pr9963

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by miklezzzz** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11159516160 11159516160-1-con-1-27 /sys/deckhouse-oss/install:pr9963

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/aws'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.27 11159245933 11159245933-1-con-1-27 /sys/deckhouse-oss/install:pr9963 astra@192.168.199.108

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Review by yalosev — APPROVED** [review]

**Pull request merged**
