### PR TITLE
[dhctl] Fix only one resource will create for namespace if it namespace does not exist

### PR DESCRIPTION
**Pull request by name212**
## Description
Fix only one resource will create for namespace if it namespace does not exist
Affect DKP == 1.64.3

Fix https://github.com/deckhouse/deckhouse/pull/9714

## Why do we need it, and what problem does it solve?
When multiple resources will be created in namespace (which will be created in resources.yaml), we wait namespace creation only one firs resource. Another resources will skip by bug in the code 

## Why do we need it in the patch release (if we do)?

Cannot create all resources by resources.yaml

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Only one resource will create for namespace if it namespace does not exist.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by mvasl — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [10163](https://github.com/deckhouse/deckhouse/pull/10163) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!

**Pull request merged**
