### PR TITLE
[cni-cilium] wiping unwanted iptables-legacy rules

### PR DESCRIPTION
**Pull request by AndreyPavlovFlant**
## Description

The init-container for cilium-agent pod checks iptables-legacy for any unwanted rules and deletes them if found.

## Why do we need it, and what problem does it solve?

Previously, due to a configuration error, cilium-agent was always creating its rules in the iptables-legacy. 
The configuration error has now been fixed, and cilium-agent is creating its own rules in the correct table. 
However, previously created rules remain in the iptables-legacy table, even if the system is using iptables-nft.

## Why do we need it in the patch release (if we do)?

Such behavior does not have a negative impact.
But having the rules in the wrong table can be confusing.

## What is the expected result?

The rules created by the cilium-agent are present only in those iptables tables (nft or lagacy) that are used by the entire node.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cni-cilium
type: fix
summary: wiping unwanted iptables-legacy rules
impact: All cilium-agent pods will be restarted.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vcd'...

**Comment by AndreyPavlovFlant** [comment]
/e2e/abort vcd;Standard;containerd;1.27 11167747078 11167747078-1-con-1-27 /sys/deckhouse-oss/install:pr9971

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...

**Comment by AndreyPavlovFlant** [comment]
/e2e/abort openstack;Standard;containerd;1.27 11167411335 11167411335-2-con-1-27 /sys/deckhouse-oss/install:pr9971 redos@31.129.35.116

**Comment by AndreyPavlovFlant** [comment]
/e2e/abort openstack;Standard;containerd;1.27 11167411335 11167411335-1-con-1-27 /sys/deckhouse-oss/install:pr9971 redos@31.129.35.110

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...

**Review by Beastlex — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...

**Review by apolovov — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit c583ffe99b0299af4027b08d49c1cb30ddd457e6 to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/11238486006) for details.

**Comment by Taior** [comment]
Cherry-picked into release-1.64 (https://github.com/deckhouse/deckhouse/pull/9971)

**Pull request merged**
