### PR TITLE
[openapi] Update some JSON schemas

### PR DESCRIPTION
**Pull request by Zhbert**
## Description

Update JSON Schemas of the following resources:
- ModuleConfig/metallb
- NodeGroup
- ModuleConfig/descheduler
- ClusterAuthorizationRule
- ClusterLoggingConfig
- PodLoggingConfig

Changes:
- Update the description of some fields.
- Add `oneOf` validation schema to `matchExpressions` fields.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: docs
type: chore
summary: |
  Update JSON Schema of the following resources:
  - ModuleConfig/metallb
  - NodeGroup
  - ModuleConfig/descheduler
  - ClusterAuthorizationRule
  - ClusterLoggingConfig
  - PodLoggingConfig
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by z9r5** [comment]
@nabokihms Please review.

Is it normal, that [there is](https://github.com/deckhouse/deckhouse/pull/6780/files#diff-ad67bc4a98722db4553166bfade375ba77dc0e57a27769321525e793d55e45baL228) such enum for the boolean type?
```

**Review by z9r5 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by yalosev — APPROVED** [review]

**Pull request merged**
