### PR TITLE
[testing] fix e2e cloud tests

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

Fix e2e cloud tests.
## Why do we need it, and what problem does it solve?

Fix typo in script path.
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: fix
summary: fix e2e cloud tests
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Comment by name212** [comment]
/e2e/abort openstack;Standard;containerd;1.25 9699036051 9699036051-1-con-1-25 /sys/deckhouse-oss/install:pr8823 redos@31.129.32.164

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
