### PR TITLE
[core] fix work registry-packages-proxy with module sources

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

Fix registry packages proxy to work with modules images.
Added additional logging info.

## Why do we need it, and what problem does it solve?

Currently registry packages proxy cannot work properly with registries from module sources.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: core
type: fix
summary: fix work registry-packages-proxy with module sources
impact: registry-packages-proxy should be restarted
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10057341256 10057341256-1-con-1-27 /sys/deckhouse-oss/install:pr9112 redos@89.169.129.242

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
