### PR TITLE
[shell_lib] Fix an error with password generation in shell hooks

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

Fix an error with password generation in shell hooks.
## Why do we need it, and what problem does it solve?

Previously shell lib uses pwgen to generate passwords. Now we use python to do it.
## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: core
type: fix
summary: Fix an error with password generation in shell hooks
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort vsphere;Standard;containerd;1.25 7958786649 7958786649-1-con-1-25 /sys/deckhouse-oss/install:pr7548 ubuntu@10.220.203.115

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Review by yalosev — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort vsphere;Standard;containerd;1.25 7959754941 7959754941-1-con-1-25 /sys/deckhouse-oss/install:pr7548 ubuntu@10.220.203.115

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort vsphere;Standard;containerd;1.25 7960551495 7960551495-1-con-1-25 /sys/deckhouse-oss/install:pr7548 ubuntu@10.220.203.115

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
