### PR TITLE
[cloud-provider-yandex] Add alert about deprecated NAT Instance zone. Add wrap-around for externalSubnetIDs

### PR DESCRIPTION
**Pull request by asviel**
## Description

Add alert about deprecated NAT Instance zone (if NAT Instance in `ru-central1-c` zone). Alert contains step-by-step guide to migrate NAT Instance.

Also in this PR, fix terraform when specifying a number of replicas greater than the number of externalSubnetIDs.

## Why do we need it, and what problem does it solve?

Yandex Cloud [deprecates](https://cloud.yandex.com/en-ru/docs/overview/concepts/ru-central1-c-deprecation) `ru-central1-c` availability zone, users are encouraged to migrate NAT Instance to another zone.

#6482

## Why do we need it in the patch release (if we do)?

We don't.

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-yandex
type: feature
summary: Add alert about deprecated NAT Instance zone.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by asviel** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 7345630792 7345630792-1-con-1-25 /sys/deckhouse-oss/install:pr6736 cloud-user@51.250.9.242

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by RomanenkoDenys — APPROVED** [review]

**Review by nabokihms — APPROVED** [review]

**Pull request merged**
