### PR TITLE
[candi] fix exit codes in bootstrap-networks scripts

### PR DESCRIPTION
**Pull request by sprait**
## Description

Fix catch exit codes in bootstrap-network scripts.

## Why do we need it, and what problem does it solve?

Non-zero exit codes may be legal in bootstrap-network scripts.

## Why do we need it in the patch release (if we do)?

Fix bootstrap new nodes in different cloud-providers.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Fix catch exit codes in cloud-providers bootstrap-network scripts.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9451](https://github.com/deckhouse/deckhouse/pull/9451) to the branch [release-1.63](https://github.com/deckhouse/deckhouse/tree/release-1.63) successful!

**Pull request merged**
