### PR TITLE
[not-merge] Testing azure lb problem

### PR DESCRIPTION
**Pull request by trofimovdals**
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/azure'...

**Comment by trofimovdals** [comment]
/e2e/abort azure;Standard;containerd;1.29 12464272390 12464272390-1-con-1-29 /sys/deckhouse-oss/install:pr11209 azureuser@51.124.190.85

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @trofimovdals. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by trofimovdals** [comment]
/e2e/abort azure;Standard;containerd;1.29 12464272390 12464272390-1-con-1-29 /sys/deckhouse-oss/install:pr11209 azureuser@51.124.190.85

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @trofimovdals. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request closed without merging**
