### PR TITLE
[documentation] Fix EKS tests 

### PR DESCRIPTION
**Pull request by libmonsoon-dev**
## Description
Fixes for e2e tests for AWS: fixed panic when rendering templates and added curl to the deckhouse container.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: documentation
type: fix
summary: Fix e2e tests for AWS. And curl to the deckhouse container.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/eks'...

**Comment by libmonsoon-dev** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.29 7985467367 7985467367-1-con-1-29 /sys/deckhouse-oss/install:pr7578

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/eks'...

**Comment by libmonsoon-dev** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.28 7986727743 7986727743-1-con-1-28 /sys/deckhouse-oss/install:pr7578

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've started the workflow for label 'e2e/run/eks'...

**Comment by libmonsoon-dev** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.28 7991060403 7991060403-1-con-1-28 /sys/deckhouse-oss/install:pr7578

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @libmonsoon-dev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by libmonsoon-dev** [comment]
https://github.com/deckhouse/deckhouse/actions/runs/7991060403/job/21828475269

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [7597](https://github.com/deckhouse/deckhouse/pull/7597) to the branch [release-1.58](https://github.com/deckhouse/deckhouse/tree/release-1.58) successful!

**Pull request merged**
