### PR TITLE
[cloud-instance-manager] Increased PSI threshold

### PR DESCRIPTION
**Pull request by zuzzas**
## Description

1. Increase psi-monitor's threshold to 30
2. Moved threshold configuration to program args to allow faster debugging

## Why do we need it, and what problem does it solve?

early-oom triggers on cgroup memory pressure. To provide a better experience for cluster users while minimizing node memory trashing, we'll raise the threshold.

## What is the expected result?

OOMs are triggered only in the event of a true memory starvation.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: fix
summary: Increase early-oom PSI threshold to 30 (from 5).
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by yalosev — COMMENTED** [review]
Don't you want to make it configurable via the flag? Like `--memory-threshold=30`
Unnamed argument looks very weird

**Comment by zuzzas** [comment]
@yalosev 
There is no formula to calculate this properly, atm.

**Review by apolovov — APPROVED** [review]

**Review by apolovov — CHANGES_REQUESTED** [review]
I agree with Yuri. Let's use a lib for args parsing.

**Comment by zuzzas** [comment]
Oh, damn, that's what you meant! Sorry, let me fix this.

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by apolovov — APPROVED** [review]

**Review by yalosev — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [3456](https://github.com/deckhouse/deckhouse/pull/3456) to the branch [release-1.42](https://github.com/deckhouse/deckhouse/tree/release-1.42) successful!

**Pull request merged**
