### PR TITLE
[registrypackages] Allow downgrading RPMs in centos

### PR DESCRIPTION
**Pull request by apolovov**
## Description
Allow downgrading RPMs in registrypackages for centos.

## Why do we need it, and what problem does it solve?
It is impossible to downgrade to previous release if there were packages upgraded in current release.

## What is the expected result?
registrypackages install the rpms despite the version.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: registrypackages
type: fix
summary: Allow downgrading RPMs in registrypackages for CentOS.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/aws'...

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [3354](https://github.com/deckhouse/deckhouse/pull/3354) to the branch [release-1.42](https://github.com/deckhouse/deckhouse/tree/release-1.42) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [3359](https://github.com/deckhouse/deckhouse/pull/3359) to the branch [release-1.41](https://github.com/deckhouse/deckhouse/tree/release-1.41) successful!

**Pull request merged**
