### PR TITLE
[cni-cilium] bump cilium version to v1.13.2

### PR DESCRIPTION
**Pull request by fl64**
## Description
Bump cilium version to v1.13.2

## Why do we need it, and what problem does it solve?
Closes https://github.com/deckhouse/deckhouse/issues/4574

## What is the expected result?
Updated cilium agents and operator are deployed.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cni-cilium
type: chore
summary: Bump cilium version to v1.13.2
impact: All cilium pods will be restarted
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/openstack'...

**Comment by kvaps** [comment]
Please double check cilium in tunnel mode:

```yaml
bpf-lb-mode: hybrid
```

logs:
```
level=fatal msg="failed to start: daemon creation failed: unable to initialize kube-proxy replacement options: Node Port \"hybrid\" mode cannot be used with tunneling." subsys=daemon
```

cc @zuzzas

**Comment by fl64** [comment]
@kvaps I just have checked this in YC and there are no fatal errors.

**Comment by fl64** [comment]
same thing for DSR mode

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/openstack'...

**Comment by fl64** [comment]
## Check LoadBalancer/NodePort problem 

```yaml
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: control-plane-manager
spec:
  version: 1
  enabled: true
  settings:
    apiserver:
      loadBalancer:
        port: 6443
```

```
 curl -k https://$(kubectl -n kube-system get svc d8-control-plane-apiserver -o json | jq .status.loadBalancer.ingress[0].ip -r):6443                  
 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}%                                                   
```
## Test case when module node-local-dns is enabled, but node-local-dns pods is restarted.
```
kubectl -n d8-cni-cilium rollout status ds/agent 

kubectl -n cilium-test-prober exec deploy/prober-other-node -- bash -c "dig +short ya.ru"                                                             

77.88.55.242
5.255.255.242

kubectl -n kube-system rollout restart ds node-local-dns

kubectl -n kube-system rollout status ds node-local-dns

kubectl -n cilium-test-prober exec deploy/prober-other-node -- bash -c "dig +short ya.ru"                                                             

5.255.255.242
77.88.55.242
```

**Comment by RomanenkoDenys** [comment]
> @kvaps I just have checked this in YC and there are no fatal errors. but i got another message: `agent-rkl24 cilium-agent level=warning msg="Disabling NodePort's \"hybrid\" mode feature due to tunneling mode being enabled" subsys=daemon`

We have config option for bpfLBMode. So we need to solve the situation when we use VXLAN and set bpfLBMode to Hybrid or DSR.

**Review by RomanenkoDenys — CHANGES_REQUESTED** [review]
We have config option for bpfLBMode. So we need to solve the situation when we use VXLAN and set bpfLBMode to Hybrid or DSR.

**Pull request closed without merging**
