### PR TITLE
[istio] splitting istio to CE and EE versions

### PR DESCRIPTION
**Pull request by fl64**
## Description
Sharing our istio module with the Community. Except some features.

## Why do we need it, and what problem does it solve?
Users' dopamine levels need to be increased.

## What is the expected result?
👩🏻‍💻 + istio = ❤️

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: istio
type: feature
summary: Splitting istio to CE (basic functionality) and EE (extra functionality) versions.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Review by z9r5 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by z9r5** [comment]
I've got approval from `@apolovov `.

**Pull request merged**
