### PR TITLE
test e2e

### PR DESCRIPTION
**Pull request by vitaliy-sn**
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by vitaliy-sn** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 6325048875 6325048875-1-con-1-25 /sys/deckhouse-oss/install:pr5968 centos@3.76.135.124

**Comment by vitaliy-sn** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 6325892926 6325892926-1-con-1-23 /sys/deckhouse-oss/install:pr5968 centos@3.77.215.127

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by vitaliy-sn** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 6325892926 6325892926-1-con-1-23 /sys/deckhouse-oss/install:pr5968 centos@3.77.215.127

**Comment by vitaliy-sn** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 6326045101 6326045101-1-con-1-27 /sys/deckhouse-oss/install:pr5968 centos@3.126.142.80

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request closed without merging**
