### PR TITLE
[kube-dns] Delete resolv-watcher image

### PR DESCRIPTION
**Pull request by tarabrind**
## Description
Currently unused.
`resolv-watcher` is a component that monitors changes in the `/etc/resolv.conf` file on a node and reacts to these changes by updating DNS settings within the Kubernetes cluster (sending a `SIGUSR1` signal to the `coredns` process to trigger a soft reload without service disruption).

Recent changes:
- [Oct 8, 2021](https://github.com/deckhouse/deckhouse/commit/51b0c0d3bf08106728a0a08cf6384021eec3dd8b): Removed Sidecar loading in Deployment.
- [Apr 21, 2023](https://github.com/deckhouse/deckhouse/commit/d4cb453794d42269c25188ce96ed531aafbcb69c): The component was rewritten in Go but was still not added to the Deployment.

## Why do we need it, and what problem does it solve?
We are removing a component that has not been in use for a long time.

## What is the expected result?
The component is removed from the repository, and it is no longer compiled.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: kube-dns
type: chore
summary: Deleted resolv-watcher image.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by apolovov — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by tarabrind** [comment]
kubectl create configmap pause-the-test

**Comment by tarabrind** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.29 12242001678 12242001678-1-con-1-29 /sys/deckhouse-oss/install:pr10940 redos@89.169.147.117

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by tarabrind** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.29 12250547373 12250547373-1-con-1-29 /sys/deckhouse-oss/install:pr10940 redos@158.160.33.241

**Comment by tarabrind** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.29 12273726345 12273726345-1-con-1-29 /sys/deckhouse-oss/install:pr10940 redos@89.169.156.209

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by tarabrind** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.29 12281133246 12281133246-1-con-1-29 /sys/deckhouse-oss/install:pr10940 redos@89.169.148.39

**Comment by tarabrind** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.29 12281681173 12281681173-1-con-1-29 /sys/deckhouse-oss/install:pr10940 user@34.40.33.8

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by tarabrind** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.29 12346986466 12346986466-1-con-1-29 /sys/deckhouse-oss/install:pr10940 redos@89.169.128.192

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by tarabrind** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.29 12347203427 12347203427-1-con-1-29 /sys/deckhouse-oss/install:pr10940 redos@89.169.142.164

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @tarabrind. I've recognized your '/e2e/abort' command and started the workflow...

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [11162](https://github.com/deckhouse/deckhouse/pull/11162) to the branch [release-1.67](https://github.com/deckhouse/deckhouse/tree/release-1.67) successful!

**Pull request merged**
