### PR TITLE
[docs][prometheus][extended-monitoring] Fix content

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Minor content fixes on the prometheus and extended-monitoring modules.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [X] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: docs
type: chore
summary: Minor content fixes on the prometheus and extended-monitoring modules.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by z9r5** [comment]
Close: #3242

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [3498](https://github.com/deckhouse/deckhouse/pull/3498) to the branch [release-1.42](https://github.com/deckhouse/deckhouse/tree/release-1.42) successful!

**Pull request merged**
