### PR TITLE
[candi] Fix SELinux permissions Bashible step in clusters without Cilium

### PR DESCRIPTION
**Pull request by gmaiorov**
## Description

This PR makes BPF-related SELinux permissions enabled conditionally based on whether Cilium agent is running on a node.

Changes were tested manually both on clusters with and without Cilium using following NodeGroupConfiguration:
```
apiVersion: deckhouse.io/v1alpha1
kind: NodeGroupConfiguration
metadata:
  creationTimestamp: "2023-04-19T15:12:42Z"
  generation: 2
  name: centos-selinux.sh
  resourceVersion: "123564106"
  uid: 81268ab3-b454-4b71-9a89-b7149fd608f1
spec:
  bundles:
  - redos
  content: |
    # Copyright 2022 Flant JSC
    # Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE.

    bb-event-on 'selinux_deckhouse_policy_changed' '_on_selinux_deckhouse_policy_changed'
    _on_selinux_deckhouse_policy_changed() {
      checkmodule -M -m -o /var/lib/bashible/policies/deckhouse.mod /var/lib/bashible/policies/deckhouse.te
      semodule_package -o /var/lib/bashible/policies/deckhouse.pp -m /var/lib/bashible/policies/deckhouse.mod
      semodule -i /var/lib/bashible/policies/deckhouse.pp
    }

    mkdir -p /var/lib/bashible/policies
    bb-sync-file /var/lib/bashible/policies/deckhouse.te - selinux_deckhouse_policy_changed << "EOF"
    module deckhouse 1.0;

    require {
      type unlabeled_t;
      type httpd_t;
      type http_port_t;
      type init_t;
      type var_lib_t;
      type sge_port_t;
      type load_policy_t;
      type var_lock_t;
      type setfiles_t;
      type unreserved_port_t;
      class tcp_socket name_connect;
      class capability sys_resource;
      class process setrlimit;
      class file { getattr open read write execute_no_trans execute };
      class tcp_socket name_bind;
    }

    #============= httpd_t ==============

    #!!!! This avc can be allowed using one of the these booleans:
    #     httpd_run_stickshift, httpd_setrlimit
    allow httpd_t self:capability sys_resource;

    #!!!! This avc can be allowed using the boolean 'httpd_setrlimit'
    allow httpd_t self:process setrlimit;
    allow httpd_t sge_port_t:tcp_socket name_bind;
    allow httpd_t unreserved_port_t:tcp_socket name_connect;
    allow httpd_t unlabeled_t:file getattr;
    allow httpd_t http_port_t:tcp_socket name_connect;

    #!!!! This avc is allowed in the current policy
    allow httpd_t unlabeled_t:file { open read };

    #============= init_t ==============
    allow init_t unlabeled_t:file write;
    allow init_t var_lib_t:file { execute execute_no_trans };

    #============= load_policy_t ==============
    allow load_policy_t var_lib_t:file read;
    allow load_policy_t var_lock_t:file write;

    #============= setfiles_t ==============
    allow setfiles_t var_lib_t:file read;
    EOF

    {{- if eq .cri "Containerd" }}
    bb-event-on 'selinux_cilium_policy_changed' '_on_selinux_cilium_policy_changed'
    _on_selinux_cilium_policy_changed() {
      checkmodule -M -m -o /var/lib/bashible/policies/cilium.mod /var/lib/bashible/policies/cilium.te
      semodule_package -o /var/lib/bashible/policies/cilium.pp -m /var/lib/bashible/policies/cilium.mod
      semodule -i /var/lib/bashible/policies/cilium.pp
    }

    if crictl ps | grep -q "cilium-agent"; then
      bb-sync-file /var/lib/bashible/policies/cilium.te - selinux_cilium_policy_changed << "EOF"
    module cilium 1.0;

    require {
      type init_t;
      type spc_t;
      type container_runtime_t;
      class bpf prog_run;
    }

    #============= spc_t ==============
    allow spc_t container_runtime_t:bpf prog_run;
    allow spc_t init_t:bpf prog_run;
    EOF
    fi

    echo "" > /var/lib/bashible/bundle_steps/033_install_mandatory_selinux_policies.sh
    {{- end }}
  nodeGroups:
  - worker-redos
  weight: 32
```

## Why do we need it, and what problem does it solve?

https://github.com/deckhouse/deckhouse/pull/4070 causes issues in CentOS-based setups when Cilium is not used.
## What is the expected result?

* BPF-related SELinux permissions is now enabled conditionally based on existing `cilium-agent` container.
* This permissions shouldn't cause issues in setups without Cilium.
## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Fix SELinux permissions Bashible step in clusters without Cilium.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...

**Comment by gmaiorov** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 4745355454 4745355454-1-con-1-23 /sys/deckhouse-oss/install:pr4418

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @gmaiorov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...

**Comment by gmaiorov** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.23 4746360742 4746360742-1-con-1-23 /sys/deckhouse-oss/install:pr4418

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @gmaiorov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @gmaiorov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [4445](https://github.com/deckhouse/deckhouse/pull/4445) to the branch [release-1.45](https://github.com/deckhouse/deckhouse/tree/release-1.45) successful!

**Pull request merged**
