### PR TITLE
[deckhouse] Bump addon-operator

### PR DESCRIPTION
**Pull request by yalosev**
## Description
Bump addon-operator

## Why do we need it, and what problem does it solve?
Modules without helm chart are removed after converge. We have to keep them present.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse
type: fix
summary: Keep enabled modules without helm charts after converge.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [7323](https://github.com/deckhouse/deckhouse/pull/7323) to the branch [release-1.57](https://github.com/deckhouse/deckhouse/tree/release-1.57) successful!

**Comment by z9r5** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 7695670254 7695670254-1-con-1-25 /sys/deckhouse-oss/install:pr7315

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
