### PR TITLE
[cni-cilium] Enabling pprof interface for agents

### PR DESCRIPTION
**Pull request by apolovov**
## Description
Enabling pprof interface for agents.

## Why do we need it, and what problem does it solve?
In case of cpu leaks it is convenient to profile the agent code with pprof.

## What is the expected result?
The pprof gathering works inside cilium-agent pod:
```
cilium-bugtool --get-pprof --pprof-trace-seconds 30
```

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cni-cilium
type: chore
summary: Enabled pprof interface in cilium-agent.
impact: cillium-agent pods will restart.
impact_level: default
```

### CODE REVIEW

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [6876](https://github.com/deckhouse/deckhouse/pull/6876) to the branch [release-1.56](https://github.com/deckhouse/deckhouse/tree/release-1.56) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [6882](https://github.com/deckhouse/deckhouse/pull/6882) to the branch [release-1.54](https://github.com/deckhouse/deckhouse/tree/release-1.54) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [6883](https://github.com/deckhouse/deckhouse/pull/6883) to the branch [release-1.55](https://github.com/deckhouse/deckhouse/tree/release-1.55) successful!

**Pull request merged**
