### PR TITLE
[cloud-provider-yandex] Forbid zero value for coreFraction field in YandexClusterConfiguration

### LINKED ISSUE #3551: [cloud-provider-yandex] YandexClusterConfiguration allows setting coreFraction to 0
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.42

### Expected Behavior

It is impossible to set coreFraction = 0.

### Actual Behavior

It is possible to set coreFraction = 0, but yandex console doesn't allow it.

### Steps To Reproduce

_No response_

### Additional Information

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by alex123012**
## Description

It is impossible to set `coreFraction` field to `0` in yandex console, but `YandexClusterConfiguration` accepts it. PR fixes this behaviour.

## Why do we need it, and what problem does it solve?

Fix #3551 

## What is the expected result?

Users can't set `0` value for `coreFraction` field in `YandexClusterConfiguration`

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-yandex
type: fix
summary: Forbid zero value for coreFraction field in YandexClusterConfiguration
impact_level: low
```

### CODE REVIEW

**Review by name212 — CHANGES_REQUESTED** [review]
Some remarks:
1. You should assignee pr for yourself only. If you need to add additional reviewers, just add reviewers, not to 'Assignees'
2. Some checks were not passed. Please fix all problems before your PR ready for review. In some cases restart failed jobs fix problem.
3. After all checks will be passed, please run e2e test. In this pr we can skip e2e test but for education purposes let run test.

**Comment by name212** [comment]
run e2e test for yandex

**Comment by name212** [comment]
summary should begin with capital letter:
`Forbid zero value for coreFraction field in YandexClusterConfiguration`

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alex123012. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by RomanenkoDenys — APPROVED** [review]

**Review by name212 — APPROVED** [review]

**Pull request merged**
