### PR TITLE
[admission-policy-engine] Fix validate spec.enforcementAction in constraints resources

### PR DESCRIPTION
**Pull request by trofimovdals**
## Description

`spec.enforcementAction` not validate in constraints resources, but supported only `[deny, dryrun, warn]`
Someone may make a mistake and enter the wrong value and the rule will not work, although there was no error message
## Why do we need it in the patch release (if we do)?

I suggest supplementing `ValidatingWebhookConfiguration` by adding validation for all resources with apiVersion `constraints.gatekeeper.sh`
## What is the expected result?

```shell
# kubectl apply -f constraint_with_syntax_error.yml
Error from server: error when creating "constraint_with_syntax_error.yml
": admission webhook "admission-policy-engine.deckhouse.io" denied the request: unrecognized enforcementAction: "wsarn" is not within the supported list [deny dryrun warn]
``` 
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: admission-policy-engine
type: feature
summary: Add validating spec.enforcementAction in constraints resources.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by trofimovdals** [comment]
image

**Comment by miklezzzz** [comment]
@trofimovdals everything is fine but you've got to update the module's tests

**Review by miklezzzz — APPROVED** [review]

**Review by yalosev — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9452](https://github.com/deckhouse/deckhouse/pull/9452) to the branch [release-1.63](https://github.com/deckhouse/deckhouse/tree/release-1.63) successful!

**Pull request merged**
