### PR TITLE
[prometheus] Rollback prometheus-module ServiceMonitor label selector to `app=prometheus`

### PR DESCRIPTION
**Pull request by konstantin-axenov**
Signed-off-by: Konstantin Aksenov <konstantin.aksenov@flant.com>

## Description

Rollback prometheus-module ServiceMonitor label selector to `app=prometheus`.

## Why do we need it, and what problem does it solve?

If enterprise edition is used or monitoring-applications module is disabled, then ServiceMonitor from prometheus module is deploed. In #1446 we broke services labels, so now they are just fixed to work as before.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: fix
summary: Rollback prometheus-module ServiceMonitor label selector to `app=prometheus`.
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Comment by z9r5** [comment]
Cherry-picked into release-1.34

**Pull request merged**
