### PR TITLE
[docs] Improve pages about SIEM and KESL

### PR DESCRIPTION
**Pull request by Zhbert**
## Description

The structure of the security pages in the cluster has been changed.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: docs
type: fix
summary: The structure of the security pages in the cluster has been changed.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'deploy/web/stage'...

**Review by z9r5 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @Zhbert. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [11130](https://github.com/deckhouse/deckhouse/pull/11130) to the branch [release-1.67](https://github.com/deckhouse/deckhouse/tree/release-1.67) successful!

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit 2174e7eaac4f88e6ce6b5d51c91d62a88d36b364 to the branch [release-1.66](https://github.com/deckhouse/deckhouse/tree/release-1.66) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/12391060622) for details.

**Comment by z9r5** [comment]
Cherry-picked into release-1.66

**Pull request merged**
