### PR TITLE
[loki] fix init container

### PR DESCRIPTION
**Pull request by aleksey-su**
## Description
Fixed a volume mount init container

## Why do we need it, and what problem does it solve?
Loki can't start

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: loki
type: fix
summary: Fixed a volume mount init container.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [5947](https://github.com/deckhouse/deckhouse/pull/5947) to the branch [release-1.51](https://github.com/deckhouse/deckhouse/tree/release-1.51) successful!

**Pull request merged**
