### PR TITLE
[dhctl] Fix ssh client startup in deckhouse installation phase

### PR DESCRIPTION
**Pull request by mvasl**
## Description

Fixed SIGSEGV in dhctl during specific bootstrap conditions.

## Why do we need it, and what problem does it solve?

This fixes bootstrap in EKS and install-deckhouse phase in general.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Fix SSH client startup in Deckhouse installation phase.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/eks'...

**Comment by mvasl** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.30 10734457571 10734457571-1-con-1-30 /sys/deckhouse-oss/install:pr9628

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/eks'...

**Comment by mvasl** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.30 10734834781 10734834781-1-con-1-30 /sys/deckhouse-oss/install:pr9628

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/eks'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.30 10770761548 10770761548-1-con-1-30 /sys/deckhouse-oss/install:pr9628

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by mvasl** [comment]
e2e fails due to kubernetes version discovery failure, eks has weird stuff in their `gitVersion` field in `kubectl version -o json`

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/eks'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/eks'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.30 10772950912 10772950912-1-con-1-30 /sys/deckhouse-oss/install:pr9628

**Comment by mvasl** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.30 10772950912 10772950912-1-con-1-30 /sys/deckhouse-oss/install:pr9628

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by mvasl** [comment]
/e2e/abort eks;WithoutNAT;containerd;1.30 10773869400 10773869400-1-con-1-30 /sys/deckhouse-oss/install:pr9628

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/eks'...

**Review by yalosev — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9668](https://github.com/deckhouse/deckhouse/pull/9668) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!

**Pull request merged**
