### PR TITLE
[prometheus] fix prometheus image size

### PR DESCRIPTION
**Pull request by aleksey-su**
## Description
Fix Prometheus image size.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: prometheus
type: fix
summary: Fix Prometheus image size.
impact_level: default
```

### CODE REVIEW

**Comment by aleksey-su** [comment]
image

**Comment by aleksey-su** [comment]
image

**Comment by aleksey-su** [comment]
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [6438](https://github.com/deckhouse/deckhouse/pull/6438) to the branch [release-1.54](https://github.com/deckhouse/deckhouse/tree/release-1.54) successful!

**Pull request merged**
