### PR TITLE
[candi] Enable GracefulNodeShutdown flag on k8s 1.20

### PR DESCRIPTION
**Pull request by zuzzas**
## Description

Feature gate was not enabled on Kubernetes 1.20.

## Why do we need it, and what problem does it solve?

Kubelet did not start on Kubernetes 1.20.

## Changelog entries

```changes
section: candi
type: fix
summary: kubelets did not start on k8s 1.20
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by zuzzas** [comment]
@nabokihms 
It's failing on 
```
ModuleRun failed in phase 'CanRunHelm'. Requeue task to retry after delay. Failed count is 188. Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec.alerting): missing required field "alertmanagers" in com.coreos.monitoring.v1.Prometheus.spec.alerting
```

I think you can merge that now.

**Review by nabokihms — APPROVED** [review]

**Review by nabokihms — APPROVED** [review]

**Comment by z9r5** [comment]
Cherry-picked into release-1.33

**Pull request merged**
