### PR TITLE
[deckhouse] Update FAQ documentation about minimalNotificationTime.

### PR DESCRIPTION
**Pull request by Dmitrykob**
## Description

Update documentation about Deckhouse update configuration. Add info that the [webhook](https://deckhouse.ru/documentation/v1/modules/002-deckhouse/configuration.html#parameters-update-notification-webhook) parameter is no longer required. 

## Why do we need it, and what problem does it solve?

fix issue https://github.com/deckhouse/deckhouse/issues/5147

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: docs
type: chore
summary: Update documentation about Deckhouse update configuration.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Review by z9r5 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Review by nabokihms — APPROVED** [review]

**Review by yalosev — APPROVED** [review]

**Pull request merged**
