### PR TITLE
[dhctl] Fix bootstrap on systems with umask 027/077

### PR DESCRIPTION
**Pull request by vitaliy-sn**
## Description

Fixed bootstrap on systems with umask 027/077

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Fixed bootstrap on systems with umask 027/077
```

### CODE REVIEW

**Comment by vitaliy-sn** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 9385309364 9385309364-1-con-1-25 /sys/deckhouse-oss/install:pr8622 centos@18.199.227.229

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by vitaliy-sn** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 9387523770 9387523770-1-con-1-25 /sys/deckhouse-oss/install:pr8622 centos@52.28.241.192

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...

**Comment by vitaliy-sn** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 9388739304 9388739304-1-con-1-25 /sys/deckhouse-oss/install:pr8622 centos@52.57.56.174

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/gcp'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
