### PR TITLE
[prometheus] Fix links to modules documentation

### PR DESCRIPTION
**Pull request by scaps1**
## Description
We've got broken links to the module documentation.

## Why do we need it, and what problem does it solve?
We've got broken links to the modules docs; the previous expression was catching the module name with its weight, and it causes errors when redirecting.

## What is the expected result?
Proper links to the modules documentation

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: fix
summary: Fix links to modules documentation
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by vladimirGuryanov — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [11343](https://github.com/deckhouse/deckhouse/pull/11343) to the branch [release-1.66](https://github.com/deckhouse/deckhouse/tree/release-1.66) successful!

**Pull request merged**
