### PR TITLE
[node-manager] Simplify ng zones check expression

### LINKED ISSUE #7936: [node-manager] does not allow to set zone if there is no restriction on zones in the provider
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.58.5

### Expected Behavior

If there is no restriction in the cluster provider the list must be obtained in another way.

### Actual Behavior

error during operation
`NodeGroup/prod-worker dry-run failed: admission webhook "nodegroup-policy.deckhouse.io" denied the request: unknown zone "us-west-2c"`
https://t.me/deckhouse_ru/32595

### Steps To Reproduce

1. aws cloud 
2. zones don't usage in provider-cluster-configuration
3. add ng usage zones

### Additional Information

https://github.com/deckhouse/deckhouse/pull/7248/files

### Logs

_No response_

### PR DESCRIPTION
**Pull request by asviel**
## Description

Simplify ng zones check expression.

## Why do we need it, and what problem does it solve?

Closes #7936.

## Why do we need it in the patch release (if we do)?

One client had a problem.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: fix
summary: Simplify ng zones check expression.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [8025](https://github.com/deckhouse/deckhouse/pull/8025) to the branch [release-1.59](https://github.com/deckhouse/deckhouse/tree/release-1.59) successful!

**Comment by deckhouse-BOaTswain** [comment]
Backport failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/8612957172) for details.

**Pull request merged**
