### PR TITLE
[node-manager] Forbid to change NodeGroup if it contains unknown zone

### PR DESCRIPTION
**Pull request by asviel**
## Description

Forbid to change NodeGroup if it contains unknown zone.

## Why do we need it, and what problem does it solve?

Now, if a NodeGroup contains an unknown zone (e.g. a typo), node-manager will remove it from internal values and all nodes in that NodeGroup will be removed.

## Why do we need it in the patch release (if we do)?

We added new zone support to YandexCloud in release 1.56 (https://github.com/deckhouse/deckhouse/pull/6652) and users can start actively changing zones in NodeGroup manifests and can break their cluster through configuration errors or typos.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: fix
summary: Forbid to change NodeGroup if it contains unknown zone.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by asviel** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 7613459980 7613459980-1-con-1-25 /sys/deckhouse-oss/install:pr7248 cloud-user@158.160.108.48

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Comment by asviel** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 7654342286 7654342286-1-con-1-25 /sys/deckhouse-oss/install:pr7248 cloud-user@158.160.99.233

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by asviel** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.25 7654343310 7654343310-1-con-1-25 /sys/deckhouse-oss/install:pr7248 user@35.198.117.88

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by asviel** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 7654349605 7654349605-1-con-1-25 /sys/deckhouse-oss/install:pr7248 centos@3.123.219.53

**Comment by asviel** [comment]
/e2e/abort openstack;Standard;containerd;1.25 7654348309 7654348309-1-con-1-25 /sys/deckhouse-oss/install:pr7248 debian@45.94.123.169

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/gcp'...

**Comment by z9r5** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.25 7656093049 7656093049-1-con-1-25 /sys/deckhouse-oss/install:pr7248 user@35.198.117.88

**Comment by z9r5** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 7655534333 7655534333-1-con-1-25 /sys/deckhouse-oss/install:pr7248 cloud-user@84.201.175.40

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by asviel** [comment]
/e2e/abort openstack;Standard;containerd;1.25 7666869449 7666869449-1-con-1-25 /sys/deckhouse-oss/install:pr7248 debian@5.159.101.212

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've recognized your '/e2e/abort' command and started the workflow...

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
