### PR TITLE
[cni-cilium] Removed useless alert

### PR DESCRIPTION
**Pull request by zuzzas**
## Description

Removed useless CiliumAgentControllersRunsFailing.

## Why do we need it, and what problem does it solve?

The Prometheus gauge is not returned to zero once an error condition clears. Perhaps, we'll take a look at this bug once we update to a fresher version of Cilium

## What is the expected result?

Alert no longer triggers.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cni-cilium
type: fix
summary: Removed CiliumAgentControllersRunsFailing alert
impact_level: low
```

### CODE REVIEW

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by konstantin-axenov** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4012998017 4012998017-1-con-1-23 /sys/deckhouse-oss/install:pr3639 cloud-user@158.160.45.114

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @konstantin-axenov. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by zuzzas** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4014311326 4014311326-1-con-1-23 /sys/deckhouse-oss/install:pr3639 cloud-user@158.160.58.249

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by zuzzas** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4015255927 4015255927-1-con-1-23 /sys/deckhouse-oss/install:pr3639 cloud-user@158.160.59.109

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've recognized your '/e2e/abort' command and started the workflow...

**Review by yalosev — APPROVED** [review]

**Pull request merged**
