### PR TITLE
[operator-trivy] Disable infra assessment

### PR DESCRIPTION
**Pull request by zuzzas**
## Description

Disabled infra assessment, since it has bugs that spawn ~1000 Jobs when something is wrong with a Node.

## Why do we need it, and what problem does it solve?

operator-trivy may sometimes spawn lots of Jobs for an infra report.

## What is the expected result?

Lots of Jobs are not spawned.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: operator-trivy
type: fix
summary: Disabled infra assessment jobs.
impact_level: low
```

### CODE REVIEW

**Comment by zuzzas** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4417723843 4417723843-1-con-1-23 /sys/deckhouse-oss/install:pr4093 cloud-user@84.252.131.232

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by zuzzas** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4418379269 4418379269-1-con-1-23 /sys/deckhouse-oss/install:pr4093 cloud-user@51.250.83.215

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [4151](https://github.com/deckhouse/deckhouse/pull/4151) to the branch [release-1.44](https://github.com/deckhouse/deckhouse/tree/release-1.44) successful!

**Pull request merged**
