### PR TITLE
[docs] Fix the text of the articles in the section «VMware vSphere»

### PR DESCRIPTION
**Pull request by Zhbert**
## Description

The "VMware vSphere" section reviewing and fixing.

## Changelog entries

```changes
section: docs
type: fix
summary: "Review and fix the 'VMware vSphere' section."
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Review by nabokihms — DISMISSED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...

**Review by z9r5 — APPROVED** [review]

**Comment by z9r5** [comment]
Cherry-picked into release-1.31

**Pull request merged**
