### PR TITLE
[candi] add waiting for kubelet client certificate generation when a node bootstrap

### LINKED ISSUE #4854: [candi] node bootstrap error message about kubelet certificates
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.45

### Expected Behavior

We don't want to see error messages about certificates

### Actual Behavior

When we bootstrap static node we see error messages:
```
=== Step: /var/lib/bashible/bundle_steps/100_disable-ntp-on-node.sh
===
Removed /etc/systemd/system/multi-user.target.wants/chronyd.service.
Error in configuration:
* unable to read client-cert /var/lib/kubelet/pki/kubelet-client-current.pem for default-auth due to open /var/lib/kubelet/pki/kubelet-client-current.pem: no such file or directory
* unable to read client-key /var/lib/kubelet/pki/kubelet-client-current.pem for default-auth due to open /var/lib/kubelet/pki/kubelet-client-current.pem: no such file or directory
Failed to annotate node test with annotation node.deckhouse.io/configuration-checksum=29d1ffd0e4fa4142676296ceb3ba0e64128fa9eb2572b95acd6439abd47e64d8 ... retry in 10 seconds.
Error from server (NotFound): nodes "test" not found
Failed to annotate node test with annotation node.deckhouse.io/configuration-checksum=29d1ffd0e4fa4142676296ceb3ba0e64128fa9eb2572b95acd6439abd47e64d8 ... retry in 10 seconds.
```

### Steps To Reproduce

1. create cluster.
2. create static node group.
3. run manual bootstrap for static node.

### Additional Information

Possibly it is a race between kubelet.conf change to add info about new generated certificates and actual certificates loading.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by artbin**
## Description

Waiting till the file /var/lib/kubelet/pki/kubelet-client-current.pem generated

## Why do we need it, and what problem does it solve?

Before using kubectl, we need to wait for the generation of the kubelet client certificate.
Close #4854

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Add waiting for kubelet client certificate generation when a node bootstrap.
impact: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Comment by name212** [comment]
/e2e/abort openstack;Standard;containerd;1.23 5209542531 5209542531-1-con-1-23 /sys/deckhouse-oss/install:pr4880 debian@37.139.62.132

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by name212** [comment]
/e2e/abort openstack;Standard;containerd;1.23 5210052322 5210052322-2-con-1-23 /sys/deckhouse-oss/install:pr4880

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]
LGTM

**Pull request merged**
