### PR TITLE
[External module manager] add module status

### LINKED ISSUE #7405: [module] move statuses from ModuleConfig to Module
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

-

### Proposed Solution

-

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
* `go_lib/deckhouse-config/status.go` and `modules/002-deckhouse/hooks/dconfig_update_status.go` are updated to be able to calculate modules' statuses, relevant tests are also updated;
* Module `status` is reflected in a module's `status` field, not in a module config;
* Module config `status` field is renamed to `message` and may contain some additional information and/or errors related to module config settings (wrong version, wrong parameters and so on);
* Module config `type` field was removed as unnecessary;
* Module config `state` field was also removed, but additional printed column is provided to reflect if a module config has `enabled` set to true;
* Some additional status messages for modules are provided so that to make it less ambiguous for a user to understand current status of a module (check examples below).

## Why do we need it, and what problem does it solve?
Closes #7405 
Moving statuses from `module configs` to `modules` should streamline understanding which modules have which statuses.

## What is the expected result?
`kubectl get modules` shows modules' statuses with some extra information.

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: external-module-manager
type: chore
summary: Move modules statuses from modules configs to modules.
impact_level: low
```

### CODE REVIEW

**Comment by miklezzzz** [comment]
before
image
image

**Comment by miklezzzz** [comment]
after
image
image

**Comment by miklezzzz** [comment]
an example when a module is ready but there is some notice from the module's config
image

**Comment by miklezzzz** [comment]
additional info
image

**Comment by miklezzzz** [comment]
additional info for a non-embedded module
image

**Comment by miklezzzz** [comment]
error message
image

**Review by z9r5 — APPROVED** [review]

**Pull request merged**
