### PR TITLE
[secret-copier] fix create secret in terminating or errored namespace

### LINKED ISSUE #5280: [secret-copier] Copying secret into terminating namespace error
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.48.3

### Expected Behavior

Secret-copier skips namespaces in Terminating status and does not try to insert a secret with `secret-copier.deckhouse.io/enabled: ""` label into them

### Actual Behavior

Secret-copier tries to insert a secret in a namespace with Terminating status and fails resulting error
```
# kubectl -n d8-system exec -ti deploy/deckhouse -- deckhouse-controller queue list
Defaulted container "deckhouse" out of: deckhouse, init-external-modules (init)
Queue '/modules/secret-copier': length 2, status: 'sleep after fail for 32s (25s left of 32s delay)'

 1. ModuleHookRun:/modules/secret-copier:kubernetes:600-secret-copier/hooks/handler.go:secrets:Kubernetes:failures 59:module hook '600-secret-copier/hooks/handler.go' failed: can't create secret object `d8-istio/my-global-secret`: secrets "my-global-secret" is forbidden: unable to create new content in namespace d8-istio because it is being terminated
 2. ModuleHookRun:/modules/secret-copier:kubernetes:600-secret-copier/hooks/handler.go:secrets:Kubernetes
```

### Steps To Reproduce

1. Have a namespace in your cluster that is stuck in Terminating status
2. Create a secret in default namespace, add label `secret-copier.deckhouse.io/enabled: ""`
3. Check deckhouse queues `# kubectl -n d8-system exec -ti deploy/deckhouse -- deckhouse-controller queue list`, find error `unable to create new content in namespace $NS_NAME because it is being terminated`

### Additional Information

_No response_

### Logs

```shell
#kubectl -n d8-system logs deploy/deckhouse | jq
...
{
  "binding": "kubernetes",
  "binding.name": "secrets",
  "event.id": "83c206fe-be33-4a5f-a8a5-febbd1621d98",
  "hook": "600-secret-copier/hooks/handler.go",
  "hook.type": "module",
  "level": "info",
  "module": "secret-copier",
  "msg": "ModuleHookRun task for 'main' group binding, trigger is Kubernetes",
  "queue": "/modules/secret-copier",
  "task.flow": "start",
  "task.id": "1218c8e7-aecc-4cc8-9ae4-19d363753c66",
  "time": "2023-07-19T11:13:48Z",
  "watchEvent": "Added"
}
{
  "binding": "kubernetes",
  "binding.name": "secrets",
  "event.id": "83c206fe-be33-4a5f-a8a5-febbd1621d98",
  "hook": "600-secret-copier/hooks/handler.go",
  "hook.type": "module",
  "level": "error",
  "module": "secret-copier",
  "msg": "Module hook failed, requeue task to retry after delay. Failed count is 83. Error: module hook '600-secret-copier/hooks/handler.go' failed: can't create secret object `d8-istio/my-global-secret`: secrets \"my-global-secret\" is forbidden: unable to create new content in namespace d8-istio because it is being terminated",
  "queue": "/modules/secret-copier",
  "task.id": "1218c8e7-aecc-4cc8-9ae4-19d363753c66",
  "time": "2023-07-19T11:13:48Z",
  "watchEvent": "Added"
}
```

### PR DESCRIPTION
**Pull request by Beastlex**
## Description

Add additional conditions for final step with create a copied secrets to the new namespaces

## Why do we need it, and what problem does it solve?

Closes #5280 

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: secret-copier
type: fix 
summary: fix create secret in terminating or errored namespace
impact_level: default 
```

### CODE REVIEW

**Comment by nabokihms** [comment]
@Beastlex Deckhouse excludes terminating namespaces here (and there is also a test)
https://github.com/deckhouse/deckhouse/blob/6b57000e5e81f168120301b9f6802ae9ce8fa49a/modules/600-secret-copier/hooks/handler.go#L180

Does it fail to skip terminating namespaces? If so, it is required to figure out why and migrate to a new solution with removing all existing code connected to terminating namespaces from secret-copier

**Comment by Beastlex** [comment]
I suppose at the time of namespace selection, it may not be in the Terminating status, but if we add a check at the time of secret creation, then on the next iteration, the namespace will no longer be included in the filter selection.

**Comment by nabokihms** [comment]
@Beastlex have you tested it? 
Do we also need to add the same ignore to update and delete functions?

**Comment by Beastlex** [comment]
No. I haven't tested it. I couldn't find opened issues or cases where errors with update or delete were there

**Pull request merged**
