### PR TITLE
[user-authn] Add custom certificate for kubeconfig generator

### PR DESCRIPTION
**Pull request by artbin**
## Description

Add custom certificate for kubeconfig generator.

## Why do we need it, and what problem does it solve?

We need to create custom certificates for kubeconfig generator.

## Why do we need it in the patch release (if we do)?

See above.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: user-authn
type: fix
summary: Add custom certificate for kubeconfig generator.
impact_level: default
```

### CODE REVIEW

**Comment by klamas1** [comment]
Maybe add guards as in similar templates?
such as https://github.com/deckhouse/deckhouse/blob/main/modules/150-user-authn/templates/kubernetes-api/custom-certificate.yaml

```
{{ if .Values.userAuthn.publishAPI.enable -}}
  {{- if eq .Values.userAuthn.publishAPI.https.mode "Global" -}}
    {{- if eq (include "helm_lib_module_https_mode" .) "CustomCertificate" }}
```

**Comment by klamas1** [comment]
You used a different helper, sorry

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [5423](https://github.com/deckhouse/deckhouse/pull/5423) to the branch [release-1.49](https://github.com/deckhouse/deckhouse/tree/release-1.49) successful!

**Pull request merged**
