### PR TITLE
[candi] Change base_scratch from spotify/scratch to base_images/scratch

### PR DESCRIPTION
**Pull request by nikiGGG**
## Description

Need to change scratch image from maintainer spotify to deckhouse.

## Why do we need it, and what problem does it solve?

'scratch' is base image for deckhouse distroless. It should be selfowned. 
## What is the expected result?

 Images building on 'spotify/scratch' should rebuild with new base 'scratch' image

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: chore
summary: Change base_scratch from spotify/scratch to base_images/scratch
impact: All containers which use spotify/scratch will be restarted (almost all deckhouse containers)
impact_level: high
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/azure'...

**Review by name212 — APPROVED** [review]

**Review by RomanenkoDenys — CHANGES_REQUESTED** [review]
Please rebase and fix description

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nikiGGG. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
