### PR TITLE
[node-manager] fix caps bootstrap multiple nodes  

### PR DESCRIPTION
**Pull request by sprait**
## Description

1. Fix recreate bootstrap-token on already bootstraped nodes.
2. Fixes from PR : #9680 
    - Remove checking for node.deckhouse.io/configuration-checksum annotation before change StaticInstance phase to Running.
    -  Check if the node status is Ready before change StaticInstance phase to Running.

## Why do we need it, and what problem does it solve?

In cases with parallel bootstrap of multiple nodes:
- Caps-controller may run bootstrap second time on node, which already bootstraping.
- Caps-controller may slowly check and set `Running` status on staticinstances.

## Why do we need it in the patch release (if we do)?

Fix errors when caps bootstrap multiple nodes.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manger
type: fix
summary: fix caps bootstrap multiple nodes.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vcd'...

  :fast_forward: `e2e: VCD, Containerd, Kubernetes 1.27` for `deckhouse:fix-caps-rebootstrap` [started](https://github.com/deckhouse/deckhouse/actions/runs/10795154837).

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [9744](https://github.com/deckhouse/deckhouse/pull/9744) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!

**Pull request merged**
