### PR TITLE
[ingress-nginx] improve log formatting

### LINKED ISSUE #3762: [ingress-nginx] Improve logs formatting
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Log formatting in the ingress nginx controller could be more intelligent. It uses a plain text template to compose a JSON.

1. Fields similar by the meaning represent different variable types, e.g., `status` is a number, and `upstream_status` is a string.
2. The JSON is only sometimes valid because variables representing numbers may be absent. Example:
```json
{"status": ,"upstream_status": 500}
```

### Proposed Solution

I see two possible options to solve the problem:
1. Deal with all edge cases by diving deeper. 
2. Using log_by_lua stage to print JSON messages.

### Additional Information

https://flant.slack.com/archives/C03B7S7P8FP/p1698326984309379?thread_ts=1698258105.226539&cid=C03B7S7P8FP

### PR DESCRIPTION
**Pull request by ipaqsa**
## Description
Provides fix for log formatting. Sets the fields `upstream_response_time` and `upstream_retries` by default.

## Why do we need it, and what problem does it solve?
Closes #3762

The fields `upstream_response_time` and `upstream_retries` are our own and are set to 0 in the locations (then they are calculated using lua code), but if the request is raw and does not match any location, these fields are not set and we get an invalid json log. 

## What is the expected result?
We get a valid json log even if the request is raw.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: ingress-nginx
type: fix 
summary: improve log formatting
```

### CODE REVIEW

**Comment by nabokihms** [comment]
This fix is no go because there are mappings in elastic search instances that expect this field to be a number, not a strings. We need another solution that will not change the changes field typing.

**Comment by ipaqsa** [comment]
@miklezzzz after:
Screenshot 2024-04-03 at 2 39 08 PM

**Comment by ipaqsa** [comment]
@miklezzzz after: 
Screenshot 2024-04-03 at 2 41 05 PM

**Review by nabokihms — CHANGES_REQUESTED** [review]
Requires changes

**Review by yalosev — APPROVED** [review]

**Review by miklezzzz — APPROVED** [review]

**Pull request merged**
