### PR TITLE
[dhctl] fix terraform plugin dir

### PR DESCRIPTION
**Pull request by sprait**
## Description

Set right path for terraform plugins.

## Why do we need it, and what problem does it solve?

Correct execution of `terrafrom init`.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Set right path for terrafrom plugins.
impact: default
```
```changes
section: testing
type: fix
summary: Update AWS AMI for CentOS.
impact: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/gcp'...

**Comment by sprait** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 9694995519 9694995519-1-con-1-25 /sys/deckhouse-oss/install:pr8831

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Comment by sprait** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 9695436469 9695436469-1-con-1-25 /sys/deckhouse-oss/install:pr8831 centos@52.28.224.111

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Comment by sprait** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 9696146520 9696146520-1-con-1-25 /sys/deckhouse-oss/install:pr8831

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...

**Comment by sprait** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.25 9696461015 9696461015-1-con-1-25 /sys/deckhouse-oss/install:pr8831

**Review by name212 — APPROVED** [review]

**Pull request merged**
