### PR TITLE
[linstor] bump DRBD version v9.1.9

### PR DESCRIPTION
**Pull request by kvaps**
Signed-off-by: Andrei Kvapil <kvapss@gmail.com>

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [x] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: linstor
type: fix
summary: Bump DRBD version to `9.21.4`.
```

### CODE REVIEW

**Review by RomanenkoDenys — CHANGES_REQUESTED** [review]
Missing description and labels

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...

**Comment by kvaps** [comment]
> Missing description and labels

That PR was in draft because I was testing e2e tests for linstor, now it contain only needed changes.

@RomanenkoDenys ready for review

**Review by RomanenkoDenys — APPROVED** [review]

**Review by z9r5 — APPROVED** [review]

**Pull request merged**
