### PR TITLE
[flow-schema] module serial number change

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
Signed-off-by: Denis Romanenko <denis.romanenko@flant.com>

## Description

Changed module number from 010 to 011 to avoid problem with prometheus crds (which is deployed in 010-prometheus-crd module)

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: chore
summary: Changed module number from 010 to 011 to avoid problem with prometheus crds (which is deployed in 010-prometheus-crd module)
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...

**Comment by RomanenkoDenys** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.21 4075415378 4075415378-1-con-1-21 /sys/deckhouse-oss/install:pr3744 centos@3.73.246.145

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/gcp'...

**Review by z9r5 — APPROVED** [review]

**Review by yalosev — APPROVED** [review]

**Review by diafour — APPROVED** [review]

**Pull request merged**
