### PR TITLE
[docs] Fix broken links

### PR DESCRIPTION
**Pull request by z9r5**
## Description
Fix broken links.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: docs
type: chore
summary: Fix broken links.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [7372](https://github.com/deckhouse/deckhouse/pull/7372) to the branch [release-1.57](https://github.com/deckhouse/deckhouse/tree/release-1.57) successful!

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit f8c5bf797a6b6a2db4145f897cfcff6b4326f4dc to the branch [release-1.56](https://github.com/deckhouse/deckhouse/tree/release-1.56) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/7798876712) for details.

**Comment by z9r5** [comment]
Cherry-picked into release-1.56

**Pull request merged**
