### PR TITLE
[kube-dns] removed unnecessary webhook

### PR DESCRIPTION
**Pull request by duckhawk**
## Description
Removed old webhook checking for deprecated service.alpha.kubernetes.io/tolerate-unready-endpoints annotation

## Why do we need it, and what problem does it solve?
This is done to reduce the load on the apiserver, this webhook is no longer needed.

## What is the expected result?
Reduce apiserver load.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: kube-dns
type: chore
summary: Removed old webhook that checked deprecated service.alpha.kubernetes.io/tolerate-unready-endpoints annotation existance.
impact_level:  low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by apolovov** [comment]
/e2e/abort static;Static;containerd;1.23 3881598892 3881598892-1-con-1-23 /sys/deckhouse-oss/install:pr3493 astra@192.168.199.57

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @apolovov. I've recognized your '/e2e/abort' command and started the workflow...

**Review by apolovov — APPROVED** [review]

**Pull request merged**
