### PR TITLE
[candi] fix working of bootstrap cloud-networks setup scripts

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
## Description

Fix working of bootstrap cloud-networks setup scripts after #4907.
Changed vsphere cloud test to test two-interface nodes and cloud-network bootstrap scripts.
## Why do we need it, and what problem does it solve?

Cloud-networks setup scripts should run before we try to fetch second-phase bootstrap scripts from bashible apiserver. If we cannot run cloud network setup scripts at the first phase, we cannot give access to apiserver in the case of two or more interfaces on the node (cloud-init scripts setup only first interface by default and if first interface is external network we need to configure internal network interface by himself).

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: fix working of bootstrap cloud-networks setup scripts
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by z9r5** [comment]
/e2e/abort vsphere;Standard;containerd;1.25 6588377594 6588377594-1-con-1-25 /sys/deckhouse-oss/install:pr6193 ubuntu@10.220.203.26

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request merged**
