### PR TITLE
[deckhouse] Persist helm client

### PR DESCRIPTION
**Pull request by nabokihms**
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/gcp'...

**Comment by nabokihms** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.23 4713888835 4713888835-1-con-1-23 /sys/deckhouse-oss/install:pr4404 user@34.159.116.65

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/gcp'...

**Comment by nabokihms** [comment]
/e2e/abort gcp;WithoutNAT;containerd;1.23 4715792506 4715792506-1-con-1-23 /sys/deckhouse-oss/install:pr4404 user@34.159.116.65

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/gcp'...

**Comment by nabokihms** [comment]
Already updated in the main branch

**Pull request closed without merging**
