### PR TITLE
[ingress-nginx] fix usage custom logs formats without our fields

### PR DESCRIPTION
**Pull request by ipaqsa**
## Description
It provides fix for ingress-nginx to avoid crashes when using custom logs formats without our fields(e.g. formatted_status).

## Why do we need it, and what problem does it solve?
When a client uses custom logs formats without our fields, they cause error in lua code.

## What is the expected result?
No crashes when using custom logs formats without our fields.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: ingress-nginx
type: fix
summary: fix usage custom logs formats without our fields
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by miklezzzz** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 9444895059 9444895059-1-con-1-25 /sys/deckhouse-oss/install:pr8621 redos@158.160.55.198

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...

**Review by nabokihms — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/gcp'...

**Comment by nabokihms** [comment]
e2e failed because of prom disks
```
VolumeMode:    Filesystem
Used By:       prometheus-main-0
Events:
  Type     Reason              Age                From                         Message
  ----     ------              ----               ----                         -------
  Warning  ProvisioningFailed  10s (x7 over 85s)  persistentvolume-controller  storageclass.storage.k8s.io "network-hdd" not found
[root@a9444895059-1-con-1-25-master-0 ~]# kubectl  get sc
No resources found
```

It seems like a not related problem. Ingress tests passed.

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [8805](https://github.com/deckhouse/deckhouse/pull/8805) to the branch [release-1.61](https://github.com/deckhouse/deckhouse/tree/release-1.61) successful!

**Pull request merged**
