### PR TITLE
[kube-dns] "prefer_udp" in stub zones

### PR DESCRIPTION
**Pull request by zuzzas**
## Description

Forgot about "prefer_udp" in stub zones in https://github.com/deckhouse/deckhouse/pull/2413

## Why do we need it, and what problem does it solve?

Same as in previous issue.

## What is the expected result?

CoreDNS with enabled stub zones are no longer affected by the aforementioned issue.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: kube-dns
type: fix
summary: Added "prefer_udp" to stub zones
impact_level: low
```

### CODE REVIEW

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [2799](https://github.com/deckhouse/deckhouse/pull/2799) to the branch [release-1.38](https://github.com/deckhouse/deckhouse/tree/release-1.38) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [2800](https://github.com/deckhouse/deckhouse/pull/2800) to the branch [release-1.37](https://github.com/deckhouse/deckhouse/tree/release-1.37) successful!

**Pull request merged**
