### PR TITLE
[cloud-provider-openstack][discovery] Add alert about orphaned disks

### LINKED ISSUE #4708: [cloud-provider-(vmware|openstack|yc)] rarely remain disk in storage but without pv in the cluster
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.45.9

### Expected Behavior

that such disks will not be in storage, or somehow report the appearance of such disks in the cluster.

### Actual Behavior

such disks are now found either randomly or after manual analysis of the entire storage

### Steps To Reproduce

_No response_

### Additional Information

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by asviel**
## Description

Added a feature to discover orphaned disks and an alert about it.

## Why do we need it, and what problem does it solve?

Partially closes #4708.

## Why do we need it in the patch release (if we do)?

We don't.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-openstack
type: feature
summary:  Add alert about orphaned disks (without PV) in the cloud.
impact_level: default
---
section: go_lib
type: feature
summary: Add orphaned disks reconcile function.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/openstack'...

**Comment by asviel** [comment]
/e2e/abort openstack;Standard;containerd;1.25 7873050868 7873050868-1-con-1-25 /sys/deckhouse-oss/install:pr7458 debian@45.12.231.80

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/openstack'...

**Comment by asviel** [comment]
image
image

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/gcp'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @asviel. I've started the workflow for label 'e2e/run/azure'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
