### PR TITLE
[e2e] Test if redos worker has selinux enabled

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
The script for bootstrapping  has been updated so that the nodes stay isolated across reboots.

## Why do we need it, and what problem does it solve?
Before these changes nodes would get access to the Internet after a reboot (due to the mix of wrong directives and using DHCP)

## What is the expected result?
The nodes stay air-gapped after a reboot.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: chore
summary: Update the script so that the nodes stay isolated from the Internet across reboots
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5114243914 5114243914-1-con-1-23 /sys/deckhouse-oss/install:pr4804

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5114243914 5114243914-1-con-1-23 /sys/deckhouse-oss/install:pr4804 astra@192.168.199.246

**Comment by miklezzzz** [comment]
/e2e/abort static;Static;containerd;1.23 5114243914 5114243914-1-con-1-23 /sys/deckhouse-oss/install:pr4804

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/static'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
