### PR TITLE
[dhctl] Print invalid YAML documents

### LINKED ISSUE #7251: [dhctl] errors of parsing yaml files do not allow to understand in which line of the file the error occurred
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Now it is clear from the error that the file is successfully divided into objects, and the error highlights a line in it, but it is not clear in which object the error occurred.

### Proposed Solution

I propose to output the object itself along with the error.

### Additional Information

image

If we take the content of the file as it is without modifications, there is a parsing error in line 10 of StaticClusterConfiguration, but it can be understood only by searching all 10 lines. 
https://deckhouse.io/gs/bm/step4.html

### PR DESCRIPTION
**Pull request by artbin**
## Description

Print invalid YAML documents.

## Why do we need it, and what problem does it solve?

Close #7251.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Print invalid YAML documents.
impact_level: default
```

### CODE REVIEW

**Comment by artbin** [comment]
Manual testing:
===========

Screenshot 2024-05-03 at 16 18 35

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

**Review by name212 — APPROVED** [review]

**Pull request merged**
