### PR TITLE
[deckhouse] Fix regexp for parsing images_digests.json

### PR DESCRIPTION
**Pull request by yalosev**
## Description
Fix images_digests regexp

## Why do we need it, and what problem does it solve?
We can't parse modules with a number in the name

## Why do we need it in the patch release (if we do)?

keep module compatibility as fast as you can

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse
type: fix
summary: Fix regexp for parsing image_digests.json.
impact_level: low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...

**Comment by yalosev** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.29 12494709926 12494709926-1-con-1-29 /sys/deckhouse-oss/install:pr11305 ec2-user@3.122.28.125

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...

**Review by RomanenkoDenys — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [11315](https://github.com/deckhouse/deckhouse/pull/11315) to the branch [release-1.67](https://github.com/deckhouse/deckhouse/tree/release-1.67) successful!

**Pull request merged**
