### PR TITLE
[candi] remove `yum versionlock` and `apt-mark hold`

### LINKED ISSUE #6242: [candi] yum versionlock delete doesn't handle cases with package dependencies
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.52

### Expected Behavior

bashible just works, without problems

### Actual Behavior

In some cases, on Redhat-based Linux distributions, you can hung up at the next step

```
Failed to execute step /var/lib/bashible/bundle_steps/003_install_mandatory_packages.sh ... retry in 10 seconds.
```

because of

```
Package yum-utils-4.0.18-4.el8.noarch is already installed.
Error: 
 Problem: problem with installed package python3-dnf-plugin-versionlock-4.0.18-4.el8.noarch
  - package python3-dnf-plugin-versionlock-4.0.18-4.el8.noarch from @System requires python3-dnf-plugins-core = 4.0.18-4.el8, but none of the providers can be installed
  - package python3-dnf-plugin-versionlock-4.0.18-4.el8.noarch from baseos requires python3-dnf-plugins-core = 4.0.18-4.el8, but none of the providers can be installed
  - cannot install both python3-dnf-plugins-core-4.0.21-23.el8.noarch from baseos and python3-dnf-plugins-core-4.0.18-4.el8.noarch from @System
  - cannot install both python3-dnf-plugins-core-4.0.21-23.el8.noarch from baseos and python3-dnf-plugins-core-4.0.18-4.el8.noarch from baseos
  - package dnf-plugins-core-4.0.21-23.el8.noarch from baseos requires python3-dnf-plugins-core = 4.0.21-23.el8, but none of the providers can be installed
  - package yum-utils-4.0.21-23.el8.noarch from baseos requires dnf-plugins-core = 4.0.21-23.el8, but none of the providers can be installed
  - cannot install the best candidate for the job
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

The reason why this happens is that we only `yum versionlock delete` packages that we take action on (`yum install`) without considering their dependencies.

In this specific case, `python3-dnf-plugin-versionlock-4.0.18-4.el8.noarch` package depends on `python3-dnf-plugins-core-4.0.18-4.el8.noarch` and vice versa (**note** package versions). But there is a new version in the repository index that yum is trying to install. Without the `--nobest` flag, yum will crash with an error if it fails to install the latest version.

### Steps To Reproduce

1. Setup clean Redhat-based Linux distributions (CentOS, ...)
2. Install **not the latest** version of `python3-dnf-plugins-core` package (`yum --showduplicates list available python3-dnf-plugins-core`)
3. Lock this version (`yum versionlock add python3-dnf-plugin-versionlock-<your-version>`)
4. Try to install `yum-utils` package (`yum install yum-utils`)

### Additional Information

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by artbin**
## Description

Remove `yum versionlock` and `apt-mark hold`.

## Why do we need it, and what problem does it solve?

Close #6242.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Remove 'yum versionlock' and 'apt-mark hold'.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — CHANGES_REQUESTED** [review]
How to remove version lock on previously installed packages ? This PR only removes addition of lock on newly installed packages.

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/aws'...

**Comment by artbin** [comment]
Manual testing
==========

Screenshot 2024-02-28 at 13 48 35

**Review by name212 — APPROVED** [review]

**Review by RomanenkoDenys — APPROVED** [review]

**Pull request merged**
