### PR TITLE
[global-hooks] Public domain template pattern fix

### PR DESCRIPTION
**Pull request by alex123012**
## Description

This PR adds a regular expression check for the publicDomainTemplate parameter in global config.

## Why do we need it, and what problem does it solve?

Now when publicDomainTemplate is not RFC 1123 compatible and user-authn module is enabled, the kubelet can't validate the API server manifest and throws an error::
```
Jan 01 00:00:00 hostname d8-kubelet-forker[22737]: E0907 00:00:00.000000  22737 file.go:187] "Could not process manifest file" err="invalid pod: [spec.hostAliases.hostnames: Invalid value: \"dex.<publicDomainTemplate>\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]" path="/etc/kubernetes/manifests/kube-apiserver.yaml"
```
After that, if cluster has only one master (not checked on multi-master setup) - cluster doesn't work, due to the unavailability of the api-server.
This is not explicit behavior at all, because the deckhouse module does not generate any errors.
## What is the expected result?

Validating publicDomainTemplate parameter after editing config in deckhouse ConfigMap.

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: global-hooks
type: fix
summary: Validating for the `publicDomainTemplate` global parameter.
impact_level: default
```

### CODE REVIEW

**Comment by z9r5** [comment]
@alex123012 Hi. 
publicDomainTemplate can have `%s` in the middle of a pattern. E.g. "kube-%s.company.my". 

Can you update the PR accordingly? 

Thanks

**Comment by alex123012** [comment]
Hi!
Ok, I'll try

**Comment by alex123012** [comment]
Hi!
I rewrote the regex with these considerations:
- %s must appear only once
- %s cannot be at the end of the pattern
- but %s can appear anywhere in the pattern

**Comment by alex123012** [comment]
Or, there is another idea:
%s must appear only once at the last domain level (smth like this ```^(?!(.*%s.*%s.*))(?=(.*%s.+))(([-a-z0-9]|%s)*([a-z0-9]|%s))?(\.([a-z0-9])(([-a-z0-9])*[a-z0-9])?)*$```)


Perhaps both regex variants are ugly, but they work:)))))))

**Comment by alex123012** [comment]
Ok, I found that Go regex library doesn't support lookarounds. I'll try to fix this.

**Comment by z9r5** [comment]
LGTM

Documentation and Getting started was checked.

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...

**Review by yalosev — APPROVED** [review]

**Comment by z9r5** [comment]
Great job, @alex123012! Thank you for your contribution!

**Pull request merged**
