### PR TITLE
[candi](bashible) Fix configure kubelet step

### PR DESCRIPTION
**Pull request by artbin**
## Description

Revert changes for `064_configure_kubelet.sh.tpl` file that was made in this pr(https://github.com/deckhouse/deckhouse/pull/5514)

## Why do we need it, and what problem does it solve?

After reverting(https://github.com/deckhouse/deckhouse/pull/5514) containerd migration to cgroupfs we have not considered the situation in which a node can have `NotManaged` Docker.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Fix configure kubelet step.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Review by name212 — CHANGES_REQUESTED** [review]
We need to revert script to 1.48 deckhouse version. before removing docker
https://github.com/deckhouse/deckhouse/blob/v1.48.9/candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Comment by artbin** [comment]
/e2e/abort openstack;Standard;containerd;1.25 5868950142 5868950142-1-con-1-25 /sys/deckhouse-oss/install:pr5553 debian@45.12.231.131

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Review by RomanenkoDenys — APPROVED** [review]

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [5560](https://github.com/deckhouse/deckhouse/pull/5560) to the branch [release-1.49](https://github.com/deckhouse/deckhouse/tree/release-1.49) successful!

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [5561](https://github.com/deckhouse/deckhouse/pull/5561) to the branch [release-1.50](https://github.com/deckhouse/deckhouse/tree/release-1.50) successful!

**Pull request merged**
